- src/Makefile
- src/score_index.h
- src/stemmer.h
I found a few minor issues that prevented compilation.  Ran a few tests on the compiled module and seems to be fine.
> minor fixes

- README.md
Link was broken.
Change from "DESIGN.md" to "docs/DESIGN.md"
> Fix link to DESIGN.md in the README

- src/benchmark/Makefile
- src/tests/Makefile
Getting a warning when compiling with clang
> Flags -lc, -lm unused

- README.md
> Add new library redisearch-rb to README.md

- docs/Commands.md
- src/index.c
- src/module.c
- src/pytest/test.py
- src/query.c
- src/rmutil/vector.h
- src/spec.c
- src/spec.h
- src/tests/test_stopwords.c
- src/tests/test_trie.c
- src/trie/trie.c
- src/trie/trie.h
- src/trie/trie_type.c
- src/trie/trie_type.h
Merging the excellent work of @xushenkun of adding trie payloads
> Trie payloads

- src/document.c
- src/document.h
- src/forward_index.c
- src/forward_index.h
- src/geo_index.c
- src/module.c
- src/numeric_index.c
- src/numeric_index.h
- src/spec.c
- src/stopwords.c
- src/tests/test_index.c
- src/varint.h
This speeds up indexing of smaller documents by quite a bit and cleans up some added cruft.
> Use mempools

- docs/Scoring.md
- mkdocs.yml
- src/doc_table.c
- src/ext/default.c
- src/ext/default.h
- src/forward_index.c
- src/forward_index.h
- src/index_result.c
- src/indexer.c
- src/pytest/test_scorers.py
- src/redisearch.h
- src/result_processor.c
- src/spec.c
- src/spec.h
- src/tests/test_index.c
Added extra scorers, and documented scoring properly  (well, better than nothing at least)
> Extra scorers

- docs/Commands.md
> Fixed typo

- src/module.c
- src/query.c
- src/trie/rune_util.c
- src/trie/trie.c
- src/trie/trie.h
- src/trie/trie_type.c
@mnunberg please review this ASAP - I want to release a fix for this tomorrow.
> limit size of prefix strings to avoid overflowing trie len 64k limit

- src/gc.c
- src/redis_index.c
- src/search_ctx.h
Solution: run smaller gc iterations and release the lock between iterations.
> fixed: cpu usage is high on numeric gc

- docs/Commands.md
Thanks for creating this amazing Redis Module. It's a pleasure to use!
> Fix typo in docs for FT.MGET

- docs/Commands.md
Described what a `+` in FT.EXPLAIN results indicates.
> Updated docs

- docs/Commands.md
- src/module.c
Just making things easier for humans.
> Changes FT.EXPLAIN to a simple string response (#361)

- src/aggregate/expr/expression.c
- src/pytest/test_conditional_updates.py
- src/value.c
- src/value.h
On conditional updates  comparison to NULL will always be false.
> see MOD-72, on conditional updates NULL values are treated as no comparables

- src/pytest/test_fuzzy.py
- src/query_parser/parser.c.inc
- src/query_parser/parser.y
Something like `%%foo%%` will match a LD of 2, where the LD is measured
by the number of percent symbols
> Allow LD of up to 3 with fuzzy matching via %-repetition

- src/numeric_filter.c
- src/pytest/test.py
- src/pytest/test_aof.py
- src/pytest/test_tags.py
- src/rmutil/args.c
- src/rmutil/args.h
- src/search_options.h
- src/search_request.c
- src/sortable.c
- src/sortable.h
- src/summarize_spec.c
This also fixes some of the tests, which were flat-out wrong, because
they passed garbage arguments.
> Stricter search parsing

- src/commands.h
- src/config.c
- src/config.h
- src/module.c
> Configuration system refactor and new FT.CONFIG command

- docs/Commands.md
> Added tag documentation to FT.CREATE

- src/dep/phonetics/double_metaphone.c
- src/document.h
- src/document_basic.c
- src/module.c
- src/query_error.h
- src/rmutil/args.c
- src/rmutil/args.h
Important to note is that I change the replication to be later on in the chain, so that commands which fail the parse stage are not propagated
> Ft add kwparse

- src/config.c
- src/config.h
- src/debug_commads.c
- src/default_gc.c
- src/default_gc.h
- src/doc_table.c
- src/fork_gc.c
- src/fork_gc.h
- src/gc.c
- src/gc.h
- src/inverted_index.c
- src/inverted_index.h
- src/module.c
- src/numeric_index.c
- src/numeric_index.h
- src/pytest/CMakeLists.txt
- src/pytest/base_case.py
- src/pytest/test.py
- src/pytest/test_gc.py
- src/redis_index.c
- src/rmutil/periodic.c
- src/rmutil/periodic.h
- src/spec.c
- src/spec.h
- src/tag_index.c
- src/tag_index.h
- src/util/arr.h
Changes:
1. Added a mechanize to implement multiple gc algorithm and configure in which gc to use.
2. Added fork gc, which uses a fork process to scan the index and sends the father process the exactly what need to be clean.
3. Added a new debug command that allows forcing gc run at any time, used this command on pytests.
> Gc impl changes

- .circleci/config.yml
- src/rmutil/test.h
- src/suggest.c
Fix compilation error on some platforms.
> No  stringify

- README.md
- docs/index.md
Signed-off-by: Itamar Haber <itamar@redislabs.com>
> Bumps latest version to 1.4.1

- LICENSE
> Fixing LICENSE typo

- README.md
- docs/index.md
Signed-off-by: Itamar Haber <itamar@redislabs.com>
> Bumps version to 1.4.2

- docs/Commands.md
- docs/Configuring.md
- docs/Escaping.md
- docs/Overview.md
- docs/Phonetic_Matching.md
- docs/Scoring.md
- docs/Spellcheck.md
- docs/Stopwords.md
- docs/index.md
Signed-off-by: Itamar Haber <itamar@redislabs.com>
> Removes '/' in local doc refs

- src/cpptests/t_index.cpp
- src/inverted_index.c
- src/inverted_index.h
This was some leftover stuff that I wrote after the initial refactor PR began. This increases overall intersection query speed by about 33%
> Intersect perf

- docs/index.md
Signed-off-by: Itamar Haber <itamar@redislabs.com>
> Changes to RSAL

- src/aggregate/aggregate.h
- src/aggregate/aggregate_exec.c
- src/aggregate/aggregate_request.c
- src/index.c
Still need to put some tests, but at least it doesn't break existing ones
> Optional iterators

- docs/Commands.md
> doc fixes -- Update Commands.md

- src/pytest/test_fuzzy.py
- src/query_parser/parser.c.inc
- src/query_parser/parser.y
Backport from master. The change is much smaller than it actually is; the .y file is the source code, the .py is the test, and the other files are auto generated
> fix issue where fuzzy can not be used with numbers only terms

- src/redisearch_api.c
> Allocate iterator using rm_calloc

- src/module.c
> see #770, alias command will raise cross slot error if used on cluster on indexes that does not located on same slot

- docs/index.md
Added the following video links:
1. [RediSearch Overview - RedisConf 2019](https://youtu.be/dq-0xagF7v8?t=520) 
1. [RediSearch & CRDT - Redis Day Tel Aviv 2019](https://youtu.be/IOWFtsKEJkg)
and blog links:
1. [Mastering RediSearch / Part I](https://redislabs.com/blog/mastering-redisearch-part/)
1. [Mastering RediSearch / Part II](https://redislabs.com/blog/mastering-redisearch-part-ii/)
1. [Mastering RediSearch / Part III](https://redislabs.com/blog/mastering-redisearch-part-iii/)
1. [Search Benchmarking: RediSearch vs. Elasticsearch](https://redislabs.com/blog/search-benchmarking-redisearch-vs-elasticsearch/)
> add video and blog post links

- .circleci/ci_build.sh
- .circleci/ci_diag_san.sh
- .circleci/ci_get_deps.sh
- .circleci/ci_test.sh
- .circleci/config.yml
- src/pytest/runtests.sh
- src/pytest/test_rdb_compatibility.py
> CI jobs for memory leaks and corruptin

- src/query_plan.c
@mnunberg lets merge after everyone will agree on this solution ..
> ignore docs which was deleted during search query

- src/pytest/test.py
- src/trie/trie.c
> fix #866, now it will not be possible to delete un-exists suggestion

- Makefile
> added clean to main makefile

- docs/Configuring.md
- src/config.c
- src/config.h
- src/fork_gc.c
- src/fork_gc.h
- src/indexer.c
- src/pytest/test_gc.py
@K-Jo I set you as a reviewer for the docs (though it cherrypicked as is from the 1.4 PR)
> Forkgc optimizations (#883)

- src/value.c
> Fix in RSValue_Equal()

- src/document_add.c
- src/fork_gc.c
- src/pytest/test.py
> Don't assume read() from pipe returns entire amount requested! (#905,

- src/cpptests/t_forkgc.cpp
@mnunberg this test pass on current master but failed on master from 2 days ago. I believe this is what causing the GC crashes.
> added gc cpp test

- src/fork_gc.c
I believe this should fix : https://github.com/RediSearch/RediSearch/issues/947
> Fork gc short read fixes

- src/pytest/test_aggregate.py
This ignores case in this test, since there is a variation in how the
results are returned for now...
> allow firstValue test to pass

- src/module.c
- src/pytest/test_replicate.py
@mnunberg 
We are timeouting on coverage/msan/asan tests but passing the rest of them.
> Issue 993 for 1.6

- src/pytest/test_aggregate.py
MIN doesn't take more than a single argument
> fix comma test

- src/module.c
- src/pytest/test.py
- src/stopwords.c
- src/stopwords.h
> Custom STOPWORDS list in ft.info

- src/aggregate/aggregate_request.c
- src/cpptests/t_document.cpp
- src/cpptests/t_extensions.cpp
- src/cpptests/t_query.cpp
- src/cpptests/t_tokenizer.cpp
- src/document.h
- src/document_add.c
- src/document_basic.c
- src/ext/default.c
- src/highlight_processor.c
- src/module.c
- src/phonetic_manager.h
- src/query.c
- src/redisearch.h
- src/redisearch_api.c
- src/search_options.h
- src/stemmer.c
- src/stemmer.h
- src/tests/test_stemmer.c
- src/tokenize.c
- src/tokenize.h
> replace string with enum for language 

- src/fork_gc.c
fix pipe leak on forkgc caused by closing the fork without holding the lock.
> Cherry pick

- src/document_add.c
Minor change which came up while look at the indexer threads
> Collapse 3 `if`s into coherent one

- src/index.c
`i` in the inner loop should be `j`.
> Fix release loop in II_GetCriteriaTester

- .circleci/config.yml
> Removed QA automation from CircleCI

- src/document.c
- src/pytest/test.py
fix #1124 
`NOINDEX tag fields can not be updated on UPDATE PARTIAL with no indexed fields`
> Fix - issue 1124

- src/aggregate/aggregate_request.c
- src/pytest/test_aggregate.py
> Remove hard limit on LIMIT

- src/config.c
- src/pytest/test_config.py
- src/pytest/test_ext.py
> set maxDocTableSize with new arg

- src/pytest/test.py
- src/pytest/test_aggregate.py
> cherrypick tests as PRs #1134 #1144

- docs/Aggregations.md
- src/aggregate/expr/expression.c
- src/aggregate/functions/string.c
- src/pytest/test.py
- src/pytest/test_if.py
- src/value.h
> Issue1058 for 1.4

- docs/Aggregations.md
- src/aggregate/expr/expression.c
- src/aggregate/expr/expression.h
- src/aggregate/functions/string.c
- src/pytest/test_if.py
replace ##1167
fix #1163 
Minimize changes by introducing EXPR_EVAL_NULL return value.
for 1.6 only
ToDo : Additional tests to ensure consistency with current 1.6
> add isnull function and EXPR_EVAL_NULL

- src/document.c
- src/numeric_index.c
- src/numeric_index.h
- src/pytest/test.py
fix inverted_sz_mb and num_records value for ft.info (#1186)
* fix number and size for NUMERIC
> cherry pick 1184 for 1.6

- src/pytest/test.py
- src/pytest/test_debug_commands.py
- src/pytest/test_expire.py
- src/pytest/test_rdb_compatibility.py
- src/pytest/test_replicate.py
> fix/skip(for now) failed tests

- src/document_basic.c
- src/module.c
- src/pytest/test.py
- src/pytest/test_followhashes.py
- src/pytest/test_gc.py
- src/pytest/test_replicate.py
- src/redis_index.c
- src/redis_index.h
- src/spec.c
Failing tests:
1. Language related (Chinese, Hindi)
2. AOF
3. Follow hashes parsing
4. Inconsistency between field name on schema and file
> Fix additional tests for 2.0

- docs/Quick_Start.md
> add redis cloud docs

- docs/Commands.md
Once finalised, we need to cherry pick this to 1.6
> update docs for tagging

- src/cpptests/t_llapi.cpp
- src/redisearch_api.c
> check NewAddDocumentCtx return value in rs_api

- src/ext/default.c
- src/pytest/test_phonetics.py
- src/spec.c
* fix fieldmask for phonetics (#1330)
> Pick issue1313 for 1.8 (#1331)

- src/id_list.c
- src/index.c
- src/index_iterator.h
- src/pytest/test_issues.py
- src/pytest/test_tags.py
* check docId vs lastDocId
* reproduce crash
* fix test
(cherry picked from commit e071d47fbfd523ac4001d7c03708e178d2a90a72)
> check docId vs lastDocId (#1286)

- docs/Escaping.md
- src/pytest/test_issues.py
- src/query_parser/lexer.c
- src/query_parser/lexer.rl
The query `FT.EXPLAIN idx -20*` which returned error `Syntax error at offset 3 near -20` now recognize `PREFIX{-20*}`
> fix -20* query

- .circleci/ci_get_deps.sh
- system-setup.py
* Updated readies
* system-setup: install awscli with pip
* system-setup: python setuptools fix
> [1.6] Updated readies + build fixes (#1367)

- .circleci/ci_get_deps.sh
- system-setup.py
* Updated readies
* system-setup: install awscli with pip
* system-setup: python setuptools fix
> [1.8] Updated readies + build fixes (#1367)

- docs/Commands.md
- src/pytest/test_followhashes.py
- src/spec.c
- src/spec.h
> Add NOINITIALINDEX flag

- docs/Aggregations.md
> fix geo doc

- src/notifications.c
- src/pytest/test_followhashes.py
> support redis unlink cmd

- docs/Commands.md
fixes #1452 
Document response of FT.SEARCH for expired documents
> note about in query expiry. issue 1452

- docs/Commands.md
- src/module.c
- src/pytest/test_followhashes.py
- src/pytest/test_issues.py
- src/spec.c
- src/spec.h
> switch from NOINITIALSCAN to SKIPINITIALSCAN and add it to FT.ALTER

- docs/Commands.md
- src/module.c
- src/pytest/test_synonyms.py
- src/spec.c
- src/spec.h
> synupdate scans keyspace unless  SKIPINITIALSCAN

- src/fork_gc.c
- src/inverted_index.c
- src/inverted_index.h
- src/pytest/test_stats.py
* Fix stats report
* remove unneeded ';'
* Update lastblkBytesCollected correctly
> Fix stats report (#1517)

- .circleci/config.yml
(cherry picked from commit ea81d4735efe4f0f9155c1c385a82fbc1ab57849)
> [2.0] CircleCI: abort_for_docs & early_return_for_forked_pull_requests (#1536)

- docs/Commands.md
- mkdocs.yml
> Break down commands documentation into subsections

- src/aggregate/aggregate_request.c
- src/pytest/test_scorers.py
> explicit error for EXPLAINSCORE w/o WITHSCORES

- src/module.c
- src/pytest/test_synonyms.py
> Fix wrong arity for syndump

- src/cpptests/t_forkgc.cpp
- src/pytest/test_followhashes.py
- src/redis_index.c
- src/rules.c
- src/rules.h
- src/spec.c
- src/spec.h
* Fix issue 1571, when filter is no longer valid, the document will be deleted from the index.
* Fix tests
* fix review
> Fix issue 1571, when filter is no longer valid, the document will be deleted from the index

- docs/Synonyms.md
> example for synonyms docs

- docs/Overview.md
- docs/Tags.md
> remove tags in keyspace from docs

- src/sortable.c
> use pointer instead of struct

- docs/Aggregations.md
- src/document.h
- src/document_basic.c
- src/pytest/test_aggregate.py
- src/rlookup.c
- src/rules.c
- src/spec.c
> FT.AGGREGATE Filter by DocId by LOADing "@__key"

- docs/Commands.md
Needs to be the same on 2.0 branch
> Making sure we have the right instructions for tagging documents

- docs/Commands.md
- src/fork_gc.c
> Fix `average` typo

- src/config.c
- src/config.h
- src/index.c
- src/util/heap.c
- src/util/heap.h
- tests/pytests/CMakeLists.txt
- tests/pytests/test_config.py
- tests/pytests/test_issues.py
- tests/pytests/test_summarize.py
places  #1602 as it was messed with rebase
fix #1392
> Union iterator for large number of children

- docs/Configuring.md
- src/config.c
- tests/pytests/test_config.py
> MAXPREFIXEXPANSIONS config

- README.md
- docs/index.md
- mkdocs.yml
* change the page title
* Update mkdocs.yml
* Update README.md
* Update index.md
Co-authored-by: Ariel Shtul <ashtul@gmail.com>
(cherry picked from commit ecebaf7daa2698dc983a14034bfff361d374dcfd)
> 2.0 cherry pick secondary

- README.md
- docs/index.md
Co-authored-by: Ariel Shtul <ashtul@gmail.com>
(cherry picked from commit 6d418ad31bbcb00b2e883cfd5b6d4e41855657b1)
> replace chat to discord (#1623)

- docs/index.md
The first video link was rendering incorrectly, fixed it.
> Fixed markdown issue in first video link

- tests/pytests/test.py
- tests/pytests/test_suggest.py
related to #1650 
* Moved `FT.SUG` tests to `test_suggest.py`
* Add test for `FT.SUGGET` with `MAX`
> move tests and add MAX test

- src/aggregate/aggregate_exec.c
- tests/pytests/test.py
- tests/pytests/test_numbers.py
> [BUG] Fix timeout PR for RS coordinator

- docs/Clients.md
(cherry picked from commit d69435430952a1b0ddc7b2f202fa1244f6e72a8c)
> Add stars to clients (#1687)

- docs/Commands.html
This file add the redirection to fix the 404 issue on https://oss.redislabs.com/redisearch/Commands.html
> Redirect doc Commands.html to /Commands/

- .circleci/config.yml
- .github/workflows/deploy-docs.yaml
Enable manual GitHub action trigger for the doc
> Enable manual trigger on doc generation (1.4)

- src/config.c
- src/config.h
- src/cpptests/t_index.cpp
- src/inverted_index.c
- src/module.c
- src/numeric_index.h
- src/pytest/test_config.py
- src/pytest/test_numbers.py
> cherry pick no compression on numeric for 1.6

- docs/requirements.txt
Vulnerable module: | PyYAML
-- | --
mkdocs@1.0.4         and         mkdocs-material@4.6.3 | Mature
> upgrade mkdocs

- src/pytest/test.py
- src/sortable.c
- src/spec.c
(cherry picked from commit 5f7f10598602764a7bf6ce0da6d6f86b5c7acadf)
> Replace assert on limit of sortable fields (#1757)

- tests/pytests/test.py
Fix failure on [CircleCI](https://app.circleci.com/pipelines/github/RediSearch/RSCoordinator/626/workflows/00e4426e-8bff-44f5-925c-532f3888426e/jobs/4399)
> Fix test where results order can vary by shard

- src/document.c
Was inserted in #751
Remove in #1782
> Return removed clearing tags pointers

- src/module.c
fix a small typographical error
> Fix small typo error

- src/redisearch_api.c
- src/redisearch_api.h
- tests/cpptests/test_cpp_llapi.cpp
> Add geo support to low-level API

- src/stopwords.c
- tests/pytests/test_issues.py
> [BUG] Fix query with stopword with upper case 

- src/index.c
- src/util/heap.c
- src/util/heap.h
- tests/pytests/test_issues.py
> Fix quick exit for heapified union iterator

- src/redisearch_api.c
- src/redisearch_api.h
* switch lon-lat
* swap lat-lon
* fix comment
Co-authored-by: swilly22 <roi@redislabs.com>
(cherry picked from commit 2a8d6d372b8359cb9a9cd2c27d4ae1d74183e6ae)
> [BUG] Fix LLAPI GEO  (#1843) - CP for 2.0

- docs/Clients.md
redisearch-php is archived and does not support RediSearch 2.0
> Update PHP client

- docs/requirements.txt
- mkdocs.yml
* use mkdocs-modules-template
* fix for e3b03adb4c1ab7d4190cc8ec614422e75e9ed752 - add requirements.txt
* upgrade mkdocs-module-template
(cherry picked from commit fa546e425ce3f4c8ac4e01f57d66be1f0f6668ba)
> upgrade mkdocs-modules-template (#1859) (2.0)

- cmake/redisearch_cflags.cmake
> add Bsymbolic flag to CMake

- system-setup.py
Changing the redis depend on brew.
Brew already includes redis 6 with TLS support.
> redis from brew

- system-setup.py
* redis from brew
* fixing the syntax issues
(cherry picked from commit 145287cd526103a59a2395ad006377fcc696fdc8)
> redis from brew (#1882)

- tests/pytests/test_scorers.py
The issue of the 7 layers was recently fixed in redis.
> Fix ScoreExplain test where reply length > 7

- src/redisearch_api.c
- tests/cpptests/test_cpp_llapi.cpp
Related to RedisGraph/RedisGraph#1244
> [LL API] Add a test for scoring

- src/rlookup.c
- tests/pytests/test_followhashes.py
* do not return payload as field
* fix tests
* fix tests
* fix tests
* fix tests
Co-authored-by: Rafi Einstein <rafi@redislabs.com>
> do not return payload as field (#1914)

- src/index.c
- tests/pytests/test_issues.py
> Sort intersect iterator's children iterators

- src/fork_gc.c
> Do not abort GC fork on broken pipe

- src/aggregate/aggregate_request.c
- src/result_processor.c
- tests/pytests/test_issues.py
> Fix death by limit

- tests/pytests/test.py
(cherry picked from commit 773a04106e4f0cfbad3a75a84ce69f3a36fd16e1)
> [2.0] Fixed parsetime() test (#1967)

- src/notifications.c
- tests/pytests/test_json.py
> [feature-search-json] Add/Organize tests

- src/index.c
- tests/pytests/test.py
> [BUG] skip intersect iterator qsort if INORDER flag is used

- .github/workflows/deploy-docs.yaml
Co-authored-by: Emmanuel Keller <74923777+emmanuelkeller@users.noreply.github.com>
(cherry picked from commit c46fef56707c0cbba60270823ec1aa4124dbe2d0)
> Restore root pages sync docs (#1873) (#1991)

- src/aggregate/aggregate_request.c
- tests/pytests/test.py
- tests/pytests/test_issues.py
> add RPScore with WITHSCORES

- src/notifications.c
- tests/pytests/test_json.py
To run also unstable tests set the env var `UNSTABLE_TESTS=1`
> Update search json tests

- src/redisearch_api.c
- src/redisearch_api.h
- src/stopwords.c
- tests/cpptests/test_cpp_llapi.cpp
Related to RedisGraph/RedisGraph#1638
> [LLAPI] Add stopwords list support

- src/trie/trie.c
- tests/pytests/test_suggest.py
> fix payload for SUGADD with existing token

- src/inverted_index.c
- src/inverted_index.h
> Remove weight from IndexReader

- src/doc_types.h
- src/notifications.c
- src/spec.c
- tests/pytests/test_followhashes.py
> use isJSON in getDocType

- docs/Commands.md
- src/aggregate/aggregate_exec.c
- src/index.c
- tests/pytests/test_geo.py
- tests/pytests/test_issues.py
- tests/pytests/test_profile.py
> check FT.PROFILE command has 5 args

- src/document.c
- src/document_basic.c
- src/json.c
- src/json.h
- src/rlookup.c
- tests/pytests/test_geo.py
- tests/pytests/test_json.py
> Retrieve JSON values w/o getJson 

- docs/Commands.md
- docs/Indexing_JSON.md
- mkdocs.yml
> Indexing JSON doc

- src/document_basic.c
- src/rejson_api.h
- src/rlookup.c
- src/rules.c
- src/rules.h
- tests/pytests/test_json.py
This might not pass tests before RedisJSON/RedisJSON#417 is merged
> Use newer ReJSON API

- src/document.c
- src/spec.c
- tests/pytests/test_issues.py
Otherwise, potentially there will be a discrepancy between values stored in the Sortable table and values in the hash/json.
> Mod 1266 - Delete document if failed to update

- tests/pytests/common.py
- tests/pytests/test.py
- tests/pytests/test_scorers.py
(cherry picked from commit 03c8e5b02bf4d6edc7110651df133d41a5c6ac04)
> [2.0] Fixed server version tests (#2123)

- tests/pytests/common.py
- tests/pytests/test.py
- tests/pytests/test_profile.py
- tests/pytests/test_scorers.py
(cherry picked from commit 03c8e5b02bf4d6edc7110651df133d41a5c6ac04)
> [2.2] Fixed server version tests (#2123)

- tests/pytests/test_json.py
(cherry picked from commit d72198d18a4901e84c3ccf7a64e1da0436e5cf80)
> [2.2] Cherry-pick from master

- src/aggregate/reducers/first_value.c
- tests/pytests/test.py
(cherry picked from commit c60e14456a33612c733b1efc1bf047e4490e3d43)
> [2.0] fix crash on coordinator on first value reducer (#2115)

- src/aggregate/reducers/first_value.c
- tests/pytests/test.py
(cherry picked from commit c60e14456a33612c733b1efc1bf047e4490e3d43)
> [2.2] fix crash on coordinator on first value reducer (#2115)

- src/aggregate/aggregate_exec.c
- tests/pytests/test_profile.py
(cherry picked from commit 2ba9141074f0f2156de6d4539375a36f03f9472a)
> [2.2] Fix FT.PROFILE tests on RSC (#2128)

- src/document.c
- src/spec.c
- tests/pytests/test_issues.py
> [2.0] [MOD-1266] delete document if failed to update. #2113

- src/redisearch_api.c
- src/spec.c
- src/spec.h
(cherry picked from commit ea661b51244be54745ad78ee400b095e72eca7af)
> [CP] Remove `FieldSpec_Initialize` (#2134)

- src/aggregate/aggregate_request.c
- src/rlookup.c
- tests/pytests/test.py
- tests/pytests/test_issues.py
> [BUG] Field loaded with 'AS' cant be used by funcs

- src/info_command.c
- tests/pytests/test.py
- tests/pytests/test_aof.py
- tests/pytests/test_json.py
> FT.INFO has identifier and attribute for fields

- src/document_basic.c
- tests/pytests/test_json.py
json iterator with 0 paths is legal
fixes #2141
> [BUG] partial JSON documents are not indexed

- src/ext/default.c
- src/query.c
- src/query_node.h
- src/query_parser/parser.c
- src/query_parser/parser.y
- tests/cpptests/test_cpp_query.cpp
- tests/pytests/test_fuzzy.py
- tests/pytests/test_tags.py
> Fix casesensitive 2138

- tests/pytests/test_tags.py
(cherry picked from commit aaec3eef6f31a94dffaf228a3cf6f1c6b0599f99)
> [2.0] SkipOnCluster (#2164)

- system-setup.py
> Updated readies (fixes #2177)

- src/document_basic.c
- src/redisearch_api.c
- src/redisearch_api.h
- src/rules.c
- src/spec.c
- src/spec.h
- src/stopwords.c
- src/stopwords.h
- tests/cpptests/test_cpp_llapi.cpp
> [LLAPI] getter functions for score, language and stopwords list

- tests/pytests/test_json.py
> Fix Coordinator tests

- docs/Aggregations.md
- docs/Commands.md
- docs/Sorting.md
> Documents SORTABLE UNF

- src/value.h
- tests/pytests/test_issues.py
used to return a constant 1337 instead of using the old hval in the calculations.
> fix RSValue_Hash with null value

- src/aggregate/aggregate_request.c
- tests/pytests/test_issues.py
> [BUG] fix FIELDS for highlight

- src/index.c
- tests/pytests/test_profile.py
> [BUG] Replace NULL with empty iterator for child of negative iterator

- src/aggregate/aggregate_request.c
- src/result_processor.c
- src/vector_index.c
- tests/pytests/test_vecsim.py
For example - `FT.SEARCH idx "@v:[aaaaaaaa TOPK 4]" SORTBY v_score ASC LIMIT 0 4 RETURN v_score`
> SORTBY on VecSim field can be sorted using vecsim_score field

- src/index.c
- tests/pytests/test_issues.py
> Fix MOD-1808, check for NULL result on intersect iterator.

- src/index.c
- tests/pytests/test_issues.py
Co-authored-by: Rafi Einstein <rafi@redislabs.com>
(cherry picked from commit 669ae1364b614df7019118909472919cf4025336)
> Fix MOD-1808 tests (#2346)

- src/rlookup.c
- tests/pytests/test.py
> Fix crash on empty field name

- src/rlookup.c
- tests/pytests/test.py
(cherry picked from commit 763a5f35c80047a6ede9af30fa169d2299e75bb7)
> Fix crash on empty field name (#2362)

- tests/pytests/test_json.py
* [TEST] JSON.ARRAPPEND/ARRINSERT/ARRPOP/ARRTRIM
* fix tests
* improve tests
(cherry picked from commit 1949ed625559d2fc219f69b752d5f10fb6711c07)
> [CP] RedisJSON array tests (#2368)

- src/aggregate/aggregate_exec.c
- tests/pytests/test_issues.py
(cherry picked from commit 199e352b93a92197765d5dc8187025f00bcc6c89)
> [BUG] Fix when LIMIT offset > number of results (#2371)

- README.md
Co-authored-by: Rafi Einstein <rafi@redislabs.com>
(cherry picked from commit f5c90d0c4faf05ba56cf1d1d74e67d2b81b972d8)
> [2.2] Update README.md (#2361)

- Makefile
(cherry picked from commit d1e6e04bed35b0529cd2ff50fb8600895e901270)
> [2.2] Updated readies, Makefile (HELPTEXT) (#2375)

- src/rs_geo.c
- tests/pytests/test_geo.py
> [BUG]  remove limit on geo percision

- README.md
> Updating redis python client

- .circleci/config.yml
(cherry picked from commit 43935fdb3183923c685fb8c41c5a700371605870)
> [2.2] CircleCI: fixed artifacts deploy logic (#2463)

- coord/src/dist_aggregate.c
> Fix FT.PROFILE for FT.AGGREGATE

- coord/src/dist_aggregate.c
(cherry picked from commit c0c9f12e5f3569253ed1cc98eb4d35ef07c4f1ab)
> Fix FT.PROFILE for FT.AGGREGATE (#2466)

- src/redisearch_api.c
- src/redisearch_api.h
- tests/cpptests/test_cpp_llapi.cpp
(cherry picked from commit 04f27b0f1a418059aea31ec04830a68b58dde4cc)
> [2.2] add LLAPI for TAG children query nodes (#2469)

- src/query.c
- src/query_node.h
- src/redisearch_api.c
- src/redisearch_api.h
- tests/cpptests/test_cpp_llapi.cpp
- tests/cpptests/test_cpp_query.cpp
(cherry picked from commit 04f27b0f1a418059aea31ec04830a68b58dde4cc)
> [2.0] add LLAPI for TAG children query nodes (#2469)

- coord/src/dist_aggregate.c
(cherry picked from commit c5a8ab42d6c5cd5dde77ceaaeb2306b9227f71a7)
> [2.2] Fix FT.PROFILE no result processor is peresent (#2473)

- src/tag_index.c
- tests/pytests/test_json.py
> [BUG] Lower case with default separator

- src/tag_index.c
- tests/pytests/test_json.py
* [BUG] Lower case with default separator
* per review
* Update tests/pytests/test_json.py
Co-authored-by: Omer Shadmi <76992134+oshadmi@users.noreply.github.com>
Co-authored-by: Omer Shadmi <76992134+oshadmi@users.noreply.github.com>
(cherry picked from commit 07bb7ca57b3353607d5ce3543d2ed99440c2c657)
> [2.2] Lower case with default separator (#2490)

- coord/src/info_command.c
- tests/pytests/common.py
- tests/pytests/test_coordinator.py
> [BUG] fix doubles for FT.INFO on COORD

- src/aggregate/expr/exprast.c
- src/aggregate/expr/exprast.h
- src/aggregate/expr/expression.c
- src/aggregate/expr/expression.h
- src/rlookup.c
- src/rlookup.h
- src/rules.c
- src/rules.h
- src/spec.c
- src/spec.h
- tests/pytests/test_followhashes.py
* load required fields for hash
* fix 1
* fix 2
* unstable test
* stash. revert this
* fix leak
* fix
* fix for RSC
* per review
* cleanup
* coverage
* more coverage
(cherry picked from commit 793e9cf09d2ee852484e1e9a6873a5ceef529b70)
> [2.2] MOD-2214 fix rule filter json (#2436)

- src/cursor.c
- src/cursor.h
- src/module.c
- src/rdb.c
- src/spec.c
- tests/pytests/test_followhashes.py
* [PERFORMANCE] free all prefixes as batch
* test
* Free cursorList as well
* Fix leak
* clean
* clean 2
* fix
(cherry picked from commit e36a2bd4e3fddef7511a70c38b9f1ebfa575e7c0)
> [2.2] Free prefix and cursor efficiantly on  Indexes_Free (#2560)

- src/rdb.c
- tests/pytests/test_short_read.py
> Enable short read test

- src/document.c
- src/field_spec.h
- src/info_command.c
- src/query.c
- src/redisearch_api.c
- src/spec.c
- src/vector_index.c
- src/vector_index.h
- tests/pytests/common.py
- tests/pytests/test_vecsim.py
added a validation check at insertion to vector index
> Vecsim add vector check

- coord/src/module.c
This PR introduces casting input structs to the expected type(s), required by the functions used for processing and post-processing of results. The casted types are typedef of each other.
> fix warnings on coordinator

- coord/src/rmr/rmr.c
* fix leak
* same leak different place
(cherry picked from commit 0d8cffbdf9fbd41092b7afefdb7bc28e8823889f)
> [2.2] Memory leak in the coordinator (#2641)

- coord/src/rmr/rmr.c
* fix leak
* same leak different place
(cherry picked from commit 0d8cffbdf9fbd41092b7afefdb7bc28e8823889f)
> [2.0] Memory leak in the coordinator (#2641)

- tests/pytests/test_vecsim.py
This is required when moving from python2 to python3...
> Convert explicitly float to int in vecsim tests

- src/ext/default.c
- tests/pytests/test_cn.py
> Fix Synonym in Chinese

- CMakeLists.txt
- coord/CMakeLists.txt
- sbin/pack.sh
This reverts commit fbff2d0f9606686d857fd3dc0b2fe4e0899f17f1.
> Revert "remove symbols strip (#2709)"

- coord/src/search_cluster.c
> Fix leak on none tls setup

- src/result_processor.c
(cherry picked from commit 8286af3ce92dd83c540a1a60f2e0fc31b56f9bfa)
> [BUG] remove assert from rploaderNext (#2716)

- coord/src/dist_aggregate.c
- src/aggregate/aggregate_exec.c
- src/gc.c
- src/indexer.c
- src/query.c
- src/query_node.h
- src/redisearch.h
- src/redisearch_api.c
- src/result_processor.c
- src/result_processor.h
- src/spec.h
- src/trie/rune_util.h
- src/trie/trie.c
- src/trie/trie.h
- src/trie/trie_type.c
- src/util/timeout.h
- tests/cpptests/test_cpp_query.cpp
Some small changes which were made in the coming `CONTAINS` PR.
Mostly dealing with `timeout` and changing `QueryPrefixNode` from being `RSToken` to holding it.
#2732
> Various changes

- coord/src/module.c
- coord/src/search_cluster.c
- src/query_parser/v1/parser.c
- src/query_parser/v1/parser.y
- src/query_parser/v2/parser.c
- src/query_parser/v2/parser.y
- tests/pytests/test_parser.py
this PR fixes some leaks introduced in coordinator during the 2.4 work
> fix vecsim leaks in coordinator

- tests/pytests/test_short_read.py
* Try reusing same port in short-read ShardMock
* Temp set verbose
* Rollback temp set verbose + diagnostic
* Add StartListening exception datails and revert "Try reusing same port in short-read ShardMock"
* Reuse same port
(cherry picked from commit 59c6f81197e1b5a528d87cb8f9de964a62827cb6)
> Cherry-pick from master to 2.2: Try reusing same port in short-read ShardMock (#2710)

- tests/pytests/test_short_read.py
* Try reusing same port in short-read ShardMock
* Temp set verbose
* Rollback temp set verbose + diagnostic
* Add StartListening exception datails and revert "Try reusing same port in short-read ShardMock"
* Reuse same port
(cherry picked from commit 59c6f81197e1b5a528d87cb8f9de964a62827cb6)
> Cherry-pick from master to 2.4: Try reusing same port in short-read ShardMock (#2710)

- coord/src/search_cluster.c
- src/query_parser/parser.c
- src/query_parser/parser.y
- tests/pytests/test_issues.py
Cherry-pick leak fixes from #2739
> [2.2] Clear some leaks

- src/aggregate/expr/expression.c
(cherry picked from commit 4b08a226c8f323d3ab84c192711944e814cf77c3)
> [2.2] Init all vars in EvalCtx (#2780)

- src/spec.c
- tests/pytests/test_vecsim.py
This PR removes the free memory check for vector similarity index creation and adds a test that compares the initial index size to the threshold limit.
It also adds more info about free vs required memoryl
> Informative error message for vector index failure

- src/aggregate/expr/expression.c
(cherry picked from commit 4b08a226c8f323d3ab84c192711944e814cf77c3)
> [2.4] Init all vars in EvalCtx (#2780)

- src/aggregate/expr/expression.c
- src/doc_types.h
- src/notifications.c
- src/redisearch.h
- src/rlookup.c
- src/rules.c
- src/spec.c
- tests/pytests/test_followhashes.py
https://redislabs.atlassian.net/browse/MOD-3180
> Add type check using IndexSpec_UpdateDoc

- src/doc_types.h
- src/notifications.c
- src/redisearch.h
- src/rlookup.c
- src/rules.c
- src/spec.c
- tests/pytests/test_followhashes.py
* Add type check for DocumentType and change DocumentType_None to DocumentType_Unsupported
(cherry picked from commit 39a46e196b4f313ca57dea965b9dfcc3166e580f)
> [2.2] Add type check using IndexSpec_UpdateDoc (#2783)

- src/doc_types.h
- src/notifications.c
- src/redisearch.h
- src/rlookup.c
- src/rules.c
- src/spec.c
- tests/pytests/test_followhashes.py
* Add type check for DocumentType and change DocumentType_None to DocumentType_Unsupported
(cherry picked from commit 39a46e196b4f313ca57dea965b9dfcc3166e580f)
> [2.4] Add type check using IndexSpec_UpdateDoc (#2783)

- deps/triemap/triemap.c
- src/hybrid_reader.c
- src/query.c
- src/spec.h
- src/trie/trie.c
- src/trie/trie.h
- src/util/timeout.h
- tests/pytests/test_coordinator.py
Fix issue in https://github.com/RediSearch/RediSearch/commit/30dc211b8f00627b4d83a828a0b7ad0b2eda04d8
> Fix mac os warnings/errors

- src/fork_gc.c
- src/inverted_index.c
- src/numeric_index.c
- src/numeric_index.h
- tests/cpptests/test_cpp_range.cpp
- tests/pytests/test.py
- tests/pytests/test_gc.py
- tests/pytests/test_geo.py
- tests/pytests/test_numbers.py
- tests/pytests/test_profile.py
* checkCardinality function
* working version
* fix
* fix min,max,uniqueSum
* fix
* print list
* add ft.profile
* per review
* fix test
(cherry picked from commit 06a4938c0f69741383577b786a60c6e5ecc7959d)
MOD-2215
> [2.4] Reduce use of cardinality (#2434)

- src/fork_gc.c
- src/inverted_index.c
- src/numeric_index.c
- src/numeric_index.h
- tests/cpptests/test_cpp_range.cpp
- tests/pytests/test.py
- tests/pytests/test_gc.py
- tests/pytests/test_geo.py
- tests/pytests/test_numbers.py
- tests/pytests/test_profile.py
This reverts commit 9a470d29334c5816d96dbd75ab7dc6a23fb64972.
> Revert "[2.4] Reduce use of cardinality (#2434) (#2805)"

- docs/commands/ft.search.md
> Remove FT.ADD point to FT.CREATE docs

- README.md
- docs/docs/Clients.md
Hi, I made a Golang Redis client library that supports Redisearch commands.
Could I add my library to the client list? Thanks!
> Add rueidis to Clients.md

- tests/pytests/test_json.py
ref https://github.com/RedisJSON/RedisJSON/pull/758
> Add test for Redis Vanila commands on JSON

- src/module.c
- tests/pytests/test_spell_check.py
(cherry picked from commit d73b283c621b109b01b85fbd443f46d92cf7380f)
> [2.4] Change MAX_LEV_DISTANCE to 4 (#2863)

- tests/pytests/test_json.py
> refix COPY JSONs on redis-server pre 6.2

- src/aggregate/aggregate_exec.c
- src/aggregate/aggregate_request.c
- tests/pytests/test_issues.py
SORTBY MAX cannot be used with FT.SEARCH
MOD-3540
> [BUG]  disable SORTBY MAX with FT.SEARCH

- sbin/get-redisjson
- src/config.c
- src/config.h
- src/cursor.c
- src/cursor.h
- src/field_spec.c
- src/field_spec.h
- src/fields_global_stats.c
- src/fields_global_stats.h
- src/fork_gc.c
- src/gc.c
- src/gc.h
- src/info_command.c
- src/module-init/module-init.c
- src/module.c
- src/spec.c
- src/spec.h
- src/stopwords.c
- src/stopwords.h
- tests/pytests/test_ext.py
- tests/pytests/test_info_modules.py
Cherry-pick for https://github.com/RediSearch/RediSearch/pull/2760
> [2.4] Expose information to INFO MODULES command

- deps/geohash/geohash_helper.c
- src/geo_index.c
- tests/cpptests/test_cpp_llapi.cpp
- tests/pytests/test_geo.py
* [BUG] set limit on lat lon radius
* move GeoFilter_Validate
* fix test
* check failures
* expand test
* revery breaking change
* Update tests/cpptests/test_cpp_llapi.cpp
Co-authored-by: Omer Shadmi <76992134+oshadmi@users.noreply.github.com>
* add llapi test 90 >x > 85
* clean
Co-authored-by: Omer Shadmi <76992134+oshadmi@users.noreply.github.com>
(cherry picked from commit 4a55f036ccbc94944fc7a122236ebf4923584e84)
> [2.2] set limit on lat lon radius for GEO (#2865)

- deps/geohash/geohash_helper.c
- src/geo_index.c
- src/query.c
- tests/cpptests/test_cpp_llapi.cpp
- tests/pytests/test_geo.py
* [BUG] set limit on lat lon radius
* move GeoFilter_Validate
* fix test
* check failures
* expand test
* revery breaking change
* Update tests/cpptests/test_cpp_llapi.cpp
Co-authored-by: Omer Shadmi <76992134+oshadmi@users.noreply.github.com>
* add llapi test 90 >x > 85
* clean
Co-authored-by: Omer Shadmi <76992134+oshadmi@users.noreply.github.com>
(cherry picked from commit 4a55f036ccbc94944fc7a122236ebf4923584e84)
> [2.4] set limit on lat lon radius for GEO (#2865)

- tests/pytests/common.py
- tests/pytests/test_rdb_compatibility.py
- tests/pytests/test_short_read.py
(cherry picked from commit 37854f7e8c5fb1ab026f96895d637db66e5f6076)
> [2.2] Fix for RDB file location in test (#2938)

- tests/pytests/common.py
- tests/pytests/test_rdb_compatibility.py
- tests/pytests/test_short_read.py
(cherry picked from commit 37854f7e8c5fb1ab026f96895d637db66e5f6076)
> [2.4] Fix for RDB file location in test (#2938)

- src/spec.c
- tests/pytests/test_info_modules.py
(cherry picked from commit a1d597f0eab9637d0f27da650121f4114ea8a5f0)
> [2.4] Fix Flaky info modules Test (#2896)

- docs/docs/Indexing_JSON.md
> MOD-2972: add documentation for multi text

- src/info_command.c
- src/spec.c
- src/spec.h
> [BUG] Fix failures of test on some OS where 1.0 is not a double

- src/query.c
- src/redisearch.h
- src/suffix.c
Fix compilation warnings and added 
```
#define BAD_POINTER ((void *)0xBAAAAAAD)
```
> [MISC] fix compilation warnings

- coord/src/module.c
- src/cursor.c
- src/cursor.h
- src/spec.c
- src/spec.h
> [2.4][BUG] processes killed by WD due to inefficient findInfo() (#3012)

- docs/commands/ft.info.md
Adds the new field `number_of_uses` to the documentation.
> Update `ft.info.md` file (regarding #2775)

- coord/src/info_command.c
- docs/commands/ft.info.md
- src/info_command.c
- src/spec.c
- src/spec.h
- tests/pytests/test.py
> [2.6] Add counter to Index and count the number of times the index was used

- coord/src/info_command.c
- docs/commands/ft.info.md
- src/info_command.c
- src/spec.c
- src/spec.h
- tests/pytests/test.py
> [2.4] Add counter to Index and count the number of times the index was used

- docs/docs/reference/Aggregations.md
- src/aggregate/functions/string.c
- tests/pytests/test_aggregate.py
Adds new APLLY function to string functionality - `srtlen`.
MOD-4141
> Support StrLen in FT.AGGREGATE

- src/aggregate/aggregate_exec.c
- tests/pytests/test.py
- tests/pytests/test_sortby.py
> [2.2] Fix SORTBY numeric field for Non-Sortable on the coordinator #3040

- docs/docs/reference/Aggregations.md
- src/aggregate/functions/string.c
- tests/pytests/test_aggregate.py
#3047 
(cherry picked from commit 606e5294c26f8db0ea22f7ea80562845ca0b5260)
> [2.4] Support StrLen in FT.AGGREGATE (#3047)

- src/aggregate/aggregate_exec.c
> [PERF] use kk >name_len instead of strlen

- src/index.c
- src/index.h
- src/query.c
> [BUG] wildcard changes

- docs/docs/reference/Vectors.md
> Update vecsim doc

- src/debug_commads.c
- src/vector_index.c
- src/vector_index.h
- tests/pytests/test_vecsim.py
update vecsim livrary to 0.5.0
> vecsim 0.5.0

- coord/src/module.c
- src/util/heap.c
- src/util/heap.h
This PR fixes a leak found on the coordinator when we have an error on a query that contains VSS.
This PR fixes [MOD-4252](https://redislabs.atlassian.net/browse/MOD-4252)
> MOD-4252: Coordinator leak fix

- src/query.c
- tests/benchmarks/search-ftsb-10K-enwiki_abstract-hashes-term-withoutsuffix-trie.yml
- tests/benchmarks/search-ftsb-10K-enwiki_abstract-hashes-term-withsuffix-trie.yml
- tests/pytests/test_contains.py
> [BUG] redirect prefix query from suffixtrie

- docs/commands/ft.aggregate.md
- docs/commands/ft.search.md
- docs/docs/Configuring.md
- docs/docs/reference/Vectors.md
> Document dialect 3 and multi projection

- tests/pytests/CMakeLists.txt
Similar to #3217 just remove test
> remove endfix

- src/numeric_index.c
- tests/pytests/test_issues.py
(cherry picked from commit b3075a5ca5a2eaa12ab5feae05b26a894d3805cf)
MOD-4255
MOD-4296
> [2.6] `NumericRangeIterator_OnReopen` is not implemented (#3171)

- src/json.c
- src/rejson_api.h
- src/rlookup.c
(cherry picked from commit a4fbace86c79494988c3e3f18aa6a18f95728200)
> [2.6] MOD-4480: Differentiate between JSON API version 2 and 3

- src/aggregate/aggregate_request.c
- src/result_processor.c
- tests/pytests/test_issues.py
Fix the issue by choosing the correct max results value depends of whether we run a search of aggregate query.
> Fix #3230, use the correct max results value.

- docs/commands/ft.create.md
Small typographical error in #2931
> Fix NOFIELDS typo

- docs/commands/ft.tagvals.md
> [DOC UPDATE] FT.TAGVAL markdown update

- deps/triemap/triemap.c
- deps/wildcard/wildcard.c
- tests/ctests/test_wildcard.c
- tests/pytests/test_wildcard.py
MOD-4653
(cherry picked from commit 15e720d5cee7b63497a223a8e49f1c5abf6d28ee)
> [2.6] avoid crash on wildcard query * (#3279)

- src/suffix.c
- tests/pytests/common.py
- tests/pytests/test_wildcard.py
* trie does not necessarily exist, even if it exists
* expanding test to work on coordinator
>  [2.6] - [4639] - Ephraim fix suffix cleanup (#3289)

- src/aggregate/aggregate.h
- src/aggregate/aggregate_exec.c
- src/config.c
- src/config.h
- tests/pytests/test_config.py
added 2 new configuration flags for multi-threading:
1. the number of threads to create (immutable after server launch)
2. enable/disable the multi-threading feature
> Multi thread configuration flags - [MOD-4565, MOD-4566]

- docs/docs/reference/Query_Syntax.md
> Query syntax: fix formatting issues 

- .gitmodules
- tests/pytests/test.py
(cherry picked from commit 29796ab5e6c45ad7166a78282566e8e1d069a902)
> [2.6] Dependency updates (readies, hiredis) (#3314)

- .gitmodules
- tests/pytests/test.py
(cherry picked from commit 29796ab5e6c45ad7166a78282566e8e1d069a902)
> [2.4] Dependency updates (readies, hiredis) (#3314)

- Makefile
- sbin/system-setup.py
(cherry picked from commit 9072e492c59d6bb51c7998d26c3610773575c0e5)
> [2.4] Build macOS with CLang (#3298)

- src/aggregate/expr/expression.c
- tests/pytests/test_issues.py
(cherry picked from commit eaaf404183f4edf449863936181e3c806b0231d0)
> [2.4] MOD-4296: Handling division by zero in expressions (#3357)

- CMakeLists.txt
changed to the new path to cmake of VecSim
> Update Vectorsimilarity submodule

- docs/docs/Indexing_JSON.md
fixing some typos in documentation after it was pointed out by #3392
> typo fixes

- src/aggregate/aggregate_exec.c
- src/aggregate/aggregate_request.c
- src/document.c
- src/ext/default.c
- src/query.c
- src/spec.c
- src/spec.h
- src/stopwords.c
- src/stopwords.h
- tests/cpptests/test_cpp_index.cpp
doing most of the TODOs related to multithreaded
removing some dead or unused code on the way for easier multithreaded maintenance.
> TODOs cleanup - [MOD-4726]

- deps/thpool/thpool.c
- deps/thpool/thpool.h
- src/concurrent_ctx.c
- src/document.c
- src/gc.c
- src/offset_vector.c
- src/spec.c
- src/tokenize.c
- src/util/mempool.c
- src/util/mempool.h
- src/value.c
- tests/cpptests/test_cpp_llapi.cpp
(cherry picked from commit 76a1545ce0320cdb2fc2382a1e02ab36b267a30e)
> [2.6] Protect mempool for async access (#3381)

- deps/thpool/thpool.c
- deps/thpool/thpool.h
- src/concurrent_ctx.c
- src/document.c
- src/gc.c
- src/offset_vector.c
- src/spec.c
- src/tokenize.c
- src/util/mempool.c
- src/util/mempool.h
- src/value.c
- tests/cpptests/test_cpp_llapi.cpp
(cherry picked from commit 76a1545ce0320cdb2fc2382a1e02ab36b267a30e)
> [2.4] Protect mempool for async access (#3381)

- src/result_processor.c
- tests/pytests/test_profile.py
> [2.6] Update Result Processor Name (#3379)

- src/util/minmax_heap.c
- tests/benchmarks/search-ftsb-10K-enwiki_abstract-hashes-fulltext-sortby.yml
* attempt to improve min-max heap
* some more optimization
* minor changes
* review fixes
* extended comment
* added a benchmark for big heap sorting
* changed BM
* improved comment
* added no content to benchmark
> [2.4] Min-Max heap performance improvement (#3430)

- commands.json
- docs/commands/ft.create.md
- docs/commands/ft.profile.md
- docs/commands/ft.search.md
Updates argument descriptions and examples
> [DOC UPDATE] Fixes multiple bugs

- src/hybrid_reader.c
> [2.4] [FIX] KNN search for 0 results with a filter fix - [MOD-5006] (#3468)

- src/hybrid_reader.c
- tests/pytests/test_vecsim.py
* handling k = 0 better
* added test for k = 0
> [2.6] [FIX] KNN search for 0 results with a filter fix - [MOD-5006] (#3468)

- src/fork_gc.c
We previously changed the fork GC so it does not need to lock the redis global lock in order to apply its changes to the spec's inverted indexes, but since we currently don't lock the spec for reading when performing a search (`FT.SEARCH`, `FT.AGGREGATE` or `FT.CURSER READ`), relying on the spec's R/W lock is not enough.
We currently can't simply lock the spec for reading when we run from the main thread, because without having a buffer as we have in the background, we might cause a deadlock with ourselves when opening a key that is expired and causes us to perform delete operation on the spec while we are still locked for reading.
A flag to disable executing expiration flow will be added in redis 7.2 and will fix the potential deadlock. Until then (for the milestone), we are bringing …
> Locking the GIL before locking the spec in the GC

- .circleci/config.yml
- tests/pytests/test_issues.py
Completion of #3466
Fix test to be deterministic (CI failed on bullseye and amz2 platforms)
> Completion of: Docs with a missing sortby field should be preceded by docs which have this field

- docs/docs/design/design.md
Please verify that the entire paragraph is still valid.
> Fixes 404 in design.md

- CMakeLists.txt
> vss 0.6.1 (#3534) - CP 2.6

- coord/src/dist_aggregate.c
- tests/pytests/test_aggregate.py
> cp #3557 to 2.6

- .circleci/config.yml
- coord/src/info_command.c
- deps/thpool/thpool.c
- deps/thpool/thpool.h
- src/info_command.c
- src/spec.c
- src/spec.h
- tests/pytests/common.py
- tests/pytests/test_geometry.py
> Fix flaky test of Geometry memory usage

- tests/pytests/test_multithread.py
Temporary to mute CI failures, until the crash in `Cursors_RenderStats` is solved
> Avoid FT.INFO after DEBUG RELOAD in tests

- src/aggregate/aggregate_exec.c
Fix TEST=test_cursors:testCursors
> Mark request as done in RESP2

- src/config.c
- src/config.h
- src/spec.c
- tests/pytests/test_async.py
- tests/pytests/test_config.py
> Slow background indexing fix [MOD-5259] [cherry-pick 2.6]

- tests/benchmarks/search-numeric-optimize.yml
- tests/benchmarks/search-numeric-sortby-desc-optimized.yml
- tests/benchmarks/search-numeric-sortby-optimized.yml
> [2.8] CP benchmark fix to 2.8

- .circleci/config.yml
- sbin/system-setup.py
- src/geometry/allocator/allocator.hpp
- src/geometry/allocator/stateful_allocator.hpp
- src/geometry/allocator/tracking_allocator.hpp
- src/geometry/geometry_api.cpp
- src/geometry/query_iterator.cpp
- src/geometry/query_iterator.hpp
- src/geometry/rtree.cpp
- src/geometry/rtree.hpp
- Updated readies
- Updated hiredis to v1.2.0
- Fix for installing modern gcc on centos7 for boost@conan
> Updated dependencies; fix for gcc/centos7

- tests/pytests/common.py
- tests/pytests/runtests.sh
- tests/pytests/test.py
- tests/pytests/test_multithread.py
replace #3732 (without feature prefix)
> Increase cluster node timeout

- tests/pytests/test_multithread.py
Reduce vectors some more to avoid flakiness
> Some more adjustments to vecsim MT tests

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
Quality of life
1. Added github actions files
> Added templates for PRs and issues

- docs/commands/ft.aggregate.md
- docs/commands/ft.search.md
adding argument `WITHCOUNT` 
explain the behaviour of SORT in `DIALECT 4`
1. #...
2. MOD...
1. ...
2. ...
> [DOCS] Improved Sorting syntax update ft.search.md and ft.aggregate.md

- src/aggregate/aggregate_request.c
- src/aggregate/expr/exprast.c
- src/document.c
- src/rlookup.c
- src/sortable.c
- src/sortable.h
- src/value.h
* minor improvements and typo fixes
* some more minor improvements
* making RSValue refcount atomic
* some review fixes
* reverted style
> [2.8] MOD-5707: making RSValue's refcount atomic (#3779)

- src/aggregate/functions/string.c
- src/value.h
- tests/pytests/test_json.py
> [2.8] MOD-5041: Fix `lower`, `upper` functions (#3771)

- src/aggregate/functions/string.c
- tests/pytests/test_json.py
> [2.6] MOD-5041: Fix `lower`, `upper` functions (#3771)

- coord/pack/ramp.yml
remove mt from pack - MOD-5716
> Cherry pick #3791 to 2.8

- deps/thpool/thpool.c
- deps/thpool/thpool.h
- src/concurrent_ctx.c
- src/config.c
- src/config.h
- src/gc.c
- src/hybrid_reader.c
- src/hybrid_reader.h
- src/module-init/module-init.c
- src/spec.c
- src/util/workers.c
- src/vector_index.c
- src/vector_index.h
- tests/cpptests/test_cpp_index.cpp
- tests/cpptests/test_cpp_thpool.cpp
- tests/pytests/test_config.py
> Vecsim CP [2.8.5]

- coord/src/dist_aggregate.c
- coord/src/dist_plan.cpp
- tests/pytests/test_aggregate.py
Cherry-picking for 2.8
1. #3808
2. #3814 
> [2.8] CP #3808, #3814

- tests/benchmarks/search-aggregate-post-filter-simple.yml
This PR extends the performance CI coverage WRT implicit loading on FILTER clauses. It includes a very lightweight query which should give us the largest possible impact difference in cases in which the implicit loading is affected.
> Include a lightweight FILTER with implicit load benchmark

- tests/cpptests/test_cpp_thpool.cpp
- tests/pytests/test_scorers.py
> [2.8] Fix tests in privileged threads and scoring

- coord/src/rmr/redis_cluster.c
On Redis 7.2 (specifically on 7.2-rc3) there was a change
made that allow running on cluster with both, tls and none
tls port.
As part of this change, `cluster slot` command will return the
port base of the connection type (tls or not tls). A side effect
of this change is that when `cluster slot` called using `RM_Call`
it is always gets the none tls port (which break our support of tls).
To fix this, use `RedisModule_GetClusterNodeInfo` Redis module API to
get the correct port.
Notice that this is a minimal fix, we should extend the Redis module API
to provide us with all the information we need (including slot range) so
we will not have to use `cluster slot` command at all. …
> CP 3837 to 2.10

- tests/pytests/test_async.py
> [2.8] MOD-5771: Remove flakiness from async indexing test

- tests/pytests/test_async.py
> [2.10] MOD-5771: Remove flakiness from async indexing test

- tests/pytests/test_resp3.py
Adds an aggregation test to the resp3 test-suite
> Add aggregation test

- coord/src/rmr/redis_cluster.c
On Redis 7.2 (specifically on 7.2-rc3) there was a change
made that allow running on cluster with both, tls and none
tls port.
As part of this change, `cluster slot` command will return the
port base of the connection type (tls or not tls). A side effect
of this change is that when `cluster slot` called using `RM_Call`
it is always gets the none tls port (which break our support of tls).
To fix this, use `RedisModule_GetClusterNodeInfo` Redis module API to
get the correct port.
Notice that this is a minimal fix, we should extend the Redis module API
to provide us with all the information we need (including slot range) so
we will not have to use `cluster slot` command at all.
> Fix tls on Redis 7.2 oss cluster (#3837)

- .circleci/config.yml
This PR removes dead automations form circle CI, so it will not fail builds
config.yml
> remove docker and dead automation

- docs/docs/_index.md
- docs/docs/index.md
- docs/docs/query/exact-match.md
- docs/docs/query/range.md
1. Changes in support of doc re-org
1. Doc re-org
1. docs/docs/<sundry>
Notes to @dmaier-redislabs: This PR includes moving docs/docs/index.md back to _index.md and includes new front matter 'hideListLinks: true', which, when combined with the redis-stack-website PR (pending), will allow you to hide list page links if so desired.
> Doc dmaier reorg

- .circleci/config.yml
- tests/pytests/test_vecsim.py
CP #3887 #3875 #3764 to 2.6
1. #...
2. MOD-5600 MOD-5816
1. ...
2. ...
> [2.6] Cherry-picks from master #3887 #3875 #3764 - fix macos build 

- docs/docs/advanced-concepts/stemming.md
1. The current state briefly: without examples in how to use the Stemmer and support to multiple languages
2. What is the change: add on example and how to apply the keyword on `LANGUAGE`support (at indexing and query)
1. #...
2. MOD...
1. ...
2. ...
> Update and adding language detailed example on stemming.md

- coord/src/config.c
- coord/src/config.h
- coord/src/dist_aggregate.c
- coord/src/module.c
- coord/src/rmr/command.c
- coord/src/rmr/command.h
- coord/src/rmr/rmr.c
- coord/src/rmr/rmr.h
- src/aggregate/aggregate_exec.c
- tests/pytests/test_cursors.py
> [2.6] Make users' cursors trigger cursor read at the shards when needed - [MOD-5580]

- .github/workflows/common-merge-and-nightly.yml
A dummy PR to test the new merge rules.
> Test merge rules

- tests/pytests/common.py
- tests/pytests/test_cursors.py
> [2.6] Fix flakiness of `testCursorOnCoordinator`

- .circleci/config.yml
- tests/pytests/test_cursors.py
- update `readies`
- Revert Python installation step
- shortened cursor test
> Fix macOS builds on 2.6

- README.md
- docs/docs/quickstart.md
1. Adds UTM information to RC "try-free" links.
1. DOC-2743
1. README.md
2. docs/docs/quickstart.md
> DOC-2743: add UTM parms to RC links

- .circleci/config.yml
- sbin/pack.sh
Fix arm package that has an incompatible filename
1. 
1. pack.sh
> Rename arm arch in pack filename

- coord/src/rmr/cluster.c
- coord/src/rmr/command.c
- coord/src/rmr/rmr.c
- tests/pytests/test_issues.py
> Fix crash in OSS upon adding a new node [2.6]

- src/debug_commads.c
- src/fork_gc.c
- tests/pytests/common.py
- tests/pytests/test_numbers.py
> [2.6] Fix uniquesum and cardinalities values corruption after gc - MOD-5815

- src/index.c
- src/index.h
- src/inverted_index.c
- src/inverted_index.h
- src/numeric_index.c
- src/redis_index.c
- src/tag_index.c
Some code cleanup related to [MOD-5646](https://redislabs.atlassian.net/browse/MOD-5646). This PR removes code duplications and unnecessary casting, in an attempt to make future bugs easier to fix, and their stack traces easier to understand.
[MOD-5646]: https://redislabs.atlassian.net/browse/MOD-5646?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Code cleanup for future events - [MOD-5646]

- src/geo_index.c
- src/geo_index.h
- src/query.c
- tests/pytests/common.py
- tests/pytests/test_geo.py
> [2.10] Enable geo queries to register to "On Reopen" - [MOD-5646] (#3914)

- src/geo_index.c
- src/geo_index.h
- src/query.c
- tests/pytests/common.py
- tests/pytests/test_geo.py
> [2.8] Enable geo queries to register to "On Reopen" - [MOD-5646] (#3914)

- coord/src/dist_aggregate.c
- coord/src/rmr/chan.c
- coord/src/rmr/chan.h
- coord/src/rmr/rmr.c
- coord/src/rmr/rmr.h
- src/cursor.c
- src/cursor.h
- src/spec.c
- tests/pytests/test_aggregate.py
- tests/pytests/test_cursors.py
- tests/pytests/test_json.py
> [2.8] Improvement for PR 3853 (cursor on coordinator) - [MOD-6089]

- coord/src/dist_aggregate.c
- coord/src/rmr/chan.c
- coord/src/rmr/chan.h
- coord/src/rmr/rmr.c
- coord/src/rmr/rmr.h
- src/cursor.c
- src/cursor.h
- src/spec.c
- tests/pytests/test_aggregate.py
- tests/pytests/test_cursors.py
- tests/pytests/test_json.py
> [2.10] Improvement for PR 3853 (cursor on coordinator) - [MOD-6089]

- src/geo_index.c
- src/geo_index.h
- src/query.c
- tests/pytests/common.py
- tests/pytests/test_geo.py
> [2.6] Enable geo queries to register to "On Reopen" - [MOD-5646] (#3914)

- src/value.c
> [2.6] Minor improvement to serializing numeric value

- Makefile
- tests/pytests/requirements.txt
- tests/pytests/runtests.sh
Backport of #3749 and #4023 to `2.6`.
> [2.6] Run flow tests with log-level Debug

- .github/workflows/stale.yml
Avoid automatically closing a stale PR.
1. #...
2. MOD...
1. ...
2. ...
> Remove automatic closing stale.yml

- coord/src/dist_aggregate.c
- coord/src/rmr/chan.c
- coord/src/rmr/chan.h
- coord/src/rmr/rmr.c
- coord/src/rmr/rmr.h
- src/cursor.c
- src/cursor.h
- src/spec.c
- tests/pytests/test_aggregate.py
- tests/pytests/test_cursors.py
- tests/pytests/test_json.py
> [2.6] Improvement for PR 3853 (cursor on coordinator) - [MOD-6089]

- src/fork_gc.c
Add a log message so we would have an indication if fork GC failed for some reason for external reasons - failure to create a pipe or a failure to create a fork process
> Add log messages when fork GC fails

- sbin/pack.sh
> Use aarch64 for arm [2.6]

- src/fork_gc.c
> add logs for failing fork GC [2.6]

- .circleci/config.yml
- sbin/get-redisjson
Update platform names in `get-redisjson` so we get the proper artifacts of RedisJSON from s3
> run platforms flows

- sbin/get-redisjson
Update platforms names in `get-redisjson` script so we would test against the right RedisJSIN artifact 
> Get right artifacts for testing redisjson

- .circleci/config.yml
Build for xenial in 2.6 (Akita) - this was removed probably by mistake
> Bring xenial back

- .github/workflows/event-pull_request.yml
- .github/workflows/event-release.yml
- .github/workflows/flow-build-artifacts.yml
- .github/workflows/flow-temp.yml
This PR introduces the `event-release.yml` workflow, which moves version snapshots on S3 buckets and auto-generates a version-bumping PR.
It also implements a caching mechanism for snapshot generation, to skip the nightly build if no changes were introduced on this day.
> GHA - refactor versioning - [MOD-5732]

- docs/docs/_index.md
- docs/docs/basic-constructs/query-constructs.md
- docs/docs/query/_index.md
- docs/docs/query/aggregation.md
- docs/docs/query/combined.md
- docs/docs/query/exact-match.md
- docs/docs/query/full-text.md
- docs/docs/query/geo-spatial.md
- docs/docs/query/range.md
- docs/docs/query/vector-search.md
Copy-edits of the newly re-organized S&Q query content.
> DOC-3138: copy-edits of new query re-org content

- .github/workflows/mariner2.yml
- .install/mariner2.sh
- sbin/get-redisjson
- sbin/upload-artifacts
- tests/pytests/runtests.sh
> [2.10] MOD-5868: Support Mariner2 OS using github actions (#3932)

- .github/workflows/mariner2.yml
- .install/mariner2.sh
- sbin/get-redisjson
- sbin/upload-artifacts
- tests/pytests/runtests.sh
> [2.8] MOD-5868: Support Mariner2 OS using github actions (#3932)

- .github/workflows/benchmark-trigger.yml
1. improved types for workflow
2. Remove a job from the flow:
1. job contained an unmaintained action that is about to be deprecated
2. one less job to run
> Improve Benchmark triggering

- .github/workflows/benchmark-flow.yml
- .github/workflows/event-merge-to-queue.yml
- .github/workflows/flow-linux-platforms.yml
- .github/workflows/flow-macos.yml
- .github/workflows/flow-temp.yml
- .github/workflows/task-test.yml
- .install/install_script.sh
> GHA refactor - post merge fixes

- README.md
1. Fixing the logo link
2. replacing and reordering badges
> GHA refactor - badges refresh

- .github/workflows/event-merge-to-queue.yml
- .github/workflows/flow-temp.yml
- .github/workflows/task-build-artifacts.yml
- .github/workflows/task-get-latest-tag.yml
- .github/workflows/task-get-linux-configurations.yml
- .github/workflows/task-test.yml
Tune the merge queue job to run a bit quicker and prepare for multiple redis-version to check against.
Doc: TBD
> GHA - Tune merge queue event for 2.6 - [MOD-6195]

- tests/pytests/test_cursors.py
When running on redis 6.0, `conn` might not get connected to the same shard as the internal connection of `env`, making the cursor it generates for the coordinator not available for the other connection.
Using the same connection (the `env` one), we don't get the flakiness
@MeirShpilraien Can you confirm if this behavior is strictly related to redis 6.0, or should we fix this on the master branch as well?
> Fix flakiness in testCursorOnCoordinator on redis 6.0

- .github/workflows/flow-build-artifacts.yml
- .github/workflows/flow-macos.yml
upgrading the macOS version on CI to pass the setup
see [passing CI](https://github.com/RediSearch/RediSearch/actions/runs/7124816221)
> CI - upgrade macos

- coord/src/module.c
- coord/src/rmr/redis_cluster.c
- coord/src/rmr/redis_cluster.h
- coord/src/rmr/rq.c
Fixing general flakiness when a shard is crashing on shutdown (sanitizer + coverage)
> Fix Coordinator Shutdown flakiness - [MOD-6073]

- coord/src/rmr/conn.c
- coord/src/rmr/endpoint.h
- tests/pytests/runtests.sh
- tests/pytests/test.py
> [2.8] Test oss global password - [MOD-6117]

- coord/src/rmr/conn.c
- coord/src/rmr/endpoint.h
- tests/pytests/runtests.sh
- tests/pytests/test.py
> [2.6] Test oss global password - [MOD-6117]

- coord/src/module.c
- coord/src/rmr/redis_cluster.c
- coord/src/rmr/redis_cluster.h
- coord/src/rmr/rq.c
- coord/src/search_cluster.c
- coord/src/search_cluster.h
> [2.6] Fix Coordinator Shutdown flakiness - [MOD-6073]

- coord/src/dist_aggregate.c
- src/aggregate/aggregate.h
- src/aggregate/aggregate_exec.c
- src/numeric_index.h
- src/profile.c
- src/profile.h
- src/result_processor.c
- tests/pytests/test.py
- tests/pytests/test_geo.py
- tests/pytests/test_issues.py
- tests/pytests/test_optimizer.py
- tests/pytests/test_profile.py
- tests/pytests/test_resp3.py
- tests/pytests/test_wildcard.py
> [2.8]MOD-6184: Return timeout errors from `FT.PROFILE` (#4165)

- src/config.c
- src/config.h
- src/index.c
- tests/pytests/test_config.py
- tests/pytests/test_issues.py
- tests/pytests/test_profile.py
- tests/pytests/test_scorers.py
> CP opt revert for precode [2.6] [MOD-5910]

- .github/workflows/task-backport_pr.yml
Fix infinite loop caused by using PAT
> Fix backport flow

- .github/workflows/event-pull_request.yml
- .github/workflows/flow-temp.yml
- .github/workflows/task-build-artifacts.yml
- .github/workflows/task-test.yml
- .install/build_package_requirments.txt
- .install/common_base_linux_mariner_2.0.sh
- .install/macos.sh
> [2.8] MOD-6273 Remove readies from macos setup

- .github/workflows/event-pull_request.yml
- .github/workflows/flow-temp.yml
- .github/workflows/task-build-artifacts.yml
- .github/workflows/task-test.yml
- .install/build_package_requirments.txt
- .install/common_base_linux_mariner_2.0.sh
- .install/macos.sh
> [2.6] MOD-6273 Remove readies from macos setup

- .github/workflows/task-backport_pr.yml
Use the official backport action now that it includes the output we wanted
> Fix backport action - use official action

- tests/pytests/test_contains.py
- tests/pytests/test_issues.py
- tests/pytests/test_wildcard.py
This PR modifies the wildcard and contains tests to run x10 times faster. In some cases, they took more than 5 minutes to execute
> Fix wildcard and contains tests - [MOD-5807]

- .circleci/config.yml
Disabling flows that we now trust GHA to do well
Currently keeping build jobs
> Disable unnecessary Circle flows - [MOD-6176]

- tests/pytests/test_contains.py
- tests/pytests/test_issues.py
- tests/pytests/test_wildcard.py
> [2.6] Fix wildcard and contains tests - [MOD-5807]

- tests/pytests/test_contains.py
- tests/pytests/test_issues.py
- tests/pytests/test_wildcard.py
> [2.8] Fix wildcard and contains tests - [MOD-5807]

- coord/pack/ramp.yml
- pack/ramp.yml
Minor fix to the capability name
1. MOD-6238
> MOD-6238: Change the capability name

- .circleci/config.yml
> [2.8] Disable unnecessary Circle flows - [MOD-6176]

- sbin/gen-test-certs
- tests/pytests/common.py
- tests/pytests/includes.py
- tests/pytests/runtests.sh
- tests/pytests/test.py
- tests/pytests/test_issues.py
> [2.8] Test TLS password - [MOD-6119]

- src/info_command.c
- tests/pytests/common.py
- tests/pytests/test_info.py
- tests/pytests/test_vecsim.py
(cherry picked from commit b0210840df139c78eae4f73c2224eccffb84b488)
PR #4236
> MOD-6198 Backport-4236-to-2.8

- src/debug_commads.c
- src/fields_global_stats.c
- src/fork_gc.c
- src/fork_gc.h
- src/gc.c
- src/gc.h
- src/module.c
- src/spec.c
- src/vector_index.c
- src/vector_index.h
- tests/pytests/test_debug_commands.py
- tests/pytests/test_issues.py
- tests/pytests/test_vecsim.py
> [2.8] Fix Freeing flow - GC and timers - [MOD-6276]

- .github/workflows/task-get-latest-tag.yml
Use `curl` retries to reduce the chance of failure
Validate the returned tag is not `null`, and fail if it is
> Improved getting tags workflow

- src/fork_gc.c
- tests/cpptests/redismock/redismock.cpp
> Fork GC cleanup

- src/rejson_api.h
- src/rlookup.c
- tests/pytests/test_expire.py
> [2.8] MOD-5769: open json key with flags  (#3916)

- docs/docs/query/_index.md
Adds an alias to correct a broken link.
> DOC-3220: add alias to correct broken link

- src/aggregate/aggregate_exec.c
- tests/pytests/test_async.py
> [2.8] MOD-6252: remove multi-threading timeout flakiness (#4257)

- .circleci/config.yml
> Build M1 for integ branch

- tests/pytests/test_issues.py
> [2.8] fix add new shard test

- src/debug_commads.c
- src/fork_gc.c
- src/gc.c
- src/gc.h
- tests/cpptests/test_cpp_forkgc.cpp
- tests/cpptests/test_cpp_llapi.cpp
- tests/pytests/test_issues.py
Removing unnecessary context allocation and freeing
> Fork gc code cleanup

- tests/pytests/test_expire.py
we skip this test for Redis versions below 7.2 due to a bug in PEXPIRE.
In older versions, a bug involving multiple time samplings during PEXPIRE execution can cause keys to prematurely expire, triggering a "del" notification and eliminating them from the index, thus missing from search results.
This impacts the test as the key should be included in the search results but return NULL upon access (i.e lazy expiration).
The bug was resolved in Redis 7.2, ensuring the test's stability.
1. #...
2. MOD-6022
1. ...
2. ...
> [MOD-6022] fix flakyness of test_expire:testExpireDocs

- coord/src/dist_aggregate.c
- src/spec.c
> [2.8] Fix NULL related bugs [MOD-6337, MOD-6336]

- tests/pytests/CMakeLists.txt
- tests/pytests/runtests.sh
Remove `_MAX_RESULTS_TO_UNSORTED_MODE` configuration from test suit
> remove test configuration for _MAX_RESULTS_TO_UNSORTED_MODE - [MOD-6113]

- tests/pytests/test_expire.py
> [2.6] [MOD-6022] fix flakyness of test_expire:testExpireDocs

- tests/pytests/test_cursors.py
1. Using the `env` for all search-related commands (same connection on cluster mode)
2. Better assertions with error messages for future issues
> Fix flakiness in testIndexDropWhileIdle - [MOD-5882]

- tests/pytests/test_cursors.py
> [2.8] Fix flakiness in testIndexDropWhileIdle - [MOD-5882]

- tests/pytests/test_cursors.py
> [2.6] Fix timeout flakiness of `testCursorOnCoordinator` - [MOD-6253]

- tests/pytests/test_cursors.py
Fixing a rare flakiness when some shard wasn't able to respond quickly enough and we dropped the index before the BG thread could execute the query.
This PR modifies the test so we must get results from all the shards before moving to drop the index, which will guarantee that all the shards calculated the results before we dropped the index.
> Fix `testIndexDropWhileIdleBG` premature drop flakiness - [MOD-6318]

- tests/pytests/test_issues.py
> [2.6] CP unflake test mod5778_add_new_shard_to_cluster [MOD-6335]

- .github/ISSUE_TEMPLATE/feature_request.md
- .github/workflows/event-merge-to-queue.yml
- .github/workflows/event-nightly.yml
- .github/workflows/event-pull_request.yml
- .github/workflows/event-push-to-integ.yml
- .github/workflows/event-release.yml
- .github/workflows/flow-build-artifacts.yml
- .github/workflows/flow-linux-platforms.yml
- .github/workflows/flow-temp.yml
- .github/workflows/task-assign-for-issue.yml
- .github/workflows/task-backport_pr.yml
- .github/workflows/task-check-docs.yml
- .github/workflows/task-get-latest-tag.yml
- .github/workflows/task-test.yml
- .github/workflows/task-website-deploy.yml
- sbin/unit-tests
- tests/pytests/requirements.txt
- tests/pytests/runtests.sh
1. Failing faster CI
2. build snapshots on every code push, not on nightly
3. Assign only bug-labeled issues to the one in issues duty
4. Make macOS test flow use parallelism
5. Get all test logs in case of failure (whether it is a sanitizer failure or not)
> improve GHA workflows - [MOD-6404]

- .github/workflows/event-merge-to-queue.yml
- .github/workflows/event-nightly.yml
- .github/workflows/event-pull_request.yml
- .github/workflows/event-push-to-integ.yml
- .github/workflows/event-release.yml
- .github/workflows/flow-build-artifacts.yml
- .github/workflows/flow-linux-platforms.yml
- .github/workflows/task-check-docs.yml
- .github/workflows/task-get-latest-tag.yml
- .github/workflows/task-test.yml
- .github/workflows/task-website-deploy.yml
- sbin/unit-tests
- tests/pytests/requirements.txt
- tests/pytests/runtests.sh
> [2.6] improve GHA workflows - [MOD-6404]

- src/debug_commads.c
- tests/pytests/test_vecsim.py
Increase GC threshold in tests where number of vectors is higher than the threshold to avoid false leaks in forks in sanitizer
> Fix sanitizer warning false leak in vecsim tests [MOD-6229]

- .github/workflows/event-merge-to-queue.yml
- .github/workflows/event-nightly.yml
- .github/workflows/event-pull_request.yml
- .github/workflows/event-push-to-integ.yml
- .github/workflows/event-release.yml
- .github/workflows/flow-build-artifacts.yml
- .github/workflows/flow-linux-platforms.yml
- .github/workflows/flow-temp.yml
- .github/workflows/task-check-docs.yml
- .github/workflows/task-get-latest-tag.yml
- .github/workflows/task-test.yml
- .github/workflows/task-website-deploy.yml
- sbin/unit-tests
- tests/pytests/requirements.txt
- tests/pytests/runtests.sh
> [2.8] improve GHA workflows - [MOD-6404]

- docs/docs/advanced-concepts/dialects.md
Documentation change only: adding a new dialect reference page for redis.io.
@adrianoamaral Please review, approve, and merge.
> DOC-3152: add a dialect reference page to redis.io

- src/synonym_map.c
- tests/pytests/test_synonyms.py
> [2.6] Fix a Leak in Synonym - [MOD-6490]

- src/synonym_map.c
- tests/pytests/test_synonyms.py
> [2.8] Fix a Leak in Synonym - [MOD-6490]

- src/debug_commads.c
- tests/pytests/common.py
- tests/pytests/test_debug_commands.py
- tests/pytests/test_replicate.py
> [2.6] Reenable replication tests - [MOD-6181]

- coord/src/rmr/cluster.c
- coord/src/rmr/conn.c
- coord/src/rmr/conn.h
- src/util/dict.c
- src/util/dict.h
- tests/memcheck/asan.supp
replace MRConnManager map trie with dict
> MOD-6489 replace MRConnManager map trie with dict

- tests/pytests/test_profile.py
- tests/pytests/test_resp3.py
Adds more docs to a test to avoid possible flakiness in cases of very fast machines.
> MOD-6382: Fix supposedly flaky test

- .github/workflows/task-test.yml
- sbin/memcheck-summary
- sbin/unit-tests
- tests/pytests/runtests.sh
> [2.6] Add verbosity to sanitizer [MOD-6315]

- coord/src/rmr/redis_cluster.c
- src/json.c
- src/redis_index.c
- src/spec.c
- src/tag_index.c
changing some of the logs that use non-existing log levels with the appropriate ones.
> Fix non-existing log levels

- coord/src/rmr/redis_cluster.c
- src/json.c
- src/redis_index.c
- src/spec.c
- src/tag_index.c
> [2.6] Fix non-existing log levels

- src/debug_commands.c
- src/document.c
- src/gc.c
- src/inverted_index.h
- src/module.c
- src/query.c
- src/rdb.c
- src/rules.c
- src/rules.h
- src/spec.c
- src/tag_index.c
- src/tag_index.h
- src/util/references.c
> Tidying up

- coord/src/module.c
- tests/pytests/test_issues.py
> [2.8] Fix unblocking client with no reply on SEARCH cluster mode - [MOD-6557]

- coord/src/module.c
- coord/src/rmr/rmr.c
- coord/src/rmr/rmr.h
- tests/pytests/test_issues.py
> [2.6] Fix unblocking client with no reply on SEARCH cluster mode - [MOD-6557]

- src/geometry/geometry_api.cpp
- src/geometry/query_iterator.cpp
- src/geometry/query_iterator.hpp
- src/geometry/rtree.cpp
- src/geometry/rtree.hpp
- tests/pytests/runtests.sh
- tests/pytests/test_geometry_sphere.py
Backport of https://github.com/RediSearch/RediSearch/pull/4313 to 2.8
1. [MOD-6513](https://redislabs.atlassian.net/browse/MOD-6513)
2. [MOD-6431](https://redislabs.atlassian.net/browse/MOD-6431)
[MOD-6513]: https://redislabs.atlassian.net/browse/MOD-6513?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOD-6431]: https://redislabs.atlassian.net/browse/MOD-6431?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
>  [2.8] [GeoShape] memory allocation patterns - [MOD-6513, MOD-6431]

- .github/workflows/flow-temp.yml
- .install/ubuntu_20.04.sh
1. #...
2. MOD...
1. ...
2. ...
> MOD-6593 build ubuntu20 script

- .github/workflows/flow-temp.yml
- .github/workflows/task-test.yml
- .install/rocky_linux_9.sh
- .install/ubuntu_20.04.sh
1. #...
2. MOD...
1. ...
2. ...
> MOD-6590 install script for rocky9

- .github/workflows/flow-self-hosted-arm.yml
- .github/workflows/self-hosted.yml.TEMPLATE
Add name and other useful tags to the EC2 instances we launch from the CI
1. [RED-120031](https://redislabs.atlassian.net/browse/RED-120031)
[RED-120031]: https://redislabs.atlassian.net/browse/RED-120031?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add tags to EC2 instances - [RED-120031]

- .circleci/config.yml
- sbin/system-setup.py
1. #...
2. MOD...
1. ...
2. ...
> remove macos requirments from system setup as it no longer exists

- .circleci/config.yml
- sbin/system-setup.py
> [2.6] remove macos and linux requirments from system setup

- .circleci/config.yml
- sbin/system-setup.py
> [2.8] remove macos and linux requirments from system setup

- tests/pytests/test_replicate.py
> [2.6] Fix testDelReplicate flakiness - [MOD-6500]

- src/util/references.c
> [2.8] added debug logging for freeing and creating a ref manager (#3740)

- tests/pytests/common.py
- tests/pytests/test_multithread.py
CP the test fix part only from #4401 (the debug command is supported only on master where we use vecsim main)
> [2.8] Fix flaky async vecsim updates with MT [MOD-6496]

- .github/workflows/flow-sanitizer.yml
> [2.6] Use clang 17 for sanitizer (#4519)

- .github/workflows/flow-sanitizer.yml
> [2.8] Use clang 17 for sanitizer

- src/geometry/rtree.cpp
- tests/pytests/test_geometry_flat.py
> [2.8] MOD-6701: Passing more descriptive error messages

- src/index.c
- tests/pytests/test_issues.py
WIP - **Describe the changes in the pull request**
Simple patch to MOD 6599 without modifying `NewUnionIterator()`
Replace #4495
1. #...
2. MOD...
1. ...
2. ...
> [2.8] MOD-6599 patch v2

- tests/pytests/common.py
- tests/pytests/test_short_read.py
> [2.8] MOD-6833  Fix timeout in test_short_reads 

- tests/pytests/common.py
- tests/pytests/test_short_read.py
> [2.10] MOD-6833 Fix timeout in test_short_reads 

- src/aggregate/aggregate_exec.c
- tests/pytests/test.py
Fixes a flaky test due to timeout.
> Fix flaky test (timeout)

- .github/workflows/event-release.yml
Following a bug probably in GHA - add validation that the release branch matches the tag
> Validate version branch upon release

- tests/pytests/runtests.sh
Fixing test script to run coordinator tests faster
> fix runtests.sh

- src/aggregate/aggregate_request.c
- src/language.h
- src/redisearch_api.c
- tests/cpptests/test_cpp_llapi.cpp
- tests/pytests/test_json.py
- tests/pytests/test_language.py
> [2.10] MOD-5740: Default querying language

- src/aggregate/functions/string.c
Backporting of #4613 to `2.6`.
> [2.6] Fix MOD-6759

- coord/pack/ramp.yml
- pack/ramp-light.yml
- pack/ramp.yml
Use the current latest available redis versions in master branch to test it properly (until redis 7.4 is available) 
> Update redis min/compatible version

- src/value.c
Removing unnecessary dereferences, allocations, and definitions
> value's mempool cleanup

- src/aggregate/aggregate_exec.c
- tests/pytests/test_cursors.py
Fix error reply on bad arguments for cursor read
> Fix cursor error

- src/config.c
- tests/pytests/test_multithread.py
Add a limit to the maximal number of threads we can use for `WORKER_THREADS`
> Limit the number of worker threads - [MOD-7011]

- src/value.c
Backporting of #4617 to `2.6`.
> [2.6] value's mempool cleanup

- tests/pytests/common.py
- tests/pytests/test_issues.py
In an attempt to fix a flakiness when the cluster is not ready
> Add a retry mechanism to verify_shard_init - [MOD-7139]

- src/spec.c
2.6 variant of #4706. Changing the log level of a loading event log message
1. #4704 
> MOD-7181: Change log level of a log message

- .github/workflows/event-merge-to-queue.yml
- .github/workflows/event-pull_request.yml
(cherry picked from commit 6f9d48a17605a8121fb3b99d7acadd81f9a37951)
> [2.10] redis 7.4 (#4716)

- .github/workflows/event-release.yml
> subscribed to publish instead of released (#4722)

- src/toksep.h
- tests/cpptests/test_cpp_tokenizer.cpp
- tests/pytests/test_issues.py
> MOD-7240: Detect escape state when tokenizing

- tests/pytests/common.py
- tests/pytests/test_rdb_compatibility.py
- tests/pytests/test_short_read.py
Update the path of the rdbs we use for our tests to our S3 bucket.
> [2.6] MOD-7256: Fix rdbs base url

- tests/pytests/common.py
- tests/pytests/test_rdb_compatibility.py
- tests/pytests/test_short_read.py
Update the path of the rdbs we use for our tests to our S3 bucket.
> [2.8] MOD-7256: Fix rdbs base url

- .github/workflows/flow-temp.yml
leftovers from PR https://github.com/RediSearch/RediSearch/pull/4725
> disable temp flow

- .github/workflows/event-deploy-snapshots.yml
- .github/workflows/event-push-to-integ.yml
- .github/workflows/event-release.yml
- .github/workflows/task-backport_pr.yml
- .github/workflows/task-check-docs.yml
> [2.6] Release flow improvement - [MOD-7287]

- .github/workflows/event-deploy-snapshots.yml
- .github/workflows/event-push-to-integ.yml
- .github/workflows/event-release.yml
- .github/workflows/task-backport_pr.yml
- .github/workflows/task-check-docs.yml
> [2.8] Release flow improvement - [MOD-7287]

- sbin/pack.sh
Set the M1 artifact name to the expected name
> Fix M1 artifact name

- .github/workflows/flow-build-artifacts.yml
> [2.10] Fix fail fast on snapshot build workflow

- .github/workflows/flow-build-artifacts.yml
> [2.8] Fix fail fast on snapshot build workflow

- .github/workflows/flow-build-artifacts.yml
> Fix fail fast on snapshot build workflow (#4784)

- coord/src/rmr/rmr.c
- src/aggregate/aggregate_exec.c
- src/aggregate/expr/expression.c
- src/debug_commands.c
- src/index.c
- src/info/field_spec_info.c
- src/info/index_error.c
- src/info_command.c
- src/module.c
- src/module.h
- src/profile.c
- src/reply.c
- src/reply.h
- src/reply_macros.h
- tests/pytests/common.py
- tests/pytests/test_issues.py
> [2.8] Fix crucial simple string misuse - [MOD-7258]

- coord/src/rmr/rmr.c
- src/aggregate/expr/expression.c
- src/debug_commads.c
- src/info_command.c
- src/module.c
- src/profile.c
- src/reply_macros.h
- tests/pytests/common.py
- tests/pytests/test_issues.py
> [2.6] Fix crucial simple string misuse - [MOD-7258]

- tests/pytests/test_rdb_compatibility.py
Fix test flakiness. By not using threads we guarantee consistent HNSW graphs
> Fix test flakiness testRDBCompatibility_vecsim

- src/aggregate/aggregate_exec.c
- src/result_processor.c
- src/result_processor.h
- tests/pytests/test_expire.py
- tests/pytests/test_replicate.py
backport [MOD-7010] Return None when key expires during query (#4777)
[MOD-7010]: https://redislabs.atlassian.net/browse/MOD-7010?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [2.8 MOD-7010] Return None when key expires during query

- .github/workflows/task-backport_pr.yml
assign the PR owner to review the backport PRs, instead of the original reviewers
> Backport - assign the PR owner to review the backport PRs

- .github/workflows/task-build-artifacts.yml
- .github/workflows/task-test.yml
> [2.8] GHA better node16/20 handle

- .github/workflows/task-build-artifacts.yml
- .github/workflows/task-test.yml
> [2.6] GHA better node16/20 handle

- .github/workflows/flow-build-artifacts.yml
- .github/workflows/flow-macos.yml
Fix macOS-apple silicone version on all existing versions.
> Fix ARM macOS version to 13

- .github/workflows/flow-build-artifacts.yml
- .github/workflows/flow-macos.yml
> [2.6] Fix ARM macOS version to 13

- .github/workflows/flow-build-artifacts.yml
- .github/workflows/flow-macos.yml
> [2.8] Fix ARM macOS version to 13

- coord/src/cluster_spell_check.c
- coord/src/dist_aggregate.c
- coord/src/dist_plan.cpp
- coord/src/info_command.c
- coord/src/module.c
- deps/triemap/triemap.c
- src/aggregate/aggregate_plan.c
- src/aggregate/aggregate_request.c
- src/aggregate/expr/exprast.c
- src/concurrent_ctx.c
- src/document_basic.c
- src/fork_gc.c
- src/hybrid_reader.c
- src/module.c
- src/numeric_index.c
- src/query.c
- src/query_parser/v1/parser.c
- src/query_parser/v1/parser.y
- src/query_parser/v2/parser.c
- src/query_parser/v2/parser.y
- src/rules.c
- src/rwlock.c
- src/spec.c
- src/spell_check.c
- src/synonym_map.c
- src/tag_index.c
- src/util/arr.h
- src/value.c
- src/vector_index.c
- tests/cpptests/test_cpp_arr.cpp
> [2.8] MOD-7355: Remove unnecessary assignments

- tests/pytests/requirements.txt
- tests/pytests/test_missing.py
Adds coverage for the functionality of the GC over the missing values index recently added.
> MOD-7415: Add coverage for missing indexing GC

- tests/pytests/test_missing.py
> Fix flaky test

- tests/pytests/test_missing.py
Fixes the env-overriding in `test_missing.py`.
> Fix env overriding

- .github/workflows/event-release.yml
Add team leaders (hard-coded) to review auto-generated version-bump PRs, to decrease the chance they will be forgotten
> Add team leaders to review auto version bump PRs

- .github/workflows/task-get-linux-configurations.yml
- .install/rocky_linux_9.sh
Support rhel9 arm64.
Tests: https://github.com/RediSearch/RediSearch/actions/runs/9974759759
https://github.com/RediSearch/RediSearch/actions/runs/9985118772
Which issues this PR fixes
1. MOD-7423
Main objects this PR modified
1. Github workflows
> MOD-7423: Support rhel9 arm64

- .github/workflows/event-release.yml
> [2.6] Add team leaders to review auto version bump PRs

- .github/workflows/event-release.yml
> [2.8] Add team leaders to review auto version bump PRs

- coord/src/dist_aggregate.c
- tests/pytests/test_issues.py
> [2.6] VERBATIM is not passed to the shards on FT.AGGREGATE - [MOD-7463]

- coord/src/dist_aggregate.c
- tests/pytests/test_issues.py
> [2.8] VERBATIM is not passed to the shards on FT.AGGREGATE - [MOD-7463]

- tests/pytests/test.py
> [2.6] Fix flakiness in test:test_cluster_set - [MOD-7228]

- tests/pytests/test.py
> [2.8] Fix flakiness in test:test_cluster_set - [MOD-7228]

- Makefile
> Fix ramp.yml path - to enable proper packing after moving coordinator code

- src/coord/module.c
- tests/pytests/test_config.py
Register the `FT.CONFIG` command if cluster mode is disabled.
> Register the `FT.CONFIG` command if cluster mode is disabled - [MOD-7444]

- src/query_parser/v1/parser.c
- src/query_parser/v1/parser.y
- src/query_parser/v2/parser.c
- src/query_parser/v2/parser.y
- tests/pytests/test_issues.py
- tests/pytests/test_parser.py
> [2.6] Fix union of stopwords - [MOD-7495]

- src/query_parser/v1/parser.c
- src/query_parser/v1/parser.y
- src/query_parser/v2/parser.c
- src/query_parser/v2/parser.y
- tests/pytests/test_issues.py
- tests/pytests/test_parser.py
> [2.8] Fix union of stopwords - [MOD-7495]

- src/query_parser/v1/parser.c
- src/query_parser/v1/parser.y
- src/query_parser/v2/parser.c
- src/query_parser/v2/parser.y
- tests/pytests/test_issues.py
- tests/pytests/test_parser.py
> [2.10] Fix union of stopwords - [MOD-7495]

- src/config.c
- src/config.h
- src/module-init/module-init.c
- tests/pytests/test_config.py
> [2.10] Support the deprecated MT configs again - [MOD-7519]

- src/coord/debug_command_names.h
- src/coord/debug_commands.c
- src/coord/rmr/redis_cluster.c
- src/coord/rmr/redis_cluster.h
- tests/pytests/test.py
- tests/pytests/test_debug_commands.py
Another iteration on the test flakiness, this time using debug commands to disable the periodic topology refresh timer
> Fix flakiness - [MOD-7228]

- src/spec.c
> [2.6] MOD-7339: Fix field statistics counting bug (#4919)

- coord/src/debug_command_names.h
- coord/src/debug_commands.c
- coord/src/rmr/redis_cluster.c
- coord/src/rmr/redis_cluster.h
- tests/pytests/test.py
- tests/pytests/test_debug_commands.py
> [2.10] Fix flakiness - [MOD-7228]

- coord/src/dist_aggregate.c
- src/aggregate/aggregate.h
- src/aggregate/aggregate_exec.c
- src/index.c
- src/profile.c
- src/profile.h
- src/query.c
- src/query_error.h
- tests/pytests/test_profile.py
- tests/pytests/test_resp3.py
> [2.8]MOD-7588: Add warning for reaching MAXPREFIXEXPANSIONS

- coord/src/dist_aggregate.c
- src/aggregate/aggregate.h
- src/aggregate/aggregate_exec.c
- src/index.c
- src/profile.c
- src/profile.h
- src/query.c
- src/query_error.h
- tests/pytests/test_profile.py
- tests/pytests/test_resp3.py
> [2.10] MOD-7588: Add warning for reaching MAXPREFIXEXPANSIONS

- src/coord/pack/ramp.yml
1. #...
2. MOD...
1. ...
2. ...
> MOD-7505 override ft.search on ramp

- src/query.c
- tests/pytests/test_resp3.py
> Small completion for TAG wildcard fix

- src/index.c
- tests/pytests/test_issues.py
>  [2.6] Fix numeric union reopen on profile [MOD-7454]

- src/coord/rmr/rmr.c
- src/coord/rmr/rq.c
- tests/pytests/test_coordinator.py
Add missing calls to `MR_requestCompleted`
> Fix coordinator pending count - [MOD-7632]

- .github/workflows/event-mirror.yml
We would like to conditionally mirror the repository to a different repository
1. Current state: no such support
2. Change: Add a CI step to conditionally mirror the branch
3. Outcome: Conditionally mirror certain branches
1. MOD-7596
1. CI Flow
> MOD-7596: Add mirroring support

- coord/src/rmr/rmr.c
- coord/src/rmr/rq.c
- tests/pytests/test_coordinator.py
`2.10` version of #4960
Add missing calls to `MR_requestCompleted`
> [2.10] Fix coordinator pending count - [MOD-7632]

- coord/src/rmr/rmr.c
- coord/src/rmr/rq.c
- tests/pytests/test_coordinator.py
`2.6` version of #4960
Add missing calls to `MR_requestCompleted`
> [2.6] Fix coordinator pending count - [MOD-7632]

- .github/workflows/event-merge-to-queue.yml
- .github/workflows/event-nightly.yml
- .github/workflows/event-pull_request.yml
- .github/workflows/event-release.yml
- .github/workflows/task-build-artifacts.yml
Manual [backport](https://github.com/RediSearch/RediSearch/pull/4965).
> [2.8] MOD-7560: Conditionally Use AWS Role To Upload Artifacts

- .github/workflows/event-merge-to-queue.yml
- .github/workflows/event-nightly.yml
- .github/workflows/event-pull_request.yml
- .github/workflows/event-release.yml
- .github/workflows/task-build-artifacts.yml
Manual [backport](https://github.com/RediSearch/RediSearch/pull/4965).
> [2.10] MOD-7560: Conditionally Use AWS Role To Upload Artifacts

- .install/build_package_requirments.txt
This PR is setting a fixed version of `ramp-packer` python module
MOD-7706
build_package_requirments.txt
> [2.6] MOD-7706 fix ramp-packer version

- .install/build_package_requirments.txt
This PR is fixing the version for `ramp-packer` python module
MOD-7706
build_package_requirments.txt
> [2.8] MOD-7706 fix ramp-packer version

- .install/build_package_requirments.txt
This PR is fixing the version for `ramp-packer` python module
MOD-7706
build_package_requirments.txt
> MOD-7706 fix ramp-packer version

- tests/pytests/includes.py
- tests/pytests/test_vecsim.py
CP #4964 to 2.10, update vecsim version to the new matching patch 0.8.1
> [2.10] HNSW vector index - handle in-place deletion after async [MOD-7643]

- .install/rocky_linux_8.sh
- .install/rocky_linux_9.sh
> [2.10] MOD-7737: Add relaxation flags to Rocky9 installations (#4989)

- .install/rocky_linux_8.sh
- .install/rocky_linux_9.sh
- .install/ubuntu_22.04.sh
> [2.6] MOD-7737: Add relaxation flags to Rocky9 installations (#4989)

- .install/rocky_linux_8.sh
- .install/rocky_linux_9.sh
- .install/ubuntu_22.04.sh
> [2.8] MOD-7737: Add relaxation flags to Rocky9 installations (#4989)

- .github/workflows/event-deploy-snapshots.yml
> Improve snapshot notifyer

- src/rules.c
- src/rules.h
- src/spec.c
- tests/pytests/test_json.py
> [2.10] Fail to load a schema rule from RDB without asserting - [MOD-7587]

- src/rules.c
- src/rules.h
- src/spec.c
- tests/pytests/test_json.py
> [2.8] Fail to load a schema rule from RDB without asserting - [MOD-7587]

- src/rules.c
- src/rules.h
- src/spec.c
- tests/pytests/test_json.py
> [2.6] Fail to load a schema rule from RDB without asserting - [MOD-7587]

- src/config.h
- src/util/workers.c
- tests/pytests/test_config.py
- tests/pytests/test_multithread.py
- tests/pytests/test_vecsim.py
Update vecsim version to include the fix in https://github.com/RedisAI/VectorSimilarity/pull/543
+
revert the workaround where we did not close thread pool to avoid the bug.
> [2.10] Avoid adding connection to marked deleted elements upon delete in-place in HNSW index [MOD-7732]

- README.md
Test backporting a PR
1. #...
2. MOD...
1. ...
2. ...
> Test Backport

- .github/workflows/task-backport_pr.yml
Add backport logic into this master_jk_test branch
1. #...
2. MOD...
1. ...
2. ...
> * use github app token for backporting workflow

- .github/workflows/task-backport_pr.yml
- README.md
1. #...
2. MOD...
1. ...
2. ...
> Master jk test 3

- sbin/upload-artifacts
> Update artifact name to upload after renaming oss to community

- tests/pytests/test_not.py
1. Current State:
`test_not:test_not_optimized` is flaky.
The names are being generated with prefixes, such as **Mr** and **Ms**, and suffixes. A set is used to avoid duplicates, but the test query can generate flaky behavior:
```sh
FT.CREATE idx indexall enable schema t text
HSET doc1 t 'John Doe'
HSET doc2 t 'Mr John Doe'
HSET doc3 t 'Bruce Wayne'
127.0.0.1:6379> FT.SEARCH idx '-(@t:Bruce Wayne)' dialect 2 LIMIT 0 0
1) (integer) 2
127.0.0.1:6379> FT.SEARCH idx '-(@t:John Doe)' dialect 2 LIMIT 0 0
1) (integer) 1
```
2. What is the change:
Generates random names using only first name and last name without any prefix or suffix.
1. MOD-7905
1. ...
2. ...
> MOD-7905: Fix test_not:test_not_optimized

- src/query.c
- src/spec.c
- tests/pytests/test_vecsim.py
> [2.6] Improve Error Message on VecSim Syntax Error - [MOD-7887]

- src/query.c
- src/spec.c
- tests/pytests/test_vecsim.py
> [2.10] Improve Error Message on VecSim Syntax Error - [MOD-7887]

- coord/src/debug_command_names.h
- coord/src/debug_commands.c
- coord/src/rmr/rq.c
- coord/src/rmr/rq.h
- tests/pytests/test.py
> [2.10] Remove an unnecessary assertion - [MOD-8008]

- src/coord/debug_command_names.h
- src/coord/debug_commands.c
- src/coord/rmr/rq.c
- src/coord/rmr/rq.h
- tests/pytests/test.py
- tests/pytests/test_debug_commands.py
> [8.0] Remove an unnecessary assertion - [MOD-8008]

- coord/src/dist_aggregate.c
- coord/src/module.c
- src/aggregate/aggregate_exec.c
- src/global_stats.c
- src/global_stats.h
- tests/pytests/common.py
- tests/pytests/test_info_modules.py
> [2.10] Add a counter of total query execution time - [MOD-7961]

- src/document.c
- src/field_spec.c
- src/field_spec.h
- src/global_stats.c
- src/global_stats.h
- src/indexer.c
- src/info_command.h
- src/module-init/module-init.c
- src/redisearch_api.c
- src/spec.c
- src/spec.h
- tests/pytests/test_index_error.py
- tests/pytests/test_info_modules.py
> [2.10] [MOD-8034] expose indexing failures to INFO modules

- coord/src/dist_aggregate.c
- coord/src/rmr/chan.c
- coord/src/rmr/chan.h
- coord/src/rmr/rmr.c
- coord/src/rmr/rmr.h
- coord/src/rmr/test/test_chan.c
- src/config.c
- src/config.h
- src/cursor.c
- src/cursor.h
- src/spec.c
- src/spec.h
- src/util/misc.c
- src/util/misc.h
- tests/ctests/test_error_parsing.c
- tests/pytests/test_config.py
- tests/pytests/test_cursors.py
Manual backport of #5137 to 2.8.
> [2.8] MOD-8009: Allow Users To Configure Cursor Index Limitation Through Global Config

- coord/src/dist_aggregate.c
- coord/src/rmr/chan.c
- coord/src/rmr/chan.h
- coord/src/rmr/rmr.c
- coord/src/rmr/rmr.h
- coord/src/rmr/test/test_chan.c
- src/config.c
- src/config.h
- src/cursor.c
- src/cursor.h
- src/spec.c
- src/spec.h
- src/util/misc.c
- src/util/misc.h
- tests/ctests/test_error_parsing.c
- tests/pytests/test_config.py
- tests/pytests/test_cursors.py
Manual backport of #5137 to 2.10.
> [2.10] MOD-8009: Allow Users To Configure Cursor Index Limitation Through Global Config

- coord/src/dist_aggregate.c
- coord/src/module.c
- coord/src/rmr/chan.c
- coord/src/rmr/chan.h
- coord/src/rmr/rmr.c
- coord/src/rmr/rmr.h
- coord/src/rmr/test/test_chan.c
- src/config.c
- src/config.h
- src/cursor.c
- src/cursor.h
- src/spec.c
- src/util/misc.c
- src/util/misc.h
- tests/ctests/test_error_parsing.c
- tests/pytests/test_config.py
Manual backport of #5137 to 2.6.
> [2.6] MOD-8009: Allow Users To Configure Cursor Index Limitation Through Global Config

- .github/workflows/task-test.yml
Manual backport of #5134 to 2.10.
> [2.10] MOD-8010: Print Step Summary In Workflow On Failure

- .github/workflows/task-test.yml
Manual backport of #5134 to 2.8.
> [2.8] MOD-8010: Print Step Summary In Workflow On Failure

- src/debug_commads.c
- src/document.c
- src/fork_gc.c
- src/indexer.c
- src/indexer.h
- src/inverted_index.c
- src/module.c
- src/numeric_index.c
- src/numeric_index.h
- src/query.c
- src/redis_index.c
- src/redis_index.h
- src/spec.c
- src/spell_check.c
- src/tag_index.c
- src/tag_index.h
- tests/cpptests/test_cpp_forkgc.cpp
> [2.6] Performance improvement in indexBulkFields - [MOD-8093]

- src/debug_commands.c
- src/document.c
- src/fork_gc.c
- src/geometry_index.c
- src/geometry_index.h
- src/indexer.c
- src/indexer.h
- src/info_command.c
- src/inverted_index.c
- src/module.c
- src/numeric_index.c
- src/numeric_index.h
- src/query.c
- src/redis_index.c
- src/redis_index.h
- src/spec.c
- src/spell_check.c
- src/tag_index.c
- src/tag_index.h
- tests/cpptests/test_cpp_forkgc.cpp
> [8.0] Performance improvement in indexBulkFields - [MOD-8093]

- src/debug_commands.c
- src/numeric_index.c
- src/numeric_index.h
- tests/pytests/test_numbers.py
> [2.8] Fix Numeric Tree Balance - [MOD-8081, MOD-8082]

- src/debug_commands.c
- src/numeric_index.c
- src/numeric_index.h
- tests/pytests/test_numbers.py
> [2.10] Fix Numeric Tree Balance - [MOD-8081, MOD-8082]

- tests/pytests/runtests.sh
Temporarly diable RLTest progress bar so `make test` will not throw an error
1. #...
2. MOD...
1. ...
2. ...
> Disable RLTest progress bar

- src/numeric_index.c
Code cleanup and reduce code duplication
> Cleanup for the trimming tree logic

- src/debug_commands.c
- src/document.c
- src/fork_gc.c
- src/inverted_index.h
- src/numeric_index.c
- src/numeric_index.h
- src/redis_index.h
- src/redisearch_api.c
- src/spec.c
- src/spec.h
- tests/cpptests/benchmark_vecsim_hybrid_queries.cpp
- tests/cpptests/index_utils.cpp
- tests/cpptests/index_utils.h
- tests/cpptests/test_cpp_extensions.cpp
- tests/cpptests/test_cpp_forkgc.cpp
- tests/cpptests/test_cpp_index.cpp
- tests/cpptests/test_cpp_llapi.cpp
- tests/cpptests/test_cpp_query.cpp
- tests/cpptests/test_cpp_range.cpp
- tests/pytests/common.py
- tests/pytests/test.py
- tests/pytests/test_json_multi_geo.py
- tests/pytests/test_json_multi_numeric.py
- tests/pytests/test_stats.py
backport #5204
- skip changes from #4858 that weren't backported
> [8.0] MOD-8097, MOD-8114 Fix memory counting

- src/info_command.c
- src/spec.c
- src/spec.h
> [2.6] MOD-8129: Fix indexed_percent info stat

- src/info_command.c
- src/spec.c
- src/spec.h
> [2.8] MOD-8129: Fix indexed_percent info stat

- .github/workflows/flow-build-artifacts.yml
- .github/workflows/flow-linux-platforms.yml
- .github/workflows/task-get-linux-configurations.yml
1. #...
2. MOD...
1. ...
2. ...
> disable unsupported OS for node 20

- src/coord/rmr/rmr.c
A followup of #5244.
Before the above PR, if we created an MR iterator, we had to wait for it to finish its current run before freeing it and additional data of an RPNet result processor. So, we made a shallow copy of the RP command and passed it to the UV thread to duplicate and send to all the shards.
Now that the RPNet's freeing flow doesn't wait for the iterator, this shallow copy is not enough, and we may access the data from the UV thread after it is freed.
In this follow-up, we make a deep copy of the command before passing it to the UV thread, to avoid this potentially unsafe read.
> Fix a potential use after free - [MOD-8108]

- src/debug_commands.c
- src/document.c
- src/fork_gc.c
- src/geometry_index.c
- src/geometry_index.h
- src/indexer.c
- src/info_command.c
- src/module.c
- src/query.c
- src/spec.c
- src/tag_index.c
- src/tag_index.h
- src/vector_index.c
- src/vector_index.h
- tests/cpptests/test_cpp_forkgc.cpp
- tests/cpptests/test_cpp_tagindex.cpp
- tests/pytests/common.py
- tests/pytests/test.py
- tests/pytests/test_common.py
- tests/pytests/test_debug_commands.py
- tests/pytests/test_index.py
- tests/pytests/test_json_multi_numeric.py
backport #5229 to 8.0
cofilct due to debug list format in test_debug_commands
> [8.0] [MOD-8125] Create inverted index in write operations only 

- coord/src/dist_aggregate.c
- coord/src/rmr/chan.c
- coord/src/rmr/chan.h
- coord/src/rmr/rmr.c
- coord/src/rmr/rmr.h
- coord/src/rmr/rq.c
- coord/src/rmr/test/test_chan.c
- src/cursor.c
- src/cursor.h
- src/spec.c
- tests/pytests/test_cursors.py
> [2.6] Fix MRIterator ownership mechanism - [MOD-8108]

- tests/pytests/common.py
Fixes a flaky cluster initialization test, in which we may get 2 different error messages for the same reason - uninitialized shard connections.
> MOD-8171: Fix flaky cluster initialization test

- src/debug_commands.c
- src/document.c
- src/fork_gc.c
- src/geometry_index.c
- src/geometry_index.h
- src/indexer.c
- src/info_command.c
- src/module.c
- src/query.c
- src/spec.c
- src/tag_index.c
- src/tag_index.h
- src/vector_index.c
- src/vector_index.h
- tests/cpptests/test_cpp_forkgc.cpp
- tests/cpptests/test_cpp_tagindex.cpp
- tests/pytests/common.py
- tests/pytests/test.py
- tests/pytests/test_common.py
- tests/pytests/test_debug_commands.py
- tests/pytests/test_index.py
- tests/pytests/test_json_multi_numeric.py
backport #5229 to 2.8
cofilct mostly in debug commands and test debug commands
> [2.8] [MOD-8125] Create inverted index in write operations only

- coord/src/dist_aggregate.c
- coord/src/rmr/chan.c
- coord/src/rmr/chan.h
- coord/src/rmr/rmr.c
- coord/src/rmr/rmr.h
- coord/src/rmr/rq.c
- coord/src/rmr/test/test_chan.c
- src/cursor.c
- src/cursor.h
- src/spec.c
- tests/pytests/test_cursors.py
> [2.8] Fix MRIterator ownership mechanism - [MOD-8108]

- src/query.c
- tests/pytests/common.py
- tests/pytests/test.py
- tests/pytests/test_issues.py
- tests/pytests/test_parser.py
- tests/pytests/test_scorers.py
- tests/pytests/test_vecsim.py
Fixing a bug where we may perform an exact match query instead of a default term search
> Fix missing expansions in text queries - [MOD-8142]

- src/query.c
- tests/pytests/common.py
- tests/pytests/test.py
- tests/pytests/test_issues.py
- tests/pytests/test_parser.py
- tests/pytests/test_scorers.py
- tests/pytests/test_vecsim.py
> [2.8] Fix missing expansions in text queries - [MOD-8142]

- src/inverted_index.c
- src/tag_index.c
Fix phrasing of OnReopen functions abort section for tag and term
1. OnReopen Functions
> MOD-8188: Fix OnReopen Comments

- src/optimizer_reader.c
1. MOD-8141
2. MOD-7337
3. MOD-6306
> Remove assertion in optimizer

- src/index.c
- src/query.c
- tests/pytests/test.py
- tests/pytests/test_issues.py
- tests/pytests/test_parser.py
- tests/pytests/test_tags.py
- tests/pytests/test_vecsim.py
> [2.6] Fix missing expansions in text queries - [MOD-8142]

- src/optimizer_reader.c
> [2.8] Remove assertion in optimizer

- src/query.c
- src/trie/rune_util.c
- src/trie/rune_util.h
- tests/pytests/test_issues.py
Validate we managed to create a rune string from the input string and return an error if not.
1. MOD-7882
2. MOD-5291
3. MOD-7895
> Fix long PREFIX/SUFFIX/INFIX/WILDCARD queries - [MOD-7882]

- src/document_basic.c
- src/spec.c
- tests/pytests/test_expire.py
> [MOD-7949] Avoid lazy expire upon scan keys in background [2.10]

- src/document_basic.c
- src/spec.c
- tests/pytests/test_expire.py
> [MOD-7949] Avoid lazy expire upon scan keys in background [2.8]

- src/query.c
- src/trie/rune_util.c
- src/trie/rune_util.h
- tests/pytests/test_issues.py
> [2.6] Fix long PREFIX/SUFFIX/INFIX/WILDCARD queries - [MOD-7882]

- tests/pytests/test_cursors.py
Fix flakiness in the `testCursorOnCoordinator` test where we request the next 100-results chunk of results before the local `_FT.AGGREGATE` command is executed.
This is not a bug, as we may get the first results from another shard and request more before the local command is triggered asynchronously.
The solution is to skip any `FT.AGGREGATE` command (user or internal) from the monitor, as they are unrelated to the verifications we make according to the monitor. We still validate we got all the expected results.
> Fix a flakiness in testCursorOnCoordinator - [MOD-8016]

- src/doc_table.c
- src/document.c
- src/field_spec.c
- src/field_spec.h
- src/redisearch_api.c
- src/sortable.c
- src/sortable.h
- src/spec.c
- src/spec.h
- tests/cpptests/test_cpp_index.cpp
- tests/pytests/test_issues.py
> [2.8] Fix Sorting Vector - [MOD-6783]

- src/doc_table.c
- src/document.c
- src/field_spec.c
- src/field_spec.h
- src/redisearch_api.c
- src/sortable.c
- src/sortable.h
- src/spec.c
- src/spec.h
- tests/cpptests/test_cpp_index.cpp
- tests/pytests/test_issues.py
> [8.0] Fix Sorting Vector - [MOD-6783]

- src/doc_table.c
- src/document.c
- src/field_spec.c
- src/field_spec.h
- src/redisearch_api.c
- src/sortable.c
- src/sortable.h
- src/spec.c
- src/spec.h
- tests/cpptests/test_cpp_index.cpp
- tests/pytests/common.py
- tests/pytests/test_issues.py
> [2.6] Fix Sorting Vector - [MOD-6783]

- .github/workflows/flow-build-artifacts.yml
- .github/workflows/flow-linux-platforms.yml
- .github/workflows/task-build-artifacts.yml
- .github/workflows/task-get-linux-configurations.yml
- .github/workflows/task-test.yml
> [2.10] MOD-8172: Fix CI for platforms that don't support Node.js > 16 (#5310)

- .github/workflows/flow-build-artifacts.yml
- .github/workflows/flow-linux-platforms.yml
- .github/workflows/task-build-artifacts.yml
- .github/workflows/task-get-linux-configurations.yml
- .github/workflows/task-test.yml
> [2.6] MOD-8172: Fix CI for platforms that don't support Node.js > 16 (#5310)

- tests/cpptests/common.cpp
- tests/cpptests/test_cpp_forkgc.cpp
Backport of https://github.com/RediSearch/RediSearch/pull/5324 to 2.6
> [2.6][MOD-8115] Free spec resources in the main thread (#5324)

- coord/src/module.c
> [2.10] MOD-8238: Remove unhandled command

- .github/workflows/flow-build-artifacts.yml
- .github/workflows/flow-linux-platforms.yml
- .github/workflows/task-build-artifacts.yml
- .github/workflows/task-get-linux-configurations.yml
- .github/workflows/task-test.yml
> [2.8] MOD-8172: Fix CI for platforms that don't support Node.js > 16 (#5310)

- src/inverted_index.c
> [2.8] Improve SkipToBlock logic - [MOD-8255]

- src/inverted_index.c
> [2.10] Improve SkipToBlock logic - [MOD-8255]

- src/inverted_index.c
> [2.6] Improve SkipToBlock logic - [MOD-8255]

- src/inverted_index.c
- src/inverted_index.h
- tests/cpptests/test_cpp_index.cpp
- tests/pytests/runtests.sh
> [2.6] Improve "Raw doc id" encoding - [MOD-8255]

- .github/workflows/flow-build-artifacts.yml
Bump macos instance version.
https://github.com/RediSearch/RediSearch/actions/runs/12408938619
> Fix macos artifact build

- src/doc_table.c
- src/doc_table.h
- src/fork_gc.c
- src/forward_index.c
- src/index_iterator.h
- src/inverted_index.c
- src/inverted_index.h
- src/numeric_index.c
- src/profile.c
- src/qint.c
- src/qint.h
- src/redisearch.h
- src/spec.c
- tests/cpptests/redismock/redismock.cpp
- tests/cpptests/test_cpp_index.cpp
- tests/cpptests/test_cpp_llapi.cpp
- tests/cpptests/test_cpp_range.cpp
- tests/ctests/test_qint.c
- tests/pytests/test_json_multi_numeric.py
> [2.6] Fixes for inverted indexes encoding - [MOD-8248]

- src/doc_table.c
- src/doc_table.h
- src/fork_gc.c
- src/forward_index.c
- src/index_iterator.h
- src/inverted_index.c
- src/inverted_index.h
- src/numeric_index.c
- src/profile.c
- src/qint.c
- src/qint.h
- src/redisearch.h
- src/spec.c
- tests/cpptests/index_utils.cpp
- tests/cpptests/redismock/redismock.cpp
- tests/cpptests/test_cpp_index.cpp
- tests/cpptests/test_cpp_llapi.cpp
- tests/cpptests/test_cpp_range.cpp
- tests/ctests/test_qint.c
- tests/pytests/common.py
- tests/pytests/test_json_multi_geo.py
- tests/pytests/test_json_multi_numeric.py
- tests/pytests/test_stats.py
>  [2.8] Fixes for inverted indexes encoding - [MOD-8248]

- src/doc_table.c
- src/doc_table.h
- src/fork_gc.c
- src/forward_index.c
- src/index_iterator.h
- src/inverted_index.c
- src/inverted_index.h
- src/numeric_index.c
- src/profile.c
- src/qint.c
- src/qint.h
- src/redisearch.h
- src/spec.c
- tests/cpptests/index_utils.cpp
- tests/cpptests/redismock/redismock.cpp
- tests/cpptests/test_cpp_index.cpp
- tests/cpptests/test_cpp_llapi.cpp
- tests/cpptests/test_cpp_range.cpp
- tests/ctests/test_qint.c
- tests/pytests/common.py
- tests/pytests/test_json_multi_geo.py
- tests/pytests/test_json_multi_numeric.py
- tests/pytests/test_stats.py
> [2.10] Fixes for inverted indexes encoding - [MOD-8248]

- src/value.c
- tests/pytests/test_aggregate.py
Manual backport of: https://github.com/RediSearch/RediSearch/pull/5187
> [2.8] MOD-8058: Avoid error with _NUM_SSTRING (#5187)

- sbin/pack.sh
- sbin/upload-artifacts
* updated readies version
* commented out macos defs on pack etc..
* remove comments
(cherry picked from commit 6f9a96ec7a541f38bc3c0882d0c8fd9611b9f748)
1. MOD-...
2. #...
1. ...
> [2.8] Update_macos_names_for_s3 (#5432)

- sbin/pack.sh
- sbin/upload-artifacts
* updated readies version
* commented out macos defs on pack etc..
* remove comments
(cherry picked from commit 6f9a96ec7a541f38bc3c0882d0c8fd9611b9f748)
1. MOD-...
2. #...
1. ...
> [8.0] Update_macos_names_for_s3 (#5432)

- sbin/pack.sh
- sbin/upload-artifacts
* updated readies version
* commented out macos defs on pack etc..
* remove comments
(cherry picked from commit 6f9a96ec7a541f38bc3c0882d0c8fd9611b9f748)
1. MOD-...
2. #...
1. ...
> [2.6] Update_macos_names_for_s3 (#5432) 

- .github/workflows/flow-macos.yml
> [MOD-8469] Test macos latest on arm instead of 13

- coord/pack/ramp.yml
- pack/ramp-light.yml
- pack/ramp.yml
To be compatible with new inserted API `RedisModule_HoldString`
> Update redis min version to 6.0.7 [MOD-8467]

- coord/src/dist_aggregate.c
- coord/src/module.c
- src/aggregate/aggregate_exec.c
- src/aggregate/aggregate_request.c
- src/buffer.c
- src/config.c
- src/config.h
- src/varint.c
- src/vector_index.c
- src/vector_index.h
- tests/pytests/test_issues.py
- tests/pytests/test_vecsim.py
> [2.10] MOD-8486: Sanitize User Input

- coord/src/dist_aggregate.c
- src/aggregate/aggregate_exec.c
- src/aggregate/aggregate_request.c
- src/buffer.c
- src/config.c
- src/config.h
- src/varint.c
- src/vector_index.c
- src/vector_index.h
- tests/pytests/test_issues.py
- tests/pytests/test_vecsim.py
> [2.8] MOD-8486: Sanitize User Input (#5454)

- .github/workflows/flow-build-artifacts.yml
> Upload macos latest for arm [2.6]

- .github/workflows/flow-build-artifacts.yml
Fix to upload latest instead of 13
> Upload artifacts mac fix on arm [2.8]

- .github/workflows/flow-build-artifacts.yml
> Upload macos latest for arm [2.10]

- .github/workflows/event-release.yml
> Fix release flow - follow-up

- .github/workflows/event-release.yml
Backport of #5469, #5479, #5481 to `2.10`.
> [2.10] Fix release flow (#5469)

- .github/workflows/event-release.yml
Backport of #5469, #5479, #5481 to `2.8`.
> [2.8] Fix release flow (#5469)

- src/debug_commands.c
- src/indexer.c
- src/spec.c
- src/vector_index.c
- tests/pytests/common.py
- tests/pytests/test_debug_commands.py
- tests/pytests/test_vecsim.py
> MOD-7570 Backport 5422 to 2.10

- .github/workflows/event-release.yml
Backport of #5469, #5479, #5481 to `2.6`.
> [2.6] Fix release flow (#5469)

- CMakeLists.txt
- src/obfuscation/obfuscation_api.c
- src/obfuscation/obfuscation_api.h
- src/query_node.h
- src/redisearch.h
- tests/ctests/test_obfuscation.c
> [2.10] MOD-7864: Obfuscation API

- CMakeLists.txt
- src/obfuscation/obfuscation_api.c
- src/obfuscation/obfuscation_api.h
- src/query_node.h
- src/redisearch.h
- tests/ctests/test_obfuscation.c
> [2.8] MOD-7864: Obfuscation API

- src/obfuscation/hidden.c
- src/obfuscation/hidden.h
- tests/cpptests/redismock/internal.h
- tests/cpptests/redismock/redismock.cpp
- tests/cpptests/test_cpp_hidden.cpp
> [2.8] MOD-7872: Add Types To Hide User Input

- src/config.c
- src/config.h
- src/coord/config.c
- src/coord/config.h
- src/module.c
> MOD-7612: Fix CONFIG param mem-leak

- .github/workflows/flow-coverage.yml
CP https://github.com/RediSearch/RediSearch/pull/5496
> Workaround for coverage, run on ubuntu22 until we fix it for 24 [MOD-8545] [2.8]

- .github/workflows/flow-coverage.yml
> Workaround for coverage, run on ubuntu22 until we fix it for 24 [MOD-8545] [2.10]

- .github/workflows/flow-coverage.yml
CP https://github.com/RediSearch/RediSearch/pull/5496
> Workaround for coverage, run on ubuntu22 until we fix it for 24 [MOD-8545] [2.6]

- src/indexer.c
- src/spec.c
- src/vector_index.c
- src/vector_index.h
- tests/pytests/common.py
- tests/pytests/test_debug_commands.py
- tests/pytests/test_vecsim.py
> MOD-7570 Backport 5422 to 2.6

- src/debug_commands.c
- src/indexer.c
- src/spec.c
- src/vector_index.c
- tests/pytests/common.py
- tests/pytests/test_debug_commands.py
- tests/pytests/test_vecsim.py
> MOD-7570 Backport 5422 to 2.8

- src/query_parser/v1/parser.c
- src/query_parser/v1/parser.y
- tests/pytests/test.py
- tests/pytests/test_tags.py
Revert the field validation introduced in #5216 from dialect 1
> Revert field validation on DIALECT 1 - [MOD-8195]

- src/fork_gc.c
- tests/cpptests/redismock/redismock.cpp
Manual backport of #4243 into 2.8
> Backport 4243 to 2.8

- src/aggregate/aggregate_request.c
- src/geo_index.c
- src/geo_index.h
- src/numeric_filter.c
- src/numeric_filter.h
- src/query.c
- src/query.h
- src/query_param.c
- src/search_options.h
- tests/pytests/test.py
1. Revert dropping legacy filters support
2. Add field validation for DIALECT > 1
> Revert Dropping Legacy Filters Support - [MOD-8256]

- tests/pytests/test_profile.py
Disable the GIL profile report test and add response output in case of failure
> Disable GIL profile report test

- src/fork_gc.c
- tests/cpptests/redismock/redismock.cpp
Manual backport  of #4243 to 2.6.
> Backport 4243 to 2.6

- src/aggregate/aggregate_request.c
- src/geo_index.c
- src/geo_index.h
- src/numeric_filter.c
- src/numeric_filter.h
- src/query.c
- src/query.h
- src/query_param.c
- src/search_options.h
- tests/pytests/test.py
> [8.0] Revert Dropping Legacy Filters Support - [MOD-8256]

- src/inverted_index.c
- tests/cpptests/test_cpp_tagindex.cpp
> [2.6] MOD-8561: Fix Inverted Index SeekTo Edge Case

- src/inverted_index.c
- tests/cpptests/test_cpp_tagindex.cpp
> [2.8] MOD-8561: Fix Inverted Index SeekTo Edge Case

- src/document.c
- tests/pytests/test_issues.py
- tests/pytests/test_vecsim.py
> [2.6] Fix Max Frequency Misscalculation - [MOD-8158]

- src/aggregate/aggregate_request.c
- tests/pytests/common.py
- tests/pytests/test_aggregate.py
> [8.0] MOD-8601: Fix error message for LOAD (#5531)

- src/aggregate/aggregate_request.c
- tests/pytests/test_aggregate.py
> [2.6] MOD-8601: Fix error message for LOAD (#5531)

- src/document.c
- tests/pytests/test_issues.py
- tests/pytests/test_vecsim.py
> [2.8] Fix Max Frequency Misscalculation - [MOD-8158]

- src/aggregate/aggregate_request.c
- tests/pytests/test_aggregate.py
> [2.10] MOD-8601: Fix error message for LOAD (#5531)

- src/aggregate/aggregate_request.c
- tests/pytests/test_aggregate.py
> [2.8] MOD-8601: Fix error message for LOAD (#5531)

- src/fork_gc.c
- src/inverted_index.c
- tests/pytests/test_issues.py
> [2.8] Fix inverted index last id update on GC

- src/fork_gc.c
- src/inverted_index.c
- tests/pytests/test_issues.py
> [2.10] Fix inverted index last id update on GC

- src/inverted_index.c
- tests/cpptests/test_cpp_index.cpp
- tests/cpptests/test_cpp_tagindex.cpp
Reverting minor improvements introduced in #5350, #5364, and a followup introduced in #5528
Complimentary to #5591 for master and 8.0.
1. #5517 
3. #5532
4. #5601
> Revert inverted index iterator changes

- src/fork_gc.c
- src/inverted_index.c
- tests/pytests/test_issues.py
> [2.6] Fix inverted index last id update on GC

- src/inverted_index.c
- tests/cpptests/test_cpp_index.cpp
> [2.6] Revert inverted index iterator changes

- src/cursor.c
- src/cursor.h
- src/info/info_redis.c
- tests/pytests/test_info_modules.py
For better readability, rename some of the global info fields (also moving and split)
> Rename info fields [MOD-8168]

- src/aggregate/aggregate_request.c
- src/highlight_processor.c
- src/hybrid_reader.c
- src/hybrid_reader.h
- src/search_options.h
- src/vector_index.c
- tests/cpptests/benchmark_vecsim_hybrid_queries.cpp
- tests/cpptests/test_cpp_agg.cpp
- tests/cpptests/test_cpp_index.cpp
- tests/pytests/test_issues.py
Support highlighting when querying KNN queries
1. Fine-tune optimization flag for KNN iterator
2. Improve the `HIGHLIGHT`/`SUMMARIZE` key validation
3. Support `HIGHLIGHT`/`SUMMARIZE` for iterators that don't implement `SkipTo`
> Support KNN and HIGHLIGHT - [MOD-8695]

- src/aggregate/aggregate_request.c
- src/highlight_processor.c
- src/hybrid_reader.c
- src/hybrid_reader.h
- src/search_options.h
- src/vector_index.c
- tests/cpptests/benchmark_vecsim_hybrid_queries.cpp
- tests/cpptests/test_cpp_agg.cpp
- tests/cpptests/test_cpp_index.cpp
- tests/pytests/test_issues.py
> [2.8] Support KNN and HIGHLIGHT - [MOD-8695]

- src/aggregate/aggregate_request.c
- src/highlight_processor.c
- src/hybrid_reader.c
- src/hybrid_reader.h
- src/search_options.h
- src/vector_index.c
- tests/cpptests/benchmark_vecsim_hybrid_queries.cpp
- tests/cpptests/test_cpp_agg.cpp
- tests/cpptests/test_cpp_index.cpp
- tests/pytests/test_issues.py
> [2.10] Support KNN and HIGHLIGHT - [MOD-8695]

- coord/src/info_command.c
- tests/pytests/test_issues.py
> [2.10] Fail `FT.INFO` if schema is inconsistent across shards - [MOD-7609]

- coord/src/info_command.c
- tests/pytests/test_issues.py
> [2.8] Fail `FT.INFO` if schema is inconsistent across shards - [MOD-7609]

- src/aggregate/aggregate.h
- src/aggregate/aggregate_request.c
- src/highlight_processor.c
- src/hybrid_reader.c
- src/hybrid_reader.h
- src/search_options.h
- src/vector_index.c
- tests/cpptests/benchmark_vecsim_hybrid_queries.cpp
- tests/cpptests/test_cpp_agg.cpp
- tests/cpptests/test_cpp_index.cpp
- tests/pytests/test_issues.py
> [2.6] Support KNN and HIGHLIGHT - [MOD-8695]

- src/inverted_index.c
- tests/cpptests/CMakeLists.txt
- tests/cpptests/redismock/internal.h
- tests/cpptests/redismock/redismock.cpp
- tests/cpptests/test_cpp_expire.cpp
- tests/cpptests/test_cpp_forkgc.cpp
- tests/pytests/test_expire.py
> [8.0] MOD-8271: Use TTL Information In IR_SkipTo 

- src/aggregate/expr/exprast.c
- src/aggregate/expr/expression.h
- src/obfuscation/obfuscation_api.c
- src/obfuscation/obfuscation_api.h
- src/result_processor.c
- src/rlookup.c
- src/rlookup.h
- src/value.c
- src/value.h
- tests/cpptests/test_cpp_agg.cpp
- tests/cpptests/test_cpp_expr.cpp
> [2.10] MOD-8275: Add A Function To Format A Parsed Expression

- src/aggregate/expr/exprast.c
- src/aggregate/expr/expression.h
- src/obfuscation/obfuscation_api.c
- src/obfuscation/obfuscation_api.h
- src/result_processor.c
- src/rlookup.c
- src/rlookup.h
- src/value.c
- src/value.h
- tests/cpptests/test_cpp_agg.cpp
- tests/cpptests/test_cpp_expr.cpp
> [2.6] MOD-8275: Add A Function To Format A Parsed Expression

- src/aggregate/expr/exprast.c
- src/aggregate/expr/expression.h
- src/obfuscation/obfuscation_api.c
- src/obfuscation/obfuscation_api.h
- src/result_processor.c
- src/rlookup.c
- src/rlookup.h
- src/value.c
- src/value.h
- tests/cpptests/test_cpp_agg.cpp
- tests/cpptests/test_cpp_expr.cpp
> [2.8] MOD-8275: Add A Function To Format A Parsed Expression

- src/ext/default.c
- tests/pytests/test_scorers.py
Backport https://github.com/RediSearch/RediSearch/pull/5670 to 2.10
> [2.10] MOD-7896: Add weight factor to BM25 scoring calculation 

- src/ext/default.c
- tests/pytests/test_scorers.py
Backport https://github.com/RediSearch/RediSearch/pull/5670 to 2.8
> [2.8] MOD-7896: Add weight factor to BM25 scoring calculation (#5670)

- src/aggregate/aggregate.h
- src/aggregate/aggregate_debug.c
- src/aggregate/aggregate_debug.h
- src/aggregate/aggregate_exec.c
- src/coord/dist_aggregate.c
- src/coord/rmr/chan.c
- src/coord/rmr/chan.h
- src/coord/rmr/rmr.c
- src/coord/rmr/rmr.h
- src/debug_commands.c
- src/module.c
- src/module.h
- src/result_processor.c
- src/result_processor.h
- src/util/timeout.h
- tests/pytests/common.py
- tests/pytests/test_cursors.py
- tests/pytests/test_debug_commands.py
- tests/pytests/test_resp3.py
- tests/pytests/test_timeout.py
> [8.0] Introducing query debug mechanism :tada: (#5554)

- CMakeLists.txt
- tests/pytests/includes.py
- tests/pytests/runtests.sh
Manual backport of #5706 to 2.6.
> [2.6] Purge readies from pytest 

- CMakeLists.txt
- build/boost/boost.cmake
- src/geometry/CMakeLists.txt
- src/obfuscation/hidden.c
- src/obfuscation/hidden.h
- src/obfuscation/hidden_unicode.c
- src/obfuscation/hidden_unicode.h
- src/obfuscation/obfuscation_api.c
- src/obfuscation/obfuscation_api.h
- src/util/hash/CMakeLists.txt
- src/util/hash/hash.cpp
- src/util/hash/hash.h
- tests/cpptests/test_cpp_hash.cpp
- tests/cpptests/test_cpp_hidden.cpp
- tests/ctests/test_obfuscation.c
Manual backport of #5716 
Conflicts were in CMakeLists.txt and obfuscation_api.h
> [8.0] MOD-8989 - Obfuscation API Changes

- src/coord/dist_aggregate.c
> Remove cmdCtx from prepareForExecution

- deps/rmutil/rm_assert.h
- src/coord/dist_aggregate.c
- src/coord/rmr/rmr.c
> [8.0] [MOD-9023] Replacing freeFlag with a reference counter 

- .install/amazon_linux_2.sh
- tests/pytests/requirements.txt
- tests/pytests/test_issues.py
- tests/pytests/test_resp3.py
> [8.0] MOD-7926: Fix Redis Package Tests 

- CMakeLists.txt
- build/boost/boost.cmake
- src/geometry/CMakeLists.txt
- src/obfuscation/hidden.c
- src/obfuscation/hidden.h
- src/obfuscation/hidden_unicode.c
- src/obfuscation/hidden_unicode.h
- src/obfuscation/obfuscation_api.c
- src/obfuscation/obfuscation_api.h
- src/util/hash/CMakeLists.txt
- src/util/hash/hash.cpp
- src/util/hash/hash.h
- tests/cpptests/test_cpp_hash.cpp
- tests/cpptests/test_cpp_hidden.cpp
- tests/ctests/test_obfuscation.c
Manual backport of #5716 
Conflicts were in CMakeLists.txt and obfuscation_api.h
> [2.10] MOD-8989 - Obfuscation API Changes

- src/aggregate/aggregate_exec.c
- tests/pytests/test_resp3.py
> [2.10] MOD-9054: Fix `total_results` field in shard RESP3 response (#5765)

- coord/src/dist_aggregate.c
- coord/src/rmr/rmr.c
- deps/rmutil/rm_assert.h
> [2.8] [MOD-9023] Replacing freeFlag with a reference counter

- coord/src/rmr/conn.c
- src/config.h
- src/debug_commands.c
- src/notifications.c
- src/util/config_api.c
- src/util/config_api.h
- tests/pytests/test_debug_commands.py
> [2.10] MOD-8996: Support hide user data from logs config parameter

- coord/src/info_command.c
- src/cursor.c
- src/cursor.h
- src/debug_commands.c
- src/document.c
- src/document.h
- src/field_spec.c
- src/field_spec.h
- src/fork_gc.c
- src/indexer.c
- src/indexer.h
- src/info/field_spec_info.c
- src/info/field_spec_info.h
- src/info/info_command.c
- src/info/info_command.h
- src/module.c
- src/notifications.c
- src/query.c
- src/search_ctx.h
- src/spec.c
- src/spec.h
- src/tag_index.c
- src/tag_index.h
- tests/cpptests/test_cpp_forkgc.cpp
- tests/cpptests/test_cpp_index.cpp
- tests/pytests/test_debug_commands.py
- tests/pytests/test_issues.py
> [2.10] MOD-7878: Support Index Debug Commands

- coord/src/rmr/conn.c
- tests/pytests/requirements.txt
- tests/pytests/test.py
- tests/pytests/test_aggregate.py
> [2.10] MOD-8674: Fix TLS connection to shards

- tests/pytests/test_profile.py
> [2.10] [MOD-9217] Fix timeout testFailOnTimeout_nonStrict ON_TIMEOUT policy 

- tests/pytests/test_profile.py
> [2.8] [MOD-9217] Fix timeout testFailOnTimeout_nonStrict ON_TIMEOUT policy

- coord/src/module.c
- src/aggregate/aggregate_exec.c
- src/result_processor.c
- src/result_processor.h
- tests/pytests/test.py
- tests/pytests/test_optimizer.py
> [2.10] MOD-9174: Fix pipeline issues (#5837)

- coord/src/module.c
- src/aggregate/aggregate_exec.c
- src/result_processor.c
- src/result_processor.h
- tests/pytests/test.py
- tests/pytests/test_optimizer.py
> [2.8] MOD-9174: Fix pipeline issues (#5837)

- .github/workflows/task-stale.yml
change stale action to have 1000 operations
1. MOD-...
2. #...
1. ...
> Update task-stale.yml to run 1000 operations

- .github/workflows/event-pull_request.yml
- .github/workflows/pr_label_size.yml
1. #...
2. MOD...
1. ...
2. ...
> PR size label

- src/value.c
- src/value.h
- tests/cpptests/test_cpp_value.cpp
adds unit tests to #5872 
1. #...
2. MOD...
1. ...
2. ...
> unit tests for 5872

- src/spec.c
- src/spec.h
> [2.10] MOD-9316: Fix Duplicate Index Loading From RDB

- deps/rmutil/args.c
- deps/rmutil/args.h
- src/aggregate/aggregate_exec.c
- src/config.c
- src/config.h
- src/coord/info_command.c
- src/debug_commands.c
- src/debug_commands.h
- src/info/field_spec_info.c
- src/info/index_error.c
- src/info/index_error.h
- src/info/indexes_info.c
- src/info/indexes_info.h
- src/info/info_command.c
- src/info/info_redis/info_redis.c
- src/module.c
- src/query_error.h
- src/spec.c
- src/spec.h
- tests/pytests/common.py
- tests/pytests/test_config.py
- tests/pytests/test_debug_commands.py
- tests/pytests/test_index_error.py
- tests/pytests/test_index_oom.py
- tests/pytests/test_resp3.py
- tests/pytests/test_vecsim.py
> [8.0] MOD-7795 Backport 5778 to 8.0

- .install/install_cmake.sh
- .install/ubuntu_24.04.sh
- CMakeLists.txt
- build/cmake/redisearch_cflags.cmake
- build/hiredis/hiredis.cmake
> [2.6] [MOD-9303] Update submodules to support cmake >= 4.0

- .github/workflows/flow-temp.yml
- .install/verify_build_deps.sh
- Makefile
> [2.6] MOD-9058 linter for dependencies on ubuntu OSs 

- .github/workflows/flow-temp.yml
- .install/verify_build_deps.sh
- Makefile
> [2.8] MOD-9058 linter for dependencies on ubuntu OSs

- tests/pytests/test_vecsim.py
> GuyAv -  fix info vecsim robust

- src/debug_commands.c
- src/info/field_spec_info.c
- tests/pytests/test_vecsim.py
1. Avoid using the dangerous debug info API upon collecting info for a vector field as part of handling redis `info` that is also used to generate metrics. This way, we are using a safe and fast API that does not use any locks.
2. Introduce new ARM hardware optimizations for the vector search
> VecSim Info API update and ARM Optimizations - [MOD-9354]

- src/debug_commands.c
- src/spec.c
- tests/pytests/test_vecsim.py
> [2.8] Use new info API of VecSim for metrics [MOD-9354]

- src/debug_commads.c
- src/spec.c
- src/vector_index.c
- tests/pytests/test_vecsim.py
> [2.6] Use new info API of VecSim for metrics [MOD-9354]

- .github/workflows/flow-temp.yml
- .install/verify_build_deps.sh
- .install/verify_build_deps_macos.sh
> [2.10] [MOD-9259] MacOS Deps check linter 

- tests/pytests/common.py
Fix flakiness of OOM testing by setting tighter limits.
> fix flaky OOM tests MOD-9406

- .github/workflows/flow-temp.yml
- .install/verify_build_deps.sh
- .install/verify_build_deps_macos.sh
> [2.6] [MOD-9258] MacOS Deps check linter

- .github/workflows/flow-temp.yml
- .install/verify_build_deps.sh
- .install/verify_build_deps_macos.sh
> [2.8] [MOD-9258] MacOS Deps check linter (#5883)

- .github/workflows/task-build-artifacts.yml
- sbin/upload-artifacts
Following #5905
1. https://github.com/RediSearch/RediSearch/actions/runs/14474138628
2. https://github.com/RediSearch/RediSearch/actions/runs/14474570369
> Fix upload-artifact Script

- Makefile
- sbin/get-platform
- sbin/upload-artifacts
backport #5905 to 2.6
https://github.com/RediSearch/RediSearch/actions/runs/14487931027
> [2.6] Simplify upload artifacts [MOD-6152] (#5905)

- Makefile
- sbin/get-platform
- sbin/upload-artifacts
backport #5905 to 2.8
https://github.com/RediSearch/RediSearch/actions/runs/14487931027
> [2.8] Simplify upload artifacts [MOD-6152] (#5905)

- sbin/upload-artifacts
> Fix Upload Script Again

- sbin/upload-artifacts
> Fix Upload Script Again 2

- src/query_parser/v2/parser.c
- src/query_parser/v2/parser.y
- tests/pytests/test_parser.py
- tests/pytests/test_profile.py
- tests/pytests/test_scorers.py
> [8.0] Improve parser for intersections [MOD-9278]

- .github/workflows/flow-build-artifacts.yml
- .github/workflows/flow-linux-platforms.yml
- .github/workflows/task-build-artifacts.yml
- .github/workflows/task-get-linux-configurations.yml
- .github/workflows/task-test.yml
Removes `ubuntu:bionic` from CI
> MOD-9516: Remove ubuntu:bionic from ci

- src/query_parser/v2/parser.c
- src/query_parser/v2/parser.y
- tests/pytests/test_dialect.py
- tests/pytests/test_parser.py
- tests/pytests/test_profile.py
- tests/pytests/test_scorers.py
> [2.10] Improve parser for intersections [MOD-9278]

- src/profile.c
- src/result_processor.c
- src/result_processor.h
- tests/pytests/common.py
- tests/pytests/test_multithread.py
> [2.10] Skip Atempting to Load Key Name - [MOD-9419]

- coord/src/rmr/rmr.c
> [2.8] Rename UV thread when spinning it up

- src/query_parser/v2/parser.c
- src/query_parser/v2/parser.y
- tests/pytests/test_dialect.py
- tests/pytests/test_parser.py
- tests/pytests/test_profile.py
- tests/pytests/test_scorers.py
> [2.8] Improve parser for intersections [MOD-9278]

- .github/workflows/flow-temp.yml
- .github/workflows/task-get-latest-tag.yml
Add the number of results to fetch (100), instead of using the default of 30
> CI improvement - Improve getting latest tags

- src/aggregate/aggregate_exec.c
- src/config.c
- src/config.h
- src/module.c
- src/query_error.h
- tests/pytests/common.py
- tests/pytests/test_config.py
- tests/pytests/test_debug_commands.py
- tests/pytests/test_index_oom.py
Change OOM behavior such that:
1. Won't fail queries after background scan fail
2.  Raise warning with RESP3
> [8.0] Fix OOM behavior  

- src/aggregate/aggregate_exec.c
- src/config.c
- src/config.h
- src/module.c
- src/query_error.h
- tests/pytests/common.py
- tests/pytests/test_config.py
- tests/pytests/test_debug_commands.py
- tests/pytests/test_index_oom.py
Reverts RediSearch/RediSearch#6039
> Revert "[8.0] Fix OOM behavior  "

- .github/workflows/event-pull_request.yml
Minor fixes for PR workflow conditions introduced in #5926
> CI fixes - PR workflow conditions

- src/cursor.c
- src/cursor.h
- tests/cpptests/test_cpp_cursors.cpp
> [2.6] Fix Cursor Purge - [MOD-9408]

- src/spec.c
Reinsert the fix after 8.0 GA is out - reverting the original revert
> Revert "Revert "[8.0] Avoid lazy expiration in background indexing for CRDT [MOD-9486]" (#6059)"

- src/cursor.c
- src/cursor.h
- tests/cpptests/test_cpp_cursors.cpp
Reinsert after reverted originally due to 8.0 GA code freeze.
> Revert "Revert "[8.0] Fix Cursor Purge - [MOD-9408]" (#6049)"

- .github/workflows/event-pull_request.yml
- src/redisearch_rs/trie_rs/src/node/metadata.rs
> Fix rust format

- .github/workflows/event-pull_request.yml
- .github/workflows/flow-coverage.yml
- Makefile
- README.md
- tests/cpptests/redismock/redismock.cpp
> [2.6] Coverage Report Without `readies` - Phase 1 - [MOD-9056]

- .github/workflows/event-pull_request.yml
- .github/workflows/flow-coverage.yml
- Makefile
- README.md
- tests/cpptests/redismock/redismock.cpp
> [2.8] Coverage Report Without `readies` - Phase 1 - [MOD-9056]

- .github/workflows/event-pull_request.yml
- .github/workflows/flow-coverage.yml
- Makefile
- README.md
- tests/cpptests/redismock/redismock.cpp
> [8.0] Coverage Report Without `readies` - Phase 1 - [MOD-9056]

- src/config.c
- src/config.h
- tests/pytests/test.py
- tests/pytests/test_aggregate.py
- tests/pytests/test_config.py
- tests/pytests/test_contains.py
- tests/pytests/test_coordinator.py
- tests/pytests/test_cursors.py
- tests/pytests/test_expire.py
- tests/pytests/test_issues.py
- tests/pytests/test_json.py
- tests/pytests/test_multibyte_char_terms.py
- tests/pytests/test_multithread.py
- tests/pytests/test_optimizer.py
- tests/pytests/test_profile.py
- tests/pytests/test_resp3.py
- tests/pytests/test_tags.py
- tests/pytests/test_wildcard.py
> [8.0] Revert changing default timeout to fail + adjust tests [MOD-7791]

- README.md
> update readme [8.0]

- .github/workflows/flow-coverage.yml
- .github/workflows/task-test.yml
> CI: Enable full backtrace for Rust panics

- src/redisearch_rs/low_memory_thin_vec/tests/tests.rs
- src/redisearch_rs/wildcard/benches/matching.rs
- src/redisearch_rs/wildcard/tests/integration/utils.rs
This PR fixes a few problems reported by `cargo clippy`.
> Some cargo clippy fixes

- .install/rocky_linux_8.sh
Install 
1. Current: CI error:
https://github.com/RediSearch/RediSearch/actions/runs/15076874801/job/42401501017
2. Change: Upgrade `python3.12-pip` and `python3.12-devel`
3. Outcome: 
https://github.com/RediSearch/RediSearch/actions/runs/15083420959/job/42403012363
> rockylinux:8 install python3.12 packages

- .github/workflows/benchmark-flow.yml
- .github/workflows/benchmark-runner.yml
- .github/workflows/benchmark-trigger.yml
- .github/workflows/event-pull_request.yml
- .github/workflows/event-push-to-integ.yml
- .github/workflows/event-weekly.yml
- .github/workflows/flow-micro-benchmarks.yml
- .github/workflows/flow-temp.yml
- .github/workflows/task-check-changes.yml
- .github/workflows/task-lint.yml
1. Improve `task-check-changes` to return true if any workflow was changed, to make sure they are tested on the CI before merging them
2. Move the `micro-benchmarks` job from pull requests to benchmarks
3. Some more simplifications and cleanups
> CI Improvements

- .github/workflows/event-merge-to-queue.yml
- .github/workflows/event-pull_request.yml
> Temp disable coverage as required for CI to pass in PRs

- .install/rocky_linux_8.sh
Manual backport of #6147 to `2.8`.
> [2.8] rockylinux:8 install python3.12 packages

- README.md
I am simply adding BM25 as the default scoring mechanism
> mention BM25 as default scorer in README

- .github/workflows/task-test.yml
- src/module-init/module-init.c
- print the actual base address
- upload the so file in case of failure
> Small Diagnostic Fix

- src/aggregate/aggregate_exec.c
- src/profile.c
- src/profile.h
- src/result_processor.c
- src/result_processor.h
- src/util/timeout.h
- tests/pytests/common.py
- tests/pytests/test.py
- tests/pytests/test_common.py
- tests/pytests/test_profile.py
- tests/pytests/test_resp3.py
Backport [5525](https://github.com/RediSearch/RediSearch/pull/5525) [5514](https://github.com/RediSearch/RediSearch/pull/5514) [5439](https://github.com/RediSearch/RediSearch/pull/5439) to 8.0
> Backport MOD-5437

- .install/ubuntu_20.04.sh
Enabler for integration with Intel's svs that should run against gcc > 10
See flow in https://github.com/RediSearch/RediSearch/actions/runs/15166061304
> Build focal with gcc-11

- .github/workflows/event-release.yml
> Fixes for the "Release by tag" flow

- CMakeLists.txt
- src/index.c
- src/index_iterator.h
- src/iterators/iterator_api.h
- src/iterators/union_iterator.c
- src/iterators/union_iterator.h
- tests/cpptests/iterator_util.h
- tests/cpptests/micro-benchmarks/CMakeLists.txt
- tests/cpptests/micro-benchmarks/benchmark_union_iterator.cpp
- tests/cpptests/micro-benchmarks/deprecated_iterator_util.h
- tests/cpptests/test_cpp_iterator_union.cpp
The union iterator and the following ones are not in use until they're all ready. We currently only use them in unit tests and microbenchmarks.
> Refactor Union Iterator - [MOD-8841]

- src/iterators/idlist_iterator.c
- src/iterators/idlist_iterator.h
- tests/cpptests/micro-benchmarks/benchmark_idlist_iterator.cpp
- tests/cpptests/redismock/util.cpp
- tests/cpptests/test_cpp_iterator_idlist.cpp
- tests/cpptests/test_distagg.cpp
It contains the code for the IDListIterator refactor.
Implementation has been taken from https://github.com/RediSearch/RediSearch/pull/5619/files
> add IDList iterator refactor - [MOD-8846]

- src/field_spec.c
- src/info/index_error.c
- src/info/index_error.h
- src/module.c
- src/spec.c
> [2.6] [MOD-9396] Fix indexError leak

- deps/thpool/thpool.c
> [2.6] Atomic keepalive mechanism for thpool [MOD-6553] 

- .github/workflows/event-merge-to-queue.yml
- .github/workflows/event-pull_request.yml
1. #...
2. MOD...
1. ...
2. ...
> use redis 8.2 branch  on CI

- src/inverted_index.c
- src/inverted_index.h
Cherry picked from commit 621675ba742278fe00833fbfaeac0317c56adf0d
Related to MOD-8848
1. decoders API
2. Introducing `IndexBlockReader`
> Refactor Decoders API

- src/redisearch_rs/trie_rs/src/node/metadata.rs
Solve a compiler error shown with rust nightly for some rust coverage
> fix ci rust errors

- src/aggregate/aggregate.h
- src/aggregate/aggregate_exec.c
- src/config.c
- src/config.h
- src/coord/dist_aggregate.c
- src/debug_commands.c
- src/debug_commands.h
- src/module.c
- src/profile.c
- src/profile.h
- src/query_error.h
- src/spec.c
- src/spec.h
- tests/pytests/common.py
- tests/pytests/test_config.py
- tests/pytests/test_debug_commands.py
- tests/pytests/test_index_oom.py
This PR backports #6114 , #6140 , #6203  to 8.0
No notable conflicts
> [8.0] Backport OOM indexing to all branches [MOD-9715]

- tests/pytests/test_debug_commands.py
Adding missing coverage to pytest
> [2.10] Add coverage to OOM indexing [MOD-9715]

- src/iterators/intersection_iterator.c
- src/iterators/intersection_iterator.h
- tests/cpptests/micro-benchmarks/benchmark_intersection_iterator.cpp
- tests/cpptests/test_cpp_iterator_intersection.cpp
Implementation is based on #5619 
Micro-benchmarks show an improvement of up to 37%
> Refactor Intersection Iterator - [MOD-8842]

- .github/workflows/event-nightly.yml
- .github/workflows/event-push-to-integ.yml
- .github/workflows/flow-micro-benchmarks.yml
> fix microbenchmark link in comment

- src/aggregate/expr/parser.c
- src/aggregate/expr/parser.y
- src/query_parser/v2/lexer.c
- tests/cpptests/test_cpp_expr.cpp
- tests/pytests/test_aggregate.py
> MOD-10176: Fix parser for negation of nonexistent function

- .github/workflows/event-nightly.yml
> fix nightly

- src/iterators/optional_iterator.c
- src/iterators/optional_iterator.h
- tests/cpptests/index_utils.h
- tests/cpptests/micro-benchmarks/benchmark_optional_iterator.cpp
- tests/cpptests/test_cpp_iterator_optional.cpp
Implement the optimized variant of the optional iterator
1. New implementation
2. A few small fixes
3. Implement new tests and benchmark cases
4. Fix SkipToOld benchmark
> Refactor Optional Iterator Optimized mode - [MOD-9678]

- build.sh
- src/ttl_table.c
- tests/pytests/test_expire.py
> [8.0] Fix TTL dictionary - [MOD-10240]

- CMakeLists.txt
> [MOD-9403] Remove stale varint target

- src/fork_gc.c
- tests/pytests/common.py
- tests/pytests/test_gc.py
- tests/pytests/test_index_oom.py
Fix GC OOM threshold related tests, added a debug log in case this keeps happening
> Fix test flakiness - [MOD-10076]

- .github/workflows/benchmark-trigger.yml
> add more specific labels for microbenchmarks

- .gitignore
- build.sh
- src/spec.c
- tests/pytests/test_short_read.py
> [2.10] Fix FieldSpec Cleanup on failed RDB load - [MOD-10307]

- .gitignore
- build.sh
- src/spec.c
> [2.6] Fix FieldSpec Cleanup on failed RDB load - [MOD-10307]

- .install/ubuntu_20.04.sh
A `2.X` dedicated version of #6449, to avoid conflicts in advance.
Solution to blocked 2.8, as proven here #6446
> [2.10] [CI] install python 3.12 on focal

- src/document_basic.c
* add check version to open key
* change to use OpenKey instead
(cherry picked from commit 15203f9c46f040d3741d065eab6c0b7a0e41d340)
1. MOD-...
2. #...
1. ...
> [2.10] - add check version to json open key (#6405)

- .github/workflows/flow-build-artifacts.yml
- .github/workflows/flow-linux-platforms.yml
- .github/workflows/task-build-artifacts.yml
- .github/workflows/task-get-linux-configurations.yml
- .github/workflows/task-test.yml
> [2.6] [CI] Remove bionic (#6457)

- src/document_basic.c
- src/info/index_error.c
- src/json.c
- tests/pytests/runtests.sh
- tests/pytests/test_json_error_handling.py
this PR should clean the warning logs when deleting a json doc
And set the index errors for some flows
> Hadle JSON.DEL logs [MOD-10266]

- src/spec.c
- tests/pytests/test_multithread.py
Add assert to create function that the dictAdd retuned OK, and log if not, so that we'll be alerted if there is an issue in the future
> add assert when adding to dict on ft.create

- .github/workflows/task-test.yml
- src/vector_index.c
update vecsim pointer to include reduced size svs lib
> Reduced size SVS binaries

- src/info/info_command.c
- src/spec.c
- src/vector_index.h
- tests/pytests/test_vecsim.py
Backport of #6507 to 8.2.
1. ...
> [8.2] Bump svs version in vecsim + change leanvec_dim argument to reduce

- src/coord/rmr/io_runtime_ctx.c
- src/coord/rmr/io_runtime_ctx.h
- tests/cpptests/coord_tests/test_cpp_io_runtime_ctx.cpp
Some additional work on top of #6313
> refactor pending queues

- src/coord/rmr/io_runtime_ctx.c
> remove unneeded RQ_Done call in rqAsyncCb

- .github/workflows/flow-micro-benchmarks-runner.yml
- .github/workflows/flow-micro-benchmarks.yml
> fix: redisbench admin install in flow microbenchmarks

- src/redisearch_rs/inverted_index/src/lib.rs
- src/redisearch_rs/inverted_index/src/tests.rs
A wrapper around an inverted index reader which can filter based on the field mask
> [MOD-10544] Make a reader which filters based on the field mask

- src/redisearch_rs/inverted_index/src/lib.rs
- src/redisearch_rs/inverted_index/src/tests.rs
Just a wrapping inverted index reader which is able to skip over documents with duplicate IDs when reading
> [MOD-10543] Make a reader which can skip duplicates

- src/query.c
- tests/pytests/test.py
> Fix an edge case in INKEYS deduplecation

- src/redisearch_rs/headers/types_rs.h
- src/redisearch_rs/inverted_index/src/lib.rs
- src/redisearch_rs/inverted_index/tests/freqs_only.rs
A few unrelated commits from my WIP branches we can already review and merge to reduce branches size.
> [MOD-10627] Various test, debug and doc II encoder/decoder improvements

- .install/verify_build_deps.sh
remove "cargo" from deps verification
> [MOD-9522] remove cargo verification

- src/redisearch_rs/c_entrypoint/types_ffi/src/lib.rs
- src/redisearch_rs/headers/types_rs.h
- src/redisearch_rs/inverted_index/src/doc_ids_only.rs
- src/redisearch_rs/inverted_index/src/fields_only.rs
- src/redisearch_rs/inverted_index/src/freqs_fields.rs
- src/redisearch_rs/inverted_index/src/freqs_only.rs
- src/redisearch_rs/inverted_index/src/lib.rs
- src/redisearch_rs/inverted_index/src/numeric.rs
- src/redisearch_rs/inverted_index/src/tests.rs
- src/redisearch_rs/inverted_index/tests/fields_only.rs
- src/redisearch_rs/inverted_index/tests/numeric.rs
- src/redisearch_rs/inverted_index_bencher/build.rs
- src/redisearch_rs/inverted_index_bencher/src/benchers/doc_ids_only.rs
- src/redisearch_rs/inverted_index_bencher/src/benchers/fields_only.rs
- src/redisearch_rs/inverted_index_bencher/src/benchers/freqs_fields.rs
- src/redisearch_rs/inverted_index_bencher/src/benchers/numeric.rs
- src/redisearch_rs/inverted_index_bencher/src/ffi.rs
- src/redisearch_rs/rqe_iterators/src/rqe_iterator.rs
Splitting out some commits from https://github.com/RediSearch/RediSearch/pull/6576 to reduce PR sizes.
> [MOD-10677] Add lifetime to RSOffsetVector

- src/redisearch_rs/rlookup/src/lookup.rs
Remove unsafe usage as proposed in https://github.com/RediSearch/RediSearch/pull/6437#discussion_r2251294915
> Follow-up: Reduce unsafe usage - MOD-10396 - MOD-10395

- src/json.c
- src/spec.c
- tests/pytests/test_vecsim.py
Support of multi option for SVS-VAMANA algorithm
#...
MOD...
1. Redisearch integration code
> Support for multi option in Redisearch for SVS-VAMANA algorithm

- build/boost/boost.cmake
- developer.md
> boost: update cmake script to version 1.88.0

- src/module.c
Bump minimal redis version to be 8.1 on master and 8.2 branches
> Bump minimal redis version

- coord/src/coord_module.h
- coord/src/dist_aggregate.c
- coord/src/module.c
- src/aggregate/aggregate.h
- src/aggregate/aggregate_exec.c
- src/index.c
- src/info/global_stats.c
- src/info/global_stats.h
- src/info/indexes_info.h
- src/info/info_command.c
- src/info/info_redis.c
- src/profile.c
- src/result_processor.c
- src/result_processor.h
- src/rs_wall_clock.h
- src/spec.c
- src/spec.h
backport https://github.com/RediSearch/RediSearch/pull/6574 to 2.10
> [2.10] [MOD-10622] Change time measurement method in FT.PROFILE

- .github/workflows/task-lint.yml
Makes this error clearer in the CI by adding diff failures to the list
> Make diff failures clearer

- src/redisearch_rs/build_utils/src/lib.rs
- src/redisearch_rs/inverted_index_bencher/build.rs
Will help implementing the iterator bencher.
> build_utils: factor out link_static_libraries()

- src/debug_commands.c
- tests/pytests/test_vecsim_svs.py
This PR includes vecsim version that points to the new binary version of svs with the fix to address the bug (crash) described in `MOD-10771`
> [MOD-10771] bump svs version

- .github/workflows/benchmark-flow.yml
- .github/workflows/benchmark-runner.yml
- .github/workflows/event-merge-to-queue.yml
- .github/workflows/event-pull_request.yml
- .github/workflows/flow-linux-platforms.yml
- .github/workflows/flow-macos.yml
- .github/workflows/task-test.yml
- build.sh
- tests/pytests/runtests.sh
> [8.2] Run against JSON 8.2

- .install/test_deps/common_installations.sh
- .install/test_deps/install_rust.sh
- tests/deps/setup_rejson.sh
> [2.6] pin a Rust nightly version

- .install/test_deps/common_installations.sh
- .install/test_deps/install_rust.sh
- tests/deps/setup_rejson.sh
> [2.8] pin a Rust nightly version

- .install/common_base_linux_mariner_2.0.sh
> ci: install clang-devel on cbl-mariner

- src/inverted_index/inverted_index.c
- src/redisearch_rs/inverted_index_bencher/src/ffi.rs
> inverted_index_bencher: fix building tests

- .install/test_deps/common_installations.sh
- Makefile
- build.sh
- src/fork_gc.c
- src/inverted_index/inverted_index.c
- src/inverted_index/inverted_index.h
- tests/deps/setup_rejson.sh
small stepping stone in [the MOD-10702 quest](https://redislabs.atlassian.net/browse/MOD-10702)
Closes: https://redislabs.atlassian.net/browse/MOD-11220
> [MOD-11220] move core logic of FGC_applyInvertedIndex to II

- sbin/memcheck-summary
remove readies from memcheck script
> remove readies from memcheck
