RediSearch/RediSearch

src/Makefile
-Bsymbolic isn't supported in OS X, use the flag in
Linux environments only
> warning: I didn't test the change on Linux
fix #4
=> Makefile: Remove -Bysmbolic from OS X LDFlags

docs/Quick_Start.md
Should be
FT.CREATE myIdx title 5.0 body 1.0 url 1.0
Was
CREATE myIdx title TEXT 5.0 body TEXT 1.0 url 1.0
which lead to this error:
(error) Could not parse field specs
=> docs: edit quickstart with correct args to FT.CREATE

src/tests/test_trie.c
Was preventing tests from passing with error:
```
test_trie.c:136:20: error: hex escape sequence out of range
char *str = "\xc4\x8caji\xc4\x87";
```
=> Patch typo in Python trie unicode test

src/tests/Makefile, src/tests/test_index.c, src/tests/test_query.c, src/tests/test_trie.c, src/tests/test_util.h, src/tests/titles.csv, src/trie/Makefile, src/trie/levenshtein.c, src/trie/rune_util.c, src/trie/rune_util.h, src/trie/trie.h, src/trie/trie_type.c
close #11 (Normalize and fold Unicode text in auto-complete)
After this change, `ft.SUGADD` and `ft.SUGGET` work like this:
```sh
127.0.0.1:6379> FLUSHALL
OK
127.0.0.1:6379> ft.SUGADD ac "hello WorlD ß" 100
(integer) 1
127.0.0.1:6379> ft.SUGGET ac "HELLO"
1) "hello world ss"
127.0.0.1:6379> 
```
Notes:
1. I couldn't get all the Python tests to pass, but this seems to work in the CLI
1. It would be nice to add a test case to the Python tests that covers multiple code points, like in the above example, but I couldn't get that to work—Python always complained about `\xc3` when I used `\xc3` or `ß`
1. I followed what's currently in the project and used `malloc` instead of [`RedisModule_Alloc`](https://github.com/antirez/redis/blob/unstable/src/modules/API.md#rm_alloc). For my own learning, …
=> Normalize and fold Unicode text in auto-complete

src/Makefile, src/module.c, src/query_parser/tokenizer.c, src/query_parser/tokenizer.h, src/tests/test_query.c, src/tests/test_range.c, src/tokenize.c, src/tokenize.h, src/trie/trie_type.c
Fix compilation warnings caught on OS X:
- NormalizeFunc was defined twice: remove the duplicate and fix
up `#include`s
- Avoid unsigned integer overflow bug vector in trie_type.c:
`slen-len` isn't safe when the lengths are unsigned.
Also modified the main Makefile to use the `-Werror` flag in all environments, since OS X doesn't complain anymore.
=> Patches for OSX compilation warnings

Makefile
The new make target builds and deploys the documentation to the
website. To run it, first `pip install s3cmd` and configure your
credentials.
=> Adds `make deploydocs` target

src/concurrent_ctx.c, src/concurrent_ctx.h, src/id_list.c, src/index.c, src/index_iterator.h, src/inverted_index.c, src/inverted_index.h, src/module.c, src/numeric_index.c, src/numeric_index.h, src/query.c, src/query.h, src/redis_index.c, src/redis_index.h, src/search_ctx.h, src/tests/test_index.c, src/tests/test_range.c
This PR addresses an inherent problem with concurrent search on redis:
Concurrent search works by switching between queries running on multiple threads, having just one query hold the redis global lock at a time. 
While this works well, there is the problem of what happens when a key has been deleted while a thread holding a reference to it was asleep.  Until now this would have crashed redis. 
This PR introduces a mechanism to re-acquire all the open keys after a thread sleeps, and aborting the query if a key it operates on has been deleted, or modified in a way that cannot allow the query to continue running. It does so by allowing a registry of open keys, automatically reopening them when concurrent execution is regained - and notifying their holder of the change, allowing aborting of …
=> Better Protection against race conditions in concurrent execution

docs/Commands.md, src/document.c, src/module.c, src/pytest/test.py, src/spec.c, src/spec.h, src/tests/test_index.c
`NOSTEM` can now be added as a keyword when creating a text field.
=> Issue #126: Support `NOSTEM`

.travis.yml, docs/Commands.md, docs/Extensions.md, src/document.c, src/document.h, src/document_basic.c, src/indexer.c, src/leakcheck.supp, src/module.c, src/pytest/test.py, src/sortable.c, src/spec.c, src/spec.h, src/tests/test_index.c, src/tests/test_trie.c
This adds the ability to do partial updates, and quick updates of score, payload, and sortable non indexed fields - without reindexing the document.
WIP - no documentation or tests yet.
The additions are:
1. Added the NOINDEX flag in fields, which means they will either be ignored or used for sortable only.
2. Added the PARTIAL keyword along with REPLACE in FT.ADD
in that case we check the fields in the document, and if it doesn’t contain indexable fields, we do a quick update in the main thread. If it contains indexable fields we load the new version of the document and index normally.
There are a few flags in the add document context to support this, and a flag in the field spec.
=> Partial update

Dockerfile
Might as well follow the FHS and match the recently-uploaded Debian packaging.
=> Use /usr/lib, not /var/lib - the latter is for program state, not libraries or modules.

src/buffer.c, src/buffer.h, src/forward_index.c, src/forward_index.h, src/inverted_index.c, src/inverted_index.h, src/pytest/test_wideschema.py, src/query.c, src/query_node.h, src/redisearch.h, src/rmalloc.h, src/run_valgrind.sh, src/spec.c, src/spec.h, src/tests/test_index.c, src/util/block_alloc.h, src/varint.c, src/varint.h
This PR makes the field mask used in index records 128 bit, with variable encoding. For indexes with less than 32 fiellds there is no change in encoding. 
For indexes with over 32 fields, we added a new "wide" encoding, where up to 128 bits of field bitmask are stored after the record and before the offset vector.
=> Support for up to 128 text fields

src/Makefile, src/dep/libnu/Makefile, src/tests/ext-example/Makefile
This should add support for kfreebsd and GNU/Hurd.
via https://bugs.debian.org/879948
Signed-off-by: Chris Lamb <chris@chris-lamb.co.uk>
=> Don't assume that !Linux is OSX.

docs/Highlight.md, docs/Tags.md, src/ext/default.c, src/forward_index.c, src/numeric_index.c, src/pytest/test.py, src/pytest/test_summarize.py, src/pytest/test_wideschema.py, src/query.c, src/stemmer.c, src/stemmer.h, src/tests/test_stemmer.c, src/tokenize.c
so that searching for a word that's both a stem and a valid term with VERBATIM - will not return documents not containing the verbatim term. 
For example, if we index two documents, one with the term "going" and one with the term "go". 
Before this PR, searching for "go" verbatim, will return the doc containing "going". 
After this PR this won't happen. 
This is because we now use two separate indexes for the term and the stem even if they are identical. we prepend a `+` to the stem. So "going" would get encoded into two indexes: `going` and `+go`. But `go` will get encoded only into `go`. Thus in verbatim mode, we search only for `go`, but in expanded mode we search for `go OR +go`.
=> Index stems with a prefix

.gitignore
This would help when packaging this for Debian - currently any changes I
make to the debian/ directly are not immediately visible due to the
default ignore rule. Applying this would mean even less diff between
upstream and the Debian version.
=> Unignore /debian dir in .gitignore

src/query.c
src/query.c:679:32: warning: format '%llx' expects argument of type 'long long unsigned int', but argument 3 has type 'long unsigned int' [-Wformat=]
s = sdscatprintf(s, "@%llx", (uint64_t)qs->fieldMask);
~~~^   ~~~~~~~~~~~~~~~~~~~~~~~
%lx
=> Fix -Wformat error for "long unsigned int"

docs/Commands.md
> Thus, deleting and re-inserting the same document over and over will inflate the index size with each re-insertion.
This is not true anymore, the GC actually removes the documents from the index after deleting them
Ref #261
=> Update documentation for FT.DEL

src/pytest/test.py, src/query.c, src/search_request.c, src/search_request.h, src/stopwords.c, src/stopwords.h
The `NOSTOPWORDS` option wasn't being honored. The empty stopword list
is now used whenever NOSTOPWORDS is detected, as this will abstract this
option from the rest of the code.
=> Fix NOSTOPWORDS

src/Makefile, src/dep/friso/Makefile.RediSearch, src/dep/libnu/Makefile, src/dep/triemap/Makefile, src/dep/triemap/test/Makefile
Whilst working on the Reproducible Builds effort [0], we noticed
that redisearch could not be built reproducibly. This is because
it links (etc.) in filesystem ordering which is non-determinstic.
Adding some $(sort ...) calls fixes this for me. You can test this
by using our "disorderfs" tool to mangle the directory ordering.
[0] https://reproducible-builds.org/
=> Please make the build reproducible

docs/Scoring.md, src/ext/default.c, src/ext/default.h, src/pytest/test_scorers.py
This PR adds the ability to rank results by comparing the Hamming distance between the query payload and the document payload. This only works if both have payloads and both payloads are the same length.
=> Added hamming distance scorer

src/aggregate/reducer.c, src/aggregate/reducer.h, src/aggregate/reducers/count_distinct.c
This adds reducers for:
- `HLL`: Returning the approximate number of distinct elements as an
opaque HLL
- `HLL_SUM` - Return the number of distinct elements from one or more
HLLs.
=> Reducers for HLL

src/inverted_index.c, src/inverted_index.h, src/redisearch.h, src/tests/test_index.c, src/tests/test_tag_index.c
I need to write tests for this. I tried removing the block's `lastId` field but it became a bit annoying. We do *sort* of use it for binary search. It's possible to remove it, but it's not super trivial. I did find some places where we could optimize the binary search even more, but I don't want to mess with that code now unless we have to.
=> 64bit ids (WIP)

src/gc.c, src/gc.h, src/rmutil/periodic.c, src/rmutil/periodic.h, src/spec.c, src/spec.h
When deleting and index, if the gc thread is inside the blocking stage:
if ((rc = pthread_cond_timedwait(&tm->cond, &tm->lock, &timeout)) == ETIMEDOUT) {
then it will get the signal and exist. But if the gc is currently running then it will not get the signal and will keep running.
Now as long as we do not create an index with the same name we are safe, the gc will failed to open it and will do nothing.
The moment we recreate the index, the gc reopen it and start running on garbage …
The more docs we have the greater the probability that we send the signal while the gc is running.
The solution is set a unique id to each index on index creation, when gc iteration starts we check that the unique id match.
If the unique id is not match we just drop the gc thread.
=> fixed: redisearch crashes on gc invocation after deleting and recreating an index

src/aggregate/aggregate_plan.c, src/pytest/test_aggregate.py
Now user will not be able to use LOAD after GROUPBY/SORTBY/APPLY/LIMIT/FILTER.
Error message will be returned to the user in such case.
=> see #374, fixed crash when using LOAD after GROUPBY

CMakeLists.txt, src/rmutil/CMakeLists.txt, src/rmutil/periodic.c, src/rmutil/test_cmdparse.c, src/rmutil/test_periodic.c
Effectively, we maintain rmutil here in RediSearch, so we ought to run
its tests to ensure its stability.
=> Don't forget to run RMUtil's own tests

.circleci/config.yml
According to this https://discuss.circleci.com/t/build-workflow-not-triggered-when-tag-is-pushed/19577/5
We need to add filter to the require jobs also, it looks like it is working.
=> fixed circle to trigger on tags

docs/Commands.md, docs/Configuring.md, docs/Escaping.md, docs/Overview.md, docs/Phonetic_Matching.md, docs/Scoring.md, docs/Spellcheck.md, docs/Stopwords.md, docs/index.md, docs/python_client.md, mkdocs.yml
These absolute links (as is normal in Markdown) get translated to their
proper equivalents with mkdoc. Without markdown links, mkdocs just
passes these links through verbatim.
=> Fix broken doc links - use absolute .md links

src/module.c, src/pytest/test.py
=> fix(spellcheck): Free only if include, exclude dicts are allocated

src/doc_table.c
This ensures every single index in the doctable is valid even if there
isn't a valid ID mapping to a valid bucket on load-time
=> preallocate entire doctable if maxid is bigger than cap (#595)

src/cpptests/t_index.cpp, src/cpptests/t_query.cpp, src/pytest/test.py, src/rmutil/args.c, src/rmutil/args.h, src/spec.c
I noticed some weird bugs when parsing the schema code (see mailing
list). I thought it would be prudent to just rewrite it rather than
using the error-prone "-exists" format
=> Convert schema/spec parsing code to AC subsystem

src/document.c, src/document.h, src/indexer.c, src/pytest/test.py, src/redisearch.h
Ensures that geo fields are replaced the moment the document ID is
popped. This uses a flag to ensure that we don't scan for geo fields
when the document does not have them, so that performance is not
impacted otherwise.
=> Clean up geo fields on REPLACE (#588)

src/cpptests/common.cpp, src/cpptests/redismock/internal.h, src/cpptests/redismock/redismock.cpp, src/cpptests/redismock/util.cpp, src/cpptests/redismock/util.h
- RMCK::hset, RMCK::flushdb utility functions
- Implement RM_Call (currently only supporting HGETALL)
- Implement the various CallReply functions
- Fix crash on destruction: ensure global dtor is called last
=> Redismock improvements:

src/spec.c, src/spec.h
We created RSDummyContext specifically for this
=> Use RSDummyContext rather than dedicated 'strctx' in spec

src/pytest/test.py
Cluster mode has different key names, so we can't predict a
failure/conflict
=> Skip test with key names on cluster

src/pytest/test.py
ft.debug, neither of which exist on the cluster (and the per-node
variant would be too complex)
=> Skip prefix test on cluster; we rely on ft.config and..

src/document.c, src/indexer.c, src/indexer.h
@mnunberg the branch name is misleading, eventually I find it easier to just close the indexer thread when all the indexer tasks have been finished.
=> drop indexer when index is dropped

src/pytest/test.py, src/value.c
…re not exists in all the documents
=> fix #848, redisearch will not crashing when sorting on fields which are not exists in all the documents

src/module-init/module-init.c, src/redismodule.h
- Adapted scheme used in RediSearch (i.e., REDISMODULE_XAPI_* macros)
- Have X in REDISMODULE_XAPI_*(X) receive (TYPE, NAME, ARGS) triplet instead of (NAME),
which makes it possible to avoid double-dipping of API names
=> Refectoring of redismodule.h

src/aggregate/aggregate_request.c, src/pytest/test.py, src/pytest/test_aggregate.py, src/rlookup.c
The fields in sortable are not an exact duplicate of the fields as
stored within the document. Therefore, we should never return from them,
since it will yield inconsistent data with normal search results.
Some more changes were done here in order to compensate for the fact
that typing information is needed to be added internal to items fetched
from the Redis hash
=> Don't return from sortables in aggregation

.gitignore, Makefile
This is a simple PR with the intent to add callgrind call graph profile rule to Makefile.
make callgrind should enable you to launch valgrind's tool callgrind with the correct parameters.
=> [add] added callgrind call graph profile rule to Makefile

src/module.c, src/pytest/test_replicate.py
* Removed string not is place
* Added correct parsing for DD
* Tests
=> Issue993 FT.DEL redismodule_replicate

src/numeric_index.c, src/util/arr.h
```
[ 41%] Building C object CMakeFiles/rscore.dir/src/numeric_index.c.o
Unit growth for small function inlining: 0->0 (0%)
Inlined 0 calls, eliminated 0 functions
```
```
[ 14%] Building C object CMakeFiles/rscore.dir/src/numeric_index.c.o
/Users/filipeoliveria/redislabs/RediSearch/src/numeric_index.c:73:25: optimized:   Inlining __inline_array_len/161 into NumericRange_Add/211 (always_inline).
Unit growth for small function inlining: 0->0 (0%)
Inlined 1 calls, eliminated 0 functions
```
=> [add] inlining array_len specifically for NumericRange_Add

src/document.c, src/highlight_processor.c, src/pytest/test_summarize.py
Fixes #1018 
This PR fixes 2 issues:
- NONINDEX fields caused crashes
- Empty fields caused crashes
=> Fix for Issue1018 for 1.4

src/aggregate/reducers/quantile.c
Remove usage of optimization which resulted in false results.
Can't find the original algorithm to try and fix.
Should the code of optimization be removed altogether?
=> remove optimization which causes inaccurate results

src/aggregate/aggregate_plan.h, src/aggregate/aggregate_request.c, src/pytest/test_aggregate.py
This reverts commit 79bf27380d50a4b0ddf18d3da0074ca1e0a1c728.
=> Revert "Change how generated reducer aliases are made"

src/dep/phonetics/double_metaphone.c, src/tokenize.c
fix #835 
BTW, none of the callers is using the `secondary` argument. Should we just eliminate it?
=> externed free from function

src/cpptests/t_value.cpp, src/value.c
Ensure that numeric values remain in tact when trying to represent them.
This is done by checking to see if the double value can be converted to
its integral value (and back) without any loss.
=> Don't truncate possible integral values when printing (#1074)

src/config.c, src/config.h
Reverted:
allow changing cursor max idle value #985:
setCursorMaxIdle()
getCursorMaxIdle()
configuration: .name = "CURSOR_MAX_IDLE"
Concurrent write mode #989:
setConcurentWriteMode()
getConcurentWriteMode()
configuration:
.name = "SAFEMODE"
.name = "CONCURRENT_WRITE_MODE"
.concurrentMode = 0
=> Revert damage by #986: work from #985, #989

src/config.c, src/config.h
bad commit:       04574d5d75a61a64e3ae25e7d2bbb663541c3c99
pre bad commit: 84ffb40cf3834b38b3a2cd3b30bd3faa5279400b
Reverted:
allow changing cursor max idle value #985:
setCursorMaxIdle()
getCursorMaxIdle()
configuration: .name = "CURSOR_MAX_IDLE"
Concurrent write mode #989:
setConcurentWriteMode()
getConcurentWriteMode()
configuration:
.name = "SAFEMODE"
.name = "CONCURRENT_WRITE_MODE"
.concurrentMode = 0
=> Revert damage by #986: work from #985, #989 (#1113)

src/doc_table.c, src/pytest/test.py, src/query.c
* see MOD-505, fix memory leak on tag searches where key pointer ownership are not pass to ConcurrentIterators
* fix failing tests
* review fixes
(cherry picked from commit 2b6aaba5979cb954d43aed188775c49e5ccb0191)
=> see MOD-505, fix memory leak on tag searches where key pointer owners(#1126)

docs/Overview.md
Fixed the spelling for the word 'receives' in the 'Scalable Distributed Search' paragraph
=> Typo in 'Scalable Distributed Search' seaction

src/aggregate/expr/expression.c, src/pytest/test.py
This PR along with #1163 (which fixes !@FIELD) fix issue #1158 
When evaluating an `OR` query, if the left side returns true, the right side isn't evaluated.
=> expression evaluation evaluate both sides of OR/AND - fix 1158

src/ext/default.c, src/pytest/test_phonetics.py, src/spec.c
fix #1313 
changes in `spec.c` are where FieldSpec used `sp` instead of `fs`.
=> [Issue-1313] fix fieldmask for phonetics

docs/Commands.md
(cherry picked from commit 0259bf4e47df057a657d2dd1da154e9f7f29804b)
=> fix docs no need to be sortable for sortby (#1357)

src/cpptests/redismock/redismock.cpp, src/cpptests/t_agg.cpp, src/cpptests/t_expr.cpp, src/module-init/module-init.c, src/tests/test_summarize.c, src/trie/trie_type.c
`-Werror=implicit-function-declaration` and `-Werror=incompatible-pointer-types` are set in `src/cmake/redisearch_cflags.cmake`. Can't see how to silence them...
=> silence compiler warning

docs/Configuring.md, src/aggregate/aggregate_request.c, src/config.c, src/config.h, src/pytest/test_config.py, src/pytest/test_issues.py, src/search_options.h
=> Fix issue 1414 remove hard limit on ft.search

docs/Query_Syntax.md
Small typo in the documentation https://redis.io/commands/georadyus  leading to a broken link
This PR fixes the link
=> Broken link to Georadius due to typo

mkdocs.yml
This fix will limit the depth in all documentation pages to 2.
looking through the pages, [Aggregation](https://oss.redislabs.com/redisearch/Aggregations/) is the only page we might want to keep in the older format.
=> limit table of content depth to:2 in mkdocs - WIP

docs/Configuring.md
(cherry picked from commit 8bc5b460b0966b1546f192b69121dd64fdc7364c)
=> [2.0] fix #1527 - extend the MAXDOCTABLESIZE docs (#1529)

src/aggregate/aggregate_request.c, tests/pytests/test_aggregate.py, tests/pytests/test_issues.py
fix #1588
This fixes a bug where the latest `sortby` params override all the previous ones.
=> Prevent multiple sortby steps

src/notifications.c, src/redismodule.h, src/result_processor.c, src/spec.c, src/spec.h
* Fix duplicate results on resharding
* Small bug fixes, more logs.
* On redis version 6.0.6 we will not filter keys which are not in our slot range to not risk in missing results
=> Fix duplicate results on resharding (#1635)

docs/index.md
RU201 has been retired and replaced by RU203, this PR updates the course name and link.
=> Updated Redis University course link

src/query_parser/parser.c, src/query_parser/parser.y, tests/pytests/test_issues.py
The parser differentiates between all terms and stopwords before creating lists of terms. Therefore stopword has to be added to a tag-list explicitly.
fix #1667 
fix #984 
We had more issues (#1237 and #1294) where users emptied their stoplist.
=> add STOPWORD to TAGLIST in query parser

src/stopwords.c, src/stopwords.h, tests/pytests/common.py, tests/pytests/test.py
The test did not run in the past b/c `env.isCluster` was missing `()`.
Fixed the use of a global empty list which was not used.
=> Use global empty list + tests

docs/Commands.md
Add a note about the right order (longitude, then latitude).
Close #1698
=> #1698 Use a less ambiguous Lon/lat coordinate in the example

.github/workflows/deploy-docs.yaml
> After some time, files may be removed from the documentation but they will still reside in the site directory. To remove those stale files, just run mkdocs with the --clean switch.
https://www.mkdocs.org/#building-the-site
Fix #1587
=> Clean old files from the doc

mkdocs.yml
Fixes two issues with the regexp exclusion:
Exclusion should be on 1.8 and not on v1.8
Currently the doc is based on two digit version 2.0 (not 2.0.x)
=> Remove branch 1.8 from the doc (master)

mkdocs.yml
Fixes two issues with the regexp exclusion:
- Exclusion should be on 1.8 and not on v1.8
- Currently the doc is based on two digit version 2.0 (not 2.0.x)
=> Doc - Exclusion of 1.8 on branch 2.0

docs/Configuring.md
Correction for docs `MAXAGGREGATERESULTS` change from 1000000 to unlimited
=> fix docs for MAXAGGREGATERESULTS to unlimited

src/module.c, tests/pytests/test.py
Prior, `FT.ALTER idx ADD SCHEMA txt TEXT` (instead of `FT.ALTER idx SCHEMA ADD txt TEXT`) would return `OK` but not change the schema.
=> return error for ft.alter w/o schema

src/redisearch_api.c, src/sortable.c, src/sortable.h, src/spec.c, tests/cpptests/test_cpp_index.cpp, tests/pytests/test_issues.py
Saves 4kb for indexes with a low number of sortable fields
=> Realloc for RSSortingTable

src/result_processor.h
Silence compiler and avoid future conflicts
=> Change time macro to avoid redefinition

src/module-init/module-init.c, src/query.c, src/redisearch_api.c, src/spec.c, src/spec.h, tests/cpptests/test_cpp_llapi.cpp
fix #1772 
Remove settings from index spec and use the global param.
For Low Level API, default changed to `minTermPrefix = 0` and `maxPrefixExpansions = LONG_MAX`
=> minTermPrefix & maxPrefixExpansions

src/document.c, src/document.h, src/document_basic.c, src/indexer.c, src/spec.c
replaces #1465
Seems like the whole `DOCUMENT_F_DEAD` flag was just to avoid realloc. Seems like too much work and complex things with copies of the document.
Relevant to #1462 where ownership issues caused us to not free some memory as it is being handled later, though logically it should be handled now.
=> Use pointer instead of in-struct copy of `Document`

README.md
The logo is broken here:
https://hub.docker.com/r/redislabs/redisearch/
=> Use absolute logo url for docker-hub

docs/Commands.md
FT.DROPINDEX deletes the document that are indexed. If the index creation is still running, the documents that have not yet been indexed will not be deleted.
=> Note on FT.DROPINDEX about possible remaining hashes

README.md
The logo is broken here:
https://hub.docker.com/r/redislabs/redisearch
=> Fix broken logo on docker hub

src/document_basic.c, tests/pytests/test_followhashes.py
`strdup` replaced with `strndup`.
Then replaced with `memcpy`.
Tnx @MeirShpilraien
=> [BUG] Mod 737 - binary payload corrupt due to `strdup` operation.

src/aggregate/aggregate_exec.c, src/rlookup.c, src/rlookup.h
An optimization that will determine the number of fields to return instead of using the `REDISMODULE_POSTPONED_ARRAY_LEN` flag.
=> remove REDISMODULE_POSTPONED_ARRAY_LEN from serializeResult

src/dictionary.c
This change causes `spellCheckDicts` to be ignored by the free routine if it is a NULL value.
=> Dictionary_Free does nothing on a non-NULL dict

src/cursor.c
Fixes sanitizer warning on [CircleCI](https://app.circleci.com/pipelines/github/RediSearch/RediSearch/3182/workflows/505dcaa6-c6fb-4a86-a03f-19b92318391f/jobs/20855).
The issue was the struct is being Nulled using `memset`, and therefore the sanitizer reports potential `use-of-uninitialized-value`.
=> assign Null explicitly to CursorList->specs

cmake/redisearch_cflags.cmake
-Bsymbolic can have unintended consequences during the linking process. We should look at removing it in general.
=> removing -Bsymbolic linker flags from OSX.

system-setup.py
Added support to build RediSearch on Arch Linux derivatives.  This is contingent on merging [readies issue #8](https://github.com/RedisLabsModules/readies/issues/8).
=> support for building on arch linux derivatives

src/rlookup.c
This PR addresses #1892 , using the old logic on CRDT deployments.
=> Fix: using old RLookup_HGETALL() logic on enterprise-crdt

src/rlookup.c
This PR cherry-picks #1902 into 2.0 branch.
=> cherry-pick fix: using old RLookup_HGETALL() logic on enterprise-crdt (#1902)

src/rlookup.c, tests/pytests/test_followhashes.py, tests/pytests/test_rdb_compatibility.py
=> do not return payload as field

src/stopwords.c
We recently introduced a global variable `__empty_stopwords`. We can use it to return fast when tokenizing terms index time or when filtering out terms at query time.
=> Return fast on empty stopword list

src/aggregate/aggregate.h, src/aggregate/aggregate_plan.h, src/aggregate/aggregate_request.c, src/profile.c, src/result_processor.c, src/result_processor.h, tests/pytests/test_profile.py
Before this change, when a search was with a limit of 0,  `Scorer`, `Sorter` and usually `Loader ResultProcessors` would be created which consume cpu time.
This PR replaces them with a `Counter` RP which adds to the count and frees the `SearchResult` content.
=> Add a counter ResultProcessor

src/rlookup.c, src/rlookup.h
We can see that specifically for queries that touch a large number of docs, and looking at on-CPU time, the line 68 of rlookup.c takes ~4-5% of CPU time for this query.
Given we have `strlen` always precomputed when we createNewKey() we can totally skip this, giving us the following expected improvement:
Note: multi-client benchmark ( 10 clients ) |   |   |  
-- | -- | -- | --
Overall requests per second |   |  
Query | master ( 2fbdeefb975828f3a58a44ab1417e890e42d390f ) | rlookup.optimization branch | % change
"FT.SEARCH" "idx" "@searchKey:<...>" "WITHPAYLOADS" "LANGUAGE" "english" "SORTBY" "gender" "ASC" "LIMIT" "0" "5000" | 12.97 | 13.77 | 6.17%
"FT.SEARCH" "idx" "@searchKey:<...>" "WITHPAYLOADS" "LANGUAGE" "english" "SORTBY" "gender" "ASC" "LIMIT" "0" "50" | 644.79 | 656.25 | 1.78% …
=> Avoid expensive unecessary strlen within RLookup_GetKeyEx()

docs/Tags.md
People have repeatedly asked me the same questions about how to use TAG fields, and most of the questions are about how escaping works. I've attempted to refactor the existing docs page on TAG fields to more clearly explain how escaping works.
=> Refactor the TAG docs based on repeated questions

src/aggregate/aggregate_exec.c, tests/pytests/test_profile.py
With Coordinator, WITHCURSOR is used internally.
=> Disable CURSOR  on shard for FT.PROFILE

src/aggregate/functions/date.c, tests/pytests/test.py, tests/pytests/test_aggregate.py
`parse_time` function can be used.
@emmanuelkeller please note the function expects a string since it uses `strptime` behind the scene. 
fix #1959
=> Fix parse_time function

docs/Commands.md
We have examples scattered around the documentation in places like the query syntax page and aggregations page. Having examples on those pages is good, and also speaking for myself, I expect lots of examples within the actual command documentation.
=> Add FT.CREATE, FT.SEARCH, and FT.AGGREGATE examples

src/index.c, tests/pytests/test.py
(cherry picked from commit c7ac47a310c4943a8601612203f2e1d7227f3c41)
=> [CP 2.0] issue #1986 skip intersect iterator qsort if INORDER flag is used (#1994)

src/config.c, src/config.h, src/document_add.c, src/document_basic.c, src/pytest/test_issues.py
This changes the behavior of `FT.ADD REPLACE` to remove all fields from the hash and insert only the new provided fields.
=> [1.6] Add REPLACE_DELETE_HASH_FIELD param

.circleci/config.yml
(cherry picked from commit defa59716fd014ac13fdad9c215967369a587b21)
=> [2.2] CircleCI: disabled ubuntu_benchmarks until fixed (#2129)

src/redisearch_api.c, src/spec.c, src/spec.h
Function `FieldSpec_Initialize` was used to patch the bug of using `tagFlags` instead of `tagSep` in `IndexSpec_CreateField`.
Code is more readable with just setting `fs->types` instead of calling a function.
=> Remove `FieldSpec_Initialize`

.circleci/config.yml, Makefile, tests/ci.benchmarks/requirements.txt, tests/ci.benchmarks/ycsb-commerce-hashes-load.yml, tests/ci.benchmarks/ycsb-commerce-hashes-run-0.yml, tests/ci.benchmarks/ycsb-commerce-hashes-run-10.yml, tests/ci.benchmarks/ycsb-commerce-hashes-run-20.yml, tests/ci.benchmarks/ycsb-commerce-hashes-run-30.yml, tests/ci.benchmarks/ycsb-commerce-hashes-run-40.yml, tests/ci.benchmarks/ycsb-commerce-hashes-run-50.yml
we now have 7 YCSB benchmark variations on RediSearch ( with HASHES ):
ingestion test
0% updateproportion, readproportion : 35%, searchproportion : 65%
10% updateproportion, readproportion : 30%, searchproportion : 60%
20% updateproportion, readproportion : 25%, searchproportion : 55%
30% updateproportion, readproportion : 20%, searchproportion : 50%
40% updateproportion, readproportion : 15%, searchproportion : 45%
50% updateproportion, readproportion : 10%, searchproportion : 40%
Search CI is green now:
https://app.circleci.com/pipelines/github/RediSearch/RediSearch/4363/workflows/57a760bf-1e83-4e77-8c64-94bc140e69fe/jobs/26928
=> Re-enabled ci benchmarks

src/dep/triemap/triemap.c, src/dep/triemap/triemap.h, tests/pytests/test_issues.py
Fixes #2116 
The previous function iterated recursively over the whole trie and collected the size of each node including the string which defines the node ID. This operation has the complexity of O(n) and presents the lower bound of memory allocation since the memory allocated for the struct would be padded to 8 bytes (since the struct contains `void *` ptr).
The calculation in this PR is based on the cardinality of the trie. It multiplies it by the size of the struct, the point and char held by its parent, and a constant of 8 bytes, to compensate for the memory which is padded out.
=> Improve FT.INFO complexity to O(1)

tests/pytests/test_aggregate.py
Test was changed to use `FT.CONFIG` at runtime instead of Env(moduleArgs=foo) at initilization time. Therefore, it should be skipped on RSC.
=> skip testMaxAggResultson on RSC

src/doc_types.h, src/notifications.c
- Avoid keyspace notification handler from defaulting to `hset` command (even when key is JSON)
- Avoid calling `isJSON` for built-in none-hash keys, e.g., Set, List, Stream, etc.
xadd user:1 * first h last simpson
lpush list:1 "sun" "morning"
hset hash:1 t 1 u 2
json.set doc:1 $ '{"t":"f"}'
ft.create idx ON JSON SCHEMA $.t AS t TEXT
=> Avoid unneeded code (small performance fix)

.circleci/ci_prepare_benchmark.sh, .circleci/config.yml, Makefile, tests/ci.benchmarks/requirements.txt, tests/ci.benchmarks/ycsb-commerce-json-load.yml, tests/ci.benchmarks/ycsb-commerce-json-run-0.yml, tests/ci.benchmarks/ycsb-commerce-json-run-10.yml, tests/ci.benchmarks/ycsb-commerce-json-run-20.yml, tests/ci.benchmarks/ycsb-commerce-json-run-30.yml, tests/ci.benchmarks/ycsb-commerce-json-run-40.yml, tests/ci.benchmarks/ycsb-commerce-json-run-50.yml
The following PR adds 7 extra benchmarks to CI using JSON, and relies on JSON+Search modules:
- ycsb-commerce-json-load: "YCSB Commerce workload (LOAD step) using RediSearch v2 + RedisJSON v2"
- ycsb-commerce-json-run-0: "YCSB Commerce workload (RUN step) using RediSearch + RedisJSON doing 0% updates"
- ycsb-commerce-json-run-10: "YCSB Commerce workload (RUN step) using RediSearch + RedisJSON doing 10% updates"
- ycsb-commerce-json-run-20: "YCSB Commerce workload (RUN step) using RediSearch + RedisJSON doing 20% updates"
- ycsb-commerce-json-run-30: "YCSB Commerce workload (RUN step) using RediSearch + RedisJSON doing 30% updates"
- ycsb-commerce-json-run-40: "YCSB Commerce workload (RUN step) using RediSearch + RedisJSON doing 40% updates"
- ycsb-commerce-json-run-50: "YCSB Commerce …
=> Enable Search+Json benchmarks on local/remote setups

docs/Aggregations.md
I noticed that the last method signature for geodistance was the same as the previous - believe it was meant to be `geodistance(lon,lat,lon,lat)` - which works with aggregations, but is not enumerated in the table
=> Fixed last geodistance method signature

src/rlookup.c
Getting a json value using a path not beginning with a dollar will surely fail, so the first attempt can be spared.
The second attempt can succeed if a proper json path is obtained from the `FieldSpec` path.
=> Avoid calling json to get a path not starting with a dollar

src/aggregate/aggregate.h, src/aggregate/aggregate_request.c, src/aggregate/group_by.c, src/config.h, src/result_processor.c, src/result_processor.h, tests/cpptests/test_cpp_agg.cpp, tests/pytests/test.py
Before this PR, Timeout was set only on the index result processor (`indexer`) which holds all inverted index iterators.
Two result processors, `sorter` and `grouper` have internal storage where they collect all results from the `indexer`.  Before this fix, if a timeout is reached while results are being read from a sorter or grouper, the query would not stop.
=> Add timeout to groupby and sorter result processors

src/field_spec.c, src/rlookup.c, src/spec.c, src/spec.h
This PR avoids seeking a field's path from the field's name when loading individual fields from a hash.
=> [OPTIM] Do not check path if index has no aliases

src/document_add.c
RM_CALL with `DEL` or `HSET`.
This function is used by `FT.ADD` which was deprecated.
=> [BUG] close key before calling RM_CALL on it

src/fork_gc.c, src/numeric_index.c, src/numeric_index.h, src/tag_index.c, tests/pytests/test_tags.py
The fix updates ForkGC to remove empty tag values from the trie.
This bug affected indexes where TAG fields are updated with new values while the old, deleted values are left in the trie.
=> [BUG] Remove empty tag values

docs/Commands.md, src/aggregate/aggregate_request.c, tests/pytests/test.py
* test + fix
* docs
* per Refi's review
* ensure a sortby or multisortby are exclusive
* MULTISORTBY to MSORTBY
(cherry picked from commit 725dfbf40817a003aab5a751073364263df6f811)
=> [2.0] FT.SEARCH has MSORTBY option (#2245)

src/aggregate/aggregate.h, src/aggregate/aggregate_request.c, src/aggregate/group_by.c, src/config.h, src/result_processor.c, src/result_processor.h, tests/cpptests/test_cpp_agg.cpp, tests/pytests/test_followhashes.py
This reverts commit 12f2741b3ed9fbecc6c378bc426fbd7c5c65a7d5.
=> Revert "Add timeout to groupby and sorter result processors (#2239)"

src/index.c, tests/pytests/test_issues.py
* Fix MOD-1808, check for NULL result on intersect iterator.
* fix access to uninitialized value
Co-authored-by: Rafi Einstein <rafi@redislabs.com>
Co-authored-by: Ariel Shtul <ariel.shtul@redislabs.com>
(cherry picked from commit 128f28f02e19e169daba05eacef3de191c4778a8)
=> Fix MOD-1808, check for NULL result on intersect iterator. (#2342)

src/document.c, tests/cpptests/test_cpp_llapi.cpp
related to #2341 fix for documents with 0 value on a numeric field.
For JSON and LLAPI, since #2133 there was a bug where a `0` value would be ignored. This PR along with #2341 fix for both.
=> [BUG] fix for NUMERIC with 0 for LLAPI

.gitmodules
This PR updates the vecsim library repo path from RedisLabsModules/VectorSimilarity to RedisAI/VectorSimilarity
=> update vecsim repo

deps/triemap/triemap.c
The performance improvements in this PR are the ones reflected from going from the RED line to the YELLOW line. 
After #2424 is merged this PR should be rebased.
=> PERF triemap: using memchr() to locate character in block of memory instead of our looped implementation

src/aggregate/aggregate_exec.c, tests/pytests/test.py
(cherry picked from commit 4e049c18f4cea92b41d23d8f636a32094749e85e)
=> [2.2] CP Timeout freeze while sorting fix #2414

src/config.c, src/config.h, src/debug_commads.c, src/fork_gc.c, src/numeric_index.c, src/numeric_index.h, tests/pytests/test_config.py, tests/pytests/test_debug_commands.py, tests/pytests/test_numbers.py
* [BUG] fix numeric field gc leak
* fix for lock failure
* move counter to tree struct
* Use pointer to pointer
* try with FT.DEBUG function
* test w/o cleaning
* w/o pipeline
* put fix back into gc
* fix test
* increase number of iterations to trigger trimming
* fix
* remove rebalance
* better test + rebalance
* set large interval
* update maxDepth
* fix balance
* add module FORK_GC_CLEAN_NUMERIC_EMPTY_NODES flag
* fix
(cherry picked from commit 82e2cb286880e7f831e683b1bb1020a4128c6b88)
=> [2.2] NUMERIC index leak fix (#2386)

coord/src/dist_aggregate.c
related to #2467 
Bug when there is no `ResultProcessor` on the coordinator in addition to `RPNet`.
=> [BUG] If no result processor is peresent

docs/Indexing_JSON.md
Align with 2.2 (no need to cherry-pick)
=> Fix doc: sub headings on indexing json array

.circleci/config.yml
(cherry picked from commit 23b9625be7efe899698cfcf9050cf8d65bc2e3f9)
=> [2.2] CircleCI: allow macOS to upload artifacts (#2504)

src/index.c, tests/cpptests/test_cpp_index.cpp
This PR fixes a bug in the intersect iterator, where calling `Read()` after `SkipTo()` returns the current id instead of the next one.
=> Fix intersect iterator

coord/src/module.c
Add MRCluster_MastersOnly to the coordination strategy of the FlatSearchCommandHandler
Co-authored-by: Ariel Shtul <ariel.shtul@redislabs.com>
(cherry picked from commit 7f2331a9fffaf7ade423e9abb24ebed63cd9f559)
=> [2.2] Update coordination strategy of FlatSearchCommandHandler (#2404)

tests/pytests/requirements.txt
This allows a longer-tail migration to the latest version as each repository is ready, without breaking individual projects.
=> Pinning rltest to the last release prior to redis-py 4 as a requirement

tests/pytests/requirements.txt
* pinning rltest to the last version prior to redis-py 4.
This allows a longer-tail migration to the latest version as each repository is ready, without breaking individual projects.
* Updated readies
Co-authored-by: rafie <rafi@redislabs.com>
(cherry picked from commit af9474d34d144e53f808c5b63c9d6e91bc3b8d08)
=> [2.4] Pinning rltest to the last release prior to redis-py 4 as a requirement (#2575)

src/config.c, src/config.h, src/module-init/module-init.c, src/module.c, src/rules.c, src/spec.c, src/spec.h, tests/pytests/test.py, tests/pytests/test_config.py
For a large index, releasing all internals might be a major task that costumes much time.
In this PR, all data that is not connected to any global data or does not require the GIL is free on a thread. The drop in consumed time is significant and would prevent a watchdog from killing the shard.
Related to MOD-2364
=> [PERF] Release some index spec info off the main thread

src/aggregate/aggregate_request.c, tests/pytests/test.py, tests/pytests/test_issues.py
Error message when two SORTBY steps exist in query -
For FT.SEARCH:
`Multiple SORTBY steps are not allowed`
For FT.AGGREGATE: 
`Multiple SORTBY steps are not allowed. Sort multiple fields in a single step`
=> [BUG] Fix multi sortby error message for FT.SEARCH

coord/src/rmr/rmr.c
A memory leak was present due to the fact the `cmd` struct was copied for a thread and then an `sds` was added to the original struct which is not freed.
Copying the ``cmd` struct after the addition of the `sds` in function `MRCluster_SendCommand` prevented the leak.
MOD-2716
=> [BUG] Memory leak in the coordinator

src/aggregate/aggregate_exec.c, src/result_processor.c, src/spec.c, tests/pytests/test_followhashes.py
This fix prevents the client from freezing if a document expired during query time.
Previously, we skipped those results but currently, it is not possible since we reply with ArraySize instead of `POSTPONED_ARRAY_LEN`.
In this fix, reply with a `NullArray` if the documents have been deleted.
=> [BUG] fix client freeze on docs expire during query

src/hybrid_reader.c, src/hybrid_reader.h, src/vector_index.c, tests/cpptests/benchmark_vecsim_hybrid_queries.cpp, tests/cpptests/test_cpp_index.cpp, tests/pytests/test_vecsim.py
followup for [this PR](https://github.com/RedisAI/VectorSimilarity/pull/145) on VectorSimilarity, now we normalize the query vector only once and if needed, then using `getDistanceFrom` that now does not normalize by itself
=> Vecsim norm opt

src/spec.c
#2632 #2631  introduces a new field and such a new RDB encver for RediSearch. This PR introduces backwords compatibility for lower encver versions
=> vecsim rdb backwords support

src/indexer.c, src/inverted_index.c, src/inverted_index.h, src/redis_index.c, src/spec.h, tests/pytests/test_issues.py
In RediSearch, TEXT fields are global and all terms are indexed into common inverted indexes.
If a field is specified in a query, the inverted index is pulled and every valid result is filtered by comparing the requested fieldMask to the fieldMask of the result.
This PR adds a fieldMask to the entire inverted index. At query time, the fieldMasks are compared and if there is no match, an empty iterator is return which saves iterating throughout the inverted index which does not contain any match.
=> [PERF] In TEXT field, skip term iterator if term does not appear in requested field

src/result_processor.c
The assert was placed as part of #2651 fix.
With EXPIRE documents, it can be reached and the fix of printing out an empty array is sufficient.
There is no need to assert.
=> [BUG] remove assert from rploaderNext

src/result_processor.c, tests/pytests/test.py
If ONTIMEOUT policy is RETURN. We should switch the sorter to Yield mode so we will get the results we found so far.
=> Fix ONTIMEOUT return policy

src/vector_index.c, tests/pytests/test_vecsim.py
Compare entire vector field name instead of a prefix when creating a new vector index.
=> Fix vector field compare

src/aggregate/expr/expression.c
This might fix the bug reported in #2766.
As R->res is not initialized, there could be an edge case where we try to compare to an uninitialized RSValue.
=> Init all vars in EvalCtx

src/aggregate/aggregate_exec.c, tests/pytests/test_issues.py
This fix will return as many results as possible.
For example, with `max results 20` and  `LIMIT 15 10`, we will return `20 - 15 = 5` results.
Fixes #2803
Fixes redis/redis-om-dotnet#119
=> [BUG] Fix freeze when offset+limit greater than maxSearchResults

coord/src/module.c, coord/src/rmr/rmr.c, deps/rmutil/rm_assert.h, src/concurrent_ctx.c, tests/pytests/test_coordinator.py
* Add BlockedClientMeasureTime to coordinator
* Add macro to check support for `BlockedClientMeasureTime`
* fix
* fix test function name
* remove CMDCTX_COORD
* cleanup
* only condition of flag should be removed
(cherry picked from commit bbb55fa0ddf333ded7b497b72cd8efdde36cdb72)
=> [2.2] Add BlockedClientMeasureTime to coordinator (#2791)

coord/src/module.c, coord/src/rmr/rmr.c, deps/rmutil/rm_assert.h, src/concurrent_ctx.c, tests/pytests/test_coordinator.py
* Add BlockedClientMeasureTime to coordinator
* Add macro to check support for `BlockedClientMeasureTime`
* fix
* fix test function name
* remove CMDCTX_COORD
* cleanup
* only condition of flag should be removed
(cherry picked from commit bbb55fa0ddf333ded7b497b72cd8efdde36cdb72)
=> [2.4] Add BlockedClientMeasureTime to coordinator (#2791)

src/module.c, tests/pytests/test_issues.py
The bug was caused as we didn't check for the minimum of required args.
MOD-3372
=> [BUG] FT.EXPLAIN w/o parameters causes a crash

coord/src/module.c, tests/pytests/test_coordinator.py
* [BUG] Do not remove curly brackets returned by ft.search
* remove comment
(cherry picked from commit bd48daa4268a8666ca8aaac20a835a919bdf9597)
=> [2.2] Do not remove curly brackets returned by ft.search (#2802)

src/config.h, src/module-init/module-init.c, src/module.c, src/module.h, src/notifications.c, src/notifications.h, src/redis_index.c, src/spec.c, src/spec.h, tests/pytests/test_replicate.py
This PR is related to temporary indexes.
**Issue**
Currently, a timer is set on both master/slave. This caused several issues.
1. Every time an index is used for either ingest or query, its temporary timer is reset. some clusters will pass read calls only to the master and not to the slave. Therefore, we risk the temporary timer might reach time prior to the timer on the master.
2. The slave call rm_call(`DEL`) on all documents. This caused primary replica inconsistency (and crash on CRDT version since the slave should not get the write command directly).
**Solution**
In this PR we set the timer for the index on the master shard only and when an index expires, RM_CALL("FT.DROPINDEX idx DD") is called are erases the index from both master and slave.
In addition, an event of …
=> Set timer for temporary index on master only

tests/pytests/includes.py, tests/pytests/test.py, tests/pytests/test_rdb_compatibility.py, tests/pytests/test_short_read.py
On CI running on a background thread sometimes takes longer than running on the main thread,
so avoid comparing such runtimes.
Keep test for coverage.
=> Avoid flaky runtime comparison on CI

README.md, docs/docs/Quick_Start.md
The redis-stack-server docker is now the prefered way for trying out the latest version. This PR attempts to address the locations accordingly, and point to this docker.
=> Updating docker to point to redis-stack-server [skip ci]

src/module-init/module-init.c, src/module.c, src/module.h, src/notifications.c, src/notifications.h, src/redis_index.c, src/spec.c, src/spec.h, tests/pytests/test_replicate.py
This PR is related to temporary indexes.
**Issue**
Currently, a timer is set on both master/slave. This caused several issues.
1. Every time an index is used for either ingest or query, its temporary timer is reset. some clusters will pass read calls only to the master and not to the slave. Therefore, we risk the temporary timer might reach time prior to the timer on the master.
2. The slave call rm_call(`DEL`) on all documents. This caused primary replica inconsistency (and crash on CRDT version since the slave should not get the write command directly).
**Solution**
In this PR we set the timer for the index on the master shard only and when an index expires, RM_CALL("FT.DROPINDEX idx DD") is called are erases the index from both master and slave.
In addition, an event of …
=> [2.2] Set timer for temporary index on master only (#2825)

commands.json
=> Fix doc: Remove unneeded optional for `highlight` and `summarize`

tests/pytests/test_vecsim.py
In `test_hybrid_query_change_policy` - validate only that scores of the results that return in every hybrid mode are equal, instead of validating both scores and ids. That is since in case of a tie in the last score, different ids may return as part of the top k search.
=> Fix flaky vecsim test

src/doc_types.h, src/spec.c
* [BUG] open RM_Key before calling getDocType on it
* add comment
* fix new tests
* fix test - skip on cluster due to copy between slots
(cherry picked from commit a274f71f74c9c26af82aa0375a40ed21e6a98104)
Calling getDocType(RedisModuleKey *key) with a null value get a reply of DocumentType_Unsupported which caused a bug in Indexes_ScanProc.
In this fix, we call RM_OpenKey if the key is not received and close it.
MOD-3584
=> [2.4] open RM_Key before calling getDocType on it (#2875)

src/doc_types.h, src/spec.c
* [BUG] open RM_Key before calling getDocType on it
* add comment
* fix new tests
* fix test - skip on cluster due to copy between slots
(cherry picked from commit a274f71f74c9c26af82aa0375a40ed21e6a98104)
Calling getDocType(RedisModuleKey *key) with a null value get a reply of DocumentType_Unsupported which caused a bug in Indexes_ScanProc.
In this fix, we call RM_OpenKey if the key is not received and close it.
MOD-3584
=> [2.2] open RM_Key before calling getDocType on it (#2875)

src/aggregate/aggregate_request.c, tests/pytests/test_coordinator.py, tests/pytests/test_issues.py
Using SORTBY with MAX to limit the number of results would freeze the server if value is less than 10 or would cause output corruption if value is greater than 10.
related to #2347
MOD-3540
=> [BUG] SORTBY with MAX corrupt reply

src/aggregate/aggregate_request.c, tests/pytests/test_coordinator.py, tests/pytests/test_issues.py
* [BUG] SORTBY with MAX corrupt reply
* better tests
(cherry picked from commit 005a7ee0959b4c9630d24fadb27f64af88010fff)
=> [2.4] SORTBY with MAX corrupt reply (#2892)

README.md
=> Fix doc links from redis.com to redis.io

src/aggregate/aggregate_exec.c, src/aggregate/aggregate_request.c, tests/pytests/test_issues.py
* [BUG] disable SORTBY MAX for FT.SEARCH
* fix bug discovered in test_aggregate:testLoadPosition
* update readies
* Updated readies
* Updated readies (2)
Co-authored-by: rafie <rafi@redislabs.com>
(cherry picked from commit 9d218cb696a09f3200a9bb43f2db267589b282da)
=> [2.4]  disable SORTBY MAX with FT.SEARCH (#2900)

src/info_command.c, src/spec.c, src/spec.h, tests/pytests/test_stats.py
Add `total_indexing_time` to FT.INFO.
This includes the time of actual indexing and excludes network time and time of determining which indexes the document should be indexed.
=> introduce total_indexing_time to ft.info

src/redisearch_api.c, src/util/dict.c, src/util/dict.h
On LLAPI, we allow multiple readers to simultaniusly read from the index. In such case we can not allow rehashing the term dictionary because rehashing is not thread safe.
The PR add the ability to disable rehashing on dictionary and use it from LLAPI when locking the index for reads.
=> Avoid terms dict rehashing on multiple readers.

deps/triemap/triemap.c, deps/triemap/triemap.h, tests/cpptests/test_cpp_llapi.cpp, tests/cpptests/test_cpp_triemap.cpp, tests/pytests/test_contains.py, tests/pytests/test_tags.py
Currently, we do not sort node's children on insertion but only at query time.
While this might be more efficient, it makes the TrieMap not thread-safe for multiple readers.
A potential improvement - find the correct location of the new node (which is placed last) and use `memmove`. Can be faster than then `qsort`.
=> On TrieMap, move qsort to insert

docs/docs/Indexing_JSON.md
Updated the Index/Search JSON doc to incorporate some feedback from @oshadmi:
- Removed mention of indexing an array of booleans as `TAG` type since this is not currently supported.
- Added info about indexing existing docs asynchronously and indexing new or modified docs synchronously.
=> Update Index/Search JSON doc

src/rules.c
The current implementation of `SchemaPrefixes_RemoveSpec(IndexSpec *spec)` iterates over all prefixes in the database and then compares all specs in the list to the spec. 
The new implementation retrieves the prefix list attached to the spec and removes the spec from those lists.
=> [PERF] efficiant removal from prefix list

src/gc.c, src/spec.c, tests/pytests/test_gc.py
* Use local GC ctx and add logs
* get the right ctx
* per review
* add test
* Skip GC on cluster and temporarily comment out part of testMultiTextNested
* streamline code
* test fixed in #2967
* fix leak
Co-authored-by: oshadmi <omer.shadmi@redislabs.com>
Co-authored-by: Omer Shadmi <76992134+oshadmi@users.noreply.github.com>
(cherry picked from commit 3f7c8dbc9d20d805c2fc544c6ec20351ba337a96)
=> [2.2] Use local GC ctx in periodic callback  (#2962)

tests/pytests/test_vecsim.py
In this test, we are using random vectors, so there is a rare condition where the hybrid iterator will switch it's state from BATCHES to ADHOC_BF instead of just running in BATCHES mode. By adding a seed, we make this test deterministic (as it is on master)
=> Add a seed to make test_hybrid_query_change_policy deterministic

tests/pytests/test_vecsim.py
This PR increases the size of the indexes we query on this test, so the query will take more time to run and therefore fail on `TIMEOUT 1`.
We now use `ON_TIMEOUT FAIL` and expect 0 on cluster and "Timeout limit was reached" message on standalone
=> fixes VecSim flaky timeout test

commands.json
Documentation should reflect that zero stopwords are allowed
Now it is
```[STOPWORDS count stopword [stopword ...]]```
Should be
```[STOPWORDS count [stopword ...]]```
=> FT.CREATE command syntax fix for zero stop-words

src/rules.c, tests/pytests/test_issues.py
In case many indexes were created with unique prefixes and dropped, the `SchemaPrefixNode` was not removed from the trie.
=> [BUG] clear SchemaPrefixNode if all related indexes were deleted

deps/triemap/triemap.c, tests/cpptests/CMakeLists.txt, tests/cpptests/test_cpp_triemap.cpp
Currently, a new child to the trie is placed at the end of the current array. Then a `qsort` function is called, which dereferences the children node pointers.
The fix finds the index for the new child and uses `memmove` to free space for it.
=> [PERF] Add child to TrieMap without using qsort

deps/triemap/triemap.c, tests/cpptests/CMakeLists.txt, tests/cpptests/test_cpp_triemap.cpp
This reverts commit 2eb0c6bc94c7ab7db1043293c39e9ac3cdc6326d.
=> Revert PR #2990 (Add child to TrieMap without using qsort)

docs/docs/reference/Query_Syntax.md
Href changed after V2 was added, and this link was pointing to a 404 page, so I've updated it to the new location.
=> Fix broken link

deps/triemap/triemap.c, deps/triemap/triemap.h, src/result_processor.c, src/rlookup.c, src/rules.c, tests/pytests/test_expire.py, tests/pytests/test_followhashes.py, tests/pytests/test_issues.py, tests/pytests/test_replicate.py
The current implementation of `SchemaPrefixes_RemoveSpec(IndexSpec *spec)` iterates over all prefixes in the database and then compares all specs in the list to the spec.
The new implementation retrieves the prefix list attached to the spec and removes the spec from those lists.
=> Cherry pick for 2.4 - DO NOT SQUASH

src/fork_gc.c, tests/pytests/test_numbers.py
This bug fix is for crashes on `NumericRange_Add` when adding a new document after documents have been deleted and the index was emptied. After the GC run, the array holding the cardinality values was nulled, and an attempt to insert a new value caused a crash.
The fix checks a cardVals array exists before updating the range.
closes #2818
closes #2817
closes #3006
related to #2434
MOD-4057
=> [BUG] fix forkGC null cardVals pointer

tests/pytests/test_vecsim.py
this PR improves this test to use `ON_TIMEOUT FAIL` policy in both standalone and cluster modes, as we already fixed on the 2.4 branch. we hope this change will solve future flakiness.
=> Improving VecSim Timeout test

commands.json, docs/commands/ft.alter.md, docs/commands/ft.create.md
Adds missing params to the syntax block:
[ FILTER {filter}]
[ SKIPINITIALSCAN]
=> [DOC] Update FT.CREATE syntax

tests/pytests/common.py
RedisJsonHdt tests also run RediSearch tests with corresponding RedisJSON
Related https://github.com/RedisJSON/RedisJsonHdt/pull/102
=> Fix test for RedisJSON 2.2 to use api ver 2

coord/src/module.c, src/aggregate/aggregate_exec.c, tests/pytests/test.py, tests/pytests/test_sortby.py
The coordinator SORTBY compare function relies on a prefix to determine the compare function.
For non-SORTABLE fields, we load a string from the hash and therefore the compare function treats it as a string.
The fix checks the type of field and aligns it if necessary.
MOD-4115
=> [BUG] Fix SORTBY numeric field for Non-Sortable on the coordinator

.circleci/config.yml, src/debug_commads.c, src/fork_gc.c, src/indexer.c, src/inverted_index.c, src/legacy_gc.c, src/redis_index.c, src/redis_index.h, src/spell_check.c
The PR modifies the process of TEXT field ingests to reduce unnecessary calls to `IndexSpec_AddTerm`, which updates the terms trie.
Currently, the code attempts to update the trie for each term in a document.
In this PR, function `openIndexKeysDict` got a new out parameter `outIsNew` which can be used to check whether a term existed before in the terms dictionary. `IndexSpec_AddTerm` is called only if the term does not exist in the term dict.
Currently, `IndexSpec_AddTerm` takes about 20% of the time. Initial benchmarks show an improvement of 15% in ingest speed, but the potential is up to 25% if terms are repeated.
=> [PERF] update the term-trie only if term does not exist in term-dictionary

src/aggregate/aggregate_request.c, src/result_processor.c, src/result_processor.h, tests/pytests/test_profile.py
This fixes a bug in ft.profile that would freeze the client.
Instead of adding a profileRP as we add RPs, all RPs are added at the end.
=> [BUG] fix ft.profile. add RPs after pipeline creation

docs/docs/Indexing_JSON.md
Fix documentation - multi numeric is not included with RediSearch Release [2.6-M01 (v.2.6.0)](https://github.com/RediSearch/RediSearch/releases/tag/v2.6.0)
It will be part of 2.6.1.
In addition, trigger a full build since the previous build was skipped after merging to master due to some commits having a comment causing CI  to be skipped.
=> Fix doc + trigger integration build which was skipped

src/config.c, src/config.h, src/trie/trie_type.c, src/trie/trie_type.h, tests/cpptests/test_cpp_config.cpp, tests/pytests/test_json_multi_text.py
Replacing the pytest `testconfigMultiTextOffsetDeltaSlopNeg` with a cpp test to avoid creating another `Env` during the same test.
Before this PR the test was failing the load of RediSearch module due to a wrong module arg, which is expected, but requires creating another `Env` in the same test, which we want to avoid.
After this PR, the module arg setter is tested in a unit test to see it fails with a negative value (other related tests remain in pytests) without failing loading of the module.
Related #2819
=> MOD3856: Fix test to avoid creating more than a single `Env`

coord/src/module.c, tests/pytests/test_search_params.py
*Replace order of param and query parsing in coordinator, so that query attributes params could be parsed properly
=> [BUG] [2.4] Replace order of param and query parsing in coordinator

coord/src/module.c, tests/pytests/test_search_params.py
Replace order of param and query parsing in coordinator, so that query attributes params could be parsed properly
=> [BUG] [2.6] Replace order of param and query parsing in coordinator

.circleci/config.yml
Currently default flow for this branch failed because 12.4.0 version of image is not supported
```
failed to create host: Image xcode:12.4.0 is not supported
```
Currently on master branch used 11.7.0 version so I think we can switch broken image to working one.
=> circle ci xcode image 12.4.0 -> 11.7.0

src/aggregate/aggregate_exec.c, tests/pytests/test_issues.py
The code did not take into account the case where `reqLimit + reqOffset <= RSGlobalConfig.maxSearchResults` but the actual number of results is smaller then `RSGlobalConfig.maxSearchResults`.
=> Fix assertion failure on wrong result counting.

src/index.c, tests/pytests/test.py
Crash happended due to invalid use of `array_ensure_append`. Added test to verify the fix.
(cherry picked from commit 2144521cbf46c09328c26487f65416211a62effb)
=> [2.4] Fix MOD-4200, crash on intersect iterator GetCriteriaTester. (#3119)

src/aggregate/aggregate_exec.c, tests/pytests/test_issues.py
The code did not take into account the case where `reqLimit + reqOffset <= RSGlobalConfig.maxSearchResults` but the actual number of results is smaller then `RSGlobalConfig.maxSearchResults`.
(cherry picked from commit 7991f4a935ef6f5e17c47da926ece8858f199b12)
=> [2.6] Fix assertion failure on wrong result counting. (#3127)

tests/pytests/test.py
With PR https://github.com/RedisJSON/RedisJSON/pull/699
JSONPath with dot notation can handle the colon (`:`) character
(related MOD-1548)
=> Fix test with JSONPath with colon using dot notation which is now supported

src/debug_commads.c, src/document.c, src/document.h, src/document_basic.c, src/indexer.h, src/json.c, src/json.h, src/spec.c, src/spec.h, src/tag_index.c, src/vector_index.c, src/vector_index.h, tests/pytests/test_rdb_compatibility.py, tests/pytests/test_vecsim.py
This PR enables multi-value vector similarity indexing. 
Multi-value indexing requires knowing upon creation if the index should support multi values. This is done by checking whether the JSON path that is given is dynamic or not. We can consider adding a new parameter for the vector field that sets explicitly if the index should be treated as a single or multi value.
This PR also requires a new parameter to be stored in the RDB, so it includes a new RDB version.
Before merging, Vector Similarity library followed branch should be changed to an official version.
=> Enable multi-value VSS MOD-3940

src/ext/default.c, src/hybrid_reader.c, src/hybrid_reader.h, src/index_result.c, src/index_result.h, src/redisearch.h, src/result_processor.c, src/vector_index.h, tests/cpptests/test_cpp_index.cpp
This PR is introduces *renaming only* of fields and functions to suit the generic "metric" concept, rather than the specific "distance" concept of `RSIndexResult` type associated with vecsim search results that returned by an iterator.
=> Change "distance result" semantics into "metric result" generic semantics

tests/pytests/test_rdb_compatibility.py
This PR fixes the test `testRDBCompatibility_vecsim()`.
It was added in PR #3118 but was not in line with the final `.rdb` file.
=> rdb Compatibility test fix

src/id_list.c, tests/pytests/test.py
When INKEYS option is used along side a wildcard query, the wildcard query is intersected with ID's list iterator that contains a list of requested docId's.
The `IL_SkipTo` function (of the ID's list iterator) was malfunction, in some cases the binary search would have return a docId which is less than the given docId that was asked to skip to. This causes the intersect iterator to traverse on all the documents returned from the wildcard query instead of skipping them. By fixing the binary search, the performance was drastically improve.
We can see it using the test that was added to the PR. The test uses `FT.PROFILE` API to check how many times the `IL_SkipTo` was called. Without the fix, we call this function 1000 times (one for each document in the index). After the fix, the function …
=> Fix RED-86036, improve performance on ID's list iterator.

coord/src/dist_aggregate.c, tests/pytests/test_dialect.py
`DIALECT` arg was not being passed by coordinator to `_FT.AGGREGATE`
Related #3060 
MOD-4152
MOD-4267
=> Pass DIALECT arg to FT.AGGREGATE on cluster

src/aggregate/aggregate_request.c, src/hybrid_reader.c, src/hybrid_reader.h, src/index_iterator.h, src/index_result.c, src/index_result.h, src/metric_iterator.c, src/metric_iterator.h, src/profile.c, src/query.c, src/query.h, src/query_ctx.h, src/redisearch.h, src/result_processor.c, src/result_processor.h, src/vector_index.c, src/vector_index.h, tests/cpptests/benchmark_vecsim_hybrid_queries.cpp, tests/cpptests/test_cpp_index.cpp
**The changes in the pull request**
This is the first PR that upgrades `VecSimRP` to be a generic `MetricLoaderRP` that loads all additional data (previously registered and got an `RLookupKey`) into its RLookup key.
1. Instead of having an array of pointers to the metric field name in the `QueryAST` structure, we now have an array of "Requests" for a metric field. Each request contains a pointer to the metric name and an address to write back the `RLookupKey` later. `IndexIterator` contains a new field "ownKey" that can hold an `RLookupKey` to which the iterator wants to yield its metric. In the future, we can modify this new field to hold multiple keys for multiple yields.
2. When evaluating a node, if it needs to yield a metric, it should …
=> MOD-4194 - Additional metrics loader

src/result_processor.c, tests/pytests/test.py
On `QITR_GetRootFilter` we were casting the `rootProc` to `RPIndexIterator`. This casting is wrong on coordinator where the root iterator is network iterator. The fix performs the cast only if the iterator type is `RP_INDEX` and return NULL otherwise.
=> Fix MOD-4290, fix wrong query iterator casting.

src/spec.c, tests/pytests/test.py
MOD-4388
(cherry picked from commit 92b63dc351269e80b1c8f9db7cb4dd3d4483e042)
=> [2.6] release failed-to-create temporary index on the main thread (#3197)

tests/pytests/test_vecsim.py
Depending on the moment the timeout occurs in the coordinator, the returned result can be either `0` or `redis.exceptions.ResponseError: Timeout limit was reached`.
This fix makes the test expect `0`, but catches the exception if it happens and validates it is a `Timeout limit was reached` exception.
[reference for the exception occuring](https://app.circleci.com/pipelines/github/RediSearch/RediSearch/10429/workflows/1a426092-08ec-4599-abea-1dd9262b1494/jobs/51349/steps?invite=true#step-114-1281)
=> [FIX] MOD-4265: fix flakiness of vector similarity timeout test

src/json.c, src/rejson_api.h, src/rlookup.c
APIs introduced with RedisJSON_V3 must be used only when it is guaranteed that they exist.
Without this fix, Using RediSearch master or >=2.6 with RedisJSON 2.2 causes a crash with multi values, since some APIs are missing, but are still attempted to be called (`getJSONFromIter` and `resetIter`)
=> MOD-4480: Differentiate between JSON API version 2 and 3

src/aggregate/aggregate_request.c, src/result_processor.c, tests/pytests/test_issues.py
(cherry picked from commit 216fa708ba9d92f7882011d81ba19ef22c2f1e51)
=> [2.6] Fix #3230, use the correct max results value

src/aggregate/aggregate_request.c, src/result_processor.c, tests/pytests/test_issues.py
Cherrypick from 216fa708ba9d92f7882011d81ba19ef22c2f1e51.
Fix the issue by choosing the correct max results value depends of whether we run a search of aggregate query.
=> Fix #3230, use the correct max results value.

docs/commands/ft.aggregate.md, docs/commands/ft.aliasadd.md, docs/commands/ft.aliasdel.md, docs/commands/ft.aliasupdate.md, docs/commands/ft.alter.md, docs/commands/ft.config-get.md, docs/commands/ft.config-help.md, docs/commands/ft.config-set.md, docs/commands/ft.create.md, docs/commands/ft.cursor-del.md, docs/commands/ft.cursor-read.md, docs/commands/ft.dictadd.md, docs/commands/ft.dictdel.md, docs/commands/ft.dictdump.md, docs/commands/ft.dropindex.md, docs/commands/ft.explain.md, docs/commands/ft.explaincli.md, docs/commands/ft.info.md, docs/commands/ft.profile.md, docs/commands/ft.search.md, docs/commands/ft.spellcheck.md, docs/commands/ft.sugadd.md, docs/commands/ft.sugdel.md, docs/commands/ft.sugget.md, docs/commands/ft.suglen.md, docs/commands/ft.syndump.md, docs/commands/ft.synupdate.md, docs/commands/ft.tagvals.md
Adds admonition about document deletion on temporary indexes to FT.CREATE and FT.DROPINDEX plus minor structural changes to other commands
=> [DOC] Update FT.CREATE and FT.DROPINDEX temporary index deletion

src/aggregate/aggregate_request.c, tests/pytests/test_issues.py
Allow alias name to begin with `AS` instead of failing
```
127.0.0.1:6379> FT.CREATE idx SCHEMA a TEXT 
127.0.0.1:6379> FT.SEARCH idx * RETURN 3 a AS asa
(error) Alias for RETURN cannot be `AS`
127.0.0.1:6379> FT.AGGREGATE idx * LOAD 3 a AS asa
(error) Alias for RETURN cannot be `AS`
```
=> Allow alias name beginning with AS

src/module-init/module-init.c, src/module.c, src/module.h
`info modules` was showing redis-server version, e.g.,
```
search_RedisSearch_version:7.0.5
```
While it should be showing RediSearch module version, e.g., for master branch
```
search_version:99.99.99
```
Or a release
```
search_version:2.6.2
```
**Alternatively**, this section can be removed, since the module version is already part of the Modules section (as a numeric value), e.g.,
```
module:name=search,ver=999999,api=1,filters=0,usedby=[],using=[],options=[handle-io-errors]
```
Related #2760
=> Show module version and redis version in module info

deps/triemap/triemap.c, deps/wildcard/wildcard.c, tests/ctests/test_wildcard.c, tests/pytests/test_wildcard.py
Related #2886
The wildcard `w'*'` is causing a crash in TAG wildcard iterator, for example:
```
127.0.0.1:6379> FT.CREATE idx SCHEMA t1 TAG
OK
127.0.0.1:6379> HSET k1 t1 val1
(integer) 1
127.0.0.1:6379> FT.SEARCH idx "@t1:{w'*'}" DIALECT 2
Error: Server closed the connection
```
(the root `TrieMapNode` of the `TrieMap` has zero `len`)
=> MOD-4653: Avoid crash on wildcard query `*` on TAG field

src/document.c, src/offset_vector.c, src/tokenize.c, src/util/mempool.c, src/util/mempool.h, src/value.c
This PR brings back the utilization of the lock in the `mempool` struct, so all the functions on a mempool will be thread-safe.
This PR includes a new function for creating a global mempool in a thread-safe manner while keeping the lazy-creation mechanism.
The PR does not include any new tests, we can see for now that the code compiles and that the current tests pass. We have to add multi-threaded tests when we have a multi-threaded pipeline ready
=> Make `mempool` usage thread-safe - [MOD-4574]

docs/docs/reference/Query_Syntax.md, src/query.c, tests/pytests/test_wildcard.py
Currently a syntax error occurs with wildcard query using `DIALECT 3`
It only works well with `DIALECT 2`.
Wildcard support should also work with dialects greater than 2, e.g.,
`FT.SEARCH idx "@t:{w'*234?'}" DIALECT 3`
=> Wildcards query should work with dialect >= 2

src/debug_commads.c, src/doc_table.c, src/doc_table.h, src/document.c, src/highlight_processor.c, src/indexer.c, src/inverted_index.c, src/redisearch.h, src/redisearch_api.c, src/result_processor.c, src/result_processor.h, tests/cpptests/test_cpp_index.cpp
This PR makes the increment and decrement of the document metadata ref count atomic and handles the potential freeing of a dmd.
For safer handling, all the functions that return a reference to a dmd also increase its ref count, and it's the caller's responsibility to decrease the ref count when it no longer needs it.
=> Make refcount for doctable metadata atomic - [MOD-4571]

src/document.c, src/document_add.c, src/document_basic.c, src/ext/default.c, src/fields_global_stats.c, src/module.c, src/rlookup.c, src/spec.c, src/spec.h
This PR makes the relevant write flows of redisearch use the `IndexSpec` R/W lock for writing. It handles:
1. Notification-based changes
2. RediSearch module key flows (`FT.ADD`, `FT.DEL`...)
3. `FT.ALTER`
5. `FT.SYNUPDATE` and `FT.SYNDUMP` (for reading)
The fact that the tests are passing suggests that every flow itself does not cause any deadlocks (ex. `FT.ADD` causes a notification-based change)
=> Index-spec write-lock pipelines usage - [MOD-4689]

src/fork_gc.c, src/fork_gc.h, src/gc.c, src/gc.h, src/redis_index.c, src/redisearch_api.c, src/search_ctx.h, src/spec.c, src/spec.h
1. removed keyspace remainings
2. made the GC use the spec's lock instead of the GIL
3. reduced the usage of the GIL to minimum
4. simplified the stopping process of the GC using a weak reference to the spec
=> Refactor FGC to use IndexSpec R/W lock - [MOD-4570]

docs/commands/ft.aggregate.md, docs/commands/ft.create.md, docs/docs/design/overview.md, docs/docs/reference/Sorting.md
ON JSON SORTABLE is always UNF whether specified or not.
Also TAG on JSON can be SORTABLE 
Also GEO can be SORTABLE
SORTABLE is not mandatory to perform SORTBY, but it can improving speed (at cost of mem size)
Fix #3385
Ref #3180
Ref #3182
=> Fix doc on SORTABLE and UNF

src/spec.c, src/vector_index.c, tests/pytests/test_vecsim.py
Until this day, the default initial capacity was 1000.
In some cases where the memory limits are very strict, this default value might be too big and will cause the `FT.CREATE` command to fail over the default values when the user didn't even specify them.
This PR fixes this behavior in the same way we already handle default block size.
First, the default value for initial capacity is now the size of a single block - so in the default case, 1024. We already verify there is enough memory available for the first block, so there is no breaking change if the block size is set to be very big.
Second, we no longer drop the initial capacity to 0 when failing on the first attempt to load from RDB, and we now set it to default (single block size, which in this case also will become the default). …
=> [FIX] VecSim initial capacity default value

src/offset_vector.c, src/util/mempool.c
This PR reverts some of #3310 changes and makes the mempool structs NOT THREAD SAFE. It appears that adding a lock for the mempool can drastically affect the performance and make using mempools worthless compared to just allocating.
It is now the developer's responsibility to make sure the mempool is not accessed by multiple threads at once.
This PR can be an example:
This PR makes the global mempools of offset vectors thread-specific, guaranteeing no two threads will ever use them at the same time (or ever).
=> Mempool refactor - remove locks and use a mempool per thread - [MOD-4690]

coord/src/module.c
Fixing a possible leak when performing `FT.SEARCH` from the coordinator.
we used to retain/hold the command's arguments (`argv`) before moving the execution to the coordinator's thread pool.
As `RedisModule_FreeString` is not thread-safe, we should have our own copies of the arguments, like we already have in `FT.AGGREGATE` from the coordinator.
This PR is related to #3394, but as a bug fix it should go to master
=> Replace retaining argv with copying it in coordinator's `FT.SEARCH` - MOD-4834

src/debug_commads.c, src/rlookup.c
a small fix for making the redis string usage in redisearch thread-safe (not retaining or freeing retained strings in the BG without holding the redis lock)
more details regarding this issue can be found [here](https://redislabs.atlassian.net/browse/MOD-4834)
=> Redis string usage made threadsafe - [MOD-4834]

src/redis_index.c, src/util/dict.h
The spec's inverted indices dictionary is performing rehashing on read operations. To be thread-safe, we can disable rehashing while we lock the spec for reading, and resume doing so after unlocking.
Another solution will be to replace the dictionary with one that does not rehash on read or perform all the spec dictionary reading in the main thread (guarded by the redis lock). The second option includes moving the iterators' build time to the main thread (after we moved it to the background).
=> Add pause and resume dict rehashing when locking for read - [MOD-4833]

coord/src/module.c, src/result_processor.c, src/spec.c, src/vector_index.c, tests/pytests/test_profile.py, tests/pytests/test_vecsim.py
* [FIX] VecSim initial capacity default value (#3397)
* replace retaining with copying (#3395)
* Update Result Processor Name (#3379)
=> [2.4] [FIX] VecSim initial capacity default value (#3397), replace retaining with copying (#3395), Update Result Processor Name (#3379)

deps/thpool/thpool.c, deps/thpool/thpool.h, src/concurrent_ctx.c, src/gc.c, src/spec.c
Sperated threadpool struct and functions into a RediSearch-specific namespace to avoid collisions with RedisGraph when building as a static lib.
=> Threadpool namespace

src/util/minmax_heap.c, tests/benchmarks/search-ftsb-10K-enwiki_abstract-hashes-fulltext-sortby.yml, tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-sortby.yml
simplifying and improving internal computations of the min-max heap, for better readability and performance
benchmark comparing changes to master code [here](https://snapshots.raintank.io/dashboard/snapshot/7lwS8N9Ep5D47IaEk4QlH0SPy4fRgjlI)
=> Min-Max heap performance improvement

src/cursor.c, src/info_command.c, src/spec.c, tests/pytests/test.py
`FT.CREATE` option `NOHL` should appear in `FT.INFO`.
It should appear also when option `NOOFFSETS` is set since it implies `NOHL` (as documented)
=> Show `NOHL` option in `FT.INFO`

.circleci/config.yml, src/aggregate/aggregate_exec.c, src/aggregate/aggregate_request.c
Delaying the timeout time computation to `prepareExecutionPlan`, where it is first needed.
timeout time calculation should be done just before we start executing the query, but today some of the execution is done while we build the iterators, and some iterators require the timeout time in their constructors.
the important thing is to calculate the timeout time after we begin dealing with the request, that is after we start dealing with it in the background (if we intend to)
=> Changing where timeout context is set - [MOD-4870]

src/hybrid_reader.c, tests/pytests/test_vecsim.py
Addressing #3465, fixing a bug where we have a filter for the KNN query and we are looking for the top 0 results.
Because the internal heap, in this case, is empty, but its size is not smaller than `k`, we tried overriding the "worst" result, but the pointer was null.
This PR makes the hybrid reader iterator to choose simple KNN search when `k == 0`, as we are going to return 0 results regardless of the child iterator, making such queries a bit faster (not reading the child iterator at all) and making the assumption that `k > 0` in the case that there is a filter, valid.
=> [FIX] KNN search for 0 results with a filter fix - [MOD-5006]

coord/src/module.c, src/aggregate/aggregate_exec.c, src/result_processor.c, tests/pytests/test_issues.py, tests/pytests/test_json_multi_text.py
Docs with a missing `sortby` field should be preceded by docs which have this field.
Should work whether field is `SORTABLE` or not and whether sortby is `ASC` or `DESC`.
Fixes #3457
=> Docs with a missing `sortby` field should be preceded by docs which has this field

src/aggregate/aggregate_exec.c, src/aggregate/aggregate_request.c, src/aggregate/expr/expression.c, src/result_processor.c, src/result_processor.h, src/rlookup.c, src/rlookup.h, src/spec.c, tests/pytests/test_multithread.py, tests/pytests/test_search_params.py
skipping fields that are already loaded
If the dialect is less than 3 and its a json index, we load all required keys.
Find where to place buffer-locker and unlocker in the pipeline by iterating the final pipeline. If there's a pager the unlocker is placed before it (the pager is the unlocker upstream) because the pager declares EOF.
remove unused rlookup flag - RLOOKUP_F_OUTPUT
added RLOOKUP_F_ORIGINAL_VALUE_DOCSRC and RLOOKUP_F_ISLOADED flags
added flags field and RESULT_PROCESSOR_F_ACCESS_REDIS flag the rp base flags
added a function to add the sorter to list of fields to load. The list is intiated during building the pipeline and not during the search itself.
If we want to create new key and not excel if one exits, we can use the new function : RLookup_GetOrCreateKey that first …
=> Optimize multi threaded search query pipleine - MOD-4847

.circleci/config.yml, tests/benchmarks/defaults.yml, tests/benchmarks/search-ftsb-10K-enwiki_abstract-hashes-fulltext-sortby.yml, tests/benchmarks/search-ftsb-10K-enwiki_abstract-hashes-term-prefix.yml, tests/benchmarks/search-ftsb-10K-enwiki_abstract-hashes-term-wildcard.yml, tests/benchmarks/search-ftsb-10K-enwiki_pages-hashes-fulltext-mixed_simple-1word-query_write_1_to_read_20.yml, tests/benchmarks/search-ftsb-10K-enwiki_pages-hashes-load.yml, tests/benchmarks/search-ftsb-10K-multivalue-numeric-json.yml, tests/benchmarks/search-ftsb-10K-singlevalue-numeric-json.yml, tests/benchmarks/search-ftsb-1K-enwiki_abstract-hashes-term-contains.yml, tests/benchmarks/search-ftsb-1K-enwiki_abstract-hashes-term-suffix-withsuffixtrie.yml, tests/benchmarks/search-ftsb-1K-enwiki_abstract-hashes-term-suffix.yml, tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-2word-intersection-query-non-sortable.yml, tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-2word-intersection-query-non-sortable@50_ops_sec.yml, tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-2word-intersection-query@100_ops_sec.yml, tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-2word-union-query-non-sortable.yml, tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-2word-union-query-non-sortable@100_ops_sec.yml, tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-2word-union-query.yml, tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-2word-union-query@100_ops_sec.yml, tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-simple-1word-query-non-sortable.yml, tests/benchmarks/search-ftsb-1M-enwiki_abstract-hashes-fulltext-simple-1word-query@100_ops_sec.yml, tests/benchmarks/search-ftsb-1M-nyc_taxis-ftadd-load.yml, tests/benchmarks/search-ftsb-1M-nyc_taxis-hashes-load.yml, tests/benchmarks/search-geo.yml, tests/benchmarks/search-numeric-sortby-desc.yml, tests/benchmarks/search-numeric-sortby.yml, tests/benchmarks/search-numeric.yml
* Extended benchmarks to include mixed-read write benchmarks. Included rate-limited benchmarks and extended the full-text variations
* Update tests/benchmarks/search-ftsb-10K-enwiki_pages-hashes-fulltext-mixed_simple-1word-query_write_1_to_read_20.yml
* Included 2 extra rate-limited benchmarks
* Reduced request count on non-sortable query
* Updated union/intersection benchmark details. Splitting search-* benchmarks into 3 different run groups to speedup feedback cycle
* Reduced CI benchmark time by breaking profile flows into severall concurrent ones
* Enable cluster benchmarks on label trigger
* Extended benchamrk setups to include 04, 08 and 16 primaries
* Included 20, 24, and 32 primaries on weekly
* Temporarily enable g5 and g6 on cluster to produce scalability numbers
---------
=> [2.6] Extended RediSearch CI benchmarks #3388

docs/commands/ft.aggregate.md
In the command we use `name` but in description we refer to it as `index_name`
=> FT.AGGREGATE: Fix index argument name and description

src/aggregate/aggregate_request.c, src/highlight_processor.c, src/redis_index.c, src/result_processor.c, src/result_processor.h, src/rlookup.c, src/rlookup.h, src/spec.c
* Release spec's lock in root rp and in the pager if it declares EOF.
* During query execution, the highlighter searches fields in the spec cache instead of the spec itself
=> [feature-threads] Added unlocking spec in root iterator function - MOD-4883

coord/src/module.c
Fails on a test with 3,000,000 documents on 3 shards. Allocation of 3M pointers on the stack causes a crash.
MOD-4974
=> [2.4] avoid allocating large array on stack

coord/src/module.c
Fails on a test with 3,000,000 documents on 3 shards. Allocation of 3M pointers on the stack causes a crash.
MOD-4974
related to #3492
=> [BUG] Use heap instead of large stack alloc

docs/docs/Indexing_JSON.md
Addressing #3496 and improving the documentation
1. making a different scenario for single and multi
2. fixing difference in name of fields in examples
=> [DOCS] fix misleading VSS with JSON example

sbin/unit-tests, src/hybrid_reader.c, src/hybrid_reader.h, src/vector_index.c, src/vector_index.h, tests/cpptests/benchmark_vecsim_hybrid_queries.cpp, tests/cpptests/test_cpp_index.cpp
`VecSimQueryParams` in `testHybridVector` wasn't initialize.
As a result,  the hybrid iterator was initialized with the wrong read function.
solution: added VECSIM_LAST_SEARCHMODE to the search modes enum and an error  parameter to `NewHybridVectorIterator` to be used when search mode parameter passed to the hybrid constructor is out of the valid range.
=> Bug fix - unintialized VecSimQueryParams in `testHybridVector`

tests/pytests/test_numbers.py
Might fail on CI with (when RediSearch tests are run by RedisJsonHdt)
> test_numbers:testEmptyNumericLeakCenter
❌  (FAIL):	5 > 5	test_numbers.py:145
=> Avoid sporadic GC in flaky test

src/rlookup.c, tests/pytests/test_issues.py
Small fix for loading a key name. We previously only looked at the name of the RLookup key, and therefore if one requests to load the key name as some costume name, we wouldn't understand and just ignore the load
=> Fix key-name loading - [MOD-5252]

coord/src/info_command.c, src/geometry/geometry_api.cpp, src/geometry/geometry_api.h, src/geometry/rtree.cpp, src/geometry/rtree.h, src/geometry/rtree.hpp, src/info_command.c, src/spec.c, src/spec.h, tests/pytests/common.py, tests/pytests/test.py, tests/pytests/test_geometry.py, tests/pytests/test_optimizer.py
Currently in the geometry index, which is using Boost geometry, there is a single global memory usage counter, used by all instances of the index (rtree class).
Currently [FT.INFO](http://ft.info/)  will report `total_geometries_index_size_mb`, which is global for all GEOMETRY indices and not per index.
Need a separate PR to modify the allocators and the new and delete operators, in order to be able to count memory usage per index (including its internal allocations of polygons and rings) and then to be able to report memory usage per GEOMETRY index.
=> MOD-5207: Add GEOMETRY total indices memory size to `FT.INFO`

src/aggregate/aggregate_request.c, src/field_spec.h, src/result_processor.c, src/result_processor.h, src/rlookup.c, src/rlookup.h, src/spec.c, tests/cpptests/test_cpp_index.cpp, tests/pytests/test.py, tests/pytests/test_expire.py, tests/pytests/test_json_multi_numeric.py, tests/pytests/test_json_multi_text.py, tests/pytests/test_multithread.py, tests/pytests/test_optimizer.py, tests/pytests/test_profile.py, tests/pytests/test_search_params.py
changes:
1. Sorter will no longer throw away docs with missing data but will give them a lower rank than any other doc, so it will return an empty doc only if there are no better documents that passed the filter. This is aligned with the changes presented in #2651
=> Refactor RPs for new GetKey API #1 - [MOD-5256]

src/fork_gc.c, tests/pytests/common.py, tests/pytests/test_numbers.py
As the inverted index `numEntries` was never updated, we kept splitting the numeric tree. This caused the memory to grow constantly.
In addition, the `numRecords` field in the spec statistics was decreased by `numEntries` upon removing a range, but since the `numEntries` kept growing, and wasn't aligned with the actual number of entries, `numRecords` decreased below 0 and overflowed.
In this PR we update `numEntries` in the GC according to the number of removed entries collected.
related issue -[MOD-5181](https://redislabs.atlassian.net/browse/MOD-5181)
[MOD-5181]: https://redislabs.atlassian.net/browse/MOD-5181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOD-5181: Bug fix - Update numeric inverted index numEntries

src/config.c, src/config.h, src/spec.c, tests/pytests/test_async.py, tests/pytests/test_config.py
To fix the previous issue in which calling sched_yield between consecutive iterations of RedisModule_Scan while we perform background indexing, we added a call for `usleep(1)`. However, this caused a significant performance regression in background indexing. The solution is calling `usleep(1)` between every X iterations, where X is a new configuration whose default is 100.
@filipecosta90
=> Slow background indexing fix [MOD-5259]

coord/src/dist_aggregate.c, coord/src/module.c, src/aggregate/aggregate.h, src/aggregate/aggregate_exec.c, src/cursor.c, src/cursor.h, src/info_command.c, src/module-init/module-init.c, src/module.c, src/spec.c, src/spec.h, tests/pytests/test_cursors.py
In this PR we re-organized the cursors management method
global cursors list 
* name was changed to `g_CursorsList` in order to emphasize that it is global.
* The cursors list no longer holds  a spec info dict - instead, **each cursor holds a weak reference** to its associated spec (if exists) that needs to be promoted to a strong reference upon execution (aka, reading from the cursor). **If the promotion fails,** it means that the spec in no longer valid and the cursor needs to be released.
**In a coordinator ctx**, for a `WITHCURSOR` query, we start the cursor with a dummy spec ref that points to NULL.
In the shards, **at the cursor's first initialization,** it is assumed to be called with a valid strong ref, so there is no need to promote it by the cursor.
* The index is no longer …
=> Make cursors thread safe

docs/commands/ft.aggregate.md
the syntax statements on FT.AGGREGATE contain multiple options for LOAD and GROUP BY being confused. Remove the duplicates
=> DOC remove multiple statements on ft.aggregate.md

deps/thpool/thpool.c, deps/thpool/thpool.h, src/notifications.c, src/util/workers.c, src/util/workers.h, src/vector_index.c
Add the support for creating and terminating the workers' thread pool upon starting and finishing the trimming event (after resharding). 
Since trimming is set to run on ~25% of the time (shard is responsive for other commands at rest of the time), we cannot wait for the thread pool to terminate when the trimming event is done, so we add a mechanism that signals the threads to terminate once there are no more jobs to be executed.
Note - since resharding capability is only available in enterprise, there are no flow tests here, but resharding test with enterprise confirms the performance improvement
=> Async VecSim index - burst threads for trimming event (resharding)

src/result_processor.c, src/util/minmax_heap.c, src/util/minmax_heap.h, tests/pytests/test_aggregate.py
Removes redundant data and unnecessary checks from the sorter logic
Also implementing `mmh_exchange_min` for the min-max heap, to efficiently replace the minimal object with a new one, without the need to pop (and fix the heap first time) and then insert (and fix the heap for the second time) it.
=> sorter simplification

coord/src/dist_aggregate.c, coord/src/module.c, src/aggregate/aggregate.h, src/aggregate/aggregate_exec.c, src/aggregate/aggregate_request.c, src/aggregate/group_by.c, src/cursor.c, src/cursor.h, src/fork_gc.c, src/info_command.c, src/module-init/module-init.c, src/module.c, src/result_processor.c, src/result_processor.h, src/spec.c, src/spec.h, tests/pytests/common.py, tests/pytests/test_cursors.py, tests/pytests/test_fuzzy.py, tests/pytests/test_json.py, tests/pytests/test_multithread.py, tests/pytests/test_optimizer.py, tests/pytests/test_vecsim.py
This PR makes the pipeline aware of the chunk limit, so if the pipeline needs to be thread-safe for loading (buffer-locker and unlocker), we can buffer only the needed amount of results needed, and unlock the redis lock on the last document returned
=> Cursors buffer-limit support - [MOD-5091, MOD-4874]

src/hybrid_reader.c, src/hybrid_reader.h, src/result_processor.c, src/util/minmax_heap.c, src/util/minmax_heap.h, tests/cpptests/test_cpp_index.cpp
Replace the hybrid iterator internal heap with a min-max heap, in order to return the top-k hybrid results in the right order by default
=> replace hybrid heap with min-max heap - [MOD-5094]

src/aggregate/aggregate_request.c, src/query_optimizer.c, src/result_processor.c, src/result_processor.h, tests/pytests/test_optimizer.py
When the optimization is to not have a sorter, don't create a sorter with an early return, and use a pager instead.
This changes the `count` in this case to be 1 and not the length of the response (both are garbage and not the intended value)
=> Remove sorter when not needed (on optimize)

tests/benchmarks/search-numeric-optimize.yml, tests/benchmarks/search-numeric-sortby-desc-optimized.yml, tests/benchmarks/search-numeric-sortby-optimized.yml
The following PR addresses the keyword change ( that's causing the CI to fail ). 
Completion of #3651
=> Updated OPTIMIZE keyword to WITHOUTCOUNT in benchmarks

src/result_processor.c, tests/pytests/test_optimizer.py
Minor refactor to the pager, to notify the pipeline of the number of results it will need.
It also splits its logic into two phases to make fewer condition checks.
=> [MT] pager limit

docs/docs/quickstart.md
This was a reference that came from redis.com.
=> docs: Added a missing alias for the search quick start page

src/fields_global_stats.c, src/fork_gc.c, src/fork_gc.h, src/gc.c, src/json.c, src/spec.c, src/vector_index.c, src/vector_index.h, tests/cpptests/benchmark_vecsim_hybrid_queries.cpp, tests/cpptests/test_cpp_index.cpp, tests/pytests/test_vecsim.py
Cherry-pick of HNSW ingest performance improvement (moving to vector blocks + optimizations) (#3701), and using RediSearch GC for cleaning deleted "zombies" vectors in tiered vector indexes (#3657).
=> [2.8] Vecsim enhancements for 2.8

coord/pack/ramp.yml, coord/src/dist_aggregate.c, deps/thpool/thpool.c, deps/thpool/thpool.h, src/aggregate/aggregate_request.c, src/rlookup.c, src/util/logging.c, src/util/logging.h, src/util/workers.c, src/vector_index.c, src/vector_index.h, tests/pytests/common.py, tests/pytests/runtests.sh, tests/pytests/test.py, tests/pytests/test_multithread.py, tests/pytests/test_resp3.py
2 cherry picks of PRs for having better stability in MT vecsim tests in CI
1 PR for improving the logging mechanism in vecsim lib (including bump version) and in thpool - have more flexibility about the log level.
@DvirDukhan:
Added cherry picks to align 2.8 branch with master on e73eea4dde3c93f0a2aed9eef1e85a0e84e54c09 which includes reverting EXPAND as default response
=> [2.8] stability and logging vecsim chreey-picks

src/rlookup.c
replace the fallback value for "expand" from `NULL` to `RS_NullVal()` so it can be safely freed using `RSValue_Free` (directly or nested when freeing the "duo" that wraps it)
TODO: @oshadmi are we able to test old APIs?
=> [FIX] fix fallback value for expand

.github/workflows/stale.yml
This PR adds the `stale` github action to mark stale issues and PRs as stale after 60 days, and closing them after 7 days if no action was taken after marking them as stale
None
Adds stale.yml to github workflows
=> added stale action

tests/benchmarks/search-high-cardinality-negation-term-baseline.yml, tests/benchmarks/search-high-cardinality-negation-term-comparison_union_all_other_terms.yml
Include 2 TAG benchmarks specifically focusing on getting the negation of a term and checking what's faster: 'negate a term or union all the other options'
This dataset contains 1M docs. The documents contains a tag field with value between 1 an 10.
This means that when we filter a tag we get around 100K docs.
The 2 added queries return the same resultset:
```
127.0.0.1:6379> ft.search idx:cardinality "-(@tag_field:{1})" LIMIT 0 0 TIMEOUT 0
1) (integer) 899882
127.0.0.1:6379> ft.search idx:cardinality "@tag_field:{10|9|8|7|6|5|4|3|2}" LIMIT 0 0 TIMEOUT 0
1) (integer) 899882
```
and the output should be similar to the following sample reply:
```
127.0.0.1:6379> ft.search idx:cardinality "@tag_field:{10|9|8|7|6|5|4|3|2}" LIMIT 0 10 TIMEOUT 0
1) …
```
=> Include 2 TAG benchmarks focusing on negation of terms and large intermediate resultsets

src/aggregate/aggregate_request.c, src/aggregate/expr/exprast.c, src/document.c, src/rlookup.c, src/sortable.c, src/sortable.h, src/value.h
Fixing thread-unsafety regarding RSValues' ref-counts.
Usually, RSValues are used in queries and are "local" to their context (no other thread will try to look at them), and the ref-count was used to pass ownership over the values.
But when a field is `SORTABLE`, its quick-access value is kept in the document metadata object in a sorting vector, as an RSValue, which any thread that performs a query might take a reference to.
Taking into consideration that:
1. A background query may use an RSValue after unlocking the spec's R/W lock (regular or cursor mode)
2. The `SORTABLE` value may need to be updated while other threads still need the old value
3. We encourage users to use `SORTABLE` fields, so we want an efficient solution for `SORTABLE` as …
=> [FIX] making RSValue's refcount atomic

src/aggregate/expr/parser.c, src/aggregate/expr/parser.h, src/aggregate/expr/parser.y
Fixed a leak when encountering a syntax error on the `APPLY/FILTER` expression.
1. MOD-5751
1. filter/apply parser
=> [FIX] leak in `APPLY/FILTER` parser

src/aggregate/expr/parser.c, src/aggregate/expr/parser.y
2.6 Fix for MOD-5751
* fixed parser leak on syntax error
* auto-generated code
* revert precedence
=> [CP] [FIX] leak in `APPLY/FILTER` parser (#3823)

src/aggregate/expr/parser.c, src/aggregate/expr/parser.y
2.4 Fix for MOD-5751
* fixed parser leak on syntax error
* auto-generated code
* revert precedence
=> [2.4] [FIX] leak in `APPLY/FILTER` parser (#3823)

src/aggregate/expr/parser.c, src/aggregate/expr/parser.y
2.8 Fix for MOD-5751
* fixed parser leak on syntax error
* auto-generated code
* revert precedence
=> [2.8] [FIX] leak in `APPLY/FILTER` parser (#3823)

coord/src/dist_plan.cpp, coord/src/dist_plan.h, src/aggregate/aggregate_plan.h, tests/pytests/test.py, tests/pytests/test_aggregate.py
Enhancing #3790 and making it non-breaking.
To do so, if we want to move the step to the shards, we have to parse the filter command, extract its necessary keys, and add a `LOAD` step for them BEFORE the `FILTER` step at the remote. This "explicit" `LOAD` step preserves the current behavior, which lets `FILTER` steps load implicitly whatever field they need.
There are a few benefits to the way I implemented the non-breaking solution:
1. The overhead is minimal - it affects only queries that may need to move a `FILTER` step to the shards. No need to track previous loads, or to check the index schema, which isn't available at the coordinator (without locking the Redis GIL).
2. The additional non-breaking code is local - for a later and better …
=> [FIX] filter on coordinator - non-breaking

coord/src/dist_plan.cpp, coord/src/dist_plan.h, src/aggregate/aggregate_plan.h, tests/pytests/test.py, tests/pytests/test_aggregate.py
* move filter step to the shards, if possible
* improved comment and changed style
* fixed a failing test
* some code simplification
* implement non-breaking solution
* fix comment
* remove a leftover cast
* changing vector type to `const char *`
* test fix
* added syntax error test for filter
* leak fix
=> [2.10] [FIX] filter on coordinator - non-breaking (#3809)

coord/src/rmr/redis_cluster.c
On Redis 7.2 (specifically on 7.2-rc3) there was a [change](https://github.com/redis/redis/pull/12233) made that allow running on cluster with both, tls and none tls port.
As part of this change, `cluster slot` command will return the port base of the connection type (tls or not tls). A side effect of this change is that when `cluster slot` called using `RM_Call` it is always gets the none tls port (which break our support of tls).
To fix this, use `RedisModule_GetClusterNodeInfo` Redis module API to get the correct port.
Notice that this is a minimal fix, we should extend the Redis module API to provide us with all the information we need (including slot range) so we will not have to use `cluster slot` command at all.
1. #...
2. MOD...
**Mark if …
=> MOD-5768: Fix tls on Redis 7.2 oss cluster

tests/pytests/test_async.py
Since we just wan't to make sure that redis is responsive during background indexing - this check is flaky by its nature. So we ar left with just checking that cluster PINGs were processed in time. 
=> Remove flakiness from async indexing test [MOD-5771]

src/phonetic_manager.c, src/tokenize.c, tests/pytests/test_phonetics.py
Currently, the function `PhoneticManager_ExpandPhonetics()` does not validate the maximum lenght of the term to expand.  When a user input a massive huge length, the stack-based buffer will end-up with take all stack memory space and trigger a DOS.
Changes done:
1. The max length was defined `MAX_TERM_TO_EXPAND_SIZE 128`, it has the same value that `MAX_NORMALIZE_SIZE`.
2. If the argument len of the function `PhoneticManager_ExpandPhonetics()` is greater than the allowed value.
1.   [3836](https://github.com/RediSearch/RediSearch/issues/3836)
2. MOD-5767
1. Function `PhoneticManager_ExpandPhonetics()`
3. Function `simpleTokenizer_Next()`
=> PhoneticManager_ExpandPhonetics: Limit lenght of term to expand - MOD 5767

src/index_result.c, src/offset_vector.c, src/redisearch.h, tests/pytests/test_issues.py
Addressing #3841
In `RSIndexResult_IterateOffsets` - we didn't check if the result is of type metric, which led to possible corruption.
=> Fix possible corruption when iterating metric result [MOD-5791]

src/fork_gc.c
In case the spec was dropped during the gc work, `StrongRef_Get` returns NULL, we skip immediately to the cleanups code section. The cleanup section includes calling `RedisSearchCtx_UnlockSpec(sctx);`.
but, since we also skip `RedisSearchCtx *sctx` initialization, `RedisSearchCtx_UnlockSpec` raises an assertion (`assert(sctx);`)
To solve this, calling `RedisSearchCtx_UnlockSpec` is guarded by `if (sp)`.
1.  FGC_parentHandleNumeric
=> Fix trying to unlock an uninitialized spec in FGC_parentHandleNumeric

.circleci/config.yml, tests/pytests/test_vecsim.py
Current errors:
- The current **nightly-twice-a-week** workflow fails for getting very close to the time limit of 5 hours. 
- The **build-macos-m1** job fails when the system setup tries to install `greenlet` package
- Error in test_vecsim:
```
test_vecsim:test_bad_index_multi_value_json: [ERROR]
Unhandled exception: 'RedisCluster' object has no attribute 'connection_pool'
```
Changes:
- The jobs `build-macos-x64` and `build-macos-m1` were split in two jobs, one the step for test search and another for test coordinator. Now, the workflow will have four jobs with a maximum run time of 3.5h:
- `build-macos-x64-search`
- `build-macos-x64-coordinator`
- `build-macos-m1-search`
- `build-macos-m1-coordinator`
- The `nightly-by-param` workflow is a copy of `nightly` than can be triggered …
=> MOD-5816: Fix macos build

.circleci/config.yml
After splitting search and coordinator runs for macos into separate jobs (in #3875) - they both persist in the CircleCI workspace files with similar names, which later on cause a failure when doing `attach_workspace`.
Simple fix is to skip persist/upload in one of the jobs.
A different fix could be to persist both but in distinct directories, but since the artifacts are actually similar - no need for both.
Another fix could be to extract the persist/upload out of the build step and have a single persist/upload.
1. Continuation to #3875
2. MOD-5600 MOD-5816
1. ...
2. ...
=> MOD-5600: Avoid conflicts in CircleCI persist workspace

.circleci/config.yml, build/conan/conanfile.txt, build/docker/Makefile, sbin/get-redisjson, sbin/pack.sh, sbin/system-setup.py, sbin/upload-artifacts
**Description:**
1. RHEL9 support in RediSearch
2. VectorSim submodule does not compile with RHEL9 gcc v12, which is installed in case of use READIES `getgcc`, then `sbin/system-setup.py` is installing gcc v11 directly, without use READIES tool.
1. rocky9 support
1. Update sbin/system-setup.py
=> MOD-5759: RockyLinux 9 support

.circleci/config.yml
`- persist-artifacts` step was accidentally removed from to `vm-build-platforms-steps` in #3895.
This PR restores this step.
Also, removed unused `build-platforms-steps`
** This PR fixes: **
[MOD-5875](https://redislabs.atlassian.net/browse/MOD-5875)
[MOD-5875]: https://redislabs.atlassian.net/browse/MOD-5875?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOD-5875 - fix upload artifacts to s3

.circleci/config.yml
* - persist-artifacts step was accidentally removed from to vm-build-platforms-steps in #3895.
This PR restores this step.
* removed unused build-platforms-steps
* some spaces corrections
(cherry picked from commit 0dae733c8df1e94252275fc9887784026d8237fd)
=> [2.8] MOD-5875 - fix upload artifacts to s3

docs/docs/advanced-concepts/vectors.md
1. Currently we don't support hybrid queries with VSS, these changes make them clear replacing hybrid queries for pre-filter queries and adjusting the current hybrid query description to hybrid approach (pre-filter query)
2. What is the change: Documentation references to hybrid query changing to pre-filter
=> Change Hybrid query to pre-filter vectors.md

.circleci/config.yml, build/conan/conanfile.txt, build/docker/Makefile, sbin/get-redisjson, sbin/pack.sh, sbin/system-setup.py, sbin/upload-artifacts
Backport of https://github.com/RediSearch/RediSearch/pull/3903 to 2.8.
=> [2.8] MOD-5759: RockyLinux 9 support (#3903)

.circleci/config.yml, tests/pytests/test_cursors.py
minor build fix
- Revert Python installation step
- shortened cursor test
2.6 gets its own fix at #3949
=> Fix macos build

src/debug_commads.c, src/fork_gc.c, tests/pytests/common.py, tests/pytests/test_numbers.py
… (#3892)
* Save the hash table key as FP binary representation of the cardinality value.
* added more values to the test
* Fixed CardinalityValue array len
in recvCardvals, we initialize arrayof(CardinalityValue) with a **capacity** of len (cardinality values count) * sizeof(CardinalityValue). Although capacity should be in elements and not in bytes. then we read the cardinality values sent from the child directly to the memory allocated for the array, instead of using array_append. It is probably more efficient and quick. However, As a result, the array header is not updated with the correct length. The array length is then assigned to the range cardinality. So before this fix, is was zero. Since we know in advance to exact number of the cardinality values, we can safly use array_newlen …
=> [2.8] Fix uniquesum and cardinalities values corruption after gc - MOD-5815

src/debug_commads.c, src/fork_gc.c, tests/pytests/common.py, tests/pytests/test_numbers.py
… (#3892)
* Save the hash table key as FP binary representation of the cardinality value.
* added more values to the test
* Fixed CardinalityValue array len
in recvCardvals, we initialize arrayof(CardinalityValue) with a **capacity** of len (cardinality values count) * sizeof(CardinalityValue). Although capacity should be in elements and not in bytes. then we read the cardinality values sent from the child directly to the memory allocated for the array, instead of using array_append. It is probably more efficient and quick. However, As a result, the array header is not updated with the correct length. The array length is then assigned to the range cardinality. So before this fix, is was zero. Since we know in advance to exact number of the cardinality values, we can safly use array_newlen …
=> [2.10] Fix uniquesum and cardinalities values corruption after gc - MOD-5815

tests/benchmarks/search-ftsb-1700K-docs-union-iterators-q3.yml, tests/benchmarks/search-ftsb-370K-docs-union-iterators-q4.yml, tests/benchmarks/search-ftsb-5200K-docs-union-iterators-q1.yml, tests/benchmarks/search-ftsb-5500K-docs-union-iterators-q2.yml
=> [2.6] Added q1, q2, q3, and q4 large union iterator benchmarks (#3953)

.circleci/config.yml, coord/src/rmr/command.c
In PR #3853 we added `depleted` flag to `MRCommand`.
The coordinator uses this flag to decide if it needs to send another cursor read command to the shards.
When more replies are needed, and there are more pending shards (their cursors have more results to send),
we iterate over the shards and we send a cursor read command to every **not depleted** shard.
Since this flag wasn't initialized, it could contain some non-zero value, and this check result was that the cursor is depleted, and the coordinator was waiting forever to a shard that was never triggered.
1. PR #3853
2. MOD-5937
1. MRCommand
=> initialize MRCommand.depleted - MOD-5937

coord/src/rmr/command.c
=> [2.6] initialize MRCommand.depleted - MOD-5937 (#3966)

tests/benchmarks/search-ftsb-1700K-docs-union-iterators-q3.yml, tests/benchmarks/search-ftsb-370K-docs-union-iterators-q4.yml, tests/benchmarks/search-ftsb-5200K-docs-union-iterators-q1.yml, tests/benchmarks/search-ftsb-5500K-docs-union-iterators-q2.yml
CP of https://github.com/RediSearch/RediSearch/pull/3953 into 2.8
=> [2.8] Added q1, q2, q3, and q4 large union iterator benchmarks (#3953)

.circleci/config.yml, sbin/pack.sh
In x86_64 with macOS, set the zip filename for the artifact to be `catalina` even though it is built on a newer OS (`monterey`)
=> Rename zip filename for macos build

.circleci/config.yml, Makefile, build/docker/Makefile
Fix for #3992 - need to set the right redis json branch for build platforms as well (all platforms al built with redis 6.2 hardcoded)
=> fix for build platforms

coord/src/search_cluster.c, tests/pytests/test.py
Fix of a bad condition. Today we don't fail due to a check of the alias list in case the `INDEXSPEC_LOAD_NOALIAS` flag isn't on, but there is no good reason comparing the length of the strings (index and alias) instead of the strings, which is prone for error.
=> MOD-5945: Fix bad comparison

src/aggregate/aggregate_exec.c, tests/pytests/test.py, tests/pytests/test_aggregate.py, tests/pytests/test_resp3.py, tests/pytests/test_vecsim.py
Currently, in case we experience a timeout throughout pipeline execution, we may reply to the client with a simple string depicting the error message, instead of replying with an error (with that same error message).
This PR fixes this, so that we always return an error.
=> MOD-5965: Return error upon timeout

src/aggregate/aggregate_exec.c, tests/pytests/test.py, tests/pytests/test_aggregate.py, tests/pytests/test_resp3.py, tests/pytests/test_vecsim.py
This reverts commit 5b2364053b06608189d406ac70f795ef15286750.
Temporary revert to quickly allow green CI. Will be done slightly different soon.
=> Revert "MOD-5965: Return error upon timeout (#3987)" (temporarily)

tests/pytests/requirements.txt, tests/pytests/runtests.sh
continues #3749 and removes a bash-only option (for the Mac and zsh users)
Also, add RLTest 0.7.2 to the requirements.
=> Fix log level for mac

coord/src/dist_aggregate.c, coord/src/rmr/chan.c, coord/src/rmr/chan.h, coord/src/rmr/rmr.c, coord/src/rmr/rmr.h, src/cursor.c, src/cursor.h, src/spec.c, tests/pytests/test_aggregate.py, tests/pytests/test_cursors.py, tests/pytests/test_json.py
This PR extends #3853 in two ways:
1. Moving the `RQ_Done` call from `MRIteratorCallback_Done` to `MRIteratorCallback_ProcessDone`. This has no effect if we are on a regular `AGGREGATE` command since it implies `inProcess==pending`. But on `AGGREGATE WITHCURSOR` we push (`RQ_Push`) the next `_FT.CURSOR READ` call manually each time, while `RQ_Done` was called only if all the cursors at the shards got depleted. This could cause a logical leak since we miss updating the request queue about the number of pending jobs. This bug is now fixed.
2. when freeing a user's cursor on coordinator mode, we will now trigger an async `FT.CURSOR DEL` at the shards, so we don't have hanging cursors, reducing the expected memory peak. This is not a bug because …
=> Improvement for PR 3853 (cursor on coordinator) - [MOD-6089]

coord/src/dist_aggregate.c, tests/pytests/test_aggregate.py
=> [2.6] Fix `TIMEOUT` parameter on `FT.AGGREGATE` from the coordinator (#3814)

deps/thpool/thpool.c, src/util/logging.c
This PR fixes the log callback. `LogCallback` receives a format and a variadic number of args for the format tags values.
A function that has the same API such as `RedisModule_Log`, expects to receive arguments of the same type (fmt + values)
Currently, we translated the variadic list to `va_list ap` and passed ap to `RedisModule_Log`. The resulting text contained some jibrish values.
The solution is to generate the message with the tags values using a function the expects to receive va_list such as `vsnprintf` and pass this message to `RedisModule_Log` 
1. #...
2. MOD...
1.`LogCallback`
2. ...
=> fix thpool size format print in redisearch_thpool_init

sbin/get-redisjson, sbin/upload-artifacts
Use catalina as the os name in x86 - to be aligned with the artifact the is created in redis JSON
=> Align os name for macos

coord/src/module.c, coord/src/rmr/rmr.c, coord/src/rmr/rmr.h, coord/src/rmr/rq.c, coord/src/rmr/rq.h
1. The current state briefly:
The sanitizer detected that we don't free UpdateTopology request (and the allocated struct it holds). We do call free when we execute the request, however, since this type of request is inserted periodically to the queue and can be still in the queue upon shut down, it will be considered as leak.
It is important to mention that this PR puprpose is to eliminate the sanitizer failure during tests, where all other types of requests will be executed and properly freed if everything works as expected.
On production, we don't care about this memory not being released, the process goes down anyway, as long as it is a "direct/indirect" memory allocation …
=> MOD-5849 - fix coordinator request leak

coord/src/module.c, coord/src/rmr/rmr.c, coord/src/rmr/rmr.h, coord/src/rmr/rq.c, coord/src/rmr/rq.h
Backport of https://github.com/RediSearch/RediSearch/pull/4057 to 2.6.
=> Backport-4057-to-2.6

.install/amazon_linux_2.sh, sbin/setup
1. Currently, on amzn2, we are linking to openssl10
2. On amzn2, we will link to openssl11
3. And additional installation and configuration of openssl11 is required for amzn2 users.
1. MOD-6012
1. On amzn2, link to openssl11
=> MOD-6012 use openssl11 on Amazon Linux 2

.github/workflows/event-merge-to-queue.yml, .github/workflows/event-nightly.yml, .github/workflows/event-pull_request.yml, .github/workflows/flow-build-artifacts.yml, .github/workflows/flow-linux-platforms.yml, .github/workflows/flow-macos.yml, .github/workflows/flow-self-hosted-arm.yml, .github/workflows/flow-temp.yml, .github/workflows/task-build-artifacts.yml, .github/workflows/task-get-latest-tag.yml, .github/workflows/task-test.yml
Instead of relying on repo variables and maintaining them, use GitHub REST API to get the latest release tag of a repo.
The new script supports both getting the latest release and getting the latest release by a prefix. This will become useful when we cherry-pick the new CI to the version branches since 2.6 does not support redis 7 and needs to be tested with the latest major 6 release.
=> GHA refactor - get latest versions - [MOD-6174]

.github/workflows/event-merge-to-queue.yml, .github/workflows/flow-linux-platforms.yml, .github/workflows/flow-macos.yml, .github/workflows/flow-sanitizer.yml, .github/workflows/task-test.yml
1. Change the required value for skipping redis installation, so `''` will get unstable by default.
2. Enabled `redis-ref` and `test-config` options on macOS and Linux dispatch flows.
3. Fix merge group concurrency
=> GHA refactor - fix dispatch

.github/workflows/event-push-to-integ.yml
Only run `event-push-to-integ.yml` if the PR includes changes to code or benchmark.
This should be changed in the future if this event triggers more stuff besides running benchmarks
=> GHA - Skip running benchmarks on unrelated PRs

.github/workflows/flow-macos.yml, deps/thpool/thpool.c
Addressing @MeirShpilraien suggestion for fixing the initialization of thread pools on module-init.
The effect is already significant for clang-sanitizer and Codecov flows, reducing the time **by half** (on the pull-request flow, 60 -> 30, 50 -> 23 minutes)
Related to MOD-6124
=> Avoid Busy Loop on thpool Initialization

.github/workflows/benchmark-trigger.yml
Improving benchmark triggering logic.
We now run benchmarks if:
1. We just labeled the PR with `action:run-benchmark`
2. We updated/opened/reopened the PR
We no longer run the benchmarks when the `action:run-benchmark` label is present and we add another label.
We also cancel previous benchmark flows because we lack runners ATM
=> GHA - improve benchmark rules

.github/workflows/event-merge-to-queue.yml, .github/workflows/task-build-artifacts.yml, .github/workflows/task-get-latest-tag.yml, .github/workflows/task-get-linux-configurations.yml, .github/workflows/task-test.yml
Tune the merge queue job to run a bit quicker and prepare for multiple redis-version to check against.
2.6 will run multiple versions.
Doc: TBD
=> GHA - Tune merge queue event for 2.8 - [MOD-6196]

.github/workflows/benchmark-flow.yml, .github/workflows/event-merge-to-queue.yml, tests/pytests/runtests.sh, tests/pytests/test_aggregate.py, tests/pytests/test_scorers.py
1. Fix the build step on the benchmark flow
2. Fixing Python missing imports and RLTest config for redis 7
3. unify Macos matrix to use fewer resources
=> Fix test and benchmark flows on 2.6

deps/thpool/thpool.c
* avoid busy loop
* TEMP set value for getting redis
* Revert "TEMP set value for getting redis"
=> [2.6] Avoid Busy Loop on thpool Initialization (#4118)

docs/docs/advanced-concepts/query_syntax.md
Fixes a broken image link on the docs/docs/advanced-concepts/query_syntax.md page.
@adrianoamaral, @dmaier-redislabs, or any other maintainer: this is an urgent fix. Please approve and merge. Thank you!
=> DOC-3174: fixes a broken image link

.github/workflows/event-nightly.yml
Temp removed the 2.10 build from nightly until we return to use this branch for milestones release. 
It is only relevant in master, as schedule workflows are not relevant in other branches
=> remove 2.10 from nightly

coord/src/rmr/conn.c, coord/src/rmr/endpoint.h, tests/pytests/runtests.sh, tests/pytests/test.py
Remove the configuration for `global_password` and add a designated test for oss password
This PR relies on using RLTest >=0.7.5. See [RLTest#208](https://github.com/RedisLabsModules/RLTest/pull/208)
This PR also exposed a leak on the oss-cluster authentication flow (oss-cluster with password). It will be included in the next patch releases
=> Test oss global password - [MOD-6117]

src/aggregate/aggregate_exec.c, tests/pytests/test_coordinator.py, tests/pytests/test_cursors.py
Currently, we return the number of aggregated results and the results aggregated until experiencing a timeout on a cursor command, no matter the timeout policy. This PR fixes this behavior to return a timeout error (accompanied with a `0` cursor id, as before) when the timeout policy is strict (i.e., `ON_TIMEOUT FAIL`).
This PR also enables to return other errors from a cursor, which is a behavior we do not currently exploit. This situation is rare also for non-cursor commands, yet we want to have unified behaviors for the cursor in this regard.
(Related to #4059)
=> MOD-5990: Return timeout error from cursor on strict timeout policy

tests/pytests/common.py, tests/pytests/test_issues.py
After we move slot 0 from its original shard in the cluster to a new shard that was added to the cluster - we test that the new shard is aware of the topology change of the cluster. As this information may take some time to propagate between shards, we wrap this check with a timeout of 10 seconds (so that we fail only if after 10 seconds it still didn't happened and not immediately).
=> Fix flaky test_mod5778_add_new_shard_to_cluster - take2 

Makefile, tests/pytests/runtests.sh
Start using the new `--test-timeout` flag of RLTest (from 0.7.7).
We set a single test timeout to 300s, after that RLTest will kill it and show where it got stuck.
This also enables us to safely set the default timeout of a query to 0 (currently done for coverage and sanitize/Valgrind flows only),
=> Set a timeout for tests using RLTest - [MOD-6023]

sbin/gen-test-certs, tests/pytests/common.py, tests/pytests/includes.py, tests/pytests/runtests.sh, tests/pytests/test.py, tests/pytests/test_issues.py
Remove the configuration of `tls` and add a designated test for TLS (and improve another test to run with TLS)
introducing `get_TLS_args()` in `common.py` that will return all the needed parameters to start an environment with TLS
=> Test TLS password - [MOD-6119]

tests/pytests/test.py, tests/pytests/test_resp3.py
Removes timeout flakiness from tests. Specifically aimed for `test_resp3:testTimedOutWarning_resp3`.
=> Remove timeout flakiness

src/debug_commads.c, tests/pytests/test_debug_commands.py, tests/pytests/test_followhashes.py
**Changes in the pull request**
The original purpose of the `testManyPrefixes` test was to measure the performance enhancement introduced in PR #2560. (enhanced performance of the cleanup process upon FLUSHALL by optimizing the way the spec:prefixes dictionary and the cursors lists are cleared)
However, the test was **unstable** and could timeout on some platforms, even after the optimization. The **sanitizer was also disabled**, which is not ideal for a cleanup test.
The PR then modifies the test to focus on the **functionality** of the cleanup process, rather than its performance. This change ensures that the test is more stable and that it properly checks that the …
=> MOD-6019 fix flaky test_followhashes:testManyPrefixes

.github/workflows/flow-macos.yml, .github/workflows/task-backport_pr.yml
Instead of using a PAT directly (and passing the responsibility of the backport work to me), we automate the drafting and un-drafting of the new PRs with the PAT so it triggers the CI while keeping the PR automation and comments on the actions-bot.
For now, it uses my fork of the backport action, until my PR for the action is approved (or denied, then we will need to decide what to do).
[backport issue](https://github.com/korthout/backport-action/issues/403)
[backport PR](https://github.com/korthout/backport-action/pull/404)
=> Fix backport flow - a better solution

.github/workflows/flow-temp.yml, deps/rmutil/alloc.c, deps/rmutil/alloc.h, deps/rmutil/cmdparse.c, deps/rmutil/cmdparse.h, deps/rmutil/strings.h
The rmutil/alloc.h file's redefinition of standard `*alloc` functions as `redismodule_*alloc` caused **conflicts**, resulting in build failures due to overridden allocation calls in other linked libraries.
The fixes introduced in version 2.8, addressing the issue, are being backported to version 2.6 through this PR.
=> backport hard redefinition of standard *alloc from rmutil

coord/src/dist_aggregate.c, coord/src/module.c, src/aggregate/aggregate_exec.c, tests/pytests/test_profile.py
We crash for commands such as `FT.PROFILE idx AGGREGATE QUERY "*"` **in the resp3 protocol**.
We fix this by fixing the `printAggProfile` function in `coord/src/dist_aggregate.c` not to open a map as a key.
=> MOD-6250: Fix crash on `FT.PROFILE .. AGGREGATE ..` commands

src/geometry/geometry_types.h, src/geometry/rtree.cpp, src/geometry/rtree.hpp, src/query.c, tests/pytests/test_geometry_flat.py, tests/pytests/test_geometry_sphere.py
Replaces #4109
1. The current state does not allow for checking if geometries intersect / are disjoint.
2. This PR adds functionality to check intersection and disjointedness of geometries. Two geometry query type keywords are added: INTERSECTS and DISJOINT. This functionality is indifferent to underlying geometry type; both POINT and POLYGON may be both querying and queried geometries.
3. Users will be able to query for indexed geometries that intersect / are disjoint to a query geometry.
1. [PM-167](https://redislabs.atlassian.net/browse/PM-167)
2. [MOD-6178](https://redislabs.atlassian.net/browse/MOD-6178)
1. …
=> MOD-6178: [GeoPoly] Intersects Disjoint

coord/src/coord_module.h, coord/src/module.c, src/aggregate/aggregate.h, src/aggregate/aggregate_request.c, tests/pytests/test.py
Currently, we don't check for a timeout in the coordinator for `FT.SEARCH` commands. This means that we leave a potentially large time-unit unchecked for timeouts, and may break our wanted promises of strict timeout policy.
In this PR a check for a timeout is added to the `FT.SEARCH` path, after processing all the results from the shards, and right before sending the results to the client (for maximal coverage). If a timeout has been reached, we behave according to the timeout protocol in use (i.e., return a timeout error if the policy is strict, and return the results aggregated otherwise).
1. The `initClock` and `timeout` fields were added to the `searchRequestCtx` struct, to hold the clock at the beginning of the execution and the timeout of the query, …
=> MOD-6278: Timeout check addition to `FT.SEARCH` in the coordinator

.github/workflows/event-merge-to-queue.yml, .github/workflows/event-pull_request.yml, tests/pytests/test_scorers.py
* fix 1: don't merge if jobs get cancelled
fix2: test_scorers:testTFIDFScorerExplanation fix result for building with redis older than 6.2.0
=> Stabalize CI 

tests/pytests/test_issues.py
Since this test tends to be flaky due to the inconsistent response of "cluster node" command and the time it takes for the cluster to acknowledge the topology changes, we allow several attempts and fail only if all failed. 
=> Remove flakiness in test of adding new node to cluster - take 3

src/debug_commads.c, tests/pytests/test_debug_commands.py, tests/pytests/test_followhashes.py
(cherry picked from commit 7049fe8325de0fb4c08d26e2c2350459286ccfbb)
https://github.com/RediSearch/RediSearch/pull/4189
=> [2.8] MOD-6019 fix flaky test_followhashes:testManyPrefixes

tests/pytests/test_multithread.py
Don't test for redis version with the bug in which we are accessing modules that had failed to be loaded (fix a potential crash)  
=> Fix test_invalid_mt_config_combinations

.github/workflows/event-merge-to-queue.yml, .github/workflows/event-pull_request.yml, tests/pytests/test_scorers.py
* fix 1: don;t merge if jobs get cancelled
fix2: test_scorers:testTFIDFScorerExplanation fix result for building with redis older than 6.2.0
=> [2.8] Stabalize CI (#4221)

src/info_command.c, tests/pytests/common.py, tests/pytests/test_info.py, tests/pytests/test_vecsim.py
This PR enhances the ft.info command by adding vector field information.
**For both HNSW and FLAT** algorithms the attributes include 
* data_type
* dim
* distance_metric.
**For HNSW**, additional attributes are also displayed:
* M
* ef_construction 
output examples:
**HNSW:**
```
8) 1)  1) identifier
2) vec2
3) attribute
4) vec2
5) type
6) VECTOR
7) algorithm
8) HNSW
9) data_type
10) FLOAT32
11) dim
12) (integer) 128
13) distance_metric
14) L2
15) M
16) (integer) 16
17) ef_construction
18) (integer) 200
```
**FLAT:**
``` 8) 1)  1) identifier
2) vec
3) attribute
4) vec
5) type
6) VECTOR
7) algorithm
8) FLAT
9) data_type
10) FLOAT32
11) dim
12) (integer) 128
13) distance_metric
14) L2
```
=> MOD-6198 add vecsim info to ft.info

src/aggregate/aggregate_exec.c, src/index.c, src/index.h, src/inverted_index.h, src/query.c, src/util/timeout.h, tests/cpptests/test_cpp_index.cpp, tests/pytests/test.py
This PR solves an edge-case in which we may spend a lot of time searching for a valid result in the `NOT` iterator without polling for timeouts. We check for timeouts with very low granularity (once in every 5000 results) in order to avoid such cases, but not add significant overhead.
1. Added a `TimeoutCtx` to the `NOTContext` (also the `NotIterator`).
=> MOD-5512: Add timeout check in NOT iterator

src/index.c, src/index.h, src/inverted_index.h, src/query.c, src/util/timeout.h, tests/cpptests/test_cpp_index.cpp, tests/pytests/test.py
Backport of #4244 to 2.6.
Notice: We removed from the test the part that depends on timeout-related PRs that were not added to 2.6 (related to the timeout response etc.).
=> [2.6] MOD-5512: Add timeout check in NOT iterator (#4244)

src/aggregate/aggregate_exec.c, tests/pytests/test_async.py
Currently we have flakiness in our multi-threading build in cases of commands that fail early on timeout. This is due to an extra section added to the error which may appear or not, depending on the time of the failure (thus the flakiness).
In this PR we remove this section of the error-message, unifying the error-response of early and late (specifically, timeout) failures for the multi-threaded build.
=> MOD-6252: Remove multi-threading timeout flakiness

.circleci/config.yml
Build macos M1 in CircleCI on integration branches (temporary until we remove it completely from Circle). Until now, we only uploaded artifacts upon tagging. For the new mechanism where tagging only moves artifacts from snapshots to production, we need to have it before.
Also, use the right snapshot directory in S3 (instead of uploading it to staging) 
1. ...
2. ...
=> Always upload macos-M1 artifacts to snapshots dir

tests/pytests/test_issues.py
After adding a new API to RLTest (https://github.com/RedisLabsModules/RLTest/pull/214) - have a more robust test for MOD-5778 that also relies on RediSearch cluster info rather than redis cluster info alone.
=> Refactor test add new shard to cluster

sbin/upload-artifacts
Set the arch name to "aarch64" in arm to be aligned with the zip filename (otherwise it won't upload to s3)
=> Fix M1 upload arch name

tests/pytests/test_rdb_compatibility.py
Previously the tests involved checking for the existence of REDISEARCH_CACHE_DIR and creating it if it didn't exist. However, since the tests are r**unning in parallel**, multiple tests could simultaneously verify the absence of REDISEARCH_CACHE_DIR, yet upon creating it, only one test succeeded while others encountered an error, causing instability in test_rdb_compatibility.
This PR resolves the issue by replacing the existence check with a try-except block. 
The code now attempts to create REDISEARCH_CACHE_DIR within a try block. In cases where the directory already exists, the except block ensures the test continues without failing.
=> MOD-6292 fix flaky CI - test_rdb_compatibility:testRDBCompatibility

coord/src/dist_aggregate.c, src/spec.c
1. Fix potential `NULL` dereference of replies in the coordinator.
2. Fix freeing an `IndexSpec` before initializing its `indexError`, leading to freeing a NULL Redis string (`NULL` dereference)
=> Fix NULL related bugs [MOD-6337, MOD-6336]

tests/pytests/test_cursors.py
Fixing a flakiness that may happen when a timeout occurs.
Since we now have `TIMEOUT 0` by default on the CI, we just have to remove the 5-second timeout.
The PR also includes cosmetic changes to the test, and moves to using the `env` connection on all search-related commands to avoid potential flakiness when creating a cursor on one shard and attempting to read it from another.
=> Fix timeout flakiness of `testCursorOnCoordinator` - [MOD-6253]

tests/pytests/test_issues.py
Fix flakiness in `test_mod5778_add_new_shard_to_cluster_TLS`, fix according to https://redis.io/commands/cluster-setslot/
=> Fix migrating slot in test

coord/src/rmr/conn.c
The PR fixes a crash on hiredis where the SSL initialization fails. It seems that hiredis do not unset the callbacks that was set by the redisInitiateSSL in case of a failure, and so later those callbacks might be called when the SSL context is not initialized and cause a crash.
An issue was open upstream to fix it on hiredis itself: https://github.com/redis/hiredis/issues/1233
A temporary fix is to reset the callbacks in case of ssl initialization failure.
1. MOD-5850
1. fix crash on tls initialization failure.
=> Fix MOD-5850, fix crash on tls initialization failure.

src/result_processor.c, tests/pytests/test_multithread.py
Fixing a minor bug in the `SafeLoader` accumulation phase, where it decreased the result limit counter **before** calling the upstream. If the upstream contains an RP that checks the result limit to decide how many results to accumulate (like the `SafeLoader` itself), it will be required to get one less result than needed.
The upstream `SafeLoader` will then be requested for one more result than it had, but at the yielding phase it relies on the correct number of requested results and it will cause it not to set the last result, but still return `RS_RESULT_OK` if the limit was greater than the number of results from the iterators.
The downstream `SafeLoader` will then buffer the empty result as a valid result, and will crash when it attempts to …
=> Fix safe loader limit - [MOD-6385]

coord/src/search_cluster.c, tests/pytests/test.py
1. CLUSTERSET memory tracking test is flaky. Memory immediately reduced from its initial value and then stabilizes.
2. Take the stabilized memory value instead of the initial.
3. Unflake the test.
1. https://redislabs.atlassian.net/browse/MOD-6321
2. https://redislabs.atlassian.net/browse/MOD-6383
1. test.py
=> Ephraim unflake clusterset memtracking

tests/pytests/CMakeLists.txt, tests/pytests/runtests.sh, tests/pytests/test_issues.py, tests/pytests/test_vecsim.py
Removing the test configuration of `UNION_ITERATOR_HEAP` from the CI.
We have a unit test for this union iterator mode, and according to the coverage report, we choose this mode 10% of the time.
This PR includes some preparation for improving the tests of the mode in edge cases.
=> Remove `union_iterator_heap` test configuration - [MOD-6114]

coord/src/dist_aggregate.c, coord/src/rmr/command.c, coord/src/rmr/rmr.c
This PR fixes a crash we currently experience due to incorrect folding in the coordinator upon `FT.AGGREGATE .. WITHCURSOR` commands (i.e., client-cursors in the coordinator).
Specifically, in some scenarios we don't wait for all the commands we send to the shards to finish, and thus free the `MRIteratorCtx` before it is used again by the uv-thread once the reply from the shard is received.
These problems occurred since we called `MRIteratorCallback_Done` without setting `cmd->depleted`, which is the criteria we later use in order to determine to which shards we wish to send the `FT.CURSOR DEL ..` command upon the folding of `rpNet` (see `rpNetFree()`). This yielded a possible state in which we have `pending=x` and `|{C | C->depleted = true}|=y` while `y > x`. This is a bug, since now …
=> MOD-6287: Fix Coordinator folding mechanism

tests/pytests/test_profile.py
Skips a flaky test, due to flaky timers behavior.
=> Skip flaky test

tests/pytests/test_vecsim.py
This is to avoid hanging, especially in new parallel configurations. Partial CP from #4266
=> [2.6] Split test vecsim timeout reached 

coord/src/rmr/cluster.c, coord/src/rmr/cluster.h, coord/src/rmr/node.c, coord/src/rmr/node.h, coord/src/rmr/node_map.c, coord/src/rmr/node_map.h
This PR replaces the existing NodeMap's hosts and nodes tries with dictionaries.
Chnages made in this PR:
* The NodeMap structure now utilizes dictionaries in place of the previous hosts and nodes tries. 
* Separation of node functions and NodeMap functions into distinct files: created node_map.h and node.c.
* Encapsulate MRNodeMap struct: The MRNodeMap struct has been made opaque by moving its definition to node_map.c.
* removed MRNodeMap_IterateRandomNodePerhost and MRCluster_RemoteCoordination strategy (These were not in active use.)
=> MOD-6449 - replace NodeMap internals tries with dictionaries

src/synonym_map.c, tests/pytests/test_synonyms.py
1. Allocate `newId` after checking if the term-id pair already exists (and only if not)
2. Fix the `TermData_IdExists` comparison function
This bug could cause a performance hit (searching for a word from a synonym group will yield a union of the same group multiple times)
1. synonym map
=> Fix a Leak in Synonym - [MOD-6490]

src/debug_commands.c, tests/pytests/common.py, tests/pytests/test_debug_commands.py, tests/pytests/test_replicate.py
Reenabling `test_replicate` tests.
They were marked as "flaky" and it was commented to remove the skip when #3525 is merged.
There were 2 fixes in #3525 (that was never merged). One was introduced separately on #3635, where it was also removed from the skipping list so we know the fix was working since the test is not flaky (AFAWK and as of today).
This PR implements the second fix + a fix for potential flakiness in `testDropTempReplicate`
=> Reenable replication tests - [MOD-6181]

coord/src/module.c, coord/src/rmr/rmr.c, coord/src/rmr/rq.c, coord/src/search_cluster.c
Initialize the uv_thread only after a job is pushed to the RQ.
Notes:
- From LibUV docs on calling `uv_run` with `UV_RUN_DEFAULT`:
> Runs the event loop until there are no more active and referenced handles or requests
So until the RQ is released (which is never), `uv_run` won't return. No need to call it in a loop
- On an OSS cluster, we call `SEARCH.CLUSTERREFRESH` every second, which pushes an update topology request to the RQ. without making this thread initialize lazily as well, we expect the uv thread to be initialized after a second passed from loading the module.
=> Initiate libuv thread lazily - [MOD-6473]

coord/src/dist_aggregate.c, src/debug_commands.c, tests/pytests/common.py, tests/pytests/test_coordinator.py, tests/pytests/test_cursors.py, tests/pytests/test_debug_commands.py
Adds a test for the coordinator fix in #4324.
A new debug command is introduced, deleting the local cursors of a shard. We use this in order to make sure that when the coordinator will ask for more results from the shard, an error will be returned.
=> MOD-6438: Add test for coord fix

src/aggregate/functions/date.c, tests/pytests/test_aggregate.py
Fix implementation of `fast_timegm` which was wrong at the beginning of leap years (we added a day offset to the entire year, including the days before the leap day)
Correctness:
- https://godbolt.org/z/qscb5d9dT
Performance:
- https://quick-bench.com/q/oTV4_9uVqPTcrj2fpDEvbbMzZ48
- https://quick-bench.com/q/2Bc8WY1Ys0vmbp-HPagWFxu81jI
```
ft.aggregate test-idx "*" APPLY day(@timestamp) AS day SORTBY 2 @day desc LIMIT 0 1
```
Returns:
```
1) "39"
2) 1) "timestamp"
2) "1704118547"
3) "day"
4) "1704153600"
```
```
1) "39"
2) 1) "timestamp"
2) "1704118547"
3) "day"
4) "1704067200"
```
Notice that `month`, `day`, `hour` and `minute` always "round down", so the result should be smaller than the original timestamp
1. …
=> Fix `fast_timegm` implementation - [MOD-6549]

src/aggregate/functions/date.c, tests/pytests/test_aggregate.py
Backport of #4394 to `2.6`
1. #4393
=> [2.6] Fix `fast_timegm` implementation - [MOD-6549]

src/aggregate/functions/date.c, tests/pytests/test_aggregate.py
Backport of #4394 to `2.8`
1. #4393
=> [2.8] Fix `fast_timegm` implementation - [MOD-6549]

coord/src/module.c, tests/pytests/test_issues.py
Add an unblock callback when blocking a client for an `FT.SEARCH` command, to free some context and reply with an error in some early unblocking flows.
1. MOD-6557
1. distributed search flow
=> Fix unblocking client with no reply on SEARCH cluster mode - [MOD-6557]

coord/src/module.c, coord/src/rmr/rmr.c, coord/src/rmr/rmr.h
Move `SEARCH.CLUSTERINFO` execution to the UV thread if we have a topology, as it could be freed at any moment from the UV thread
=> [2.8] move ClusterInfoCommand to UV thread - [MOD-6504]

coord/src/rmr/endpoint.c, coord/src/rmr/redise.c, coord/src/rmr/redise_parser/grammar.c, coord/src/rmr/redise_parser/grammar.y, tests/pytests/test.py
Followup of #4390.
In this PR we handle syntax errors on `MREndpoint_Parse` failure, and remove the new line (`\n`) from the error and log message, as it is not allowed to have a new line in a reply of `RedisModule_ReplyWithError`.
Some redis versions seemed to handle the new line, but on 2.6 when tested against redis 6.0, the client got no reply back.
1. `SEARCH.CLUSTERSET` topology parser (coordinator)
=> Fix topology parser syntax error handling - [MOD-6552, MOD-6543]

.github/workflows/event-merge-to-queue.yml, .github/workflows/flow-linux-platforms.yml
We previously discovered that if we have a matrix that uses a reusable workflow, if one of the matrix variances fails, the matrix result is `cancelled` instead of `failure`. Seems like a GitHub bug.
We thought if we added `cancelled` to the pr-validation job list of bad results, we would work around this behaviour. But on 2.6 merge queue flow, we have a matrix that calls a reusable workflow that calls another reusable workflow.
In this case, if some of the deepest (level 3) jobs fail, their parent matrix (level 2) will report `cancelled`, which will then cause the top matrix (level 1) to **IGNORE THE RETURN STATUS AND REPORT SUCCESS**.
As a workaround, until https://github.com/actions/runner/issues/3041 gets a solution, we have to flatten out …
=> Fix GHA merge queue flow

coord/src/module.c, coord/src/rmr/rmr.c, coord/src/rmr/rmr.h
Move `SEARCH.CLUSTERINFO` execution to the UV thread if we have a topology, as it could be freed at any moment from the UV thread
=> [2.6] move ClusterInfoCommand to UV thread - [MOD-6504]

tests/pytests/test.py
Fixes a rarely flaky test, in which we may get an unhandled error.
=> [2.6] Fix flaky notIter test

src/doc_table.h, src/document.c, src/index.c, src/indexer.c, src/inverted_index.c, src/query.c, src/tag_index.c, src/tag_index.h, tests/pytests/common.py, tests/pytests/test_tags.py
Adds support for indexing empty values in the indexing and querying pipeline for TAGs.
Since the current TAG indexing mechanism uses a `TrieMap` to store the mapping between terms and their corresponding `InvertedIndex`s, which has a root node corresponding to the empty string `''`, we chose to exploit it by removing the empty string neglecting parts of the code. By doing so, the changes needed were minimal.
=> MOD-6530: Support empty values indexing for TAGs

tests/pytests/test_replicate.py
In this test, we used the redis `WAIT` command to synchronize the master and replica.
The `WAIT` command waits for the write command **sent on the waiting connection** to be synchronized on the replica, but in the test, we used a different connection to send the commands and for waiting, so we actually didn't wait for anything
=> Fix `testDelReplicate` flakiness

deps/thpool/thpool.c
Using the number of running threads instead of the thread ID to decide if the thread should take a high or low priority job.
=> Refactor thpool priviliged mechanizm - [MOD-6576]

src/query.c, tests/pytests/test_tags.py
Fixes a leak in the TAG prefix node evaluation, due to not freeing the allocated index-iterators array when no results are found in the suffix TrieMap.
=> MOD-6644: Fix leak in tag prefix node evaluation

tests/pytests/test_async.py
CP of removing the flaky testing of the amount of seconds took for a PING to return
=> [2.6] Fix flaky test mod4745

src/inverted_index.c
An issue was raised here:
https://github.com/RediSearch/RediSearch/issues/4428
Very simple change to reset sameId to 0 on IR_Rewind(), as it is initialized to 0 at creation time.
=> Reset sameId variable on rewind

tests/pytests/common.py, tests/pytests/test_rdb_compatibility.py, tests/pytests/test_short_read.py
Adds a test to the short-read tests as part of the EMPTY TAG indexing.
Update: We also refactor the path of the test-rdbs to a non-production s3 bucket, so that it is more accessible for our modifications.
=> MOD-6531: Empty TAG indexing short-read test

src/query.c, tests/pytests/test_issues.py
Backport of https://github.com/RediSearch/RediSearch/pull/4125 to 2.6.
=> [2.6] MOD-6186 - Fix FT.EXPLAIN, FT.EXPLAINCLI: INFIX, SUFFIX

src/query.c, tests/pytests/test_issues.py
Backport of https://github.com/RediSearch/RediSearch/pull/4125 to 2.8.
=> [2.8] MOD-6186 - Fix FT.EXPLAIN, FT.EXPLAINCLI: INFIX, SUFFIX

src/geometry/geometry_types.h, src/query.c
1. Currently GeoShape syntax accepts prefixes of operators
2. This changes the check to require that operators are spelled out in full
1. [MOD-6663](https://redislabs.atlassian.net/browse/MOD-6663)
1. query.c
[MOD-6663]: https://redislabs.atlassian.net/browse/MOD-6663?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOD-6663: GeoShape must supply complete predicate, not just prefix

src/query_parser/v2/parser.c, src/query_parser/v2/parser.y, tests/pytests/test_vecsim.py
With the previous condition. any prefix of `KNN` and `VECTOR_RANGE` could pass as a valid command
=> Fix bad usage of strncmp

coord/src/module.c, deps/triemap/triemap.c, deps/triemap/triemap.h, src/doc_table.c, src/extension.c, src/rules.c, src/rules.h, src/tag_index.c
We currently have an array of `char *` prefixes, that we calculate `strlen` for every prefix of every index for every document we index (BG indexing mostly).
This PR replaces the `char *` array with an `sds` array, that stores its length and uses `sdslen` instead of `strlen` where we had it before.
=> use sds instead of char * - [MOD-6711]

src/geometry/rtree.cpp, tests/pytests/test_geometry_flat.py
1. Currently, when attempting to parse an invalid GEOMETRY, we report "invalid geometry"
2. Changes to provide explanation for different classes of why the GEOMETRY was invalid.
1. [MOD-6701](https://redislabs.atlassian.net/browse/MOD-6701)
1. GeoShape WKT parser.
[MOD-6701]: https://redislabs.atlassian.net/browse/MOD-6701?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOD-6701: Passing more descriptive error messages

coord/src/module.c, tests/pytests/test_issues.py
Backport of #4497 to `2.6`.
Added more flags to `cannotBlockCtx` to support redis 6.0
Also handling some additional and deprecated commands for coverage.
=> [2.6] Handle MULTI / EXEC and LUA properly - [MOD-6541]

coord/src/module.c, tests/pytests/test_issues.py
Backport of #4497 to `2.8`.
Handling some additional and deprecated commands for coverage.
=> [2.8] Handle MULTI / EXEC and LUA properly - [MOD-6541]

src/geometry/geometry_types.h, src/query.c
=> [2.8] MOD-6663 GeoShape must supply complete predicate, not just prefix

.github/workflows/flow-sanitizer.yml
The sanitizer fails on ci using clang-16. We use clang-17 instead which is currently stable.
=> MOD-6792: Fix Sanitizer bug on ci

src/config.c, src/debug_commands.c, src/fork_gc.c, src/inverted_index.c, src/numeric_index.c, tests/pytests/test_cursors.py, tests/pytests/test_numbers.py
We have a bug in our numeric index - we don't update the `revisionId` when we trim the Tree (in `NumericRangeTree_TrimEmptyLeaves`), causing us not to abort the reading of the numeric index for an invalidated cursor upon opening an invalidated `NumericRangeIterator`, and possibly crash.
=> MOD-6597: Fix numeric index deletion
