- src/config.c
- src/debug_commads.c
- src/fork_gc.c
- src/inverted_index.c
- src/numeric_index.c
- tests/pytests/test_cursors.py
- tests/pytests/test_numbers.py
> [2.6] MOD-6597: Fix numeric index deletion (#4513)

- coord/src/module.c
- coord/src/rmr/redis_cluster.c
- src/aggregate/functions/function.c
- src/aggregate/functions/string.c
- src/config.c
- src/dictionary.c
- src/document_add.c
- src/info/index_error.c
- src/language.c
- src/notifications.c
- src/rlookup.c
- src/rules.c
- src/spec.c
- src/suffix.c
- tests/pytests/test.py
`strncmp` (and `strncasecmp`) returns 0 if both strings are equal up to n characters, and that means it returns 0 if both strings have the **same prefix** of length n.
This means that we should not use this function for comparing complete strings unless one of the strings is not null-terminated. And we must check that their length are equal.
It is important to note that `strncmp` is not more efficient than `strcmp`, and there is no benefit of running `strncmp(s1, s2, strlen(s2))` instead of `strcmp(s1, s2)` (unless we actually want to check if `s2` is a prefix of `s1`)
This PR fixes the usage of all the `strncmp` in the project. Some of the fixes are just code cleanup with no actual effect on the code, while in other cases it's a bug fix
1. …
> Fix all `strncmp` unintentional usage - [MOD-6709]

- src/document.c
zeroing the memory of RSAddDocumentCtx
1. MOD-6831
> MOD-6831 unintlized memory in RSAddDocumentCtx can cause crash while ingest/load

- src/index.c
- tests/pytests/test_issues.py
Remove double free of iterator in IntersectItarator_Free().
1. MOD-6599
1. ...
2. ...
> [2.6] MOD-6599: Remove double free in IntersectIterator_Free()

- src/query.c
- tests/pytests/test.py
This is an additional change part of MOD-6768:
1. Add a test for `FT.EXPLAIN` using `GEO` field
2. Remove unneeded flag `printAttributes`
1. MOD-6768
1. ...
2. ...
> MOD-6768: Fix FT.EXPLAIN - Add GEO test

- src/query.c
- tests/pytests/test.py
Backport of changes to fix `FT.EXPLAIN` to 2.6:
* #4511 
* #4547 
* GEOSHAPE tests were removed from CP code because GEOSHAPE field type is not supported in 2.6
1. MOD-6768
1. ...
2. ...
> [2.6] MOD-6768: Fix FT.EXPLAIN

- coord/src/dist_aggregate.c
- coord/src/dist_profile.h
- coord/src/module.c
- coord/src/rmr/command.c
- coord/src/rmr/command.h
- src/aggregate/aggregate_exec.c
- src/aggregate/aggregate_request.c
- src/index.c
- src/profile.c
- src/profile.h
- src/reply.c
- src/reply.h
- tests/pytests/test.py
- tests/pytests/test_geo.py
- tests/pytests/test_issues.py
- tests/pytests/test_optimizer.py
- tests/pytests/test_profile.py
- tests/pytests/test_resp3.py
- tests/pytests/test_wildcard.py
This PR modifies the reply structure of `FT.PROFILE` to get a uniform reply, whether we have a standalone instance or a cluster, whether we run `FT.PROFILE SEARCH` or `FT.PROFILE AGGREGATE`, and whether we use `RESP2` or `RESP3`
We now always have:
1. On `RESP2`
```
[
[ < FT.SEARCH / FT.AGGREGATE reply > ],
[
Shards,
[[ < Shards profile data. Array of length 1 for standalone > ]]
Coordinator,
[ < Coordinator profile data, or empty array on standalone > ]
]
]
```
2. On `RESP3`:
```
{
Results: { < FT.SEARCH / FT.AGGREGATE reply > },
Profile: {
Shards: [{ < Shards profile data. Array of length 1 for standalone > }],
Coordinator: { < Coordinator profile data, or empty map on standalone > }
}
}
```
This alignment enables us to have single-sharded …
> Align FT.PROFILE response - [MOD-6816]

- sbin/get-redisjson
`macos-latest-xlarge` (used in the flow-macos.yml flow, added in #4559) was updated from Ventura to Sonoma - yielding the `get-redisjson` script not to find the rejson artifact.
We fix the get-redisjson script to get the right RedisJSON artifact from s3 for Sonoma (Monterey).
> MOD-6960: Get right RedisJSON artifact for macOS Sonoma

- tests/pytests/test_info_modules.py
Removes flakiness from a test by commenting out a check for the total indexing time which is not always `> 0`.
> MOD-6975: Remove test flakiness

- tests/pytests/test_short_read.py
We uploaded a new RDB to s3 that creates both EMPTY TEXT/TAG fields in order to validate rdb compatibility.
> MOD-6580: Update short-read test to use rdb with EMPTY TEXT\TAG fields

- src/aggregate/aggregate.h
- src/aggregate/aggregate_exec.c
- src/aggregate/aggregate_request.c
- src/cursor.c
- src/cursor.h
- src/result_processor.c
- src/result_processor.h
- src/rlookup.h
- tests/pytests/test_multithread.py
Support modifying the RP pipeline when the execution thread is different from the one the pipeline was built for (relevant for cursors only)
> Dynamic loader RP - [MOD-6573]

- src/inverted_index.c
- src/inverted_index.h
- src/query.c
- src/query_error.h
This is the second part (first - #4641) of the support for retrieving the documents holding "missing values" (i.e., don't contain a value for a specific field) via the `ismissing(@field)` syntax.
In this PR we add the `iIndexIterator` and `IndexReader` creation for the soon-to-be missing index in the `IndexSpec` (dictionary `fieldName`-->`InvertedIndex`). This inverted index is added in #4638 (WIP at this point).
> MOD-6535: Querying missing values - Part 2

- src/geometry/query_iterator.cpp
- src/id_list.c
- src/index.c
- src/index_result.c
- src/index_result.h
- src/inverted_index.c
- src/query.c
- tests/pytests/test_missing.py
This PR fixes a problem with the missing values read from the missing inverted index - in which we a bad value loaded for the `fieldMask` of the `VirtualResult` (`0`), instead of the expected `RS_FIELDMASK_ALL` value (`0xFFFFFFFF`).
> MOD-6535: Fix intersect problem

- Makefile
- sbin/build-redisjson
1. Current state
Sanitizer flow is failing when try to use RedisJSON repo with latest nightly rust toolchain. The issue is related to: https://github.com/rust-lang/rust/issues/125319
2. Change
To avoid changes in RedisJSON repo, we are patching 'deps/RedisJSON/deps/readies/bin/getrust' to use the last nigthly rust toolchain that worked on: `nightly-2024-05-16`
1. #...
2. MOD...
1. ...
2. ...
> build-redisjson using fixed rust nightly version

- .github/workflows/event-merge-to-queue.yml
Beagle should not run with redis versions newer than 7.2
> Set 2.8 version to follow only 7.2 redis versions

- sbin/build-redisjson
Backport of #4657 to `2.6`
* build -redisjson using fixed rust nightly version
* export RUST_GOOD_NIGHTLY
* don't export RUST_GOOD_NIGHTLY in build-redisjson
* Remove unneeded NIGHTLY=1
* patch getrust from build-redisjson
* Fix getrust path
* use GOOD_NIGHTLY=nightly-2024-05-16
> [2.6] build-redisjson using fixed rust nightly version (#4657)

- .github/workflows/event-merge-to-queue.yml
Akita should not run with redis versions newer than 7.2
> Set 2.6 version to follow 7.2 redis versions (not newer)

- src/buffer.c
- src/buffer.h
- src/fork_gc.c
- src/inverted_index.c
- src/inverted_index.h
- src/numeric_index.c
- src/numeric_index.h
- src/qint.c
- src/redis_index.c
- src/redisearch.h
- src/spec.h
- src/tag_index.c
- src/tag_index.h
- src/varint.c
- tests/cpptests/index_utils.cpp
- tests/cpptests/test_cpp_forkgc.cpp
- tests/cpptests/test_cpp_index.cpp
- tests/cpptests/test_cpp_llapi.cpp
- tests/cpptests/test_cpp_tagindex.cpp
- tests/ctests/bench-decoder.c
- tests/pytests/common.py
- tests/pytests/test.py
- tests/pytests/test_json_multi_geo.py
- tests/pytests/test_json_multi_numeric.py
- tests/pytests/test_numbers.py
- tests/pytests/test_stats.py
Backport of https://github.com/RediSearch/RediSearch/pull/4218 to `2.10`.
(cherry picked from commit 959ed1a9770e38a097075c8a67f0fbf9e226d7fe)
> [2.10] MOD-5977 MOD-5866: Fix inverted index memory counting (#4218)

- src/buffer.c
- src/buffer.h
- src/fork_gc.c
- src/inverted_index.c
- src/inverted_index.h
- src/numeric_index.c
- src/numeric_index.h
- src/qint.c
- src/redis_index.c
- src/redisearch.h
- src/spec.h
- src/tag_index.c
- src/tag_index.h
- src/varint.c
- tests/cpptests/index_utils.cpp
- tests/cpptests/test_cpp_forkgc.cpp
- tests/cpptests/test_cpp_index.cpp
- tests/cpptests/test_cpp_llapi.cpp
- tests/cpptests/test_cpp_tagindex.cpp
- tests/ctests/bench-decoder.c
- tests/pytests/common.py
- tests/pytests/test.py
- tests/pytests/test_json_multi_geo.py
- tests/pytests/test_json_multi_numeric.py
- tests/pytests/test_numbers.py
- tests/pytests/test_stats.py
Backport of https://github.com/RediSearch/RediSearch/pull/4218 to `2.8`.
(cherry picked from commit 959ed1a9770e38a097075c8a67f0fbf9e226d7fe)
Some of the fields returned by `FT.INFO` in `2.8` are strings but the same fields in master are returned as integers. Thus, some tests needed to include the type conversion.
> [2.8] MOD-5977 MOD-5866: Fix inverted index memory counting (#4218)

- src/json.c
- src/spec.c
- src/vector_index.c
- src/vector_index.h
- tests/pytests/common.py
- tests/pytests/requirements.txt
- tests/pytests/test_multithread.py
- tests/pytests/test_vecsim.py
Backport of #4584 to `2.10`.
* adding support for the bf16 type in the API
* support JSON casting to BF16
* improved casting
* add support for fp16
* update VecSim tag (supports fp16 and bf16)
* remove temporary definitions
* added tests
* minor fix
* review fixes (tests)
* more data types in multithread
* fix another test
* remove NaN/Inf support
* replace bfloat16 module with tensorflow
* limit urllib3 version
* remove cpu only tensorflow
* set jsons from numpy array
* fix build for arm ubuntu
* attempt
* attempt
* test
* attempt
* attempt
* another attempt
* implement bfloat16 myself
* revert installation scripts
* simplify create_np_array_typed
* extend comment
> [2.10] Support BF16 and FP16 - [MOD-6765, MOD-6776]

- tests/pytests/test_tags.py
Workaround for bug MOD-6886
Status: Flaky test  in https://github.com/RediSearch/RediSearch/pull/4433
Change: Create index before HSET
1. #...
2. MOD...
1. ...
2. ...
> MOD-6886: Workaround - create INDEX before HSET

- .github/workflows/task-backport_pr.yml
Update the action's tag version to `v3`.
In [this update](https://github.com/korthout/backport-action/releases/tag/v3.0.0), the experimental CP detection method was introduced as a stable feature and will now detect the merging method **by default**. This means that from now on, we will CP the squashed commit instead of all the commits of the PR. This should help us avoid conflicts with intermediate changes and will make the process of fixing conflicts faster (only against the final changes)
> Improve backport flow

- coord/src/info_command.c
- tests/pytests/common.py
- tests/pytests/test.py
- tests/pytests/test_resp3.py
- Running FT.INFO in an RSCoordinator environment
- The fields stopwords_list, total_indexing_time, total_ms_run, total_cycles, average_cycle_time_ms, last_run_time_ms, gc_numeric_trees_missed, and gc_blocks_denied were not shown in the output.
3. What is the change
The mentioned fields will now be collected and reduced by RSCoordinator and should be shown when the user runs FT.INFO.
5. Adding the outcome (changed state)
When the FT.INFO command is used in an environment which uses the RSCoordinator the mentioned fields should be printed out with aggregated values.
1. MOD-6920
1. …
> MOD-6920: add missing ft.info fields when used inside of a cluster

- coord/src/info_command.c
- tests/pytests/common.py
- tests/pytests/test.py
- tests/pytests/test_geo.py
- tests/pytests/test_issues.py
- tests/pytests/test_json.py
- tests/pytests/test_vecsim.py
Manual backport of https://github.com/RediSearch/RediSearch/pull/4679 to 2.6.
> [2.6] MOD-6920: add missing ft.info fields when used inside of a cluster #4686 #4687

- coord/src/info_command.c
Fix the ft.info field ordering
1. The ordering of ft.info field index options was after index definition
2. Change: moving index options to be before index definition
3. index options should now be before index definition
1. [MOD-7021](https://redislabs.atlassian.net/browse/MOD-7021)
1. Coordinator aggregation of ft.info fields
[MOD-7021]: https://redislabs.atlassian.net/browse/MOD-7021?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix ft.info ordering in the coordinator environment

- src/geometry/rtree.cpp
- src/geometry/rtree.hpp
- tests/pytests/test_geometry_flat.py
- tests/pytests/test_geometry_sphere.py
This PR addresses DISJOINT queries on GEOSHAPE indices.
1. The current state does not properly account for disjointedness of polygons whose MBRs are not disjoint. In effect this means that the *only* thing being checked was disjointedness of MBRs, because if MBRs are disjoint, then the undelying polygons must necessarily be as well.
2. The change is to apply a union of predicates (p1 || p2) instead of an intersection (p1 && p2).
3. This PR enables us to correctly identify disjoint polygons whose MBRs intersect
1. [Issue 4664](https://github.com/RediSearch/RediSearch/issues/4664)
2. [MOD-7126](https://redislabs.atlassian.net/browse/MOD-7126)
1. RTree
[MOD-7126]: …
> MOD-7126: Fix GEOSHAPE DISJOINT for intersecting MBRs

- coord/src/info_command.c
Manual backport of https://github.com/RediSearch/RediSearch/pull/4689 to 2.6.
>  [2.6] MOD-7021: Fix ft.info ordering in the coordinator environment

- tests/cpptests/test_cpp_thpool.cpp
small fix to https://github.com/RediSearch/RediSearch/pull/4446:
in test_cpp_thpool:TestPauseResume
Update the current jobs in progress used in the while condition to verify the job is pulled
> fix: update while loop condition

- deps/thpool/thpool.c
- tests/cpptests/test_cpp_thpool.cpp
Introduce a ticketing mechanism to the thread pool to correctly ensure we have enough threads performing as privileged when choosing a queue to pull a job from.
3 threads, 1 should be privileged, infinite jobs (both high and low priority)
1. All the threads are working (many jobs to execute)
2. A thread finishes his current job and is about to pull another one
3. Since `num_jobs_in_progress` is higher than the number of expected privilege threads (2 > 1), the thread behaves as if it is not privileged
4. This will repeat for all the threads. None of the threads behave as privileged!
1. All the threads are working (many jobs to execute)
2. A thread finishes his current job and is about to pull another one
3. If one of the other threads is privileged, it will behave as unprivileged and take …
> Fix privileged mechanism - [MOD-6838]

- src/notifications.c
- src/spec.c
- src/spec.h
Removing an old log message and some other minor cleanup.
On `2.6` we still support redis versions with no loading events, so we cannot CP this PR to it. 
#4707 only changes the logging level
1. #4704
> Removing an old warning-level log message - [MOD-7181]

- src/result_processor.c
Fixing sorting by multiple keys, when the two rows are missing the primary(s) key(s) but hold a value for secondary(s).
Consider the case where `doc1 = {docID = 1, n = 93}`, `doc2 = {docID = 2, n = 46}`.
We want to sort by a `missing` field as the primary sort, and by `n` as a secondary.
``` ... SORTBY 2 @missing @n ... ```
Since both are missing a value for `missing`, we should treat them as equals and continue to compare them according to the secondary `n` key. We get that `doc2` is the first and `doc1` is the second (`doc1.n > doc2.n`)
Before the fix, we would see that they both are missing `missing` and we will immediately fall back to comparing them by docID (our last resort). In this case we get that `doc1` is the first and `doc2` is the …
> Fix sorting multiple fields

- .github/workflows/event-release.yml
Fix GH action for release to subscribe to published releases (release and pre-release) https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#available-events
> subscribed to publish instead of released

- src/spec.c
- tests/pytests/test_missing.py
We throw an error in the case a field is defined with the `NOINDEX` and `INDEXMISSING` options in the index creation. This is because this combination doesn't make sense, since the missing values won't contribute to the results of the search queries.
> MOD-7203: Throw error upon NOINDEX and INDEXMISSING options for field creation

- src/toksep.h
- tests/cpptests/test_cpp_tokenizer.cpp
- tests/pytests/test_issues.py
Backport of #4733 to `2.8`.
(cherry picked from commit e3222df87c33acf7c80cb52968f70c1960ae880b)
> [2.8] MOD-7240: Detect escape state when tokenizing (#4733)

- src/aggregate/group_by.c
- tests/pytests/test_aggregate.py
Cleanup for the group extraction recursion, so it easier to follow whats going on
> Groupby recursion cleanup - [MOD-7245]

- src/aggregate/reducers/minmax.c
- tests/pytests/test_issues.py
The initial value for the `MAX` reducer was `DBL_MIN`, which is the smallest positive value a `double` can hold.
If all the values of the reducer process are negative, it won't replace the initial value and return `DBL_MIN` instead of an actual value from the index
> Fix MAX reducer for negative values [MOD-7252]

- src/config.c
- src/debug_commands.c
- src/util/workers.c
- src/util/workers.h
- tests/pytests/common.py
- tests/pytests/test_debug_commands.py
- tests/pytests/test_multithread.py
This PR introduces the ability to adjust the `WORKER_THREADS` configuration dynamically. Any changes to `WORKER_THREADS` will actively add or remove running threads, if they exist.
Specifically, setting `WORKER_THREADS` to **0** will change the state of the threads to `TERMINATE_WHEN_EMPTY`. This means that the threads will continue to execute any remaining jobs in the queue and then terminate. New jobs will be executed by the main thread.
> [MOD-6578] Dynamic Adjustment of Worker Threads

- src/aggregate/expr/expression.c
- tests/pytests/test_aggregate.py
- tests/pytests/test_missing.py
- tests/pytests/test_search_params.py
1. The current state briefly 
When a value for a property in the query is missing we output a generic error
Output a more human readable error with the property name and a suggestion to consider using EXISTS to filter out fields without the value
Add tests to check the behavior of ismissing with exists.
A more human readable error message
1. https://redislabs.atlassian.net/browse/MOD-7201
1. error message for missing property value
> MOD-7201: Improve error message for missing property value

- coord/src/dist_aggregate.c
- src/aggregate/group_by.c
- src/aggregate/reducer.h
- src/aggregate/reducers/count_distinct.c
- src/aggregate/reducers/deviation.c
- src/aggregate/reducers/first_value.c
- src/aggregate/reducers/minmax.c
- src/aggregate/reducers/random_sample.c
- src/aggregate/reducers/sum.c
- src/aggregate/reducers/to_list.c
- src/value.c
- src/value.h
- tests/cpptests/test_cpp_rlookup.cpp
General code cleanup for the `GROUPBY` reducers.
- `group_by.c` - since 2.8, we validate correctly that each reducer has a unique destination key, so we don't need to override `writeGroupValues` after every reducer.
- `first_value.c` - use `RS_NullVal` (today's convention) instead of `RS_StaticNull`.
- `minmax.c` - split `min` and `max` callbacks.
- `to_list.c` - replace triemap with a dictionary.
> Cleaning reducers - [MOD-7251]

- src/aggregate/expr/expression.c
- tests/pytests/test_aggregate.py
- tests/pytests/test_missing.py
Manual backport of https://github.com/RediSearch/RediSearch/pull/4740 to 2.8.
> [2.8] MOD-7201: Improve error message for missing property value

- src/aggregate/expr/expression.c
- tests/pytests/test_aggregate.py
- tests/pytests/test_missing.py
Manual backport of https://github.com/RediSearch/RediSearch/pull/4740 to 2.6.
> [2.6] MOD-7201: Improve error message for missing property value

- .github/workflows/flow-build-artifacts.yml
Set fail-fast to false as we have on other matrixes, so we don't get `cancelled` conclusion
> Fix fail fast on snapshot build workflow

- coord/src/rmr/rmr.c
- src/aggregate/aggregate_exec.c
- src/aggregate/expr/expression.c
- src/debug_commands.c
- src/index.c
- src/info/field_spec_info.c
- src/info/index_error.c
- src/info_command.c
- src/module.c
- src/module.h
- src/profile.c
- src/reply.c
- src/reply.h
- src/reply_macros.h
- tests/pytests/common.py
- tests/pytests/test_issues.py
We currently abuse the simple string reply type and reply with many strings in all kinds of cases as simple strings instead of bulk strings (using `RedisModule_ReplyWithCString` or `RedisModule_ReplyWithStringBuffer`).
Since it is considered a breaking change to fix the reply type, In this PR we add validation that the replied strings don't contain illegal characters for simple strings and escape them if they do.
> Fix crucial simple string misuse - [MOD-7258]

- src/geo_index.c
- src/index.c
- src/index.h
- src/numeric_index.c
- src/query.c
- src/rs_geo.c
- tests/cpptests/benchmark_vecsim_hybrid_queries.cpp
- tests/cpptests/test_cpp_index.cpp
- tests/pytests/test_empty.py
Extends the empty string indexing & querying support for `TEXT` fuzzy searching.
> MOD-7241: Support empty string in fuzzy search

- coord/src/config.c
- src/aggregate/aggregate.h
- src/config.c
- src/config.h
- src/debug_commands.c
- src/module-init/module-init.c
- src/notifications.c
- src/spec.c
- src/util/workers.c
- src/util/workers.h
- tests/pytests/common.py
- tests/pytests/test.py
- tests/pytests/test_async.py
- tests/pytests/test_config.py
- tests/pytests/test_coordinator.py
- tests/pytests/test_cursors.py
- tests/pytests/test_debug_commands.py
- tests/pytests/test_multithread.py
- tests/pytests/test_rdb_compatibility.py
- tests/pytests/test_short_read.py
- tests/pytests/test_vecsim.py
In this PR, we deprecate the previous configurations `WORKER_THREADS` and `MT_MODE`, and introduce the new dynamic configurations `WORKERS` and `MIN_OPERATION_WORKERS`.
- `WORKERS` is the number of threads to use most of the time
- `MIN_OPERATION_WORKERS` is a lower limit for the number of threads while a server operation is underway. If this value is higher than `WORKERS`, additional threads will be allocated to reach this limit until the operation ends, then the number of threads will be reverted to `WORKERS`.
- `MT_MODE_OFF` => `WORKERS 0 MIN_OPERATION_WORKERS 0`
- `MT_MODE_FULL WORKER_THREADS <n>` => `WORKERS <n> MIN_OPERATION_WORKERS 0`
- `MT_MODE_ONLY_ON_OPERATIONS WORKER_THREADS <n>` => `WORKERS 0 MIN_OPERATION_WORKERS <n>`
New logic …
> Workers new configs - [MOD-7216]

- src/aggregate/aggregate_exec.c
- src/result_processor.c
- src/result_processor.h
- tests/pytests/test_expire.py
- tests/pytests/test_replicate.py
This **BREAKING** PR standardizes the reply when a document expires during a query. **It reverts the behavior change introduced in 2.8 to align with 2.6**. Previously, if the loader failed to open a key (indicating that the key expired after the query command was fired), the reply might contain **partial values** of this document, depending on whether it contains `SORTABLE` fields.
In this PR, a failure to load a key from the Redis keyspace marks the `SearchResult` as expired, ensuring that the only value of the document in the reply is NULL.
This standardization also fixes a bug in queries where RLOOKUP construction is lazy, such as '*' queries. The bug caused the content of an expired key to depend on the order of results. When serializing a result of an expired document, we would try …
> [MOD-7010] Return None when key epires during query

- src/aggregate/aggregate_exec.c
- src/result_processor.c
- src/result_processor.h
- tests/pytests/test_expire.py
- tests/pytests/test_replicate.py
backport #4777 
[MOD-7010] Return None when key epires during query 
[MOD-7010]: https://redislabs.atlassian.net/browse/MOD-7010?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [2.10 MOD-7010] Return None when key epires during query 

- src/query_parser/v2/lexer.c
- src/query_parser/v2/lexer.rl
Remove `printf` used in lexer during debug.
1. #...
2. MOD...
1. ...
2. ...
> Remove lexer debug printf

- src/result_processor.c
- tests/pytests/test_expire.py
In some pipelines, we can re-use the search result by clearing it before populating it with a new result.
If not cleared appropriately, it might affect subsequent results.
This change ensures the flag indicating expiration is cleared and the search result struct is ready to be re-used.
> Clear flags of SearchResult

- src/result_processor.c
- tests/pytests/test_expire.py
Backport of https://github.com/RediSearch/RediSearch/pull/4823 to `2.8.`
> [2.8] Clear flags of SearchResult

- .github/workflows/task-build-artifacts.yml
- .github/workflows/task-test.yml
A better node16/20 protection is needed (even if only temporarily)
some envs that require node16 still attempted to use node20.
see https://github.com/actions/checkout/issues/1809
and https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
> GHA better node16/20 handle

- .install/rocky_linux_8.sh
- .install/ubuntu_22.04.sh
Install gcc12.3+ on supporting OS to enable building with `AVX512_FP16` optimization in vecsim.
> [MOD-7341] Upgrade gcc

- coord/src/dist_aggregate.c
- src/aggregate/aggregate.h
- src/aggregate/aggregate_request.c
- src/result_processor.c
- src/result_processor.h
- src/rlookup.h
- src/search_options.h
- tests/pytests/test_scorers.py
Introduce the new `ADDSCORES` query attribute that causes the scorer to yield the score as an RLookupKey named `__score`, so it is returned as any other attribute of the row, and available for the rest of the pipeline. `ADDSCORES` is only available with `FT.AGGREGATE`
1. Replaces #4826
1. Introduce the `ADDSCORES` attribute that causes the scorer to yield the score under an RLookupKey name (named `__score`)
> Expose scores to pipeline - [MOD-7190]

- .github/workflows/task-get-linux-configurations.yml
- .install/rocky_linux_8.sh
Support rhel8 arm64.
Tests: https://github.com/RediSearch/RediSearch/actions/runs/9975702094
Which issues this PR fixes
1. MOD-7422
Main objects this PR modified
1. Github workflows
> MOD-7422: Support rhel8 arm64

- tests/pytests/common.py
- tests/pytests/includes.py
- tests/pytests/test.py
- tests/pytests/test_debug_commands.py
- tests/pytests/test_empty.py
- tests/pytests/test_expire.py
- tests/pytests/test_followhashes.py
- tests/pytests/test_geometry_flat.py
- tests/pytests/test_geometry_sphere.py
- tests/pytests/test_index_error.py
- tests/pytests/test_issues.py
- tests/pytests/test_json.py
- tests/pytests/test_json_multi_geo.py
- tests/pytests/test_json_multi_numeric.py
- tests/pytests/test_json_multi_tag.py
- tests/pytests/test_json_multi_text.py
- tests/pytests/test_language.py
- tests/pytests/test_missing.py
- tests/pytests/test_resp3.py
- tests/pytests/test_stemmer.py
- tests/pytests/test_vecsim.py
This PR adds the ability to `skip` JSON tests when no JSON module is found
MOD-7459
1. Added `NOJSON` option for `skip` decorator on pytest
2. Added this skip option on all JSON pytests
> MOD-7459 skip json tests when no json module is found

- coord/src/dist_aggregate.c
- tests/pytests/test_issues.py
`VERBATIM` ([documented to work](https://redis.io/docs/latest/commands/ft.aggregate/) with `FT.AGGREGATE`) is not passed to the shards when using cluster mode.
1. #4893
> VERBATIM is not passed to the shards on FT.AGGREGATE - [MOD-7463]

- tests/pytests/test.py
Fix test flakiness by rerunning the `CLUSTERSET` command every iteration (now 20) instead of just waiting for the topology for 10 seconds.
Flakiness happens when the "fake" `CLUSTERSET` is sent right before the every 1-sec cron `CLUSTERREFRESH` call and immediately overrides by it, making the 10-sec timeout wait for a result that is not going to come.
> Fix flakiness in test:test_cluster_set - [MOD-7228]

- src/query.c
- src/query_param.c
- src/query_param.h
- src/query_parser/v2/parser.c
- src/query_parser/v2/parser.y
- tests/pytests/test_dialect.py
- tests/pytests/test_fuzzy.py
- tests/pytests/test_search_params.py
- tests/pytests/test_synonyms.py
Backport of #4636 to 2.8.
Differences from master:
1. `test_dialect:test_v1_vs_v2` that were using `FT.EXPLAINCLI` were modified to use `FT.EXPLAIN`
2. `test_fuzzy:testFuzzyWithNumbersOnly` does not use `set_max_dialect()` because it is not part of `common.py` in 2.8, then the test uses a fixed value `MAX_DIALECT=4`
1. MOD-7025
> [2.8] MOD-7025: Avoid expansion/stemming from numeric values

- src/query_parser/v1/parser.c
- src/query_parser/v1/parser.y
- src/query_parser/v2/parser.c
- src/query_parser/v2/parser.y
- tests/pytests/test_issues.py
- tests/pytests/test_parser.py
If a union (`OR`) of words starts with multiple stopwords (at least 2), we set the union to `NULL` but later fail to validate if it is valid or not.
> Fix union of stopwords - [MOD-7495]

- src/config.c
- src/config.h
- src/module-init/module-init.c
- tests/pytests/test_config.py
A follow-up of #4741.
Instead of removing the effect of the deprecated configurations, we now consolidate with them if the new configurations were not used.
This will allow loading the module with the old configurations, having the values of the new configurations set accordingly, and later be modified with the new configurations only.
> Support the deprecated MT configs again - [MOD-7519]

- src/spec.c
Fixes a bug we had in our field statistics counting, in which we count fields as added to the index even when we already had the index when uploaded from rdb (relevant for replica-of as well), and thus practically did nothing, and ended up with a false field count.
Will be tested with RE cluster separately, yet tested locally and fixes the problem.
> MOD-7339: Fix field statistics counting bug

- src/index.c
- tests/pytests/test_profile.py
Removes a redundant inner warning about passing the `MAXPREFIXEXPANSIONS` config param.
It's both redundant since we already report it elsewhere in the response, and not 100% accurate, since it will be raised even when the amount of expansions is exactly equal to the value of the config param, such that we actually did not prevent further expansions.
It is important to note that this warning appeared in the response only when it existed, i.e., when the warning was not thrown, it did not appear in the response. This eases up the breakage a bit, but it is still breaking.
> MOD-7614: Remove redundant `MAXPREFIXEXPANSIONS` warning

- src/index.c
- tests/pytests/test_issues.py
Fixing a crash caused by a wrong cast of iterators when in PROFILE mode
1. `UI_Foreach`
> Fix numeric union reopen on profile [MOD-7454]

- src/query.c
> [2.8] MOD-7616: Small completion for TAG wildcard fix

- .github/workflows/event-merge-to-queue.yml
- .github/workflows/event-nightly.yml
- .github/workflows/event-pull_request.yml
- .github/workflows/event-release.yml
- .github/workflows/task-build-artifacts.yml
Support using AWS roles when uploading artifacts to AWS.
1. We use AWS access keys to authenticate against AWS
2. Conditionally authenticate using AWS role
3. Upload to AWS either by using AWS access key or AWS role.
1. CI
> Conditionally Use AWS Role To Upload Artifacts

- src/coord/rmr/rmr.c
- src/coord/rmr/rq.c
- src/coord/rmr/rq.h
When changing the conn-pool size, we should also change the RQ `maxPending` limit accordingly
> Change maxPending requests when changing the number of connections

- .github/workflows/benchmark-flow.yml
- .github/workflows/event-deploy-snapshots.yml
- .github/workflows/event-merge-to-queue.yml
- .github/workflows/event-mirror.yml
- .github/workflows/event-pull_request.yml
- .github/workflows/event-push-to-integ.yml
- .github/workflows/event-release.yml
- .github/workflows/flow-build-artifacts.yml
- .github/workflows/flow-coverage.yml
- .github/workflows/flow-self-hosted-arm.yml
- .github/workflows/self-hosted.yml.TEMPLATE
- .github/workflows/task-assign-for-issue.yml
- .github/workflows/task-backport_pr.yml
- .github/workflows/task-build-artifacts.yml
- .github/workflows/task-check-docs.yml
- .github/workflows/task-get-latest-tag.yml
- .github/workflows/task-get-linux-configurations.yml
- .github/workflows/task-release-drafter.yml
- .github/workflows/task-stale.yml
- .github/workflows/task-take-shift.yml
- .github/workflows/task-test.yml
- .github/workflows/task-website-deploy.yml
Decide which ubuntu runner to use based on a github variable
1. We always use `ubuntu-latest`
2. Use the runner from the `RUNS_ON_UBUNTU_LATEST` variable
3. Allow to choose which ubuntu latest runner without modifying our code
2. MOD-7695
1. Workflow Files
> MOD-7695: Decide Ubuntu Runner Using Variable

- .install/rocky_linux_8.sh
- .install/rocky_linux_9.sh
Adds the `--nobest` and `--skip-broken` relaxation flags to the Rocky platform installations.
> MOD-7737: Add relaxation flags to Rocky9 installations

- src/geometry/CMakeLists.txt
This PR adds the ability to fetch boost headers via cmake in case `BOOST_DIR` wasn't given or it does not exist.
This can allow users to avoid calling `install_boost.sh` if they do not wish to. There is a performance penalty on fetching boost via CMake
MOD-7646
CMakeLists.txt of geometry
> MOD-7646 cmake fetch boost if not exists

- src/config.h
- src/util/workers.c
- tests/pytests/test_config.py
- tests/pytests/test_multithread.py
- tests/pytests/test_vecsim.py
As a mitigation for the issue, set the default config to 0 to avoid opening and closing the threadpool for switching from async to in-place delete in vecsim upon operations.
> Change default operation workers to zero as a workaround [MOD-7732]

- src/rules.c
- src/rules.h
- src/spec.c
- tests/pytests/test_json.py
In case we fail to load a schema rule (for example, when a JSON index is loaded from the RDB but the JSON module is not available), return an error instead of asserting
> Fail to load a schema rule from RDB without asserting - [MOD-7587]

- src/ext/default.c
- src/fork_gc.c
- src/index.c
- src/index.h
- src/indexer.c
- src/info_command.c
- src/inverted_index.c
- src/inverted_index.h
- src/profile.c
- src/query.c
- src/redis_index.c
- src/redis_index.h
- src/result_processor.c
- src/rules.c
- src/rules.h
- src/spec.c
- src/spec.h
- tests/cpptests/test_cpp_index.cpp
- tests/cpptests/test_cpp_llapi.cpp
- tests/pytests/test_existing.py
- tests/pytests/test_followhashes.py
- tests/pytests/test_missing.py
- tests/pytests/test_not.py
- tests/pytests/test_rdb_compatibility.py
- tests/pytests/test_resp3.py
- tests/pytests/test_short_read.py
This PR aspires to fix the latency issue we have with our wildcard and NOT iterators, in which the doc-id increment is done one-by-one, resulting in a lot of time wasted on looking for un-existing documents.
The problem is encountered when there are many writes and deletions, such that there are big "holes" in the docIds of the existing docs in the database. This caused us to waste time incrementing the docIds and checking whether their corresponding documents exist.
We opt to fix this by adding an "existing-docs" inverted-index, holding the doc-ids of all the currently existing docs (up to GC update), which the wildcard and NOT iterators can utilize to efficiently jump between large doc-id deltas instead of the single-increment jumps used …
> MOD-7253: Fix wildcard latency

- .github/workflows/event-pull_request.yml
- tests/pytests/test_short_read.py
1. Nightly fails with redis unstable in test_short_read
2. Adding a wait for replica to be up before sending commands (`PING` could return `LOADING`)
3. Related to [this](https://github.com/redis/redis/pull/13495) change in redis 
1. MOD-7740
> MOD-7740: Fix test_short_read to wait for replica to be up

- src/fork_gc.c
Cherry-picks a small fix done in #4869 (the PR is not cherry-picked to 2.10) regarding the memory report of the "missing" index
> CP missing indexing memory reporting fix

- src/indexer.c
- src/redisearch_api.c
- src/redisearch_api.h
- src/rules.h
- tests/cpptests/test_cpp_llapi.cpp
Adds a unit-test for the existing-indexing feature that was introduced in #4869, mainly verifying the memory addition relative to the existing scenario without this feature enabled.
Also contains a small fix that is relevant for our unit-tests.
> MOD-7748: Add existing-indexing unit-test

- tests/cpptests/redismock/redismock.cpp
Add minimal mock support for HPEXPIRETIME
1. We get an error in our cpp tests about HPEXPIRETIME error
2. Add HPEXPIRETIME mock support
3. Getting rid of the error in our tests
2. MOD-7863
1. Tests
[MOD-7863]: https://redislabs.atlassian.net/browse/MOD-7863?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOD-7863: Add HPEXPIRETIME Mock Support

- tests/pytests/requirements.txt
Constrain redis python package version to 5.0.8 to avoid resp3 test breakage introduced in 5.1 release.
1. Tests are failing due to resp3 changes
2. Pin the redis package to an older version
3. Tests will pass
1. MOD-7912
1. requirements.txt
> MOD-7912: Constrain Redis Python Package

- .github/workflows/event-pull_request.yml
- .github/workflows/flow-temp.yml
- tests/pytests/runtests.sh
- tests/pytests/test_acl.py
This PR fixes 2 unrelated bugs:
Before this PR, we were linking `stdlib++` **statically**.
[This pr](https://github.com/redis/redis/pull/11884) links **dynamically** redis to `stdlib++`.
This change led to a crash in our geometry library, utilizing c++ boost library.
To fix that, we changed the linker flags in `readies` to align with `redis` and link to `stdlib++` **dynamically** as well.
Since we are pointing to a branch in `readies` that is detached from its `master` branch, this change **won't affect other modules that point to `readies` `master` branch.**
Skip `test_acl_search_commands` when redis version is less than 7.9, since redis dId not create the search acl category with search commands before 8.0 milestones.
> [MOD-7897, MOD-7936]  link dynamically to stdc++, fix ACL test

- .github/workflows/flow-build-artifacts.yml
- .github/workflows/flow-macos.yml
MacOS 12 is no longer maintained, moving to support versions >= 13 for CE
> build with macos-13

- tests/cpptests/redismock/redismock.cpp
Manual backport of https://github.com/RediSearch/RediSearch/pull/5025 to 8.0.
> [8.0] MOD-7863: Add HPEXPIRETIME Mock Support

- src/aggregate/aggregate_request.c
- tests/pytests/test_issues.py
- tests/pytests/test_json.py
1. Current state:
HIGHLIGHT/SUMMARIZE is not supported on JSON index, it works on some cases it but could fail.
The limitation is documented [here](https://redis.io/docs/latest/develop/interact/search-and-query/indexing/#limitations)
In case of use HIGHLIGHT/SUMMARIZE on a JSON index an error will be returned.
```sh
127.0.0.1:6379> FT.CREATE idx on json schema $.name AS name TEXT
OK
127.0.0.1:6379> FT.SEARCH idx 'john' summarize
(error) HIGHLIGHT/SUMMARIZE is not supported with JSON indexes
127.0.0.1:6379> FT.SEARCH idx * HIGHLIGHT
(error) HIGHLIGHT/SUMMARIZE is not supported with JSON indexes
```
1. MOD-7551
**Main objects …
> MOD-7551: Return error on json limitations

- .github/workflows/task-backport_pr.yml
Use github app token for backporting workflow.
1. If PR has workflow changes then the current token doesn't have enough permissions to create the PR.
2. Move to using a github app token
3. Less failures during backporting
1. MOD-7932
1. ...
2. ...
> MOD-7932: Use Github App Token For Backporting

- .install/amazon_linux_2.sh
- tests/pytests/common.py
- tests/pytests/requirements.txt
- tests/pytests/test_issues.py
- tests/pytests/test_resp3.py
* Unpin redis requirements.txt version
* Fix resp3 tests breakage
1. redis python version 5.1.0 made breaking changes, at first we pinned the version
now we want to solve the breakage for master and 8.0.
3. Unpin the version for redis in requirements.txt and fix the tests breakage.
4. Tests will pass with redis 5.1.0 package
1. MOD-7926
1. Tests
> MOD-7926: Fix Redis Package Tests 

- src/query.c
- src/spec.c
- tests/pytests/test_vecsim.py
1. Postponed the field name validation after registering the score field name, to avoid a misleading error message when the field name is not a vector field.
2. Improve error messages when failing to create a new vector field.
> Improve Error Message on VecSim Syntax Error - [MOD-7887]

- .github/workflows/task-backport_pr.yml
* check author association instead of user id to generalize the logic, bots should have author association should be NONE
1. We moved to using github apps that have a different user id than the hard coded value of the github bot
2. Rely on the comment author association to check if we should trigger the workflow
3. Better safeguard against unwanted triggering of the workflow
1. MOD-7965
1. Backport Workflow
> MOD-7965: Check Comment Author Association To Filter Github Apps From Triggering Workflow

- tests/pytests/test_multithread.py
After trying to deflake the test by removing the 30-second timeout for the forkGC in the test, we still see that the test hangs while the child fork process is not running, and we reach the hard test limit of 5 minutes. 
Hence, we avoid testing it with sanitizer since this environment seems to not fit this kind of test that relies on low priority process to run. 
> Skip test_multithread:test_async_updates_sanity with sanitizer 

- src/coord/debug_command_names.h
- src/coord/debug_commands.c
- src/coord/rmr/rq.c
- src/coord/rmr/rq.h
- tests/pytests/test.py
- tests/pytests/test_debug_commands.py
We removed an unnecessary assertion in the UV thread initialization that verifies the shard has topology information waiting before the first distributed command is sent.
The assertion is unnecessary because we have a mechanism that sets aside jobs until we can send them to all the relevant shards.
Note that still, no command will be sent until the topology is set.
> Remove an unnecessary assertion - [MOD-8008]

- src/info_command.h
- src/module-init/module-init.c
- src/redisearch_api.c
- tests/pytests/test_info_modules.py
Add new metrics for minimal and maximal index memory consumption.
We add both byte count and MB values for both the min and max metrics.
New metrics:
1. `search_min_memory_index`
2. `search_min_memory_index_human`
3. `search_max_memory_index`
4. `search_max_memory_index_human`
> Add metrics of min and max memory consumption of indexes - [MOD-7584]

- .github/workflows/flow-macos.yml
Addressing https://github.com/actions/runner-images/issues/10721
`macos-12` runners are deprecated. We move to build and pack our binaries with `macos-13`
> Update Macos runners to 13

- src/coord/dist_aggregate.c
- tests/pytests/test_scorers.py
Propagating the `SCORER` attribute to the shards on `FT.AGGREGATE` cluster mode
> Send `SCORER` to the shards with `FT.AGGREGATE` on cluster mode - [MOD-8060]

- src/global_stats.c
- src/global_stats.h
- src/info_command.h
- src/module-init/module-init.c
- src/redisearch_api.c
- src/spec.c
- src/spec.h
- tests/pytests/test_info_modules.py
Introducing new VecSim-related metrics to the info command under the existing `fields_statistics`: `fields_vector` dictionary sub-section
1. `used_memory` - total memory consumption of all vector indexes on the shard
2. `mark_deleted_vectors` - total number of marked deleted vectors on the shard
> Add VecSim related metrics - [MOD-7967]

- .github/workflows/task-test.yml
1. When the workflow fails it is hard to know which step failed
2. Print a summary of the tests so it will be easier to see which step failed
3. It will be easier to see which step failed
1. MOD-8010
1. Workflow
> MOD-8010: Print Step Summary In Workflow On Failure

- src/fork_gc.c
- src/indexer.c
- src/module.c
- src/rules.c
- src/spec.c
- src/vector_index.c
1. Use a valid RedisModuleCtx when logging
2. Generate a detached context with the module name instead of the default `<module>`
> Improve usage of RedisModuleCtx

- src/debug_commands.c
- src/document.c
- src/fork_gc.c
- src/geometry_index.c
- src/geometry_index.h
- src/indexer.c
- src/indexer.h
- src/info_command.c
- src/inverted_index.c
- src/module.c
- src/numeric_index.c
- src/numeric_index.h
- src/query.c
- src/redis_index.c
- src/redis_index.h
- src/spec.c
- src/spell_check.c
- src/tag_index.c
- src/tag_index.h
- tests/cpptests/test_cpp_forkgc.cpp
We are removing a redundant caching mechanism in `indexBulkFields` that is no longer in use and takes a long time to initialize.
The caching mechanism helped with field keys and inverted index caching. The first is no longer relevant, and the second only helps when we use bulk indexing (which we don’t do anymore).
The redundant caching mechanism requires a large memory initialization, which takes a large percentage of the indexing time for no reason.
This is a performance fix, the bug does not affect the correctness of any search
Removing the need for "formatted keys", stop using the spec's dictionary for fields, and store the relevant data in the field spec instead (today we usually extract the field data by first obtaining the field spec by its name, then getting the formatted redis …
> Performance improvement in indexBulkFields - [MOD-8093]

- src/config.h
- src/coord/config.c
- src/coord/config.h
- src/coord/rmr/conn.c
- src/coord/rmr/endpoint.c
- src/coord/rmr/endpoint.h
- src/coord/rmr/redis_cluster.c
- src/module.c
- tests/ctests/coord_tests/test_cluster.c
- tests/pytests/test_config.py
We add a new load-time configuration parameter `OSS_ACL_USERNAME`, which is the username with which the coordinator authenticates against the shard connections it holds.
This, together with the existing `OSS_GLOBAL_PASSWORD` will allow the user to configure an ACL user that will be able to execute RediSearch internal commands.
* Notice: Since we are talking about load-time config-params, once a user connects with a bad username\password, this will trigger an authentication loop in our uv-thread, that will end only when the config-params' values are set to the correct values, and the shards are reset (i.e., shutdown and started back). This is the current state we have with the existing password config-param as well. A change of that mechanism …
> MOD-8050 MOD-8052: Add ACL username config param

- src/debug_commands.c
- src/numeric_index.c
- src/numeric_index.h
- tests/pytests/test_numbers.py
Fixing 2 bugs in the numeric tree regarding the tree balancing
1. A miscalculation when rotating a subtree can cause the `maxDepth` value to become larger than both child subtrees, which can later yield sub-optimal tree balancing.
2. An assumption that when a leaf got split in the subtree, the `maxDepth` value has to grow by 1 (which is not true when the splitting leaf was not in the max depth), could cause the parent range to get released prematurely. (only when `_NUMERIC_RANGES_PARENTS` is set to `2`)
Starting with this fix, we will also start balancing the root node to achieve a better tree.
This is a performance fix. Both bugs don't affect the correctness of any search.
> Fix Numeric Tree Balance - [MOD-8081, MOD-8082]

- src/fork_gc.c
- src/global_stats.c
- src/global_stats.h
- src/module-init/module-init.c
- tests/cpptests/test_cpp_forkgc.cpp
- tests/pytests/test_info_modules.py
Add the total logically deleted documents (i.e., documents that were deleted and have not yet been handled by the GC) among all indexes to the global shard info report. 
> Add global marked deleted to stats [MOD-6053]

- src/document_basic.c
- tests/pytests/test_index_error.py
Backport of #5150 to 2.8.
backport changes: using `IndexError_AddError` instead of `FieldSpec_AddError` that was not backported
> [2.8] [MOD-8035] Add field index error for JSON field indexing failures

- tests/pytests/common.py
- tests/pytests/test_info_modules.py
This PR addresses an issue where passing an unsupported skip condition to the skip function results in the test being skipped without any alert or error. 
The introduced changes ensure that unsupported skip options cause the test to fail, thereby preventing silent skips.
> Remove kwargs from skip function

- tests/pytests/common.py
- tests/pytests/test_info_modules.py
- tests/pytests/test_rdb_compatibility.py
- tests/pytests/test_vecsim.py
- remove kwargs from skip function in pytest
(cherry picked from commit f20012dd6d47d517f246eb8e816a8df8d29f3e27)
see #5207
- fix unsupported skips (no_json)
- skip test when MT config is not on with noWorkers=True
> Fix and add skips in pytest

- tests/pytests/test_info_modules.py
The previous test relied on force invoking GC that does not call the `onTerm` callback of the GC once the index is removed (which is the purpose of the test). Instead, the marked deleted documents of the removed index were accounted for only if the index was removed after the GC run started (and they did not have the GC exited early).
Fix the test to use the periodic GC call instead of the force debug task, where it is freed as needed, and the marked deleted docs are accounted for anyway.
> Deflake marked deleted test

- CMakeLists.txt
- src/commands.h
- src/module.c
We were building the OSS build when `COORD=rlec`, getting the wrong artifact.
This PR fixes the setting of `RS_CLUSTER_ENTERPRISE` such that it is exposed correctly to the build.
> MOD-8102: Fix CMake setting of cluster build type

- src/debug_commands.c
- src/document.c
- src/fork_gc.c
- src/inverted_index.h
- src/numeric_index.c
- src/numeric_index.h
- src/redis_index.h
- src/redisearch_api.c
- src/spec.c
- src/spec.h
- tests/cpptests/benchmark_vecsim_hybrid_queries.cpp
- tests/cpptests/index_utils.cpp
- tests/cpptests/index_utils.h
- tests/cpptests/test_cpp_extensions.cpp
- tests/cpptests/test_cpp_forkgc.cpp
- tests/cpptests/test_cpp_index.cpp
- tests/cpptests/test_cpp_llapi.cpp
- tests/cpptests/test_cpp_query.cpp
- tests/cpptests/test_cpp_range.cpp
- tests/pytests/common.py
- tests/pytests/test.py
- tests/pytests/test_json_multi_geo.py
- tests/pytests/test_json_multi_numeric.py
- tests/pytests/test_stats.py
This PR fixes bugs in statistics updates during gc.
In the previous implementation, when the inverted index of a numeric range returned with no docs from the fork process, `range->invertedIndexSize` stat was set to 0.
This is wrong since an empty range consumes memory of inverted index metadata struct size + block struct size + initial block capacity size.
In this PR `range->invertedIndexSize` is decreased by `nbytesCollected` and increased by `nbytesAdded`.
In addition, once the gc parent finishes iterating all the nodes received from the fork, it starts cleaning empty nodes. 
`NumericRangeTree_TrimEmptyLeaves` returns the amount of memory released due to empty nodes removal.
This is where we update the stats of a completely removed range (inverted index).
before the fix: 
``` …
```
> MOD-8097, MOD-8114 Fix memory counting

- src/module.c
- src/module.h
- tests/pytests/test_acl.py
In this PR we introduce the new `_search_internal` ACL command category, to which we register all of our internal commands, i.e., all the `_FT.*` commands. We register these commands ONLY to this command category, such that only the coordinator will be eligible to execute them via the permissions given to its user-defined ACL user.
A correct configuration of the ACL permissions, in which all other users are disallowed to execute RediSearch internal commands by appending the `-@_search_internal` command category to their command permissions.
Notice: These commands change between our OSS and enterprise builds. On enterprise this command category should not be used.
> MOD-8062: Hide internal commands in new ACL category for RediSearch internal commands

- src/debug_commands.c
- src/document.c
- src/fork_gc.c
- src/inverted_index.h
- src/numeric_index.c
- src/numeric_index.h
- src/redis_index.h
- src/redisearch_api.c
- src/spec.c
- src/spec.h
- tests/cpptests/benchmark_vecsim_hybrid_queries.cpp
- tests/cpptests/index_utils.cpp
- tests/cpptests/index_utils.h
- tests/cpptests/test_cpp_extensions.cpp
- tests/cpptests/test_cpp_forkgc.cpp
- tests/cpptests/test_cpp_index.cpp
- tests/cpptests/test_cpp_llapi.cpp
- tests/cpptests/test_cpp_query.cpp
- tests/cpptests/test_cpp_range.cpp
- tests/pytests/common.py
- tests/pytests/test.py
- tests/pytests/test_json_multi_geo.py
- tests/pytests/test_json_multi_numeric.py
- tests/pytests/test_missing.py
- tests/pytests/test_stats.py
backport #5204
- skip changes from #4858 that weren't backported 
- no WithMissingInfo test in test_cpp_llapi
- https://github.com/RediSearch/RediSearch/pull/5008 contained, among other changes, a bug fix in FGC_parentHandleMissingDocs, where we update gc stats before counting the bytes collected by removing an empty index. However, **this pr was reverted in 2.10, including the bug fix.**
This backport re-includes this bug fix.
> [2.10] MOD-8097, MOD-8114 Fix memory counting (#5204)

- src/debug_commands.c
- src/document.c
- src/fork_gc.c
- src/inverted_index.h
- src/numeric_index.c
- src/numeric_index.h
- src/redis_index.h
- src/redisearch_api.c
- src/spec.c
- src/spec.h
- tests/cpptests/benchmark_vecsim_hybrid_queries.cpp
- tests/cpptests/index_utils.cpp
- tests/cpptests/index_utils.h
- tests/cpptests/test_cpp_extensions.cpp
- tests/cpptests/test_cpp_forkgc.cpp
- tests/cpptests/test_cpp_index.cpp
- tests/cpptests/test_cpp_llapi.cpp
- tests/cpptests/test_cpp_query.cpp
- tests/cpptests/test_cpp_range.cpp
- tests/pytests/common.py
- tests/pytests/test.py
- tests/pytests/test_json_multi_geo.py
- tests/pytests/test_json_multi_numeric.py
- tests/pytests/test_stats.py
backport #5204
- skip changes from #4858 that weren't backported 
- no WithMissingInfo test in test_cpp_llapi
- revert removing RedisModuleCtx from gc wrapper args in test_cpp_forkgc
> [2.8] MOD-8097, MOD-8114 Fix memory counting

- src/dictionary.c
- src/dictionary.h
- tests/pytests/test_spell_check.py
Deleting a spellcheck dictionary when it becomes empty.
1. The current state:
* Empty spellcheck dictionaries are not deleted, and they remains existing although they doesn't contains any term.
* `FT.DICTDEL` on an unexistent dictionary, creates an empty dictionary.  
* `FT.DICTDUMP` returns an error if the dictionary does not exist
2. What is the change.
* If the dictionary becomes empty, it is deleted.
* `FT.DICTDEL` does not create empty dictionaries
* `FT.DICTDUMP` returns an empty array if the dictionary does not exist.
```c
127.0.0.1:6379> FLUSHALL
OK
127.0.0.1:6379> FT.DICTDEL dict xx
(integer) 0
127.0.0.1:6379> FT.DICTDUMP dict
(empty array)
```
1. MOD-7915
**Main …
> MOD-7915: Delete empty spellcheck dictionaries

- src/debug_commands.c
- src/document.c
- src/fork_gc.c
- src/geometry_index.c
- src/geometry_index.h
- src/indexer.c
- src/info_command.c
- src/module.c
- src/query.c
- src/spec.c
- src/tag_index.c
- src/tag_index.h
- src/vector_index.c
- src/vector_index.h
- tests/cpptests/test_cpp_forkgc.cpp
- tests/cpptests/test_cpp_tagindex.cpp
- tests/pytests/common.py
- tests/pytests/test.py
- tests/pytests/test_common.py
- tests/pytests/test_debug_commands.py
- tests/pytests/test_index.py
- tests/pytests/test_json_multi_numeric.py
backport #5229 to 2.10
mainly conflicts with #5216
> [2.10] [MOD-8125] Create inverted index in write operations only

- src/tag_index.c
- tests/pytests/test_tags.py
Fixing a bug when we abort from the `TagReader_OnReopen` callback prematurely, causing an invalid read later when reading from an iterator that was not reopened properly.
> Fix Tag OnReopen Callback - [MOD-8011]

- Makefile
- sbin/build-redisjson
- sbin/get-redisjson
Fix `get-redisjson` to build the package only if it is not found locally.
If  RedisJson package is not available for download for the current OS/platform, the package is built locally, but the validation is wrong, the file is not found and it is always rebuilt locally.
Set $BINROOT variable, if it's empty and pass it to `build-redisjson` to generate `redisjson.so` file in the expected path.
`redisjson.so` is build locally only when it is not found locally.
1. #...
2. MOD...
1. ...
2. ...
> Fix get-redisjson

- .github/workflows/task-build-artifacts.yml
- .github/workflows/task-test.yml
Fixes the checkout of redis in workflows (patch for #5310)
Should be CP'd to 8.0 only, fixed on the other version branches separately (in the CP PRs for #5310).
> Fix redis checkout

- tests/cpptests/common.cpp
- tests/cpptests/index_utils.cpp
- tests/cpptests/test_cpp_forkgc.cpp
This PR fixes flaky class FGCTest cpp tests.
In these tests we create a spec and add documents, potentially causing the global `TotalIIBlocks` number (global counter of the inverted indexes blocks across the model) to increase.
This number is decreased upon spec deletion in `IndexSpec_FreeUnlinkedData`
`IndexSpec_FreeUnlinkedData` is sent to a background thread if `RSGlobalConfig.freeResourcesThread` is set to its default value - `true`. In this case tests might start running while the clean-up process of previous tests is still active in the background and we can't rely on the global counters to not include changes made in previous tests, such as `TotalIIBlocks` number.
To fics that, this PR sets `RSGlobalConfig.freeResourcesThread` to false in all cpp tests, i.e disables the free …
> [MOD-8115] Free spec resources in the main thread

- tests/cpptests/common.cpp
- tests/cpptests/index_utils.cpp
- tests/cpptests/test_cpp_forkgc.cpp
> [2.8][MOD-8115] Free spec resources in the main thread (#5324)

- .github/workflows/task-build-artifacts.yml
- .github/workflows/task-test.yml
Fixes the CI checkout mechanism of old platforms to use the correct ref, while before we have an un-set `env:REF` variable, with which we default to the `master` branch.
CP'd to `8.0`, `2.10` only, as the fix is incorporated in #5322 (2.8) and #5323 (2.6).
> MOD-8172: Fix CI checkout

- .github/workflows/event-merge-to-queue.yml
- .github/workflows/event-pull_request.yml
- src/debug_commands.c
- src/document_basic.c
- src/spec.c
- tests/pytests/test_expire.py
Use new expiration API to avoid regression issues with HFE support when expiration isn't being used
1. Before: Using `RM_Call` was expensive and as a result our indexing took a hit even when expiration isn't used
2. Change: Using a new redis API to avoid using RM_Call and efficently check if a hash key has any fields with expiration before collecting the expiration times.
3. Outcome: Faster indexing time, fixing the regression that was introduced with HFE PR.
1. HFE
> MOD-7976: Fix HFE Regression

- src/module.c
- tests/pytests/common.py
- tests/pytests/test.py
- tests/pytests/test_acl.py
- tests/pytests/test_async.py
- tests/pytests/test_cursors.py
- tests/pytests/test_issues.py
- tests/pytests/test_profile.py
- tests/pytests/test_spell_check.py
- tests/pytests/test_synonyms.py
In this PR we add the keys ACL validation to all of our command handlers.
Specifically, we validate that a user can only access an index if his ACL key permissions are a superset of the prefixes indexes by the index it wishes to access.
Notice: After this PR we cannot query an added shard on OSS that does not know the index, since it will now return an `no such index` as part of the ACL validation we now do in the coordinator. This is a very unwanted situation that should not happen (shard that is not aware of the indexes in the DB), and can cause wrong results to be returned to the user! After this PR, we at least know that we will not return wrong results, since we do not allow such a query to "fly" without all the shards of the cluster knowing about all the existing indexes.
> MOD-8053: Validate ACL key permissions for RediSearch commands

- .github/workflows/task-test.yml
Fixes the redis ref used in our `task-test.yml` flow.
CP'd only to `8.0` and `2.6`, added to `2.10` and `2.8` in #5333  and #5322 respectively.
> MOD-8172: Fix redis ref in CI

- src/buffer.c
- src/document.c
- src/tokenize.c
- src/tokenize.h
- src/tokenize_cn.c
- src/varint.c
Removing redundant calls to `strlen` that may slow text field indexing.
This PR doesn't have any new tests, as it doesn't introduce new logic. The fact that all the current tests pass is all the validation we need.
> Improve text indexing performance - [MOD-8249]

- src/info/indexes_info.c
- src/info/indexes_info.h
- tests/pytests/test_info_modules.py
Fix the following metrics calculations, to address background indexing:
1. total_active_writes
2. num_active_indexes_indexing
3. num_active_indexes
`total_active_writes` now counts the BG indexer thread as well.
`num_active_indexes_indexing` and `num_active_indexes` now count all indexes that currently index data **or waiting for a BG indexing process**
> Improve counting active writes - [MOD-8151]

- src/inverted_index.c
Fix the `IndexReader_SkipToBlock` logic to always set the current block as the first one containing a document with an ID greater or equal to the one we search for.
In some edge cases, we may have set the current block to the one before the next relevant block, causing an additional full block scan before we find the next relevant result.
This issue also causes an unexpected out-of-range case in the `seekRawDocIdsOnly` skipper, which assumes we are currently at the right block.
1. `IndexReader_SkipToBlock`
> Improve SkipToBlock logic - [MOD-8255]

- .github/workflows/event-nightly.yml
- .github/workflows/task-test.yml
- Makefile
SInce nightly should run against redis unstable, and we have sanitizer run, we need to be able to differentiate and use the appropriate `CC_STATIC_LIBSTDCXX` flag (in redis >= 8 this should be set to false). Hence, we add a hint to the makefile so that building sanitizer for running against unstable would not use `CC_STATIC_LIBSTDCXX` (as opposed to running against redis < 8 where it is needed)
> Let sanitizer run against redis unstable

- src/inverted_index.c
- tests/cpptests/test_cpp_index.cpp
- tests/pytests/runtests.sh
This PR fixes the raw doc ID seeker logic, by removing a previous workaround required by the bug fixed in #5350.
It also enables the raw doc id configuration in the coverage flow, for a more accurate coverage report. 
1. Raw doc ID seeker
2. Added unit test for Raw doc ID encoder, decoder, and seeker
> Improve "Raw doc id" encoding - [MOD-8255]

- src/module.c
Fixes a leak in which we don't free the RedisModule_String of the ACL `user_name` .
> MOD-8053: Fix leak

- src/index.c
- src/index.h
- src/inverted_index.c
- src/query.c
- tests/cpptests/test_cpp_index.cpp
- tests/pytests/test.py
- tests/pytests/test_existing.py
- tests/pytests/test_issues.py
- tests/pytests/test_scorers.py
This PR incorporates the existing-index optimization done in #4869 for the OPTIONAL iterator, which is activated by passing  the `INDEXALL` argument in the index creation command.
It replaces the doc-id incremental counter with an iterator over the existing documents at the time of creation of the iterator.
> MOD-8192: Optimize OPTIONAL iterator with existing-index

- .github/workflows/benchmark-runner.yml
This PR allows for more precise benchmark retriggers. By default it won't change the current flow. but if you specify the allowed_setup input it will only run that setup related flows and skip all others.
> Allow to specify the inputs.allowed_setup on benchmark workflow dispatch

- tests/pytests/common.py
- tests/pytests/test.py
- tests/pytests/test_aggregate.py
- tests/pytests/test_aof.py
- tests/pytests/test_cursors.py
- tests/pytests/test_dialect.py
- tests/pytests/test_ext.py
- tests/pytests/test_followhashes.py
- tests/pytests/test_fuzz.py
- tests/pytests/test_fuzzy.py
- tests/pytests/test_geo.py
- tests/pytests/test_issues.py
- tests/pytests/test_json.py
- tests/pytests/test_json_multi_geo.py
- tests/pytests/test_json_multi_numeric.py
- tests/pytests/test_json_multi_tag.py
- tests/pytests/test_json_multi_text.py
- tests/pytests/test_numbers.py
- tests/pytests/test_rof.py
- tests/pytests/test_scorers.py
- tests/pytests/test_short_read.py
- tests/pytests/test_sortby.py
- tests/pytests/test_stats.py
- tests/pytests/test_tags.py
- tests/pytests/test_vecsim.py
Refactor all existing Python test cases under tests/pytests/ to use f-strings for string formatting. Ensure all instances of older string formatting methods (e.g., % operator, str.format() ) are updated to use f-strings. This will enhance code readability.
The refactoring was done using flynt tests/pytests.
> MOD-8393: Refactor python test to use fstring

- .install/install_boost.sh
jfrog link is currently broken. We use the link from the official boost site instead.
> [MOD-8451] install boost from official site

- Makefile
We recently changed and moved to dynamic linking of libstdc++ to be compatible with redis 8. However, in old OSs (bionic) we get an old lib version as a result and fail. Hence we revert this and move back to link statically (this search version should not run against redis 8 anyway).
> Link static libstdcxx for old OS support

- commands.json
Deprecation notes regarding PAYLOAD were added to FT.SUGADD and FT.SUGGET.  This param was not deprecated with the FT.SUG* commands.  This PR removes those deprecation notes from command.json.
> MOD-8410: remove payload deprecation notes from FT.SUGADD and FT.SUGGET

- src/aggregate/aggregate_exec.c
- src/aggregate/aggregate_request.c
- src/buffer.c
- src/config.c
- src/config.h
- src/coord/dist_aggregate.c
- src/module.c
- src/varint.c
- src/vector_index.c
- src/vector_index.h
- tests/pytests/test_issues.py
- tests/pytests/test_vecsim.py
Sanitize user input in regard to query limits and k in knn queries.
1. Current: Any number value was allowed, could cause memory issues
2. Change: Set a maximum for certain inputs and prevent higher number values from being used.
3. Outcome: More correct program behaviour, memory wise.
1. Argument Parsing
> MOD-8486: Sanitize User Input

- src/debug_commands.c
- src/indexer.c
- src/spec.c
- src/vector_index.c
- tests/pytests/common.py
- tests/pytests/test_debug_commands.py
- tests/pytests/test_vecsim.py
Validation on vector index pointer accesses to prevent null pointer access. 
Solving 2 bugs:
1. Creating index with schema containing vector index field with invalid parameters, resulting in crash when Inserting and then updating a doc that's in the index but without a vector field.
2. Debug command vecsim_info crashes when the vector index was created with invalid parameters.
> MOD-7570: Valid safe vector index pointer access

- .github/workflows/event-release.yml
1. Fix permissions of the workflow, allowing it to generate a version bump PR (again)
2. Split validation and version bump PR, so if the latter fails, we can still release the snapshots successfully
3. Enable manual triggering of the release workflow
> Fix release flow

- src/ext/default.c
- src/query.c
- src/spec.c
- src/spec.h
- tests/pytests/test.py
- tests/pytests/test_dialect.py
- tests/pytests/test_parser.py
Manual backport of #4956 to `2.8`.
The function `IndexSpec_GetFieldByBit()` was backported from master, because it is used by the patch.
> [2.8] MOD-7634: Fix NOSTEM 

- src/config.c
- src/config.h
- src/coord/config.c
- src/coord/config.h
- src/coord/rmr/redis_cluster.c
- src/module-init/module-init.c
- src/module.c
- src/spec.c
- src/spec.h
- src/tokenize_cn.c
- tests/pytests/requirements.txt
- tests/pytests/test_config.py
Manual backport of #5129 to `8.0`.
(cherry picked from commit 5ca0699b306344f752fa0023b09bdc1b9162e6db)
> [8.0] MOD-7612: config params (#5129)

- src/ext/default.c
- src/query.c
- src/spec.c
- src/spec.h
- tests/pytests/test.py
- tests/pytests/test_dialect.py
- tests/pytests/test_parser.py
Manual backport of #4956 to `2.6`.
The function `IndexSpec_GetFieldByBit()` was backported from master, because it is used by the patch.
> [2.6] MOD-7634: Fix NOSTEM 

- .github/workflows/flow-coverage.yml
On ububntu24 lcov is running with version 2, in which our tests currently fail. This is a workaround until we fix
> Workaround for coverage, run on ubuntu22 until we fix it for 24 [MOD-8545]

- sbin/get-redisjson
Fix parameter passing from `get-redisjson` when calling `build-redisjson`
> Fix get-redisjson script

- src/module.c
- src/query_error.h
- tests/pytests/test.py
This pull request ensures FT.ALIASADD fails when adding an alias that matches an existing index name, preventing conflicts.
> MOD-8229: FT.ALIASADD does not fail when adding an alias that is an existing index name

- src/module.c
- src/query_error.h
- tests/pytests/test.py
This PR adds error handling for unknown options in the FT.DROP and FT.DROPINDEX commands. The logic for handling document deletion and retention remains the same.
> MOD-8240: FT.DROPINDEX does not fail with an illegal third argument. 

- src/index.c
- src/inverted_index.c
- src/inverted_index.h
- tests/cpptests/test_cpp_index.cpp
- tests/pytests/test_tags.py
This PR fixes to issues:
1. A bug in the raw-docId seeker used in the `IR_skipTo()` function, in which we did not update the `ir->lastId` field of the index reader.
2. A crash in the optimized NOT iterator, caused due to passing `NULL` in the `hit` argument of the `SkipTo` call.
Fixes MOD-8553 as well (for which #4677 was used for a workaround).
> MOD-8413 MOD-8553: Fix optimized NOT iterator

- src/fork_gc.c
- src/fork_gc.h
- tests/cpptests/redismock/redismock.cpp
1. Current: We don't know how much the copy on write optimization was successful during the run of the GC process.
2. Change: Use redis API to send heartbeats from the child which will report to the parent process about our copy on write state.
3. Outcome: Easier to prove or disprove situations where we run out of memory and copy on write is suspected.
1. GC
> MOD-7069: Send GC heartbeats to track copy on write behaviour

- src/aggregate/aggregate_request.c
- src/search_options.h
- tests/pytests/test_issues.py
Fix a bug when a query has multiple GEOFILTER filters. Instead of applying them all (like we do with the legacy numeric filters), we override the single filter pointer, causing a leak and also yielding wrong results.
This PR is parallel to #XXXX, and targeted to version 2.10 and prior.
> [2.10] Fix legacy geofilter leak - [MOD-8568]

- src/aggregate/aggregate_exec.c
- tests/pytests/common.py
- tests/pytests/test_common.py
- tests/pytests/test_profile.py
- Added unittests for utility functions in test_common.py
- Replaced env.assertContains() with env.assertTrue(recursive_contains(...)) due to unexpected behavior of assertContains when using contains ANY
- Minor change in qiter->isProfile boolean usage
> Fix test FT.PROFILE report GIL time

- src/aggregate/reducers/deviation.c
- src/aggregate/reducers/first_value.c
- src/aggregate/reducers/minmax.c
- src/aggregate/reducers/quantile.c
- src/aggregate/reducers/sum.c
- src/util/quantile.c
- tests/pytests/test_aggregate.py
Improve the default value of reducers (when all the values in the group are missing)
1. MOD-7786
2. MOD-7787
3. MOD-7789
4. MOD-7800
5. MOD-7802
1. Quantile
2. First Value
3. Min/Max
4. Sum/Average
5. Standard Deviation
> Improve reducers no-value behavior - [MOD-7786, MOD-7787, MOD-7789, MOD-7800, MOD-7802]

- src/aggregate/aggregate_request.c
- src/geo_index.c
- src/search_options.h
- tests/pytests/test_issues.py
Fix a bug when a query has multiple GEOFILTER filters. Instead of applying them all (like we do with the legacy numeric filters), we override the single filter pointer, causing a leak and also yielding wrong results.
This PR is parallel to #5516 and targeted to master and 8.0 branches.
> Fix legacy geofilter leak - [MOD-8568]

- src/inverted_index.c
- tests/cpptests/test_cpp_tagindex.cpp
1. Current: Seeking to the last doc id in the last block when the reader is already pointing at it can crash.
2. Change: Avoid advancing to the next block if the id we need is in the end of the current block.
3. Outcome: Avoid crashing in this edge case.
We revert part of the changes from MOD-8255, PR #5350 
1. Inverted index
> MOD-8561: Fix Inverted Index SeekTo Edge Case

- .github/workflows/task-get-latest-tag.yml
- src/module.c
- tests/pytests/test_config.py
1. Current:
CONFIG params aren't loaded for redis 8.0-m03
2. Change: 
Modify minimum redis version required to load CONFIG params
3. Outcome:
CONFIG params and their related tests are enabled for redis 8.0-m03
Since redis 8.0-m03 tag has not been released, it is not found by the CI.
- Build on Linux using redis [8.0-m03](https://github.com/RediSearch/RediSearch/actions/runs/12916112213)
- Tests using [redis-unstable](https://github.com/RediSearch/RediSearch/actions/runs/12917175737/job/36023022278?pr=5538) 
1. MOD-...
2. #...
1. ...
> Load config params for Redis 8.0-m03

- src/aggregate/aggregate_request.c
- tests/pytests/common.py
- tests/pytests/test_aggregate.py
Fixes the error message for `LOAD`, which may be quite confusing when this is received:
```
127.0.0.1:6379> FT.AGGREGATE idx "@title:Hulk" LOAD 3 @title @genre
(error) Bad arguments for LOAD: SUCCESS
```
> MOD-8601: Fix error message for LOAD

- tests/pytests/test_issues.py
Fix flakiness in the test `test_mod_8142`, caused due to timing with a redundant background index scan
> Fix flakiness in a test - [MOD-8611]

- pack/ramp-light.yml
- pack/ramp.yml
increase min redis pack version to 6.0.20, as it the lowest cluster version that support redis 6.0.7
1. MOD-...
2. #...
1. ...
> increase min redis pack version

- src/config.c
- src/config.h
- tests/pytests/test.py
- tests/pytests/test_aggregate.py
- tests/pytests/test_config.py
- tests/pytests/test_contains.py
- tests/pytests/test_coordinator.py
- tests/pytests/test_cursors.py
- tests/pytests/test_expire.py
- tests/pytests/test_issues.py
- tests/pytests/test_json.py
- tests/pytests/test_multithread.py
- tests/pytests/test_optimizer.py
- tests/pytests/test_profile.py
- tests/pytests/test_resp3.py
- tests/pytests/test_tags.py
- tests/pytests/test_wildcard.py
1. Current: Default value for the ON_TIMEOUT configuration is `TimeoutPolicy_Return`
2. Change: Change the default to be `TimeoutPolicy_Fail`
3. Outcome: Stricter default behaviour
1. Configuration
> MOD-7791: Change ON_TIMEOUT default value

- src/aggregate/aggregate_request.c
- src/coord/dist_aggregate.c
- src/geo_index.c
- src/geo_index.h
- src/module.c
- src/module.h
- src/numeric_filter.c
- src/numeric_filter.h
- src/query.c
- src/query.h
- src/query_node.h
- src/query_param.c
- src/query_param.h
- src/vector_index.c
- src/vector_index.h
- tests/pytests/test_empty.py
* Added check for empty numeric string before legacy SEARCH FILTER (only if dialect version is greater than 2).
* Added check for an empty string when evaluating pramas (only if dialect version is greater than 2).
1. An empty string param doesn't evaluate as 0.
> Fix Empty Numeric Value - [MOD-7244]

- .github/workflows/flow-coverage.yml
- .github/workflows/task-backport_pr.yml
- .github/workflows/task-get-latest-tag.yml
1. Automatically press the "Merge when ready" button for backported PRs
2. Bump codecov action version from `v3` to `v5`, and update parameter names
3. Use the GitHub token in the curl call when getting the latest releases of a repo, to significantly reduce the chance of passing the rate limit of the API usage (from 60 RPH to at least 1000), like [here](https://github.com/RediSearch/RediSearch/actions/runs/13033211468/job/36357164174).
see these for more info:
- https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28
- https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#example-2-calling-the-rest-api
- https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVer …
> CI Improvements

- src/fork_gc.c
- src/inverted_index.c
- tests/pytests/test_issues.py
Fix a bug in the GC, which should update the last ID of an inverted index when cleaning it, in case it was modified.
This last ID in the index is used in the inverted-index reader iterator to test if we can expect more results from this iterator quickly.
An edge case where the last id(s) were deleted and this value was not up-to-date could cause the index reader iterator to assume it has a block to skip to, while that's not the case, causing unsafe access to the end of the block array.
1. MOD-8673
2. #5517 
3. #5532
1. Add assertions to verify block index ranges
2. Fix the GC apply function
> Fix SkipTo edge case - [MOD-8561 MOD-8673]

- src/query_parser/v1/parser.c
- src/query_parser/v1/parser.y
- src/query_parser/v2/parser.c
- src/query_parser/v2/parser.y
Observe the following segment of the union step helper from the parser `v2`:
```c
if (B->type == QN_UNION && B->opts.fieldMask == RS_FIELDMASK_ALL) {
A = B;
child = C;
} else if (C->type == QN_UNION && C->opts.fieldMask == RS_FIELDMASK_ALL) {
A = C;
child = B;
} else {
A = NewUnionNode();
QueryNode_AddChild(A, B);
A->opts.fieldMask |= B->opts.fieldMask;
child = C;
}
// Handle child
QueryNode_AddChild(A, child);
A->opts.fieldMask |= child->opts.fieldMask;
QueryNode_SetFieldMask(A, A->opts.fieldMask);
```
1. Notice that in the first two cases, `A` is set to a union with its entire field mask turned on.
2. On the first line of the third case, we set `A` to a default union node, which has its field mask entirely turned on as well.
3. Therefore, any step of the form `A->opts.fieldMask |= ...` …
> Parser Performance Improvement - [MOD-8656]

- .github/workflows/event-merge-to-queue.yml
- .github/workflows/event-pull_request.yml
Modifies our pull-request and merge-queue CI flows to run against the redis `unstable` branch instead of the latest `8.0` tag.
> Run CI against redis unstable

- .github/workflows/flow-build-artifacts.yml
Fixes the redis version of the artifact deployment flow to unstable, since it has content we need for our build.
> MOD-8791: Fix redis version of artifact deployment to unstable

- src/module.c
- tests/pytests/test.py
Backport https://github.com/RediSearch/RediSearch/pull/5343 to 8.0
> [8.0] MOD-8240: FT.DROPINDEX does not fail with an illegal third argument

- src/query_parser/v2/parser.c
- src/query_parser/v2/parser.y
- tests/pytests/test_parser.py
Backport https://github.com/RediSearch/RediSearch/pull/5572 to 8.0
> [8.0] MOD-8178: Remove stopwords filtering from termlist parsing (#5572)

- src/module.c
Add a `return REDISMODULE_ERR` after failing the ACL check of the `FT.ALIASADD` command.
> ACL check fix

- src/coord/info_command.c
- tests/pytests/test_issues.py
Adding validation to the schema field-statistics array, so we fail if any of the shards have a different schema size from the rest.
The inconsistency may occur if the index is dropped and recreated, or altered with `FT.ALTER`, while executing the `FT.INFO` command, so some shards are aware of the schema changes and some still see the previous one
1. `FT.INFO` reply aggregation in cluster mode
> Fail `FT.INFO` if schema is inconsistent across shards - [MOD-7609]

- commands.json
Mark command `FT.CONFIG` as deprecated
3. Outcome: Should affect redis documentation generated from commands.json
1. MOD-7761
> MOD-7761: Mark command `FT.CONFIG` as deprecated

- commands.json
Let users know which command is replacing the deprecated command
1. MOD-7761
2. #5660
1. ...
> MOD-7761: Add `replaced_by` info for FT.CONFIG command

- .github/workflows/benchmark-flow.yml
- .github/workflows/event-deploy-snapshots.yml
- .github/workflows/event-merge-to-queue.yml
- .github/workflows/event-nightly.yml
- .github/workflows/event-pull_request.yml
- .github/workflows/event-push-to-integ.yml
- .github/workflows/event-release.yml
- .github/workflows/flow-build-artifacts.yml
- .github/workflows/flow-coverage.yml
- .github/workflows/flow-linux-platforms.yml
- .github/workflows/self-hosted.yml.TEMPLATE
- .github/workflows/task-assign-for-issue.yml
- .github/workflows/task-backport_pr.yml
- .github/workflows/task-build-artifacts.yml
- .github/workflows/task-check-docs.yml
- .github/workflows/task-get-latest-tag.yml
- .github/workflows/task-get-linux-configurations.yml
- .github/workflows/task-release-drafter.yml
- .github/workflows/task-spellcheck.yml
- .github/workflows/task-stale.yml
- .github/workflows/task-take-shift.yml
- .github/workflows/task-test.yml
- .github/workflows/task-website-deploy.yml
Allow CI to run for PRs whose origin is a forked repository without our repo variables
1. Current: No default value for repo variables - CI for PRs from forked repositories doesn't run
2. Change: Provide default values for the variables
3. Outcome: PRs from forked repos can run the CI.
1. Workflow files
> MOD-8917: Provide Default Values For Repo Variables

- .github/workflows/event-pull_request.yml
- .github/workflows/task-spellcheck.yml
* use the correct ref in the spellcheck flow so pull requests from forked repositories can still run the CI
1. Current: In pull requests from forked repositories the ref is not recognized when we try and checkout it in our repo
2. Change: use the sha from the github pull request event object which should be the ref we can checkout
3. Outcome: Spellcheck flow can pass for pull requests from forked repositories.
1. Spellcheck workflow
> MOD-8928: Change Spellcheck Checkout Ref

- .install/macos.sh
`.install/macos.sh` invokes `.install/install_boost.sh`, which relies on `wget` to download the boost archive.
`wget` may not be available on the host system if `.install/macos.sh` doesn't explicitly take care of installing it.
> fix(macOS): Install wget via brew in .install/macos.sh

- .install/install_boost.sh
`wget`, by default, won't overwrite an existing file. It'll append a number suffix to the target path, e.g. `${BOOST_NAME}.tar.gz.2`.
This breaks the installation process if a previous download was interrupted halfway (e.g. via CTRL+C) leaving behind an incomplete archive.
By passing the -O flag, we opt out of this behaviour: the downloaded file will be at the expected path, overwriting what's already there if necessary.
> fix(setup): Force wget to save the boost archive to the expected location

- src/ext/default.c
- tests/pytests/test_scorers.py
Backport https://github.com/RediSearch/RediSearch/pull/5670 to 2.6
In the original PR to master, some tests used BM25STD, which isn't available in this version, so I modified them to use BM25.
> [2.6] MOD-7896: Add weight factor to BM25 scoring calculation (#5670)

- .github/workflows/event-merge-to-queue.yml
- .github/workflows/event-nightly.yml
- .github/workflows/event-pull_request.yml
- .github/workflows/task-build-artifacts.yml
- .github/workflows/task-test.yml
A follow-up of #5726 - align snapshot setup to the changes introduced in the PR in `task-test.yml`, fix sanitizer parameters
- Fix snapshot build flow
https://github.com/RediSearch/RediSearch/actions/runs/13809413739
- Move sanitizer jobs to run directly on the runner (not in a container)
- Add an option to run coverage/sanitizer flows on draft PRs, by labeling the PR with `enforce:sanitize` or `enforce:coverage`
> Fix CI - snapshot build and nightly - [MOD-9036]

- deps/rmutil/rm_assert.h
- src/coord/dist_aggregate.c
- src/coord/rmr/rmr.c
- tests/pytests/test_coordinator.py
This PR fixes a race condition on `freeFlag` in the coordinator mechanism. 
The issue occurred because `freeFlag` was expected to be reset by the uv thread when the coordinator reached `MRIterator_Release` but since the flag is reset from the a BG thread, this was not always the case. 
This led to an incorrect sequence of operations, ultimately causing an assertion failure.
To resolve this, freeFlag has been **replaced with a reference counter**, which:
- **Increases** before pushing a new job to the RQ.
- **Decreases** when the coordinator no longer requires more replies.
- **Decreases** again when all shards have finished pushing replies to the channel.
* Added `RS_DEBUG_LOG_FMT` and `RS_DEBUG_LOG` macros for debug logging in `deps/rmutil/rm_assert.h`.
* when `ENABLE_ASSERT=1` it will …
> [MOD-9023] Replacing freeFlag with a reference counter

- tests/pytests/requirements.txt
Since deepdiff 8.4.0 the module requires pytz installation.
Use previous version to avoid redundant modules installations.
> Lock deepdiff module version

- .github/workflows/flow-coverage.yml
- .install/install_rust.sh
- .install/test_deps/common_installations.sh
- Makefile
- src/redisearch_rs/trie_rs/src/lib.rs
We add support for computing test coverage for Rust code, both locally and in CI. This is done via a new tool, [`cargo-llvm-cov`](https://github.com/taiki-e/cargo-llvm-cov).
The coverage file is located next to the coverage report for C code and uploaded alongside it to Codecov in CI. Codecov will merge the two reports for us on the server side.
There are no user-facing changes to the pre-existing `make` commands. 
`make coverage` will now transparently compute coverage for Rust code as well as C code. If you only wish to compute Rust coverage, you can do so via `make rust-tests COV=1`.
> MOD-8969: Compute test coverage for Rust code

- coord/src/coord_module.h
- coord/src/debug_command_names.h
- coord/src/debug_commands.c
- coord/src/dist_aggregate.c
- coord/src/module.c
- coord/src/rmr/chan.c
- coord/src/rmr/chan.h
- coord/src/rmr/rmr.c
- coord/src/rmr/rmr.h
- src/aggregate/aggregate.h
- src/aggregate/aggregate_debug.c
- src/aggregate/aggregate_debug.h
- src/aggregate/aggregate_exec.c
- src/debug_commands.c
- src/module.c
- src/module.h
- src/result_processor.c
- src/result_processor.h
- src/util/timeout.h
- tests/pytests/common.py
- tests/pytests/requirements.txt
- tests/pytests/test_cursors.py
- tests/pytests/test_debug_commands.py
- tests/pytests/test_resp3.py
- tests/pytests/test_timeout.py
backport https://github.com/RediSearch/RediSearch/pull/5554 to 2.10
In **master**, `src/module.c` combines both **coordinator** and **standalone** logic, allowing to implementation of the debug mechanism for both modes in this file. However, in **version 2.10**, we still maintain separate files for each module:  
- **Coordinator:** `coord/module.c`  
- **Standalone:** `src/module.c`  
Similarly, `debug_commands.c` was merged into a single file in master.  
Due to these structural differences, this **cherry-pick had to be done manually** to properly extract coordinator-related code and place it in the correct files.  
| Component                      | Master  | 2.10  |
|--------------------------------|-------------------------|-----------------------------------------|
| **expose …
> [2.10] CP TIMEOUT related bugs & Query Debug Mechanism 

- src/redisearch_rs/Cargo.toml
- src/redisearch_rs/trie_rs/Cargo.toml
- src/redisearch_rs/trie_rs/src/ffi.rs
- src/redisearch_rs/trie_rs/src/lib.rs
Implement an FFI module in Rust that is almost equivalent to `deps/triemap/triemap.h` insofar its functionality that is used outside the triemap dependency. The major difference between `ffi.rs` and `triemap.h` is the fact that `ffi.rs` exposes the defined structs that are used externally (`TrieMap`, `TrieMapIterator`) only behind opaque pointers, so that using code does not rely on their internals.
After analysis of the code base, it has been concluded that the only occurrences of code altering or reading the fields of these structs is upon initialization of the `TrieMapIterator`. Therefore, the `TrieMap_Iterate` function takes an additional parameter of type `tm_iter_mode`, which is meant to allow for setting the iteration mode upon initialization if `TrieMapIterator`.
A further …
> MOD-8970: Define an FFI API for trie_rs corresponding to deps/triemap/triemap.h

- tests/pytests/requirements.txt
> [2.6] Lock deepdiff module version

- .install/install_boost.sh
- .install/install_script.sh
Previously, `install_boost.sh` was sourced in `install_script.sh,` and if Boost was already installed, it executed exit 0. Since source runs the script in the current shell, this caused `install_script.sh` to terminate early, preventing the execution of subsequent installation scripts.
Solution
This update captures the exit code of `install_boost.sh` and ensures `install_script.sh` continues if the exit code is 0 (Boost installed) and stops with the correct error code if the script fails.
> Prevent install.sh from exiting early when Boost is already installed

- .github/workflows/task-get-linux-configurations.yml
1. Current: 
The `pre-deps` for ubuntu and rocky are only set `if 'alpine:3' in arm_platforms`
2. Change:
Fix indentation to set pre-deps for ubuntu and rocky
Ubuntu and rocky pre-deps are set without dependency on `alpine:3` 
1. MOD-...
2. #...
1. ...
> Fix indentation to set pre-deps

- .github/workflows/event-merge-to-queue.yml
- .github/workflows/event-pull_request.yml
- .github/workflows/task-test.yml
- .install/install_rust.sh
- .install/test_deps/common_installations.sh
- Makefile
[`miri`](https://github.com/rust-lang/miri) is an official tool to catch undefined behaviour in Rust programs.
It runs the Rust code through a (sandboxed) platform-independent interpreter, tracks which operations are being performed and compares them to Rust's operational semantics to catch UB.
This is particularly useful when working on codebases with a significant amount of `unsafe` code, as in our case.
You need to opt into running tests through `miri`, with a dedicated `RUN_MIRI` option.
In CI it's enabled exclusively for the `sanitize` check (PR event flow + merge-queue event flow).
There is no need to run `miri` on multiple platforms, since the check is platform-independent.
> MOD-8969: Run Rust tests through miri to catch undefined behaviour

- src/info/info_redis.c
- tests/pytests/test_info_modules.py
Fixes the section name from `garbage collector` to `garbage_collector` in the `INFO` command response.
> MOD-9105: Fix section name in `INFO` response

- src/redisearch_rs/Cargo.toml
- src/redisearch_rs/low_memory_thin_vec/Cargo.toml
- src/redisearch_rs/low_memory_thin_vec/src/header.rs
- src/redisearch_rs/low_memory_thin_vec/src/layout.rs
- src/redisearch_rs/low_memory_thin_vec/src/lib.rs
- src/redisearch_rs/low_memory_thin_vec/tests/tests.rs
`LowMemoryThinVec` is pointer-sized, since it stores its length and capacity on the heap, in the same allocation used to store its elements.
The implementation is based on a fork of the `thin_vec` crate. In `low_memory_thin_vec`:
- We remove code paths that are unnecessary for our usecase (e.g. `gecko-ffi`, draining, splicing)
- We reduce the maximum capacity of the `std` variant to `u16`, matching what we expect to use in our Rust trie re-implementation.
- We leverage newer `std` APIs to simplify or remove existing unsafe blocks and move computations to compile-time via `const` annotations where possible.
- We review all existing unsafe blocks and add proper safety comments.
A fork will allow us to evolve the code in whatever direction we deem optimal as the porting work progresses. …
> [MOD-8971] Introduce `LowMemoryThinVec`, a low-memory port of `thin_vec::ThinVec`

- coord/src/dist_aggregate.c
- coord/src/rmr/chan.c
- coord/src/rmr/chan.h
- coord/src/rmr/rmr.c
- coord/src/rmr/rmr.h
- src/aggregate/aggregate.h
- src/aggregate/aggregate_debug.c
- src/aggregate/aggregate_debug.h
- src/aggregate/aggregate_exec.c
- src/debug_commands.c
- src/result_processor.c
- src/result_processor.h
- src/util/timeout.h
- tests/pytests/common.py
- tests/pytests/test_cursors.py
- tests/pytests/test_debug_commands.py
- tests/pytests/test_resp3.py
- tests/pytests/test_timeout.py
This PR cherry-picks PR #5734 to 2.8, which previously cherry-picked PR #5554 to 2.10, since 2.10 is structurally closer to 2.8 than master.
However, **2.8 does not support `FT.DEBUG` in coordinator mode**, so the query debug mechanism is **only available in standalone mode**. This required **removing certain coordinator-related code** that was included in the original PR.  
---
- **Coordinator changes**: Removed all modifications to `coord/src/module.c`.  
- **Debug commands**:  
- Support only **`FT.SEARCH` / `FT.AGGREGATE`** commands.  
- Removed support for **`_FT.SEARCH` / `_FT.AGGREGATE`** commands (used for coordinator-shard communication).  
- **Distributed aggregation**: Removed split distributed command in `dist_aggregate.c`.  
- **Internal-only options**:  
- Removed …
> [2.8] CP TIMEOUT related bugs & Query Debug Mechanism

- .install/install_script.sh
> [2.8] Prevent install.sh from exiting early when Boost is already installed

- .install/install_script.sh
> [8.0] Prevent install.sh from exiting early when Boost is already installed

- .install/install_script.sh
> [2.10] Prevent install.sh from exiting early when Boost is already installed

- src/aggregate/aggregate_exec.c
- tests/pytests/test_resp3.py
> [2.8] MOD-9054: Fix `total_results` field in shard RESP3 response

- .github/workflows/benchmark-flow.yml
Similiar to the change that is being done to run the benchmarks on ARM in which we needed to update the OS image from 22.04 to 24.04 ( https://github.com/RediSearch/RediSearch/pull/5751 ), we should do the same thing to amd64. This PR addresses it. 
1. ...
> Updated the base image of benchmarks to run on 24.04

- src/doc_table.c
- src/doc_table.h
- tests/cpptests/test_cpp_index.cpp
- tests/cpptests/test_cpp_llapi.cpp
- tests/pytests/test_stats.py
Manual backport of #5099 to `2.6`.
(cherry picked from commit b4234edfc5031a996c903a824a51a02c75825925)
* 2.6 does not contain `tests/cpptests/test_cpp_llapi.cpp`:  `TEST_F(LLApiTest, testInfoSizeWithExistingIndex)`
* sizeof(DocTable) = 64 bytes, because does not contain `TimeToLiveTable* ttl;`
* TEST_F(LLApiTest, testInfoSize) was modified because 2.6 does not contain the changes to count numeric range tree overhead
> [2.6] MOD-5904: Fix DocTable memsize (#5099)

- src/doc_table.c
- src/doc_table.h
- tests/cpptests/test_cpp_index.cpp
- tests/cpptests/test_cpp_llapi.cpp
- tests/pytests/test_resp3.py
- tests/pytests/test_stats.py
Manual backport of #5099 to `2.8`.
(cherry picked from commit b4234edfc5031a996c903a824a51a02c75825925)
* 2.8 does not contain `tests/cpptests/test_cpp_llapi.cpp`:  `TEST_F(LLApiTest, testInfoSizeWithExistingIndex)`
* sizeof(DocTable) = 64 bytes, because does not contain `TimeToLiveTable* ttl;`
> [2.8] MOD-5904: Fix DocTable memsize (#5099)

- src/doc_table.c
- src/doc_table.h
- tests/cpptests/test_cpp_index.cpp
- tests/cpptests/test_cpp_llapi.cpp
- tests/pytests/test_resp3.py
- tests/pytests/test_stats.py
Manual backport of #5099 to `2.10`.
(cherry picked from commit b4234edfc5031a996c903a824a51a02c75825925)
* 2.10 does not contain `tests/cpptests/test_cpp_llapi.cpp`:  `TEST_F(LLApiTest, testInfoSizeWithExistingIndex)`
* sizeof(DocTable) = 64 bytes, because does not contain `TimeToLiveTable* ttl;`
> [2.10] MOD-5904: Fix DocTable memsize (#5099)

- src/coord/rmr/conn.c
- src/coord/rmr/redis_cluster.c
- tests/pytests/requirements.txt
- tests/pytests/test.py
- tests/pytests/test_aggregate.py
This PR fixes a bug in which we connected to the shards from the coordinator with TLS connections depending on whether TLS ports existed in the server configuration or not, instead of depending on the Redis `tls-cluster` config param.
Overall the fix of the condition upon which we connect to our coordinator and shards with TLS on OSS-cluster ONLY:
* Old condition: Whether there are any TLS ports configured for the cluster.
* New condition: Whether or not the `tls-cluster` config param is true or false.
From Redis Documentation:
> Cluster
When Redis Cluster is used, use tls-cluster yes in order to enable TLS for the cluster bus and cross-node connections.
From [link](https://redis.io/docs/latest/operate/oss_and_stack/management/security/encryption/#:~:text=to%20the%20master.-,Cluster,to%20e …
> MOD-8674: Fix TLS connection to shards

- tests/pytests/test_profile.py
set ON_TIMEOUT to RETURN so that test returns the expected profile output when the timeout is reached on non-strict timeout policy
> [MOD-9217] Fix timeout testFailOnTimeout_nonStrict ON_TIMEOUT policy

- .install/macos.sh
- pin cmake in macos to prevent errors in deps cmake files about unsupported cmake version
1. Current: brew update updates cmake to version 4 which causes deps/hiredis compilation to fail due to too low of a cmake version in `cmake_minimum_required` directive.
2. Change: Prevent the update for cmake by pinning the cmake version, we wanted a quick fix for now.
3. Outcome: CI can pass
1. macos.sh
> MOD-9274: Pin CMake Version For Mac OS

- src/aggregate/aggregate_exec.c
- tests/pytests/test_cursors.py
This PR fixes the aggregation of results when using strict timeout policy together with the safe-loader (i.e., multi-threading).
Specifically, the decrement of the `resultsLimit` was done too early, such that the safe-loader saw an already-decremented value, thus fetching one less result than needed.
The decrement was moved to the body of the loop, in case the `Next()` call succeeded, i.e., `RS_RESULT_OK` was returned from the pipeline.
A test was already encountering this bug, but was changed to use the non-strict timeout policy, thus hiding the bug. This setting was removed from the test, such that now it will use the strict timeout policy and test this behavior (Cursor + MT).
> MOD-9222: Fix strict timeout result aggregation

- tests/pytests/test_config.py
* expect vector sets to be loaded by default
1. Current: vector set module was implicitly added in redis and it is causing some of our tests to fail
2. Change: account for vector sets existence in our tests when using module list command
3. Outcome: CI will pass
1. tests
> Account For Vector Set Module In Tests

- src/aggregate/expr/expression.c
- tests/pytests/test_profile.py
Fix a case where null was passed into a pointer and the pointer was later dereferenced.
1. Current: We pass NULL as the length pointer, the pointer, in certain cases it will be immediately dereferenced.
2. Change: Use a local variable and pass its address
3. Outcome: No longer crash on that specific call for dereferencing null.
1. RSValue
> [2.10] Fix RSValue String Convert Call

- src/aggregate/aggregate_exec.c
> [2.8] MOD-9222: Fix strict timeout result aggregation (#5844)

- sbin/upload-artifacts
1. Current: 
2.6 `sbin/upload-artifact.sh` sets architecture name `arm64v8` for ARM
2. Change: 
Fix `sbin/upload-artifact.sh` to set `aarch64` as architecture name for ARM
3. Outcome:
ARM package names will be updated using `aarch64` architecture name
1. MOD-9310
1. ...
> [2.6] MOD-9310: Fix upload artifacts arch name

- .github/workflows/task-test.yml
- .install/alpine_linux_3.sh
- Makefile
- src/redisearch_rs/Cargo.toml
- src/redisearch_rs/low_memory_thin_vec/src/lib.rs
- src/redisearch_rs/trie_rs/Cargo.toml
- src/redisearch_rs/trie_rs/src/ffi.rs
- src/redisearch_rs/trie_rs/src/lib.rs
- src/redisearch_rs/trie_rs/src/trie.rs
**Stacked on #5744.**
Implement TrieMap type, with insertion, removal, finding, and basic iteration
Add a TrieMap implementation, that uses `LowMemoryThinVec` to store
node labels and children. This version includes implementations
for insertion, removal, finding, and ordered iteration over entries.
Additionally, `TrieMap::mem_usage` allows one to compute the current
memory usage of the trie.
Furthermore, an implementation of `std::fmt::Debug` is done,
as a means of inspecting the structure of the trie. Combined
with snapshot testing based on the `insta` crate, this allows
developers to verify the correctness of the data structure.
As a sanity check, a `proptest`-based tests is included,
which asserts the behavior of `TrieMap<T>` is identical
to that of `BTreeMap<Vec<c_char>, T>` given a …
> [MOD-8972] - Implement basic TrieMap functionality in Rust

- .github/workflows/flow-build-artifacts.yml
1. Current:
github action **Trigger Build and Upload Artifacts for Environments**  fails
```sh
/home/runner/work/_temp/...: SyntaxWarning: invalid escape sequence '\.'
if bool(fullmatch('[0-9]+\.[0-9]+', ref)) or ref == 'master': # e.g. 2.8, 2.10, master
```
2. Change:
Use raw string for the regular expression.
3. Outcome:
github action runs without error
1. MOD-...
1. ...
> Fix regex pattern in build artifact validation

- src/info/indexes_info.c
- tests/pytests/test_info_modules.py
Temporarily disable `search_used_memory_vector_index` and `search_marked_deleted_vectors` metrics, as they rely on `VecSimIndex_Info` call over a tiered index, which is an api designed for debug operation and not for production since it may be time consuming. 
The fix will come shortly to all branches in a different PR.
> [MOD-9313] Disable extended vecsim info [2.10]

- .install/install_cmake.sh
- .install/macos.sh
**CMake 4.0 removes support for versions earlier than 3.5.** Calls to `cmake_minimum_required()` or `cmake_policy()` with older policy versions now **result in an error.**
All CMake files included in this repo, including dependencies, must meet this requirement.
To address this, dependencies have been updated to versions that set `cmake_minimum_required()` to 3.5 or higher.
- `googletest` updated to `v1.16.0`
- `hiredis` updated to the latest commit on master ([commit 1387948](https://github.com/redis/hiredis/commit/138794853c6adb677e34f6003df339befc1b8a13))
This PR also reverts #5850, which pinned CMake to a version <4 on macOS. This restriction is no longer needed since the updated dependencies are now compatible with CMake 4.0.
> [MOD-9303] Update submodules to support cmake >= 4.0

- src/spec.c
- src/spec.h
need to consume the entirety of the rdb when loading an index, even if it is a duplicate
1. Current: Since we avoid reading from the rdb if the index is a duplicate then redis issues an error since the aux rdb part was not consumed in its entirety.
2. Change: Revert to old behaviour where we consumed the entire aux RDB part, turning on spec flags to avoid some side effects.
3. Outcome: RDB flow will behave in the expected way.
1. spec
> MOD-9316: Fix Duplicate Index Loading From RDB

- tests/pytests/requirements.txt
Pins the pytest dependencies' versions to reduce the flakiness of our CI.
Adds a pin to the `orderly-set` package, which was updated to `5.4.0`, which uses syntax supported from Python 3.9 and on. Until we remove Python 3.8 from our CI, we pin this package version to `5.3.0` such that the platforms that use Python3.8 are able to execute the test-suite.
> MOD-9234: Pin test dependencies

- .install/verify_build_deps.sh
In .install/verify_build_deps.sh we use the following command to get `cmake` version:
```
cmake --version | grep -oP 'cmake version \K[0-9.]+' | cut -d. -f1,2
```
However, `-P` option for `grep` is not supported on **Alpine**.
This PR replaced cmake version extraction with a compatible set of commands:
```
cmake --version | grep "cmake version" | sed -E 's/.*cmake version ([0-9]+\.[0-9]+).*/\1/'
```
* `.install/verify_build_deps.sh:get_cmake_version` function: Replaced the `grep -oP` command with `grep` and `sed` to extract the CMake version.
> get_cmake_version is not complatible with alpine, fix that

- src/aggregate/aggregate_exec.c
- src/module.c
- src/result_processor.c
- src/result_processor.h
- tests/pytests/test.py
- tests/pytests/test_cursors.py
- tests/pytests/test_optimizer.py
CP of #5837 to `8.0`
One conflict in `result_processor.h`, relating to the un-backported `initTime, GILTime` fields.
> [8.0] MOD-9174: Fix pipeline issues (#5837)

- src/ext/default.c
- tests/pytests/test_issues.py
Fix an edge case where the document has no text at all, causing its `maxFreq` and `len` to be zero, and attempting to use this values to normalize the scores yields `inf` for non-zero scores, and `nan` for zero scores (`x/0` and `0/0` respectively). This causes the obviously not matching document to score very high, yielding meaningless results that are preferred over better matches, or just messing with the sorting when comparing scores to `nan`
> Fix scores when document has no text - [MOD-9423]

- build/libuv/Makefile
This pull request includes a small change to the `build/libuv/Makefile` file. 
The change forces libuv to build as a static library by setting `LIBUV_BUILD_SHARED=OFF`, ensuring a static linkage to this dep.
Without this change, some systems like amz2 and rhel8 fail to find libuv and the server startup fails
```
4031:M 20 Apr 2025 15:00:34.423 # Module /var/opt/redislabs/persist/modules/search/21017/amzn2/x86_64/module.so failed to load: libuv.so.1: cannot open shared object file: No such file or directory
4031:M 20 Apr 2025 15:00:34.423 # Can't load module from /var/opt/redislabs/persist/modules/search/21017/amzn2/x86_64/module.so: server aborting
```
> [MOD-9437] Avoid linking `libuv` dynamically 

- src/coord/rmr/rq.c
Name the UV-thread when we spawn it.
Naming logic was copied from `thpool.c`
> Rename UV thread when spinning it up

- .codespell/ignore_wordlist.txt
- src/query_parser/v2/parser.c
- src/query_parser/v2/parser.y
- tests/pytests/test_parser.py
- tests/pytests/test_profile.py
- tests/pytests/test_scorers.py
Improve intersection parsing (`DIALECT 2` and above) so parentheses and sub-queries order won't affect text scores
> Improve parser for intersections [MOD-9278]

- Makefile
- src/redisearch_rs/Cargo.toml
- src/redisearch_rs/trie_bencher/.gitignore
- src/redisearch_rs/trie_bencher/src/bencher.rs
- src/redisearch_rs/trie_bencher/src/lib.rs
- src/redisearch_rs/trie_bencher/src/main.rs
- src/redisearch_rs/trie_rs/Cargo.toml
- src/redisearch_rs/trie_rs/src/lib.rs
- src/redisearch_rs/trie_rs/src/node/accessors.rs
- src/redisearch_rs/trie_rs/src/node/metadata.rs
- src/redisearch_rs/trie_rs/src/node/mod.rs
- src/redisearch_rs/trie_rs/src/node/trait_impls.rs
- src/redisearch_rs/trie_rs/src/node/trie_ops.rs
- src/redisearch_rs/trie_rs/src/trie.rs
- src/redisearch_rs/trie_rs/src/utils.rs
- src/redisearch_rs/trie_rs/tests/trie.rs
A Rust trie that's much closer to the structure of the original C implementation in `deps/triemap`.
Both label and children arrays are inlined in the buffer backing the node, matching the original C design.
This requires us to use `realloc` whenever we add/remove a child or modify the label.
At the same time, it minimizes memory overhead (no capacity to keep track of!) and pointer indirection when performing trie operations.
Rust doesn't provide (yet) a lot of machinery to define and manipulate custom dynamically-sized types, such as the one we're defining here. This translates into a significant number of `unsafe` blocks, which must be reviewed with extreme care. 
I've tried, whenever possible, to build safe(r) abstractions and thus minimize the cognitive overhead/the complexity of the …
> [MOD-9230] "Faithful" trie reimplementation

- CMakeLists.txt
- src/redisearch_rs/Cargo.toml
- src/redisearch_rs/redis_mock/Cargo.toml
- src/redisearch_rs/redis_mock/src/allocator.rs
- src/redisearch_rs/redis_mock/src/lib.rs
- src/redisearch_rs/redisearch_rs/Cargo.toml
- src/redisearch_rs/redisearch_rs/src/lib.rs
- src/redisearch_rs/redisearch_rs/src/trie.rs
- src/redisearch_rs/trie_bencher/Cargo.toml
- src/redisearch_rs/trie_bencher/src/lib.rs
- src/redisearch_rs/trie_rs/Cargo.toml
- src/redisearch_rs/trie_rs/src/lib.rs
`redisearch_rs` is the unified entrypoint for C users of the Rust code. It contains all the C-to-Rust FFI modules and it's the only unit linked against the final redisearch.so library.
As part of the refactor, we also introduced `redis_mock`, a crate that provides an alternative implementation of Redis' allocation functions. It has been extracted from `trie_bencher` for future use in other parts of the Rust workspace.
> Introduce a facade crate, `redisearch_rs`.

- src/ext/default.c
- tests/pytests/test_issues.py
- tests/pytests/test_search_params.py
- tests/pytests/test_tags.py
> [2.8] Fix scores when document has no text - [MOD-9423]

- src/ext/default.c
- tests/pytests/test_issues.py
- tests/pytests/test_search_params.py
- tests/pytests/test_tags.py
> [2.10] Fix scores when document has no text - [MOD-9423]

- src/ext/default.c
- tests/pytests/test_issues.py
> [2.6] Fix scores when document has no text - [MOD-9423]

- src/cursor.c
- src/cursor.h
- tests/cpptests/test_cpp_cursors.cpp
Fixing the cursors API so one can safely call `FT.CURSOR DEL` on some cursor currently being read by another connection on another thread.
Instead of attempting to delete the requested cursor, if we see that it is currently being used, we mark it for deletion. When the using thread finishes with the cursor, it will delete the cursor even if it was not depleted.
The issue can only happen using `WORKERS` or cluster mode (Coordinator).
1. MOD-9432
2. MOD-9433
3. MOD-9434
4. MOD-9435
1. Cursor API internals
> Fix Cursor Purge - [MOD-9408]

- .codespell/.codespellrc
- src/redisearch_rs/.gitignore
- src/redisearch_rs/Cargo.toml
- src/redisearch_rs/wildcard/Cargo.toml
- src/redisearch_rs/wildcard/benches/matching.rs
- src/redisearch_rs/wildcard/src/fmt.rs
- src/redisearch_rs/wildcard/src/lib.rs
- src/redisearch_rs/wildcard/tests/integration/fmt.rs
- src/redisearch_rs/wildcard/tests/integration/main.rs
- src/redisearch_rs/wildcard/tests/integration/matches.rs
- src/redisearch_rs/wildcard/tests/integration/parse.rs
- src/redisearch_rs/wildcard/tests/integration/properties.rs
- src/redisearch_rs/wildcard/tests/integration/utils.rs
This PR covers wildcard matching. It is the first of a series of PRs aimed at breaking https://github.com/RediSearch/RediSearch/pull/5928 down into smaller (and easier to review) chunks.
Wildcard matching is implemented as a standalone crate, named `wildcard`.
It mirrors the functionality provided by `src/wildcard.*`, restricted to `c_char` (for now). The test suite in `tests/ctests/test_wildcard.c` has been ported over to Rust too, alongside new test cases (e.g. property-based tests).
> [MOD-9547] Implement wildcard matching, as a preliminary step towards wildcard trie iterators.

- CMakeLists.txt
- src/spec.c
Fix a compilation error in spec.c related to the -Wformat-security flag.
Add -Wformat-security to the CMake build flags.
> [MOD-9566] Fix format-security compilation and enforce flag in CMake

- CMakeLists.txt
- src/spec.c
Reverts RediSearch/RediSearch#6040
> Revert "[8.0] [MOD-9566] Fix format-security compilation and enforce flag in CMake"

- src/spec.c
Backport of https://github.com/RediSearch/RediSearch/pull/6002 to 2.8.
> [2.8] Avoid lazy expiration in background indexing for CRDT [MOD-9486] 

- .install/rocky_linux_9.sh
Fixes a CI issue with Rocky9
This PR updates the `rocky_linux_9.sh` installation script to address dependency conflicts encountered during the installation of `gcc-toolset-13` and related packages on Rocky Linux 9. 
- Added the `--allowerasing` flag to the dnf install command to allow `dnf` to resolve package conflicts by removing or replacing conflicting packages (e.g., glibc and curl).
- Ensured that the script continues to install required dependencies (glibc, glibc-devel, etc.) without errors.
- Retained the use of --nobest and --skip-broken to handle edge cases where the best candidate for a package cannot be installed.
Without the --allowerasing flag, the script fails due to dependency conflicts, such as:
- glibc version mismatches.
- Conflicts between curl and curl-minimal.
- These …
> MOD-9581: Fix rocky9 CI

- tests/pytests/test.py
Temporarily skips a flaky TLS test
> Temporarily skip flaky test

- CMakeLists.txt
- src/spec.c
Reinsert after reverted originally due to 8.0 GA code freeze.
> Revert "Revert "[8.0] [MOD-9566] Fix format-security compilation and enforce flag in CMake" (#6046)"

- .github/workflows/event-pull_request.yml
- .github/workflows/flow-coverage.yml
- Makefile
Following #5856. Will be CP manually to the original PR's backports.
1. Add a step to upload artifacts on failed tests
2. Changed coverage to extract files to report only from `src`, `deps/thpool`, and `deps/triemap`, instead of removing deps, tests, and additional stuff supplied by readies.
> CI Improvement - Coverage fixes

- .codespell/ignore_wordlist.txt
- src/config.c
- src/config.h
- tests/pytests/test.py
- tests/pytests/test_aggregate.py
- tests/pytests/test_config.py
- tests/pytests/test_contains.py
- tests/pytests/test_coordinator.py
- tests/pytests/test_cursors.py
- tests/pytests/test_expire.py
- tests/pytests/test_issues.py
- tests/pytests/test_json.py
- tests/pytests/test_multibyte_char_terms.py
- tests/pytests/test_multithread.py
- tests/pytests/test_optimizer.py
- tests/pytests/test_profile.py
- tests/pytests/test_resp3.py
- tests/pytests/test_tags.py
- tests/pytests/test_wildcard.py
Revert default timeout policy back to return partial results rather than failing the query. Reverts #5555
> Revert changing default timeout to fail + adjust tests [MOD-7791]

- .github/workflows/event-pull_request.yml
- .github/workflows/flow-micro-benchmarks.yml
- src/redisearch_rs/redisearch_rs/Cargo.toml
The existing flow doesn't run all microbenchmarks—it only triggers the one for the trie.
Starting with #6000, we'll have additional microbenchmarks for other crates in the workspace
This PR modifies the CI flow to trigger a full microbenchmark run.
> Run all Rust benchmarks in the workspace

- CMakeLists.txt
- Makefile
- build.sh
bd569209494b0afa76256e9211f20ebf1ce353d7 caused a regression in the Rust build process: `libredisearch_rs.a` is no longer linked against the final .so artifact. This PR brings the linking back and ensures that the bindir used for `redisearch_rs` is aligned across Makefile and CMakeLists.txt
> Fix Rust build after switching off readies

- src/spec.c
Backport of https://github.com/RediSearch/RediSearch/pull/6002 to 2.10.
> [2.10] Avoid lazy expiration in background indexing for CRDT [MOD-9486]

- src/config.c
- src/config.h
- tests/pytests/common.py
- tests/pytests/test_config.py
- tests/pytests/test_debug_commands.py
- tests/pytests/test_index_oom.py
Change the default value of _BG_INDEX_MEM_PCT_THR to 100% (Align to Redis behavior).
The pytests structure remains the same, with changing _BG_INDEX_MEM_PCT_THR to 80% at the start of each test.
> [MOD-9560] Change default config value for _BG_INDEX_MEM_PCT_THR

- .github/workflows/task-lint.yml
- Makefile
- src/redisearch_rs/.cargo/config.toml
- src/redisearch_rs/Cargo.toml
- src/redisearch_rs/tools/license_header_linter/Cargo.toml
- src/redisearch_rs/tools/license_header_linter/src/main.rs
Adds a CI check to ensure that all Rust files include the expected license header.
> Enforce license headers for Rust files

- src/redisearch_rs/tools/license_header_linter/src/main.rs
Otherwise, `cargo fmt` fails on them.
> Don't add unnecessary \n after the license header

- src/redisearch_rs/Cargo.toml
- src/redisearch_rs/trie_rs/Cargo.toml
- src/redisearch_rs/trie_rs/src/iter/filter.rs
- src/redisearch_rs/trie_rs/src/iter/iter_.rs
- src/redisearch_rs/trie_rs/src/iter/lending.rs
- src/redisearch_rs/trie_rs/src/iter/mod.rs
- src/redisearch_rs/trie_rs/src/iter/values.rs
- src/redisearch_rs/trie_rs/src/lib.rs
- src/redisearch_rs/trie_rs/src/node/trie_ops.rs
- src/redisearch_rs/trie_rs/src/trie.rs
- src/redisearch_rs/trie_rs/src/utils.rs
- src/redisearch_rs/trie_rs/tests/integration/iter.rs
- src/redisearch_rs/trie_rs/tests/integration/main.rs
- src/redisearch_rs/trie_rs/tests/integration/trie.rs
- src/redisearch_rs/trie_rs/tests/integration/utils.rs
This PR introduces the machinery required to implement the trie iterators from `deps/triemap.c`. 
It is the second of a series of PRs aimed at breaking https://github.com/RediSearch/RediSearch/pull/5928 down into smaller (and easier to review) chunks.
> [MOD-9547] Core trie iterators

- src/aggregate/aggregate_exec.c
- src/query_error.h
- src/util/timeout.h
- tests/pytests/test.py
This PR fixes two issues:
1. A flaky test in our CI - it was flaky since we could have gotten a timeout error even on non-strict timeout policy, since it happens early on in the command parsing, and that is how we currently handle early "failures" (e.g., syntax failure gets the same treatment).
2. Timeout error for early timeouts - A new timeout error was added: `"Timeout limit was reached during command parsing"`.
This timeout error will be dispatched if an EARLY timeout is experienced, such that we do not even get to the pipeline execution phase.
This will add clarity regarding the time of the error, and create some separation from the "regular" timeouts that occur in the middle of a query - which depend on the timeout policy.
This error is independent of the timeout policy.
> MOD-9612: Fix flaky test and change early timeout error message

- src/aggregate/aggregate_exec.c
- src/query_error.h
- src/util/timeout.h
- tests/pytests/test.py
- tests/pytests/test_contains.py
- tests/pytests/test_wildcard.py
This PR skips the early timeout check we perform between building the iterator tree and building the pipeline.
In this way - we will still fail early upon using the strict timeout policy, but will continue to fail (stop collecting results, and return the collected ones) a bit later in case of non-strict timeout policy.
Related #6100
> MOD-9612: Do not check for early timeouts in non-strict timeout policy

- .github/workflows/flow-macos.yml
- .install/test_deps/common_installations.sh
- tests/pytests/requirements.txt
We had `gevent<=24.11.1` in requirements.txt, but this version is not available as a prebuilt wheel on some platforms.
Since pip prioritizes the latest version satisfying the requirement, it attempts to install 24.11.1 even if it means building from source. For example, on Ubuntu Focal (aarch64), the latest wheel available is 22.10.2, but pip chooses to download and compile 24.11.1 from source. This leads to a failure due to a syntax error in gevent's .pyx source file — an issue outside our control.
Using `--only-binary=gevent` forces pip to install the latest available wheel, avoiding the build and resolving the problem.
Recommendation: In such cases, we should bound the version from below as well as from above, to ensure pip picks a compatible version with an available binary.
CI …
> MOD-9671: Use wheel for gevent

- CMakeLists.txt
- src/util/circular_buffer.c
- tests/ctests/test_khtable.c
C23 is now the default in gcc (version 15) and is being shipped by default in some Linux distributions (e.g Fedora 42).
> Fix build for C23

- CMakeLists.txt
Always produce a `compile_commands.json` file for `clangd`, to get LSP support in Zed.
The file will be located in the bin directory, and thus be git-ignored by default.
> Save compile_commands.json

- src/aggregate/aggregate_exec.c
- tests/pytests/test.py
- tests/pytests/test_contains.py
- tests/pytests/test_wildcard.py
> [2.10] MOD-9612: Do not check for early timeouts in non-strict timeout policy

- src/aggregate/aggregate_exec.c
- tests/pytests/test.py
- tests/pytests/test_contains.py
- tests/pytests/test_wildcard.py
> [8.0] MOD-9612: Do not check for early timeouts in non-strict timeout policy

- .github/workflows/flow-coverage.yml
- Makefile
When the coverage job was split into "unit" and "flow", we ended up not running Rust tests and thus not computing coverage for the Rust code.
This PR fixes the regression.
> Compute coverage for Rust tests in CI

- .github/workflows/flow-macos.yml
Due to a bug in redis introduced in https://github.com/redis/redis/pull/13916 we had to disable macos on arm (macos-latest-xlarge) CI flow
The bug was fixed in https://github.com/redis/redis/pull/14038
This PR restore macos-latest-xlarge CI flow
> restore macos-latest-xlarge

- src/aggregate/aggregate_exec.c
- tests/pytests/test.py
- tests/pytests/test_contains.py
- tests/pytests/test_wildcard.py
> [2.8] MOD-9612: Do not check for early timeouts in non-strict timeout policy

- .github/workflows/flow-build-artifacts.yml
1. Current: Redis last tag (8.0.0) is used for packaging, but it fails
2. Change: Use Redis 7.4.x is used for packaging
3. Outcome: Packaging works
1. MOD-...
2. #...
1. ...
> [2.8] Get redis 7.4 for packaging

- src/redisearch_rs/trie_bencher/benches/iter.rs
- src/redisearch_rs/trie_bencher/src/bencher.rs
- src/redisearch_rs/trie_rs/src/iter/into_values.rs
- src/redisearch_rs/trie_rs/src/iter/mod.rs
- src/redisearch_rs/trie_rs/src/node/metadata.rs
- src/redisearch_rs/trie_rs/src/node/mod.rs
- src/redisearch_rs/trie_rs/src/node/trait_impls.rs
- src/redisearch_rs/trie_rs/src/node/trie_ops.rs
- src/redisearch_rs/trie_rs/src/trie.rs
- src/redisearch_rs/trie_rs/tests/integration/iter/values.rs
Stacked on #6119.
Implement a new `TrieMap` iterator that consumes the map and yields all the values it contains.
It will be used in `TrieMap_Free` to invoke the specified free callback on each stored value when freeing the whole map.
> [MOD-9693] IntoValues trie iterator.

- pack/ramp-oss-cluster.yml
Fix ramp file for package compiled with `COORD=oss` - RediSearch 2.10
1. Current: ramp file is not complete
2. Change: Copy missing configuration from `coord/pack/ramp.yml`
3. Outcome: Fixed ramp file for oss cluster package 
1. MOD-...
2. #...
1. ...
> [2.10] Fix ramp-oss-cluster.yml

- src/redisearch_rs/low_memory_thin_vec/src/lib.rs
replace `mem::replace` with `mem::take`
According to the docs, this is better when `Default` is implemented for a type https://rust-lang.github.io/rust-clippy/master/index.html#mem_replace_with_default
> Fix linting failure on Rust LowMemoryThinVec drop implementation

- .gitignore
Seems clang creates a cache under this directory, so let's put it to git ignore list.
> Add .cache to git ignore list

- src/redisearch_rs/trie_rs/src/trie.rs
- src/redisearch_rs/trie_rs/tests/integration/trie.rs
Track (eagerly) the number of unique keys in the trie without requiring a full traversal.
It boils down to incrementing/decrementing a field whenever we perform a removal or an insertion.
> [MOD-9735] Track the number of unique keys in the trie.

- build.sh
The Rust profile for debug builds is named dev, even though it puts its artefacts in a folder named debug.
> Use the correct profile name for Rust debug builds

- src/info/info_redis/block_client.c
- src/info/info_redis/types/blocked_queries.c
- src/info/info_redis/types/blocked_queries.h
- src/module-init/module-init.c
- Try to print active cursors and queries information on exit
- On startup, print the base address of the library
- Fix reference count bug for cursors
1. Active Queries Container
1. MOD-9774
2. MOD-9775 (?)
> MOD-9787: Add More Diagnostics When Active Queries Are Not Empty

- .github/workflows/task-build-artifacts.yml
- sbin/upload-artifacts
1. Current: Redisearch OSS is not uploaded to s3
2. Change: Build, pack, and upload redisearch-community package
3. Outcome: redisearch-community package available on s3 repo.
1. MOD-...
2. #...
1. ...
> MOD-9766: Build and pack RediSearch OSS

- src/redisearch_rs/trie_bencher/benches/iter.rs
- src/redisearch_rs/trie_bencher/src/bencher.rs
- src/redisearch_rs/trie_bencher/src/c_map.rs
- src/redisearch_rs/trie_bencher/src/ffi.rs
- src/redisearch_rs/trie_rs/src/iter/iter_.rs
- src/redisearch_rs/trie_rs/src/iter/lending_range.rs
- src/redisearch_rs/trie_rs/src/iter/mod.rs
- src/redisearch_rs/trie_rs/src/iter/range.rs
- src/redisearch_rs/trie_rs/src/iter/values.rs
- src/redisearch_rs/trie_rs/src/trie.rs
- src/redisearch_rs/trie_rs/tests/integration/iter/mod.rs
- src/redisearch_rs/trie_rs/tests/integration/iter/range.rs
Stacked on top of #6130 
Add a range iterator to the Rust `TrieMap` implementation.
The micro-benchmarks against the C implementation are of limited significance due to #6134, but they allowed us to identify that bug in the first place.
> [MOD-9695] Trie range iterator

- src/redisearch_rs/trie_bencher/benches/iter.rs
- src/redisearch_rs/trie_bencher/src/bencher.rs
- src/redisearch_rs/trie_bencher/src/c_map.rs
- src/redisearch_rs/trie_bencher/src/ffi.rs
- src/redisearch_rs/trie_rs/src/iter/contains.rs
- src/redisearch_rs/trie_rs/src/iter/lending_contains.rs
- src/redisearch_rs/trie_rs/src/iter/mod.rs
- src/redisearch_rs/trie_rs/src/trie.rs
- src/redisearch_rs/trie_rs/tests/integration/iter/contains.rs
- src/redisearch_rs/trie_rs/tests/integration/iter/mod.rs
Stacked on top of #6155.
An iterator that returns all entries that contain a given fragment. The traversal is optimized to skip the check whenever we know that ancestors verified the predicate.
The performance is on par with the C version.
> [MOD-9734] Trie contains iterator

- src/config.c
- src/config.h
- src/debug_commands.c
- src/indexer.c
- src/indexer.h
- src/spec.c
- tests/cpptests/redismock/redismock.cpp
- tests/pytests/test_config.py
- tests/pytests/test_debug_commands.py
- tests/pytests/test_issues.py
This PR should fix the issue that a shard may not respond to "PING" while indexing on load.
this is done by yielding to redis after certain amount of indexing operations. the amount of operations between "yields" is configurable with FT.CONFIG SET INDEXER_YIELD_EVERY_OPS <num operations>.
It is possible to check the number of "yields" was called with FT.DEBUG YIELDS_ON_LOAD_COUNTER
> [8.0] Yield to redis while indexing - [MOD-9220] (#6103)

- src/config.c
- src/config.h
- src/debug_commands.c
- src/indexer.c
- src/indexer.h
- src/spec.c
- tests/cpptests/redismock/redismock.cpp
- tests/pytests/test_config.py
- tests/pytests/test_debug_commands.py
- tests/pytests/test_issues.py
This PR should fix the issue that a shard may not respond to "PING" while indexing on load.
this is done by yielding to redis after certain amount of indexing operations. the amount of operations between "yields" is configurable with FT.CONFIG SET INDEXER_YIELD_EVERY_OPS <num operations>.
It is possible to check the number of "yields" was called with FT.DEBUG YIELDS_ON_LOAD_COUNTER
> [2.10] Yield to redis while indexing - [MOD-9220] (#6103)

- .github/workflows/task-build-artifacts.yml
- Makefile
In the transition phase to the new script, the `MT_BUILD` flag did not pass properly to make via makefile while we are still building for pack the old way via `makefile`
> Fix MT build with makefile [2.10]

- src/redisearch_rs/wildcard/Cargo.toml
- src/redisearch_rs/wildcard/src/lib.rs
Use the optimized `is_prefix` routine from `memchr` to compare literal chunks.
Bench results:
```text
foobar vs foobar        time:   [2.6312 ns 2.6336 ns 2.6355 ns]
change: [-40.342% -39.767% -39.379%] (p = 0.00 < 0.05)
Performance has improved.
fo?bar vs foobar        time:   [6.2195 ns 6.2738 ns 6.3359 ns]
change: [-11.746% -10.794% -9.7779%] (p = 0.00 < 0.05)
Performance has improved.
fo?bar vs foobarz       time:   [582.61 ps 589.51 ps 601.84 ps]
change: [+2.6597% +6.9849% +12.974%] (p = 0.00 < 0.05)
Performance has regressed.
foo*baz vs foobarbaz    time:   [8.5217 ns 8.6821 ns 8.9057 ns]
change: [-20.867% -19.625% -17.899%] (p = 0.00 < 0.05)
Performance has improved.
foo*bar*red??*l*bs? vs foobarbazredxxlxxbsx
time:   [25.760 ns 25.843 ns 25.939 ns]
change: [-16.295% -15.976% …
```
> Optimize chunk comparisons in wildcard matching

- src/forward_index.c
- src/forward_index.h
- src/inverted_index.c
- src/inverted_index.h
- src/rules.c
- tests/cpptests/test_cpp_index.cpp
This PR refactors `inverted_index` to prepare it for porting to Rust. The refactor does not change functionality in any way. But makes the following changes:
1. Removes the dependency on `forward_index.h` by moving `InvertedIndex_WriteForwardIndexEntry` to `forward_index`.
1. Removes definitions which are not implemented from `inverted_index.h`
1. Makes public functions that are only used by `inverted_index` private.
> [MOD-9798] Refactor `inverted_index`

- .github/workflows/event-release.yml
Fix to release package `redisearch-community` to `redisearch-oss` s3 directory
1. Current: 
The files to release are filtered by the pattern: `{dir}/snapshots/{dir}`
That's valid for versions 2.x because for enterprise and oss versions the name of the directory matches with the name of the package.
But for Redisearch 8.x the oss version is named `redisearch-community` and should be copied to `redisearch-oss` directory.
2. Change:
Modify the filter function, for oss version the pattern will be: `redisearch-oss/snapshots/redisearch-community`
3. Outcome: 
For redisearch 8.x.x
`redisearch-community` packages will be released to `redisearch-oss` dir
1. MOD-9766
2. #...
1. ...
> [8.0] MOD-9766: Fix event-release to upload redisearch-community

- .github/workflows/event-merge-to-queue.yml
- .github/workflows/event-pull_request.yml
- .github/workflows/task-test.yml
Due to a bug in redis which was fixed in unstable but not in 8.0 exiting from a forked child process which was compiled in coverage can deadlock.
This can lead to failures in the coverage CI flow.
For now, we decided to disable the coverage when compiling the redis server.
Also bringing the coverage back as requirement
1. Current: We compile redis with coverage
2. Change: Stop compiling redis with coverage
3. Outcome: Coverage CI should pass since forked child should not deadlock on exit.
1. Workflows
> MOD-9774: Stop Compiling Redis-With Coverage

- .github/workflows/task-test.yml
- src/inverted_index.c
- src/inverted_index.h
- src/redisearch_rs/Cargo.toml
- src/redisearch_rs/buffer/Cargo.toml
- src/redisearch_rs/buffer/src/lib.rs
- src/redisearch_rs/buffer/src/mock.rs
- src/redisearch_rs/buffer/src/tests.rs
- src/redisearch_rs/ffi/.gitignore
- src/redisearch_rs/ffi/Cargo.toml
- src/redisearch_rs/ffi/README.md
- src/redisearch_rs/ffi/build.rs
- src/redisearch_rs/ffi/src/lib.rs
- src/redisearch_rs/redisearch_rs/Cargo.toml
- src/redisearch_rs/trie_bencher/Cargo.toml
- src/varint.c
- tests/cpptests/test_cpp_index.cpp
This PR provides the Rust bindings to the `Buffer` API that is currently implemented in C. This will be useful for oxidization of the modules that rely on this API (e.g Varint). Except for the memory growth in `BufferWriter`, all other functionality is implemented in Rust.
This is the first part of the split of #5996.
> MOD-9768: Add Rust abstractions for Buffer*

- src/redisearch_rs/ffi/build.rs
Scope build invalidation to *.c and *.h files.
We also restructure the build script to simplify future additions.
> chore: Improve granularity of build invalidation logic for FFI bindings

- tests/pytests/runtests.sh
Right now we call run_tests three times, but when one run fails we have no idea which one of the three failed and have to look at each one manually.
This PR tries to help by outputting an error for each of the run if it failed.
1. Current: No indication on which run_tests call failed.
2. Change: Provide some indication on which run_tests failed using the github summary file.
3. Outcome: Easier Development
1. run_tests script and function
> Indicate Which Test Suite Failed

- tests/cpptests/micro-benchmarks/benchmark_idlist_iterator.cpp
- tests/cpptests/micro-benchmarks/benchmark_union_iterator.cpp
- tests/cpptests/micro-benchmarks/benchmark_wildcard_non_optimized_iterator.cpp
Fix `SkipTo` target ID in the new iterator miro-benchmarks.
Use the iterator's `lastDocId` value to ensure we request a skip forward, regardless of the previous `SkipTo` call status
> Fix skipTo target id

- src/aggregate/aggregate_request.c
- src/id_list.c
- src/index.h
- src/query.c
- src/query.h
- src/query_node.h
- src/search_options.h
- tests/pytests/test.py
Simplify the `INKEYS` feature flow and performance.
1. Redefine structs with `sds` instead of `char*`, to improve `strlen` performance (note - the values were already `sds` type, which is convertible to `char*`)
2. Move key to id translate from `argv` to node evaluation, so it is done in the background when using multithreading, and guarantee more up-to-date IDs
3. Add deduplication validation
4. Pass ownership instead of another allocation and copying the ID list
> Simplify INKEYS flow

- tests/pytests/test_debug_commands.py
Test `test_update_debug_scanner_config` was flaky with `Debug mode enabled but scanner is not a debug scanner' should contain 'Scanner is not initialized'`, I believe this happened due to a scenario in which the background scan callback phase was done (all key were scanned) but the scanner was not yet freed (didn’t reach the end of Indexes_ScanAndReindexTask and the scanner instance was still "alive").
To fix this, I changed the wait for the scan finish from relaying on the `percent_indexed` info to the `indexing` info that indicates when the scanner is freed.
> Fix flaky test_debug_commands:test_update_debug_scanner_config [MOD-9854]

- .install/microsoft_azure_linux_3.0.sh
This PR reverts #6283
The temporary workaround is not needed anymore: https://github.com/RediSearch/RediSearch/actions/runs/15552559267
> Revert temporary azure:linux setup workaround

- src/result_processor.c
Check for timeout inside the rpidxNext loop to avoid getting killed by watchdog.
1. Current: Once we go into the loop of reading from the iterator tree we don't check for timeouts in the result processor, we seem to rely on the iterators to perform the timeout check.
2. Change: Check for timeout in the rpidx result processor read function.
3. Outcome: Avoid getting killed by the watchdog.
1. Rpidx result processor.
> MOD-9856: Check For Timeout Inside RpidxNext Loop

- src/index_result.h
- src/redisearch.h
- src/redisearch_rs/Cargo.lock
- src/redisearch_rs/Cargo.toml
- src/redisearch_rs/c_entrypoint/types_ffi/cbindgen.toml
- src/redisearch_rs/c_entrypoint/types_ffi/src/lib.rs
- src/redisearch_rs/ffi/Cargo.toml
- src/redisearch_rs/headers/types_rs.h
- src/redisearch_rs/inverted_index/Cargo.toml
- src/redisearch_rs/inverted_index/src/lib.rs
This moves the `RSAggregateResult` definition to Rust in preparation of moving the `RSIndexResult` to Rust too. This will make it easier to port the inverted index to Rust.
The Rust definition is exactly the same as the old C definition, so nothing in the C code needs to be updated.
> [MOD-9999] Migrate `RSAggregateResult` to Rust

- src/redisearch_rs/ffi/build.rs
This PR is a simple one-line fix for the Rust `ffi` crate build issues. We don't need the `FP_` constants and since they cause trouble, lets just disable generation of them.
> fix `ffi` CI build issues

- deps/thpool/thpool.c
- src/spec.c
Currently in redisearch_thpool_destroy we call redisearch_thpool_terminate_threadsimmediatly,
this can result in a race condition in bg indexing in which the thpool is destroyed before the bg indexing task started and thus creating a leak. 
[Validate gh-readonly-queue/2.10/pr-6294-e7ddc75819184ebfd0cc11cff3d1a6328f231996 · RediSearch/RediSearch@0123c19](https://github.com/RediSearch/RediSearch/actions/runs/15605403699/job/43953619796)
> Add redisearch_thpool_wait in redisearch_thpool_destroy [MOD-10105]

- src/fork_gc.c
- src/fork_gc.h
- src/info/info_command.c
- tests/pytests/test_gc.py
Move the locking of the spec in IndexInfoCommand->fillReplyWithIndexInfo
Hopefully this will fix the bug and some flaky tests
Plus handle the while loop in FGC_recvFixed, that seems to block the gc thread
> 8.0 - lock before opening indexes if info - [MOD-10007] [MOD-9761] (#6279)

- src/tokenize.c
- tests/pytests/test_issues.py
- tests/pytests/test_multibyte_char_terms.py
Manual backport of #5524 to `2.6`.
(cherry picked from commit efda03de8780f3858810a3312673f84f671e4214)
Changes
- Update `testLongTerms(env)` because now the term is not truncated.
> [2.6] MOD-6786 Fix search on larger then 128 terms (#5524)

- src/tokenize.c
- tests/pytests/test_issues.py
- tests/pytests/test_multibyte_char_terms.py
Manual backport of #5524 to `2.8`.
(cherry picked from commit efda03de8780f3858810a3312673f84f671e4214)
Changes
- Update `testLongTerms(env)` because now the term is not truncated.
> [2.8] MOD-6786 Fix search on larger then 128 terms (#5524)

- src/aggregate/aggregate_exec.c
- src/aggregate/aggregate_request.c
- src/aggregate/expr/expression.c
- src/aggregate/reducer.c
- src/coord/dist_plan.cpp
- src/rlookup.c
- src/rlookup.h
- src/spec.c
- tests/cpptests/test_cpp_agg.cpp
- tests/cpptests/test_cpp_expr.cpp
- tests/cpptests/test_cpp_resultprocessor.cpp
- tests/cpptests/test_cpp_rlookup.cpp
This refactor this RLookup C interface to make porting to Rust easier. In particular it 
replaces the `RLookup_GetKey`/`RLookup_GetKeyEx` functions which have their behavior controlled through the `mode` argument with mode-specific aliases: `RLookup_GetKey_Read`/`RLookup_GetKey_ReadEx` and `RLookup_GetKey_Write`/`RLookup_GetKey_WritEx`.
> MOD-10187 Refactor Refactor RLookup_GetKey* C interface for porting

- build.sh
- src/ttl_table.c
- tests/pytests/test_expire.py
- Remove redundant implementations
- Fix (by removing) the incorrect comparison function, which should return `true` (1) on **equality**, and `false` (0) otherwise
The bug can occur if a low ID is mapped to the same bucket as a high ID that is **in** the dictionary. Looking for the low ID may return the high ID as a match
> Fix TTL dictionary - [MOD-10240]

- .github/workflows/event-merge-to-queue.yml
- .github/workflows/event-nightly.yml
- .github/workflows/flow-linux-platforms.yml
- .github/workflows/task-get-linux-configurations.yml
CI adjustments for Redis 8 - since we are going to build redis open source with modules for Debian Bullseye only with gcc11, no need to keep testing the previous build with gcc10 (following work done in https://github.com/RediSearch/RediSearch/pull/6198)
In addition, Amazon Linux 2 is not supported in OSS, so no need to build it for arm anymore (still supported in enterprise only for x86)
> Test only for debian with gcc11 + remove arm from amzn2

- src/redisearch_rs/redis_mock/src/allocator.rs
We use the allocator shims to ensure that we have the same allocators when running benchmarks that compare the Rust and C implementations. This will also be used in Rust Unit tests, which link to C Code. 
The `mempool_t` C-code uses zero as an argument for' malloc', e.g., This PR fixes crashes that `mempool_t` is called from in Rust benchmarks or unit tests. 
It is an extraction of: https://github.com/RediSearch/RediSearch/pull/6342
Before this PR we panicked if the allocation functions in Rust were called with a zero size. However, that is too restrictive: The C standard permits this and leaves it open to the implementer to decide whether to return a nullptr or an actual address. The standard only states that the a pointer returned by `malloc` called with size zero must never be …
> MOD-10248 - Less restrictive Rust allocator shim

- src/redisearch_rs/Cargo.toml
- src/redisearch_rs/low_memory_thin_vec/src/lib.rs
- src/redisearch_rs/wildcard/src/fmt.rs
> Prevent CI breakage when Rust 1.88.0 is released (#6375)

- .github/workflows/flow-micro-benchmarks.yml
- src/info/info_command.c
- src/json.c
- src/spec.c
- src/spec.h
- src/vector_index.c
- src/vector_index.h
- tests/pytests/test_json.py
- tests/pytests/test_multithread.py
- tests/pytests/test_rdb_compatibility.py
- tests/pytests/test_vecsim.py
Adds required support for SVS-VAMANA, including:
1. Add a new RDB serialization version to support SVS-VAMANA. This one does not include saving `initial_cap` and `block_size` index parameters as we used to in the past. Backward compatibility exists, though these args are ignored in practice.
2. Remove logic for validations of `initial_cap` and `block_size` so that index creation will not exceed memory limits. The logic was reduces and the minimum needed was left (validation that a single vector will not exceed the maximum block size allowed). Tests were also removed and adjusted.
3. Add support for JSON, but not for multi just yet (enable sanity tests and fail gracefully in multi).
4. Remove exposure of some svs args …
> Add serialisation for svs + adjustments [MOD-10097]

- src/vector_index.c
Change the dynamic libsvs.so to a static one in vecsim, to avoid packing it as a runtime dependency.
> vecsim with svs as static lib [MOD-10245]

- src/aggregate/aggregate.h
- src/aggregate/aggregate_debug.c
- src/aggregate/aggregate_exec.c
- src/aggregate/aggregate_request.c
- src/coord/dist_aggregate.c
- src/coord/dist_plan.cpp
- src/profile.c
- src/query_optimizer.c
- src/result_processor.c
- tests/cpptests/test_cpp_agg.cpp
- tests/cpptests/test_distagg.cpp
Would like to separate the pipeline structure out of the AREQ struct.
This is needed to allow the hybrid its own pipeline while not giving it other stuff it does not need like the index iterators.
This PR wraps common pipeline related members in an AREQ function so it will be easier to replace in a future PR.
1. Current: Direct usage of AREQ pipeline members
2. Change: Wrap the usage with a function when possible
3. Outcome: Better encapsulation of some AREQ members.
1. AREQ
> MOD-10299: Wrap Common AREQ Members Usage With Functions

- src/inverted_index/inverted_index.c
- src/redisearch_rs/inverted_index_bencher/src/ffi.rs
One return was missing in the wrapper.
We also got the return value wrong, it's meant to return true if the value was *not* filtered out.
> inverted_index_bencher: fix test of C version

- src/redisearch_rs/Cargo.toml
- src/redisearch_rs/buffer/tests/tests.rs
- src/redisearch_rs/c_entrypoint/triemap_ffi/tests/trie.rs
- src/redisearch_rs/ffi/build.rs
- src/redisearch_rs/low_memory_thin_vec/tests/tests.rs
- src/redisearch_rs/qint/tests/qint.rs
- src/redisearch_rs/trie_rs/src/iter/contains.rs
- src/redisearch_rs/trie_rs/src/iter/iter_.rs
- src/redisearch_rs/trie_rs/src/iter/range.rs
- src/redisearch_rs/trie_rs/src/node/metadata.rs
- src/redisearch_rs/varint/tests/varint.rs
- src/redisearch_rs/varint/tests/vector_writer.rs
- src/redisearch_rs/wildcard/src/lib.rs
- src/redisearch_rs/wildcard/tests/integration/fmt.rs
Every new Rust release introduces new lints in `clippy` and the compiler itself.
This PR fixes the newly reported violations from 1.88.0.
> Fix lints that will be introduced in Rust 1.88.0

- src/aggregate/aggregate_request.c
- src/result_processor.c
- src/result_processor.h
- src/spec.c
- tests/cpptests/test_cpp_rpdepleter.cpp
Adds an index-spec locking & freeing mechanism that will allow index-space consistency among the two subqueries of the `FT.HYBRID` command.
The locking flow should be as follows:
1. Pipeline thread locks the index for read.
2. Both depleter threads lock the index for read.
3. Pipeline thread releases the index lock, such that the depleter threads can release the index-lock and catch the GIL without deadlocks.
4. Depleter threads release the index lock before loading the documents.
New behavior of `RPDepleter`:
* In case the depleter also performs the index locking logic, it will now return `RS_RESULT_DEPLETING` until the lock is taken by both background threads (depleters), such that the pipeline thread will not sleep until it releases the lock, such that there will be no deadlock when …
> MOD-10301: Add index locking/freeing mechanism for index-space consistency

- src/coord/dist_aggregate.c
- src/coord/rmr/reply.c
- src/coord/rmr/reply.h
- src/module.c
- tests/pytests/test_issues.py
- tests/pytests/test_profile.py
1. Current: Profiling info is added to the profiling info array when we are done consuming the reply (and only if we do)
2. Change: Take the profiling info only, and right when we take a reply from the channel
3. Outcome: Profiling info is available even if we don't consume the entire reply. Profile info left in the channel will still be missing
We now split the profiling info from the full reply and move the ownership over it to the profiling info array. The rest of the reply is still owned by the RPNet result processor.
This relies on `hiredis` being able to handle the `NULL` we set instead of the sub-section of the profiling data, which now has to be released separately.
1. MOD-8157
1. shards reply ownership on `FT.PROFILE AGGREGATE`
> Fix missing profile info - [MOD-6327]

- src/legacy_types.c
- src/legacy_types.h
- src/module.c
- src/numeric_index.c
- src/numeric_index.h
- src/redis_index.c
- src/redis_index.h
- src/spec.c
- src/tag_index.c
- src/tag_index.h
- src/trie/trie_type.c
- src/trie/trie_type.h
1. Current: We create modern types from legacy RDBs, just to be ignored and released when the loading event ends
2. Change: Remove legacy code, keep only RDB loading logic to consume the RDB without attempting to create the actual data structures
3. Outcome: Simpler support, without needing to implement dedicated constructors (especially as we migrate to Rust)
1. Legacy types
> Simplify legacy RDB support - [MOD-10352]

- .github/workflows/flow-micro-benchmarks-runner.yml
- .github/workflows/flow-micro-benchmarks.yml
Reverts #6442, change instance type instead
i8g.xlarge and r8g.xlarge have the same number of CPUs and RAM (and the same CPU type), which is what we care about in the micro-benchmarks
> [CI] Fix Nightly

- src/query.c
- src/query.h
- src/query_error.h
- src/query_node.h
- tests/cpptests/query_test_utils.h
- tests/cpptests/test_cpp_query.cpp
- tests/cpptests/test_cpp_query_validation.cpp
This PR contains the same changes of #6376 but applied to feature-RRF branch.
For HYBRID command add:
Vector filter validation - cannot use weights, cannot use vector commands
Search query validation - cannot use vector commands
> [feature-RRF] MOD-10224: Add vector filter validation 

- src/aggregate/aggregate_exec.c
- src/result_processor.c
- src/rlookup.c
- src/rlookup.h
Removed not used C Code and replaced direct field accesses with inline functions for `RLookupRow`.
First of all, stacked PRs for `RLookupRow`
Follow Up PRs: #6472 #6476 #6484
> RLookupRow - Refactor C-Code - MOD-10394

- src/redisearch_rs/Cargo.lock
- src/redisearch_rs/Cargo.toml
- src/redisearch_rs/rlookup/Cargo.toml
- src/redisearch_rs/rlookup/src/lib.rs
- src/redisearch_rs/rlookup/src/lookup.rs
First "ugly" porting of `RLookupKey` to Rust. This PR just adds the struct and most basic methods. Leaving future work to followup PRs.
Note that there is one diversion from the C code: The `RLookupKey` flag `NameAlloc` is now transient too (i.e. only an argument to the methods and not persisted into the key itself) since the allocation state is already tracked via the `_name` and `_path` `Cow` fields.
> `RLookupKey` transliteration

- src/redisearch_rs/rlookup/src/lookup.rs
This implements the "linked-list of keys" component and associated methods for `RLookup`. This type abstracts the actual storage of keys from the Rest of the RLookup implementation.
Stacks on top of #6431
> RLookup: KeyList linked-list implementation

- src/redisearch_rs/valgrind.supp
Help running the Rust tests suite with valgrind which is handy to detect memory leak and invalid access.
> redisearch_rs: add valgrind suppression file for tests

- src/redisearch_rs/inverted_index/src/freqs_only.rs
- src/redisearch_rs/inverted_index/src/lib.rs
- src/redisearch_rs/inverted_index/src/numeric.rs
- src/redisearch_rs/inverted_index/src/tests.rs
- src/redisearch_rs/inverted_index/tests/freqs_only.rs
- src/redisearch_rs/inverted_index/tests/numeric.rs
- src/redisearch_rs/inverted_index_bencher/src/benchers/freqs_only.rs
- src/redisearch_rs/inverted_index_bencher/src/benchers/numeric.rs
Implements an `InvertedIndex` in Rust which only allows writing new records. Reading records will happen in another PR.
> [MOD-10326] Rust InvertedIndex - Writing only

- src/redisearch_rs/ffi/src/lib.rs
- src/redisearch_rs/inverted_index/src/freqs_only.rs
- src/redisearch_rs/inverted_index/src/lib.rs
- src/redisearch_rs/inverted_index/src/numeric.rs
- src/redisearch_rs/inverted_index/src/tests.rs
- src/redisearch_rs/inverted_index/tests/freqs_only.rs
- src/redisearch_rs/inverted_index/tests/numeric.rs
- src/redisearch_rs/inverted_index_bencher/src/benchers/freqs_only.rs
- src/redisearch_rs/inverted_index_bencher/src/benchers/numeric.rs
- src/redisearch_rs/inverted_index_bencher/src/ffi.rs
This makes Rust constructors for all the `RSIndexResult` types. Nothiing uses these yet as the `Clone` and `Drop` implementation for `RSIndexResult` is still missing (will be in a next PR).
> [MOD-10446] Have Rust constructors for all the index types

- src/inverted_index/inverted_index.c
- src/inverted_index/inverted_index.h
- src/redisearch_rs/Cargo.lock
- src/redisearch_rs/buffer/src/reader.rs
- src/redisearch_rs/buffer/src/writer.rs
- src/redisearch_rs/inverted_index/Cargo.toml
- src/redisearch_rs/inverted_index/src/freqs_fields.rs
- src/redisearch_rs/inverted_index/src/freqs_only.rs
- src/redisearch_rs/inverted_index/src/lib.rs
- src/redisearch_rs/inverted_index/tests/freqs_fields.rs
- src/redisearch_rs/inverted_index_bencher/Cargo.toml
- src/redisearch_rs/inverted_index_bencher/benches/encoding_decoding.rs
- src/redisearch_rs/inverted_index_bencher/src/benchers/freqs_fields.rs
- src/redisearch_rs/inverted_index_bencher/src/benchers/mod.rs
- src/redisearch_rs/inverted_index_bencher/src/ffi.rs
Implement the freqs fields encoder and decoder in Rust.
Note: inlining was turned off in Rust to be comparable with the C calls
Both Rust encoder and decoder are faster than the C version, in normald and wide mode.
```
Encode - FreqsFields/C    time:   [2.6159 µs 2.6176 µs 2.6194 µs]
Encode - FreqsFields/Rust time:   [1.9075 µs 1.9083 µs 1.9092 µs]
Decode - FreqsFields/C    time:   [10.721 ns 10.746 ns 10.774 ns]
Decode - FreqsFields/Rust time:   [8.9110 ns 8.9224 ns 8.9346 ns]
Encode - FreqsFields Wide/C    time:   [4.4013 µs 4.4071 µs 4.4137 µs]
Encode - FreqsFields Wide/Rust time:   [3.1365 µs 3.1388 µs 3.1412 µs]
Decode - FreqsFields Wide/C    time:   [46.058 ns 46.124 ns 46.195 ns]
Decode - FreqsFields Wide/Rust time:   [22.759 ns 22.810 ns 22.892 ns]
```
> [MOD-10379] Implement the encodeFreqsFields and  encodeFreqsFieldsWide encoder/decoder in Rust

- src/coord/rmr/conn.c
- src/coord/rmr/conn.h
- src/coord/rmr/rmr.c
- src/util/dict.c
- src/util/dict.h
- tests/pytests/test.py
- tests/pytests/test_multithread.py
Follow up from #6313 
This PR makes sure that the SHARD_CONNECTION_STATES command gives the real status of all the connections from all the IO Runtimes
> [MOD-10431] accumulate conn state from different IO Runtimes

- src/ext/default.c
- src/geo_index.c
- src/hybrid_reader.c
- src/index.c
- src/index_result.c
- src/index_result.h
- src/iterators/intersection_iterator.c
- src/iterators/union_iterator.c
- src/offset_vector.c
- src/optimizer_reader.c
- src/redisearch_rs/c_entrypoint/types_ffi/cbindgen.toml
- src/redisearch_rs/c_entrypoint/types_ffi/src/lib.rs
- src/redisearch_rs/headers/types_rs.h
- src/redisearch_rs/inverted_index/src/lib.rs
- tests/cpptests/test_cpp_index.cpp
- tests/cpptests/test_cpp_range.cpp
We need to change the internal layout of this struct to be able to have it allocated on the Rust memory side. This change causes all the internals to be accessed via some method which will hide this change once it happens.
There are only a few direct accesses left inside `index_result.*` which will be moved with the change that will move the allocation to the Rust side.
> [MOD-10485] Guard access to `RSAggregateResult` internals

- coord/src/coord_module.h
- coord/src/dist_aggregate.c
- coord/src/module.c
- coord/src/rmr/command.c
- coord/src/rmr/command.h
- coord/src/rmr/test/minunit.h
- coord/src/rmr/test/test_command.c
- coord/src/shard_window_ratio.c
- coord/src/shard_window_ratio.h
- coord/src/special_case_ctx.h
- coord/tests/unit/CMakeLists.txt
- coord/tests/unit/minunit.h
- coord/tests/unit/test_shard_window_ratio.c
- src/config.h
- src/query.c
- src/query_node.h
- src/vector_index.h
- tests/pytests/common.py
- tests/pytests/test_shard_window_ratio.py
Backports PR #6383  (MOD-10359 - Implement shard window ratio optimization)
A manual backport was required due to significant differences in the directory structure between branches.
This PR consists of three commits:
**e35c57fe7** + **bcff44bcd**: **Manual backport of shard window ratio feature**: Core implementation backport from master branch with directory structure adaptations for 2.10
**a5a1f4c10**: **Gate shard_k_ratio behind `ENABLE_UNSTABLE_FEATURES` flag**: Added feature flag protection to ensure shard window ratio optimization is only available when unstable features are explicitly enabled, with appropriate error handling and test coverage.
**aa291a40f**: **Fix macOS compilation error with CLOCK_MONOTONIC_RAW**: Removed restrictive `_POSIX_C_SOURCE=200112L` definitions from …
> [2.10]backport of 6383 shard k ratio

- src/redisearch_rs/rlookup/src/lookup.rs
This PR adds the `CursorMut::override_current` method translating the C `overrideKey` function.
stacks on top of #6433
> add `CursorMut::override_current` - MOD-10391

- src/redisearch_rs/inverted_index/src/fields_only.rs
- src/redisearch_rs/inverted_index/src/freqs_fields.rs
- src/redisearch_rs/inverted_index/src/freqs_only.rs
- src/redisearch_rs/inverted_index/src/lib.rs
- src/redisearch_rs/inverted_index/src/numeric.rs
- src/redisearch_rs/inverted_index/src/tests.rs
- src/redisearch_rs/inverted_index/tests/fields_only.rs
- src/redisearch_rs/inverted_index/tests/freqs_fields.rs
- src/redisearch_rs/inverted_index/tests/freqs_only.rs
- src/redisearch_rs/inverted_index/tests/numeric.rs
Implements an inverted index reader in Rust. This only has the reader and is missing the code to:
- skip to
- verify field mask expiration for doc ID
- skip duplicates (#6523)
- filter out records (#6524)
> [MOD-10327] Rust inverted index reader

- CMakeLists.txt
Add missing `-g` flag so we don't lose the debug symbols before we extract them (so we actually get a version that includes them)
The `-ggdb` flag was a common debug flag with `readies`, but I keep it only for actual debug builds now. According to [the docs](https://gcc.gnu.org/onlinedocs/gcc/Debugging-Options.html), using only `-g` will make the debug info better but may not work with other debuggers. If we ever want a more portable debug info, we can add it back
For the `2.X` branches, #6541 implements the fix
> Add missing compilation flag for debug symbols

- src/redisearch_rs/rlookup/src/lookup.rs
1. Current: `build.sh BUILD` exits with a warning as an error
2. Change: Gate the method behind a unit test
3. Outcome: Nightly/Benchmark workflows built again
1. MOD-...
2. #...
1. ...
> Fix build error in nightly

- build.sh
- tests/cpptests/micro-benchmarks/benchmark_index_iterator.cpp
There is an instance where micro-benchmark failed but is not possible to see which run failed: ( https://github.com/RediSearch/RediSearch/actions/runs/16517620518/job/46711989640 ).
This could let us investigate better
> fix microbenchmark segFault in inverted_index_iterator

- src/redisearch_rs/ffi/build.rs
- src/redisearch_rs/headers/varint.h
- src/redisearch_rs/rlookup/src/bindings.rs
- src/redisearch_rs/rlookup/src/lib.rs
- src/redisearch_rs/rlookup/src/lookup.rs
First "ugly" porting of `RLookup` to Rust. This diff contains nothing but the crate setup, type definitions and `RLookup` constructors/destructor.
Stacks on top of #6431, #6432, #6433
> Initial `RLookup` transliteration - MOD-10393

- src/iterators/empty_iterator.c
- src/iterators/idlist_iterator.c
- src/iterators/intersection_iterator.c
- src/iterators/inverted_index_iterator.c
- src/iterators/inverted_index_iterator.h
- src/iterators/iterator_api.h
- src/iterators/not_iterator.c
- src/iterators/optional_iterator.c
- src/iterators/union_iterator.c
- src/iterators/wildcard_iterator.c
- tests/cpptests/iterator_util.cpp
- tests/cpptests/iterator_util.h
- tests/cpptests/test_cpp_iterator_index.cpp
- tests/cpptests/test_cpp_iterator_intersection.cpp
- tests/cpptests/test_cpp_iterator_not.cpp
- tests/cpptests/test_cpp_iterator_optional.cpp
- tests/cpptests/test_cpp_iterator_union.cpp
Implement new `Revalidate` API for the union, intersection, optional, and not iterators.
This PR also aligns the behavior of the `Revalidate` API regarding some edge cases with the return code (see the enum in `iterator_api.h` for the full details)
> Refactor "on reopen" logic - implement Revalidate for the internal iterators - [MOD-10534]

- src/debug_commands.c
- src/fork_gc.c
- src/forward_index.c
- src/indexer.c
- src/inverted_index/inverted_index.c
- src/inverted_index/inverted_index.h
- src/iterators/inverted_index_iterator.c
- src/redis_index.c
- src/tag_index.c
- tests/cpptests/index_utils.cpp
- tests/cpptests/index_utils.h
- tests/cpptests/micro-benchmarks/benchmark_index_iterator.cpp
- tests/cpptests/test_cpp_forkgc.cpp
- tests/cpptests/test_cpp_index.cpp
- tests/cpptests/test_cpp_iterator_index.cpp
- tests/cpptests/test_cpp_iterator_intersection.cpp
- tests/cpptests/test_cpp_iterator_not.cpp
- tests/cpptests/test_cpp_iterator_optional.cpp
- tests/cpptests/test_cpp_iterator_union.cpp
This adds accessors and setters for all the `IndexBlock` fields rather than accessing the fields directly. This work will make it easier to switch the `InvertedIndex` to Rust since the inverted index has `IndexBlock`s as one of its fields.
This is the first of two PRs with the next PR focusing on guarding the `InvertedIndex` struct
> [MOD-10629] Guard direct access to the `IndexBlock` internals

- .github/workflows/task-lint.yml
Should prevent commits where the main code has been updated but the generated code derivated from it was not committed.
This happened multiple times while changing the Rust code while the generated C bindings were not updated.
> ci: lint: check git diff

- src/redisearch_rs/rlookup/src/lookup.rs
This diff adds the `RLookup::get_key_write` method translating the C `RLookup_GetKey_Write` and `RLookup_GetKey_WriteEx` functions.
Stacks on top of #6431, #6432, #6433, #6434
> add `RLookup::get_key_write` - MOD-10396

- src/redisearch_rs/inverted_index/src/fields_only.rs
- src/redisearch_rs/inverted_index/src/freqs_fields.rs
- src/redisearch_rs/inverted_index/src/freqs_only.rs
- src/redisearch_rs/inverted_index/src/lib.rs
- src/redisearch_rs/inverted_index/src/numeric.rs
- src/redisearch_rs/inverted_index/src/tests.rs
- src/redisearch_rs/inverted_index/tests/fields_only.rs
- src/redisearch_rs/inverted_index/tests/freqs_fields.rs
- src/redisearch_rs/inverted_index/tests/freqs_only.rs
- src/redisearch_rs/inverted_index/tests/numeric.rs
- src/redisearch_rs/inverted_index_bencher/src/benchers/fields_only.rs
- src/redisearch_rs/inverted_index_bencher/src/benchers/freqs_fields.rs
- src/redisearch_rs/inverted_index_bencher/src/benchers/freqs_only.rs
- src/redisearch_rs/inverted_index_bencher/src/benchers/numeric.rs
We need to change the Decoder trait so records can borrow from the inverted index.
This is required to prevent extra copies when decoding the offsets vector.
> [MOD-10530] Redesign Decoder API to allow borrowing from the II

- src/inverted_index/inverted_index.c
- src/inverted_index/inverted_index.h
- src/redisearch_rs/inverted_index/src/doc_ids_only.rs
- src/redisearch_rs/inverted_index/src/lib.rs
- src/redisearch_rs/inverted_index/tests/doc_ids_only.rs
- src/redisearch_rs/inverted_index_bencher/benches/encoding_decoding.rs
- src/redisearch_rs/inverted_index_bencher/src/benchers/doc_ids_only.rs
- src/redisearch_rs/inverted_index_bencher/src/benchers/mod.rs
- src/redisearch_rs/inverted_index_bencher/src/ffi.rs
Implement the doc ids only encoder and decoder in Rust.
Note: inlining was turned off in Rust to be comparable with the C calls
Both Rust encoder and decoder are faster than the C version, in normald and wide mode.
```
Encode - DocIdsOnly/C    time:   [28.890 ns 29.275 ns 29.794 ns]
Encode - DocIdsOnly/Rust time:   [24.172 ns 24.341 ns 24.649 ns]
Decode - DocIdsOnly/C    time:   [21.613 ns 21.671 ns 21.731 ns]
Decode - DocIdsOnly/Rust time:   [5.9417 ns 5.9533 ns 5.9686 ns]
```
> [MOD-10384] Implement the  encodeDocIdsOnly encoder/decoder in Rust

- Makefile
- build.sh
- src/redisearch_rs/Cargo.toml
- src/redisearch_rs/inverted_index/tests/doc_ids_only.rs
- src/redisearch_rs/inverted_index/tests/fields_only.rs
- src/redisearch_rs/inverted_index/tests/freqs_fields.rs
- src/redisearch_rs/inverted_index/tests/freqs_only.rs
- src/redisearch_rs/inverted_index/tests/numeric.rs
- src/redisearch_rs/tools/license_header_linter/src/main.rs
- src/redisearch_rs/trie_bencher/src/bencher.rs
- src/redisearch_rs/trie_bencher/src/corpus.rs
- src/redisearch_rs/varint_bencher/src/bencher.rs
Instead explicitly exclude requiring C code.
This should prevent CI not running on new crates as we no longer have to
maintain the default members list.
Also fix clippy warnings in crates that were not checked by the CI.
> remove default-members from workspace

- src/redisearch_rs/rlookup/src/lookup.rs
This diff adds the `RLookup::get_key_load` method translating the C `RLookup_GetKey_Load` and `RLookup_GetKey_LoadEx` functions.
Stacks on top of #6431, #6432, #6433, #6434
> add `RLookup::get_key_load` - MOD-10397

- src/fork_gc.c
- src/iterators/inverted_index_iterator.c
- src/iterators/inverted_index_iterator.h
- src/iterators/wildcard_iterator.c
- src/query.c
- tests/cpptests/micro-benchmarks/benchmark_index_iterator.cpp
- tests/cpptests/test_cpp_iterator_index.cpp
1. Add two new dedicated APIs for wildcard and missing, removing the generic API, which is no longer needed
2. Each API sets its `Revalidate` mechanism - wildcard is compared with the current spec's wildcard index, and missing performs a lookup in the missing value indexes dictionary
> Add `Revalidate` support for optimized wildcard and missing values indexes - [MOD-10732]

- src/debug_commands.c
- src/fork_gc.c
- src/indexer.c
- src/inverted_index/inverted_index.c
- src/inverted_index/inverted_index.h
- src/iterators/inverted_index_iterator.c
- src/numeric_index.c
- src/profile.c
- src/redis_index.c
- src/spell_check.c
- src/tag_index.c
- tests/cpptests/index_utils.cpp
- tests/cpptests/index_utils.h
- tests/cpptests/test_cpp_forkgc.cpp
- tests/cpptests/test_cpp_index.cpp
- tests/cpptests/test_cpp_iterator_index.cpp
- tests/cpptests/test_cpp_iterator_intersection.cpp
- tests/cpptests/test_cpp_iterator_not.cpp
- tests/cpptests/test_cpp_iterator_optional.cpp
- tests/cpptests/test_cpp_iterator_union.cpp
This prepares the code using `InvertedIndex` from not accessing its fields directly. This is needed to port this type to Rust as it will have a new space once in Rust.
> [MOD-10328] Guard access to `InvertedIndex` internals

- src/inverted_index/inverted_index.c
- src/inverted_index/inverted_index.h
- src/redisearch_rs/inverted_index/src/fields_offsets.rs
- src/redisearch_rs/inverted_index/src/full.rs
- src/redisearch_rs/inverted_index/src/lib.rs
- src/redisearch_rs/inverted_index/src/test_utils.rs
- src/redisearch_rs/inverted_index/tests/fields_offsets.rs
- src/redisearch_rs/inverted_index_bencher/benches/encoding_decoding.rs
- src/redisearch_rs/inverted_index_bencher/src/benchers/doc_ids_only.rs
- src/redisearch_rs/inverted_index_bencher/src/benchers/fields_offsets.rs
- src/redisearch_rs/inverted_index_bencher/src/benchers/fields_only.rs
- src/redisearch_rs/inverted_index_bencher/src/benchers/freqs_fields.rs
- src/redisearch_rs/inverted_index_bencher/src/benchers/freqs_only.rs
- src/redisearch_rs/inverted_index_bencher/src/benchers/full.rs
- src/redisearch_rs/inverted_index_bencher/src/benchers/mod.rs
- src/redisearch_rs/inverted_index_bencher/src/benchers/numeric.rs
- src/redisearch_rs/inverted_index_bencher/src/ffi.rs
Implement the fields offsets encoder and decoder in Rust.
Note: inlining was turned off in Rust to be comparable with the C calls.
Rust encoders are as fast the C ones.
Decoders are faster than the C versions.
``` 
Encode - FieldsOffsets/C    time:   [4.4944 µs 4.5374 µs 4.5909 µs]
Encode - FieldsOffsets/Rust time:   [4.6087 µs 4.6325 µs 4.6577 µs]
Decode - FieldsOffsets/C    time:   [17.598 ns 17.620 ns 17.643 ns]
Decode - FieldsOffsets/Rust time:   [16.283 ns 16.291 ns 16.299 ns]
Encode - FieldsOffsets Wide/C    time:   [6.4141 µs 6.4460 µs 6.4820 µs]
Encode - FieldsOffsets Wide/Rust time:   [6.3252 µs 6.3704 µs 6.4202 µs]
Decode - FieldsOffsets Wide/C    time:   [56.175 ns 56.336 ns 56.533 ns]
Decode - FieldsOffsets Wide/Rust time:   [25.958 ns 25.979 ns 26.000 ns]
```
> [MOD-10381] Implement the encodeFieldsOffsets and encodeFieldsOffsetsWide encoder/decoder in Rust

- .install/install_boost.sh
- src/util/hash/hash.cpp
- src/util/hash/hash.h
1.84.0 does not build with clang++ 20 which we'll need to enable Rust/C LTO. 
`digest_type` signature changed in newer Boost so updated the hashing code accordingly.
> [MOD-10767] update boost to 1.88.0

- src/inverted_index/inverted_index.c
- src/inverted_index/inverted_index.h
- src/redisearch_rs/inverted_index/src/lib.rs
- src/redisearch_rs/inverted_index/src/offsets_only.rs
- src/redisearch_rs/inverted_index/tests/offsets_only.rs
- src/redisearch_rs/inverted_index_bencher/benches/encoding_decoding.rs
- src/redisearch_rs/inverted_index_bencher/src/benchers/mod.rs
- src/redisearch_rs/inverted_index_bencher/src/benchers/offsets_only.rs
- src/redisearch_rs/inverted_index_bencher/src/ffi.rs
Implement the offsets only encoder and decoder in Rust.
Note: inlining was turned off in Rust to be comparable with the C calls.
Rust encoder is almost as fast as the C one.
Rust decoder is faster than the C version.
```
Encode - OffsetsOnly/C    time:   [729.34 ns 730.81 ns 732.39 ns]
Encode - OffsetsOnly/Rust time:   [719.61 ns 721.94 ns 724.72 ns]
Decode - OffsetsOnly/C    time:   [18.146 ns 18.172 ns 18.202 ns]
Decode - OffsetsOnly/Rust time:   [10.978 ns 10.988 ns 11.004 ns]
```
> [MOD-10382] Implement the  encodeOffsetsOnly encoder/decoder in Rust

- src/inverted_index/inverted_index.c
- src/inverted_index/inverted_index.h
- src/redisearch_rs/inverted_index/src/freqs_offsets.rs
- src/redisearch_rs/inverted_index/src/lib.rs
- src/redisearch_rs/inverted_index/tests/freqs_offsets.rs
- src/redisearch_rs/inverted_index_bencher/benches/encoding_decoding.rs
- src/redisearch_rs/inverted_index_bencher/src/benchers/freqs_offsets.rs
- src/redisearch_rs/inverted_index_bencher/src/benchers/mod.rs
- src/redisearch_rs/inverted_index_bencher/src/ffi.rs
Implement the freqs offsets encoder and decoder in Rust.
Note: inlining was turned off in Rust to be comparable with the C calls.
Rust and C encoders are pretty much as fast. 
Rust decoder is faster than the C version.
```
Encode - FreqsOffsets/C    time:   [2.7519 µs 2.7656 µs 2.7800 µs]
Encode - FreqsOffsets/Rust time:   [2.8322 µs 2.8454 µs 2.8593 µs]
Decode - FreqsOffsets/C    time:   [18.670 ns 18.693 ns 18.718 ns]
Decode - FreqsOffsets/Rust time:   [14.216 ns 14.232 ns 14.251 ns]
```
> [MOD-10383] Implement the encodeFreqsOffsets encoder/decoder in Rust

- src/debug_commands.c
- src/ext/default.c
- src/fork_gc.c
- src/forward_index.c
- src/index_result.c
- src/index_result.h
- src/inverted_index/inverted_index.c
- src/iterators/hybrid_reader.c
- src/iterators/idlist_iterator.c
- src/iterators/inverted_index_iterator.c
- src/iterators/optimizer_reader.c
- src/numeric_index.c
- src/offset_vector.c
- src/profile.c
- src/redisearch_rs/c_entrypoint/types_ffi/src/lib.rs
- src/redisearch_rs/headers/types_rs.h
- src/redisearch_rs/inverted_index/src/lib.rs
- tests/cpptests/test_cpp_index.cpp
- tests/cpptests/test_cpp_iterator_index.cpp
- tests/cpptests/test_cpp_iterator_metric.cpp
- tests/cpptests/test_cpp_range.cpp
We want to remove the `union` on this field to replace it with a proper Rust `enum`. Doing so will change the layout of the field a bit. This PR makes it easier to update that layout by putting all the accessors of the data field behind function getters.
> [MOD-10158] Guard access to `RSIndexResult`'s data field

- .github/workflows/task-build-artifacts.yml
- .github/workflows/task-test.yml
- build.sh
- src/vector_index.c
- tests/pytests/includes.py
- tests/pytests/test_vecsim.py
Avoid building against Intel's pre-compiled library for SVS by default; use the open source version instead. The pre-compiled shred lib that contains LVQ and LeanVec implementations is going to be used in tests and for building the module for RE only.
> Avoid using SVS shared lib as default [MOD-10830] 

- src/info/indexes_info.c
- src/info/info_command.c
- src/redisearch_api.c
- src/spec.c
- src/spec.h
- tests/pytests/test_info_modules.py
Backport of https://github.com/RediSearch/RediSearch/pull/6613 to 2.8.
> [2.8] Update vectors memory in total index info memory [MOD-10841]

- src/redisearch_rs/c_entrypoint/types_ffi/src/lib.rs
- src/redisearch_rs/headers/types_rs.h
- src/redisearch_rs/inverted_index/src/doc_ids_only.rs
- src/redisearch_rs/inverted_index/src/fields_offsets.rs
- src/redisearch_rs/inverted_index/src/fields_only.rs
- src/redisearch_rs/inverted_index/src/freqs_fields.rs
- src/redisearch_rs/inverted_index/src/freqs_offsets.rs
- src/redisearch_rs/inverted_index/src/freqs_only.rs
- src/redisearch_rs/inverted_index/src/full.rs
- src/redisearch_rs/inverted_index/src/lib.rs
- src/redisearch_rs/inverted_index/src/numeric.rs
- src/redisearch_rs/inverted_index/src/offsets_only.rs
- src/redisearch_rs/inverted_index/src/raw_doc_ids_only.rs
- src/redisearch_rs/inverted_index/src/test_utils.rs
- src/redisearch_rs/inverted_index/src/tests.rs
- src/redisearch_rs/inverted_index_bencher/src/ffi.rs
- src/redisearch_rs/rqe_iterators/src/rqe_iterator.rs
This gives the lifetimes better names and makes a separate lifetime for the aggregate children. This work makes the `Ref` and `Owned` structs needed for MOD-10746 easier
> [MOD-10845] Improve the lifetimes of `RSIndexResult`

- coord/src/dist_aggregate.c
- coord/src/module.c
- src/aggregate/aggregate.h
- src/aggregate/aggregate_exec.c
- src/index.c
- src/info/global_stats.c
- src/info/global_stats.h
- src/info/indexes_info.h
- src/info/info_command.c
- src/info/info_redis.c
- src/profile.c
- src/result_processor.c
- src/result_processor.h
- src/rs_wall_clock.h
- src/spec.c
- src/spec.h
backport https://github.com/RediSearch/RediSearch/pull/6574 to 2.6
This PR also fixed a typo in ft.profile response
Post Proc**c**essing Time -> Post Processing Time
> [2.6] [MOD-10622] Change time measurement method in FT.PROFILE

- .install/install_boost.sh
- build/boost/boost.cmake
Fix CI [failure](https://github.com/RediSearch/RediSearch/actions/runs/17019997462/job/48247641065) (on Jammy)
```
Resolving archives.boost.io (archives.boost.io)... failed: Name or service not known.
wget: unable to resolve host address 'archives.boost.io'
```
Use the formal url https://github.com/boostorg/boost/releases/download
For backports, if using boost 1.84.0 or older the url needs to be stripped from the suffix `-b2-nodocs`,
instead of `boost-1.88.0-b2-nodocs.`
use `boost-1.84.0`
1. MOD-...
2. #...
1. ...
> MOD-10951: Update boost download url

- .install/install_boost.sh
- build/boost/boost.cmake
Update Boost 1.84.0 download URL from broken archives.boost.io to formal release
(cherry picked from commit b1744c15fb855338ff91bcb73ceada5a32728616)
Backport of #6668
1. MOD-...
2. #...
1. ...
> MOD-10951: [2.10] Update Boost 1.84.0 download URL 

- .github/workflows/event-deploy-snapshots.yml
- .github/workflows/task-build-artifacts.yml
- Makefile
- build.sh
- sbin/pack.sh
Following https://github.com/RediSearch/RediSearch/pull/6558, packing is no longer working for 2.10 versions and below (see, for example, https://github.com/RediSearch/RediSearch/actions/runs/17189863277/job/48764009633), where we still need to support the search-light module variant and coord-oss, and we have separate build flows and naming for standalone and coordinator.  
Also, due to a syntax error, we did not get notifications when building the snapshots failed after merging PRs to 2.10.
Here, we fix it by reverting the logic that sets up the variable required for packing in such versions.
> [2.10] Fix to support lite and properly pack + fix notification syntax error

- src/query.c
- tests/pytests/test_rrf.py
Updated `query_EvalSingleTagNode` to set the weight to `0.0` when either  
`QEXEC_F_IS_HYBRID_SEARCH_SUBQUERY` or `QEXEC_F_IS_HYBRID_VECTOR_AGGREGATE_SUBQUERY`  
is present, preventing tag fields from contributing to document scores in hybrid  
search components while preserving normal tag scoring for `FT.SEARCH` and `FT.AGGREGATE`.
Includes a test verifying that identical hybrid queries produce identical scores  
regardless of tag field matches.
This PR is based on https://github.com/RediSearch/RediSearch/pull/6667
> MOD-10227: Disable tag scoring for FT.HYBRID

- .install/amazon_linux_2.sh
libclang-dev does not exist on this image.
> fix amazon_linux_2 clang-devel install

- src/module.c
1. Current: 
In Redis, the "master" client (such as replication) may not have an associated user, and `RedisModule_GetCurrentUserName()` will return NULL in such cases.
Redisearch was not validating the previous case.
2. Change: 
Allow access in ACLUserMayAccessIndex when no user is associated
Similar approach was used by RedisTimeSeries in [CheckKeyIsAllowedByAcls](https://github.com/RedisTimeSeries/RedisTimeSeries/blob/e3acedeac7a202aa769f1b95bb69b21ded32194a/src/module.h#L37
)
3. Outcome:
> MOD-10748: Fix ACLUserMayAccessIndex

- src/redisearch_rs/Cargo.lock
- src/redisearch_rs/build_utils/Cargo.toml
- src/redisearch_rs/build_utils/src/lib.rs
- src/redisearch_rs/inverted_index_bencher/build.rs
- src/redisearch_rs/inverted_index_bencher/src/ffi.rs
We can generate API requiring lifetimes by defining type aliases.
> inverted_index_bencher: remove blocklist_item

- src/debug_commands.c
- src/inverted_index/inverted_index.c
- src/inverted_index/inverted_index.h
- src/redisearch_rs/c_entrypoint/types_ffi/cbindgen.toml
- src/redisearch_rs/c_entrypoint/types_ffi/src/lib.rs
- src/redisearch_rs/headers/types_rs.h
- src/redisearch_rs/inverted_index/src/debug.rs
- src/redisearch_rs/inverted_index/src/lib.rs
Refactor the II code in `debug_commands.c` so we can more easily port it to Rust next.
> [MOD-10831] Refactor debug_commands II code

- src/fork_gc.c
- tests/pytests/test_gc.py
Manual backport of #6672 to `2.10`.
(cherry picked from commit 56f6f0e)
Changes:
- Fix conflict in `test_gc_oom()` to create index before adding the docs. 
- Fix conflict in `test_gc_oom()` to call set_tight_maxmemory_for_oom(env) instead of `env.expect('config', 'set', 'maxmemory', 1).ok()`
> [2.10] MOD-10975: Fix fd leak when OOM (#6672)

- .gitignore
When running the bench manually, for profiling for example, the benchmark output is written directly to the crate directory rather than to bin/.
@GuyAv46 : fix the issue we had the other day with loads of files not being properly ignored.
> ignore criterion output in sub dirs

- src/fork_gc.c
- src/inverted_index/inverted_index.c
- src/inverted_index/inverted_index.h
- src/redis_index.c
- src/redis_index.h
- src/redisearch_rs/inverted_index/src/lib.rs
- src/redisearch_rs/inverted_index/src/tests.rs
- src/tag_index.c
- tests/cpptests/index_utils.cpp
- tests/cpptests/index_utils.h
- tests/cpptests/test_cpp_range.cpp
Have Rust report the memory usage of an inverted index.
Also refactors the C implementations to:
- align with the incoming FFI changes
- remove the duplicate memory usage definition in `index_utils`
> [MOD-10705] Rust Inverted index memory usage and C refactors

- src/forward_index.c
- src/forward_index.h
- src/indexer.c
- src/inverted_index/inverted_index.c
- src/inverted_index/inverted_index.h
- src/tag_index.c
- tests/cpptests/index_utils.cpp
- tests/cpptests/index_utils.h
- tests/cpptests/micro-benchmarks/benchmark_index_iterator.cpp
- tests/cpptests/test_cpp_index.cpp
- tests/cpptests/test_cpp_iterator_index.cpp
- tests/cpptests/test_cpp_iterator_intersection.cpp
- tests/cpptests/test_cpp_iterator_not.cpp
- tests/cpptests/test_cpp_iterator_optional.cpp
- tests/cpptests/test_cpp_iterator_union.cpp
This removes the `encoder` argument from `InvertedIndex_WriteForwardIndexEntry` (and all the functions calling it) to align it with the incoming Rust code.
This argument is redundant since the inverted index (which is already an argument) already knows which encoder it should use.
> [MOD-11101] Remove encoder arg from `InvertedIndex_WriteForwardIndexEntry`

- src/redisearch_rs/inverted_index/src/doc_ids_only.rs
- src/redisearch_rs/inverted_index/src/fields_offsets.rs
- src/redisearch_rs/inverted_index/src/fields_only.rs
- src/redisearch_rs/inverted_index/src/freqs_fields.rs
- src/redisearch_rs/inverted_index/src/freqs_offsets.rs
- src/redisearch_rs/inverted_index/src/freqs_only.rs
- src/redisearch_rs/inverted_index/src/full.rs
- src/redisearch_rs/inverted_index/src/lib.rs
- src/redisearch_rs/inverted_index/src/numeric.rs
- src/redisearch_rs/inverted_index/src/offsets_only.rs
- src/redisearch_rs/inverted_index/src/raw_doc_ids_only.rs
- src/redisearch_rs/inverted_index/src/tests.rs
Enforce the encoder/decoder relation using the type system.  This will help implementing the II iterator.
The branch also contains a couple of trivial changes to the II.
> [MOD-11129] Enforce encoder/decoder relationship in the type system

- src/inverted_index/inverted_index.c
- src/inverted_index/inverted_index.h
- src/iterators/inverted_index_iterator.c
- src/iterators/inverted_index_iterator.h
- src/profile.c
- tests/cpptests/test_cpp_iterator_index.cpp
Creates a reader around the inverted index to prevent the iterator from accessing the index directly. This also establishes the API which the Rust implementation needs to expose for the reader.
> [MOD-11103] Inverted Index Reader and API

- src/redisearch_rs/rqe_iterators/src/empty.rs
- src/redisearch_rs/rqe_iterators/src/lib.rs
Creating and destroying a result each time is killing performances.
> iterator: return a borrow instead of an owned result

- src/redisearch_rs/inverted_index/src/debug.rs
- src/redisearch_rs/inverted_index/src/lib.rs
- src/redisearch_rs/inverted_index/src/tests.rs
This makes a Rust equivalent for providing a debug summary about an inverted index.
> [MOD-10704] Implement Rust providing a debug summary for an inverted index

- src/redisearch_rs/inverted_index/src/doc_ids_only.rs
- src/redisearch_rs/inverted_index/src/fields_offsets.rs
- src/redisearch_rs/inverted_index/src/fields_only.rs
- src/redisearch_rs/inverted_index/src/freqs_fields.rs
- src/redisearch_rs/inverted_index/src/freqs_offsets.rs
- src/redisearch_rs/inverted_index/src/freqs_only.rs
- src/redisearch_rs/inverted_index/src/full.rs
- src/redisearch_rs/inverted_index/src/lib.rs
- src/redisearch_rs/inverted_index/src/numeric.rs
- src/redisearch_rs/inverted_index/src/offsets_only.rs
- src/redisearch_rs/inverted_index/src/raw_doc_ids_only.rs
- src/redisearch_rs/inverted_index/src/tests.rs
- src/redisearch_rs/inverted_index/tests/numeric.rs
Rather than tracking this in the numeric encoder, this creates a new wrapper to track the entries instead.
> [MOD-11098] Have a wrapper to track the number of entries in an inverted index

- src/numeric_filter.c
- src/numeric_filter.h
- src/numeric_index.c
- src/query.c
- src/query_optimizer.c
- src/redisearch_rs/c_entrypoint/types_ffi/cbindgen.toml
- src/redisearch_rs/c_entrypoint/types_ffi/src/lib.rs
- src/redisearch_rs/headers/types_rs.h
- src/redisearch_rs/inverted_index/src/lib.rs
- tests/cpptests/test_cpp_iterator_index.cpp
- tests/cpptests/test_cpp_query.cpp
The inverted index reader might need to filter records based on the numeric filter. For the Rust implementation to do the same, the `NumericFilter` struct needs to be accessible by Rust. There this PR ports the struct over to Rust for easy direct access.
> [MOD-11194] Port `NumericFilter` to Rust

- src/value.c
- src/value.h
A number of functions defined in the `value` module are not actually in use. In preparation of porting this module to Rust, this PR does away with unused code.
> [MOD-10347] Remove unused code from RSValue

- src/forward_index.c
- src/indexer.c
- src/inverted_index/inverted_index.c
- src/redisearch_rs/headers/types_rs.h
- src/redisearch_rs/inverted_index/src/fields_offsets.rs
- src/redisearch_rs/inverted_index/src/freqs_offsets.rs
- src/redisearch_rs/inverted_index/src/full.rs
- src/redisearch_rs/inverted_index/src/index_result.rs
- src/redisearch_rs/inverted_index/src/offsets_only.rs
- src/redisearch_rs/inverted_index/src/test_utils.rs
- src/redisearch_rs/inverted_index/tests/index_result.rs
- src/redisearch_rs/inverted_index_bencher/src/ffi.rs
- src/tag_index.c
this var is duplicate info as it is the same as the offset length, so no need to store it separately
Closes [MOD-11082](https://redislabs.atlassian.net/browse/MOD-11082)
[MOD-11082]: https://redislabs.atlassian.net/browse/MOD-11082?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOD-11082] remove offsets_tz var in RSIndexResult

- src/redisearch_rs/inverted_index/src/lib.rs
- src/redisearch_rs/inverted_index/src/tests.rs
This allows the Rust index reader to skip ahead to a block with the given doc ID. This is equivalent to the following two pieces of C code
https://github.com/RediSearch/RediSearch/blob/48ef03c645284ad0338dd821352b02b7a55f0b15/src/inverted_index/inverted_index.c#L1370-L1412
https://github.com/RediSearch/RediSearch/blob/48ef03c645284ad0338dd821352b02b7a55f0b15/src/inverted_index/inverted_index.c#L1428-L1441
> [MOD-10707] Implement `skip_to` functionality on the Rust index reader

- src/inverted_index/inverted_index.c
- src/inverted_index/inverted_index.h
- src/iterators/inverted_index_iterator.c
- src/redisearch_rs/c_entrypoint/types_ffi/cbindgen.toml
- src/redisearch_rs/c_entrypoint/types_ffi/src/lib.rs
- src/redisearch_rs/headers/types_rs.h
- src/redisearch_rs/inverted_index/src/lib.rs
The inverted index reader might need to filter out records based on this `DecoderCtx` struct. For the Rust reader to do the same it needs access to this struct. Therefore, this PR ports the struct to Rust as an idiomatic Rust enum enabling the Rust code to have direct and safe access to it.
> [MOD-11195] Port `DecoderCtx` to Rust

- src/redisearch_rs/inverted_index/src/lib.rs
- src/redisearch_rs/inverted_index/src/tests.rs
This ports over the last filters which will be needed by the inverted index reader in Rust. They are equivalent to these lines in C
https://github.com/RediSearch/RediSearch/blob/74035a27a248489bb797bd49ac080ce6a6a51de4/src/inverted_index/inverted_index.c#L837-L849
The Rust version splits this into two separate wrappers. One for filtering the numeric values, and another for filtering the geo radius.
> [MOD-11171] Rust filter wrapper around inverted index reader

- src/redisearch_rs/inverted_index/src/fields_offsets.rs
- src/redisearch_rs/inverted_index/src/freqs_offsets.rs
- src/redisearch_rs/inverted_index/src/full.rs
- src/redisearch_rs/inverted_index/src/lib.rs
- src/redisearch_rs/inverted_index/src/offsets_only.rs
- src/redisearch_rs/inverted_index/src/raw_doc_ids_only.rs
- src/redisearch_rs/inverted_index/tests/fields_offsets.rs
- src/redisearch_rs/inverted_index/tests/freqs_offsets.rs
- src/redisearch_rs/inverted_index/tests/full.rs
- src/redisearch_rs/inverted_index/tests/offsets_only.rs
- src/redisearch_rs/inverted_index/tests/raw_doc_ids_only.rs
The `seekFreqOffsetsFlag` and `seekRawDocIdsOnly` seeker were missing on the Rust decoders. This adds the C equivalent seekers in Rust.
I also saw that `FieldOffsets`, `Full`, and `OffsetsOnly` can benefit from the same seeker logic. This causes these to skip the offsets decoding when the target has not been reached yet.
> Implements seekers for Rust decoders

- module.conf
Split Redis.full.conf to modules - include search configs
Copy from redis.full.conf, except for:
1. added the new search-enable-unstable-features, search-bm25std-tanh-factor and  search-indexer-yield-every-ops configs
2. Fix the default on-timeout to reflect the reality (from fail to return)
> [MOD-11137] Add module.conf file

- src/aggregate/aggregate.h
- src/aggregate/aggregate_exec.c
- src/aggregate/aggregate_request.c
- src/config.c
- src/config.h
- src/coord/dist_aggregate.c
- src/info/info_redis/info_redis.c
- src/module.c
- src/result_processor.c
- src/result_processor.h
- tests/pytests/test_config.py
Add ignore as option to ON_OOM config.
Because on_oom and on_timeout do not share policy options, the changes from #6769 are reverted and the policy enums are seperated. 
Because of the revert, I suggest, for an easier review, to review by commit and not the PR as is, the revert commit was done automaticly.
> [MOD-11398] Add "ignore" option to ON_OOM config

- src/redisearch_rs/c_entrypoint/inverted_index_ffi/cbindgen.toml
- src/redisearch_rs/c_entrypoint/inverted_index_ffi/src/lib.rs
- src/redisearch_rs/headers/future/inverted_index.h
This finished the FFI layer needed to expose the Rust inverted index reader. The autogenerated code is in `headers/future` so the C code won't call these yet until a later PR.
> [MOD-11260] FFI layer for inverted index reader

- src/info/info_command.c
- src/inverted_index/inverted_index.c
- src/inverted_index/inverted_index.h
- src/redisearch_rs/c_entrypoint/inverted_index_ffi/src/lib.rs
- src/redisearch_rs/headers/future/inverted_index.h
- src/redisearch_rs/inverted_index/src/lib.rs
- src/spec.c
- tests/cpptests/test_cpp_forkgc.cpp
This has Rust also track the total number of index blocks and exposes it via FFI. The Rust FFI is still inside `headers/future` so the C code wont' call this yet. The C is also updated to have access to it behind an accessor (the same as the incoming one via the FFI)
> [MOD-11045] Have Rust track the total number of index block

- src/redisearch_rs/inverted_index_bencher/src/ffi.rs
- src/redisearch_rs/inverted_index_bencher/src/lib.rs
This provides the `isWithinRadius` and `DocTable_Exists` symbols for the inverted index benchmarks to allow it to build correctly on some systems for testing. For eg [here alpine](https://github.com/RediSearch/RediSearch/actions/runs/17840600610/job/50762745996) fails to link to it in CI. It also disables the flaky numeric FFI test
> Provide FFI stubs and ignore flaky test

- src/spec.c
- src/spec.h
- tests/cpptests/redismock/redismock.cpp
- tests/cpptests/redismock/redismock.h
- tests/cpptests/test_cpp_rdb.cpp
We noticed some fields do not get initialized correctly when the index spec is initialized from an RDB.
Added mock rdb support for tests and added tests to compare an index to itself after it stored to an RDB and loaded again.
1. Current: Missing index spec struct members initialization
2. Change: Create one function to initialize all regular members and call it from both the new function and when loading from an RDB.
3. Outcome: More correct index initialization when loading an index from an RDB.
1. Index Spec
> MOD-11190: Add IndexSpec RDB Comparison Tests - Fix Index RDB field initialization

- src/redisearch_rs/c_entrypoint/rlookup_ffi/src/row.rs
- src/redisearch_rs/c_entrypoint/sorting_vector_ffi/src/lib.rs
- src/redisearch_rs/rlookup/src/row.rs
- src/redisearch_rs/rlookup/tests/row.rs
- src/redisearch_rs/sorting_vector/tests/sorting_vector.rs
- src/redisearch_rs/value/src/lib.rs
This fixes use-after free due to inconsistent handling of refcounts in `RLookupRow` and `value`. The test mock implementation did not implement `Drop` and used a weird `Rc`-based workaround for refcount increases while the "production" `RSValueFFI` implemented `Drop` and `Clone` using atomic refcounting. This lead to a mismatch between test-behavior and "production" behavior where tests passing would mean the runtime behavior was incorrect.
This change simplifies `MockRSValue` to also use atomic reference counting, removes the manual and unsafe `increment` and `decrement` methods of `RSValueTrait` and fixes the uses in `RLookupRow` to be correct.
> fix: RLookupRow use-after-free due to inconsistent refcount handling

- src/util/arg_parser.c
- src/util/arg_parser.h
- tests/cpptests/test_cpp_arg_parser.cpp
The parsing logic of Hybrid is intertwined with that of AGGREGATE and SEARCH.
Some keywords shouldn't be supported in HYBRID but will silently get accepted because we use the same parsing functions.
e.g handleCommonArgs.
This PR is meant to provide an infrastructure to separate the parsing flow of Hybrid and improve the ease in which we parse commands.
1. Current: No simple parsing framework exists
2. Change: Add an ArgsParser struct
3. Outcome: Provide an infrastructure for parsing commands.
1. ArgsParser
> MOD-11172: Add Argument Parser Struct To Improve Parsing Experience

- src/vector_index.c
- tests/pytests/test_hybrid_vector_normalizer.py
Support `SVS-VAMANA` vector index type in `FT.HYBRID`
Changes include: 
- Handle its case in `getVecSimMetricFromVectorField`
- Test it in `tests/pytests/test_hybrid_vector_normalizer.py`
> MOD-11352: Support SVS in FT.HYBRID

- tests/pytests/test_expire.py
Aim to reduce flakyness in `test_expire.py` by giving more time so that COARSE clocks may have enough precision 
https://www.kernel.org/doc/html/latest/core-api/timekeeping.html
Here it says that with COARSE results may show 10 ms in the past
> test: increase timeout to avoid flakyness due to some clock precision

- tests/pytests/test_hybrid_multithread.py
Add 
```
env.expect(debug_cmd(), 'WORKERS', 'DRAIN').ok()
```
Before validating the threadpool stats to make sure they are stable 
Add `enableDebugCommand=True` to the environment creation since this test uses debug commands
> Fix test_hybrid_multithread flakiness

- src/hybrid/hybrid_exec.c
- tests/pytests/common.py
- tests/pytests/test_hybrid.py
- tests/pytests/utils/hybrid.py
1. Current: `FT.HYBRID` response format is :
```
expected = [
'format', 'STRING',
'results',
[
['attributes', ['__key', 'vector_01', '__score', '0.333333333333']],
['attributes', ['__key', 'both_01', '__score', '0.5']],
['attributes', ['__key', 'both_05', '__score', '0.5']],
],
'total_results', 3,
'warnings', [],
'execution_time', ANY
]
```
2. Change: `FT.HYBRID` Response format
```
expected = [
'total_results', 3,
'results',
[
['__key', 'vector_01', '__score', '0.333333333333'],
['__key', 'both_01', '__score', '0.5'],
['__key', 'both_05', '__score', '0.5'],
],
'warnings', [],
'execution_time', ANY
]
```
3. Outcome: Response format is aligned with the PRD: https://redislabs.atlassian.net/wiki/spaces/DX/pages/3981803720/P …
> MOD-11584: Align FT.HYBRID response format with the PRD
